// OpenAero rulesYY-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####   Régles France 2018 Espoirs à Doret    Version 2018.0.01    ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####      Modifications mineures (commentaires) et connus 2014    ###################
//#####      Corrections, modifications espoirs 2015, connus 2015    ###################
//#####      Ajout de règles (déclenchés) d'inconnu Doret 2015.      ###################
//#####      Prise en compte du distingo entre rotation alternées    ###################
//#####      (,) et rotations même sens (;) dans les régles 2015.    ###################
//#####      Modifications 2016, connus 2016, nouveaux noms.         ###################
//#####      Modifications 2017, connus 2017, connu_x -> connu x.    ###################
//#####      Modifications 2018, connus 2018, noms (in)connu-libre   ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2018 : Espoirs, Desavois, National2 et Doret.

//##### (Une partie des) Règles spécifiques à la France.

rules.push(rule("XSJ|nih`*Husfmpr(oaai~X"));rules.push(rule("^jjjd%7-cg)6e!az;|)%+T-k.wz\"66,p\"*&(\'>l.7$*3$=<&\'&ej?e$.6,&/,f!)%+--i#:!\"l:,<*\'9ot3&1;"));rules.push(rule("_d\"jj}7<43"));rules.push(rule("Qlg~k2Ayddnc#Lwrna~}/fgi"));rules.push(rule("T_Lgmja\"D{|afux%ccelgjw\\"));rules.push(rule("Vm&hku;2;4"));rules.push(rule("Wjdwo0@qhjad(I}hbwy-goe"));rules.push(rule("XSJ|nih`*Husfmpr(`gmunX"));rules.push(rule("[` kbq9328"));rules.push(rule("Sahwggak#bfs8;?"));
rules.push(rule("Qgia;\"jbk7<"));rules.push(rule("Rdhi5,ee`26"));rules.push(rule("Sehi:,ee`26"));rules.push(rule("Tveaj.dml<9"));rules.push(rule("Uvzdh.dml<9"));rules.push(rule("[n`vwphkom!cn65"));rules.push(rule("_mntnccj+qltg`|1?"));rules.push(rule("]ack&wo}cb}90"));rules.push(rule("Rpfhn,|cz}b{`ky;2"));rules.push(rule("[fbtf4Bp`fok/Bxuedtp)enm"));rules.push(rule("[#Ktbggg!M~`nyv*ljo "));rules.push(rule("Vum%7-ggelbmh"));rules.push(rule("Ssfwnk5=>"));rules.push(rule("Tte~ho452"));
rules.push(rule("]kb`fldj+sfmlu5<"));rules.push(rule("^i}h~u\'ysqgtmr5R<S)P4\'9[_\'5^/9"));rules.push(rule("Qu}~`hx(dlkf4$thzmijt+socrql"));rules.push(rule("Rv|vlqg#bfs8;"));rules.push(rule("[yxjf$WRHF1|`kg?TVXpT"));rules.push(rule("Qv`u#\\WBK7Kod|vg!izkl\'}wcajf)qlhyykbbeq"));rules.push(rule("Ufecp.{kv^i`z/:+[3Q(_m/^/;P \'\\:(2P/#4$&03R7S)Wa!Q(X8664UP T6&=W-;#q?\\8T\".2\'r>T=Z-4~"));rules.push(rule("_}zkn(DbYbep]5=,3/udqUljw3$zZ$7S"));rules.push(rule("Rp|hg,FcQnkZbbt#4$pn|Socs1%Q!=^"));
rules.push(rule("Rua}/OgSocsTme&>)Vmuixg`i+dfycqgéa\"hfxk}cbqo"));rules.push(rule("Vt~io Kbq[cm|S9=7+8*iwVenu2,&7\\\'>Wq]/2Y:}>W\"4Z=y<V*8T0~5S 5R1\""));rules.push(rule("^yg~&HkuYbep]6:<.2\'Yj~lrjfj\"`dxk}ién%fdkj}éa\"à!?>>°"));rules.push(rule("Sbehmv%hkiu~io~&>)Jm^i`zP3>"));rules.push(rule("U0$?(2\'5\"OZ6?4IY?9"));rules.push(rule("Y>\"<!6%1*CT98?LS2?"));rules.push(rule("Z3#72\'5,5%;"));rules.push(rule("Q8&= ;)9"));rules.push(rule("[:#4-?*3!F^4><EW0>"));rules.push(rule("[<#>-=*3!F^4>"));
rules.push(rule("T5$?(0\'5\"OZ6="));rules.push(rule("U2$>(7\'0"));rules.push(rule("[3#3-;*6!FcQnkZbbt"));rules.push(rule("Q6&> =):%D_<22Jm^i`zPodw"));rules.push(rule("X?\"=!4%6*CT98"));rules.push(rule("]4 >)8+>"));rules.push(rule("]5 :)?+;-HlVenuWda}"));rules.push(rule("Z;#7-;*1!F^4>"));rules.push(rule("R3\'5,0&=#;\'FdrRgo}[538"));rules.push(rule("_>!6%2$<&M[>3"));rules.push(rule("X9\"<!5%6*CT98?LS2?"));rules.push(rule("Y;\"=!6%4\'?"));rules.push(rule("X9\"<!0%4*CT98"));
rules.push(rule("W5%4$<(2$6"));rules.push(rule("R:\'1,2&?.AU141Ci\\hhv^`c|"));rules.push(rule("^6!2%1$9&Mf[cm|Sf`u"));rules.push(rule("T<$8(1\'5\"OZ6="));rules.push(rule("^?!6%3$>&PYML"));rules.push(rule("W6%4$>(7"));rules.push(rule("V1%1$<(2)JP;9"));rules.push(rule("W6%7$<(0)JP;97@]=8"));rules.push(rule("R5\'7,3&="));rules.push(rule("U4$?(0\'0\"OZ6="));rules.push(rule("Y1\";!2%1*CT98"));rules.push(rule("Z3#7-;*0"));rules.push(rule("^9!?%=$9&M[>1"));rules.push(rule("^7!6%6$;"));
rules.push(rule("T3$>(7\'5"));rules.push(rule("X:\"<!6%4\'?"));rules.push(rule("R5\'<,7&?.AU141CT9:"));rules.push(rule("X0\"8!6%4*CT98?LS2>5AU16"));rules.push(rule("V7%4$>(2"));rules.push(rule("T5$<(1\'5"));rules.push(rule("R;\'6,2&8"));rules.push(rule("Z8#2-8*3,:"));rules.push(rule("T=$?(0\'<"));rules.push(rule("]: 7)3+;-HQ37"));rules.push(rule("[2#7-:*0"));rules.push(rule("_6!6%6$5"));rules.push(rule("V>%1$<(2)JP;97@]=8"));rules.push(rule("[2#7-;*6"));rules.push(rule("V7%7$9(7)JP;;"));
rules.push(rule("^9!5%4$<&M[>3:FcQnkZbbt"));rules.push(rule("W?%1$>(2)JP;97@]=8"));rules.push(rule("[>#5-8*3!F^4><EW0?=M[>1"));rules.push(rule("^6!2%4$>&M[>3:FcQnkZbbt"));rules.push(rule("Q9&9 9):%DbYbep]ig~"));rules.push(rule("[3#3-?*6!F^4>"));rules.push(rule("S;\'1,9&>.AhTdfyYkfv"));rules.push(rule("S:\'6,2&:"));rules.push(rule("U^Lgmja\"Emoyhbv%}tldkvhgb.lhekP"));
rules.push(rule("[ohkl)9\"db,!qy )8*!k.0,v2.89++g<+#;:\",az ! bv$#!#&<`/&+%og+74-x}=oba%ln/gk(e?-c)db*ld&!.%+$#($\"/)(>+/55%$#ke$$/7(lno,:oe<-cid"));rules.push(rule("Sh$icy5=9?"));rules.push(rule("_b`un8Lgmja\"Emoyhbv%}tldkvhgb.nkg"));rules.push(rule("SXOvcoki.Kbxd|bop&tpneczfhe%ccelgjw\\"));rules.push(rule("Yb!cn64?8"));rules.push(rule("Vkdwo0@qhjad(Hk|f}jc~)s{kon|eaa\'jif"));rules.push(rule("W\\Mwkcef)@grizaft$uxbkl}mmo(`gmunX"));rules.push(rule("_d\"jj}7?63"));
rules.push(rule("Vdjvokod$icy5=<"));rules.push(rule("Smlc/lab3:"));rules.push(rule("Wudifht.dml<9"));rules.push(rule("V`jh? kjg93"));rules.push(rule("Wajh= kjg93"));rules.push(rule("Xnmc7*fld07"));rules.push(rule("Yz|ga*fld07"));rules.push(rule("Z|iw$iko5="));rules.push(rule("^zzueue~+nh|?0"));rules.push(rule("Sfdtvxde`j*fdr06"));rules.push(rule("Vdjvokod$vgqmmz26"));rules.push(rule("Tveaj.{ardix3="));rules.push(rule("Xzcbc*j~cslev<9"));rules.push(rule("Vuedz tfyacu5="));
rules.push(rule("Wt{ld tfyacu5="));rules.push(rule("_b`un8Lgmja\"Emoyhbv%}tldkvhgb.nkg"));rules.push(rule("^&Iujkih&Glwcwge} wyjgbrjfj\"`d`\'"));rules.push(rule("]~h/:+dn{gmjaf"));rules.push(rule("Zzbuoc934"));rules.push(rule("[{bume934"));rules.push(rule("Ucfbgw`je,xcgas65"));rules.push(rule("Vayj}+w|vlqg3Q5W+Q<+7TX,0T\"?"));rules.push(rule("X|y|awdv\'cgnl9\"wa~ohbx%|hhw{a"));rules.push(rule("W`yj}+u{kv<V5R!\\:1WQ(2U*0"));
rules.push(rule("_y}h(dlkf4$pn|mzfhe%|htw`gcmm,c`iddyc#ma\"00<°"));rules.push(rule("Tcxbss$vmmdi|2Y9Y$%4_\'_77Up=S)?,V#"));rules.push(rule("Uweajf{)l`ei3/sdkdhgvq$go(zg}fl`"));rules.push(rule("Wu~io US@J?sg`b5YP[yP"));rules.push(rule("[|e.ZTKO5Jghry`*lpfj$tsa`bj\'~kc|sfdalu"));rules.push(rule("Uwac.ZtkoWc{Pub`d0tleh8_SR}uZ"));rules.push(rule("Tsbt+Pyml^gyQ}nnk7Kod|vg!{i{cb+j-gulg\"wzebcb+pddwvligo|,}zu+ik-pf{pkbi`k"));rules.push(rule("Tvac.GBA<zcbc=#Y}V*8T_dGU%r\'\\mCWV*8TXu("));
rules.push(rule("Wpc|\'C@@4tcr(hk/céhioceké)`co{,bjt+weygw`klr(oabwdvéo~"));rules.push(rule("Yjc`y*}`xyww{w?_1P \'\\:(3Pz29-^/ W?:1Vy;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Xzybj*]42=&>)rgs|}z}t199"));rules.push(rule("Vqc|\'[7;9$?!Xm}/cn%xbrb}mmo({byloxtf)à$398°,}zu+io~&ulvvhkmbjt"));rules.push(rule("]{cb&Hku?3)9\"wm~z~syv014"));rules.push(rule("Z}e.Dez88,3/Wjv*ic#{kv`|eaa\'xpzhtjlqpd(à,7?°\'xpx-efz$tdzxglfg`y"));
rules.push(rule("_l`i}(|htw|tsuz3Q>W+\"V7.0Y~08%R!/P4<P/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Vt~io Kbq=2tx,3/qnw~xvr}vq;4>"));rules.push(rule("Xdw\"Jj}3=ss)9\"Qi.kb+weygw`kl!{y~jub`c#à)=2°!{y|/kj%|htw`gcmm,c`iddyc"));rules.push(rule("Tgecp.apulc{ux8T4Z-!_3,1Qr>7\"Y$%384+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("Zxxjf$Icy1<j`\'6%|htwmksuz435"));rules.push(rule("_xg~&Hku?3mk\"<(\\o|\'o`*iwhpknf,}zwnwchsql$à\"88°,}zu+ik-pf{pkbi`k/cnvihhghjvd"));
rules.push(rule("Tgecp.gkrt{d3Q>W+;V71TX,0T\"U:*3X7c=]0X,Z9>:7ZW+7=]0**8t=>&:m>T4(2R50\\55Q7W+7w"));rules.push(rule("[yxjf$JQQ}f`r%7cis|wj;f("));rules.push(rule("]zfv*EVZxukfqv!5,^nt+ao-ul{pkd(|aztxé`*lvqèz$n`(z|fkg`"));
rules.push(rule("VAyj}+mlc?_ =R!6W+8Q(X;0_}9P >[%^9:[_\'_02Up?S):Y$;Z-=x3]&>R!\\91<5[_\'6~0T\"<S)>Y$V71Tx0]&=R!4W+v?Z-;X,Z:98R[%y8Q(0U*Y5UP s5W+>Q(X;7_]&p;S)P79PZ-8X,Z:?:R{>Y$>Z-;X,}?P T5?XV#]2;Y^/:p9S)9Y$V57TX,0t;R!3W+8Q(2u3^/;P >[%y=Q(;U*Y0:99R[%y=Q(0U*0]&W<<3Vy=Q(0U*1]&W?=3Vy=Q(;U*4]&W?=3Vy=Q(X:<_]&8R!\\96Wq1_\'<^/;P T69Xv:Z-1X,9T\"U=4Vy2Q(7U*Y0;QR!5w=V#2_\'_05UP s?W+>Q(2:X,0t4R!2W+Q<5^U*Y0:8Ss?W+?Q(X;0_]&W<<Zw=V#0_\'_150QR!6w=V#3_\'<^/9p6S)>Y$V34TX,Z9>Ss?W+Q80^U*4]&>\'s>W+;V61TX,"));
rules.push(rule("Rllc/oiak2abbcp)gmo{ejé}ébx%ibknl$léfixgybx"));rules.push(rule("[hbhu$Lmsyx||:U<V#Zg\"X,Z;4SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("Qs}`k\"Jj}=?6Kfv\"<@c|~syv01?"));rules.push(rule("Tsbt+Nh|538Da}\'6%Zlu#ma\"sgxo{ndk*ninykqéd(da}nqjdygol$qtxi|fb~wo-à&4;4°"));rules.push(rule("Rafjt,]|::vwy0X:U*^e#P T5<XV#.X8):\\!1*><U<V#;32Z2]&1>"));rules.push(rule("Xzybj*Fdr>03\\t64(1[3>t~u951"));
rules.push(rule("Qv`u#Bfs6<=Ss=1\"<(\\o|\'o`*iwhpknf,m`j{jyéh&pfqq!<9°.bheqkcr#zqrdzekzun%à*>03°"));rules.push(rule("Wddk| Bl=1suz3Q>W+Vi-_\'_68UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("]{cb&Hku7;9@m5=,3Kh?0{ytp381"));rules.push(rule("Y~dw\"Jj};56Gf07!5,^nt+ao-tl}evhgb.lhfue~éc#zkwr(8;°/cnvihhghjv!{y~jub`c#à)5:1°"));
rules.push(rule("S`fjt,zczPvwy0X:U*;]&$U>*>X#Q(+R5/9U%3a/71S?_\'=^/ W8\">Vy;=/_\',Y0%4S&:{C.?=]0X,08P \'\\:(?P/_\',Y0%4S&:ec.?=]0X,08P \'\\=(3Pz29-^/ W?\"?V,7c@\';?\\8T\"U>*3XV#]2$1_]&$U>*3X#0t\'8?\\8T\"?T69XV#7_\',Y0%4S&:x!;6X:U*?s3R>S)6"));rules.push(rule("Xzybj*EjUIcn`[rn{,3/udqU|rqz>rg:"));rules.push(rule("^yg~&KeRBfdm]qg.2\'O`gd&géjhgokdé.hxl~d`#`jvdzhg{"));rules.push(rule("Wfgiez+glbptdi}/:+KLN=U8<2:Emv85;Me=Nh|178Y~;20Hku7;9@m5="));rules.push(rule("Y0\":!4%7"));
rules.push(rule("V?%7$>(;"));rules.push(rule("W5%7$8(2$0\")9>\">4\'4>!76 "));rules.push(rule("U2$?(0\'7\"OZ6<"));rules.push(rule("V1%7$9(2)JD;9"));rules.push(rule("V>%3$9(0)WrhfSazXyloc"));rules.push(rule("[2#7-8*3,:"));rules.push(rule("T=$?(0\'0"));rules.push(rule("[<#>-:*6!F^4>"));rules.push(rule("W6%4$<(2$0"));rules.push(rule("U<$4(0\'6"));rules.push(rule("Q4&? =):%D_<12Icy1<j`"));rules.push(rule("U=$;(;\'5\"ON6?4IY?86HQ37"));rules.push(rule("U<$?(0\'2"));
rules.push(rule("_:!4%4$?&M[>3:F^4=<EW0>"));rules.push(rule("S;\'0,0;\"?/IY?;6HQ36"));rules.push(rule("Z2#3-1*3,:,@I=:"));rules.push(rule("]4 >6%4$9+;"));rules.push(rule("S4\'0,3&=.AhTAo`o\\ykq"));rules.push(rule("[3#2-:*3!Emv67oj"));rules.push(rule("Z2#3-:*1,<,@]=:"));rules.push(rule("T5$<(4\'0\"RXE@"));rules.push(rule("S6\'7,3&8.AU171@g{04fn"));rules.push(rule("R5\'<,0&8.AU141CT9;?LS2?"));rules.push(rule("Y1\"8!5%4*@g{04wq3B\\550KL75"));rules.push(rule("Q9&: 9)9%D_<22JP;:7@]=8"));
rules.push(rule("T6$>(2\'5/3"));rules.push(rule("^9!4%4$?&M[>3"));rules.push(rule("[2#2-:*4"));rules.push(rule("[:#4-=*0!F^4="));rules.push(rule("U=$8(2\'6\"OZ6?4IY?8"));rules.push(rule("Z2#0-=*3!Emv67~u1CT9;?LG2?"));rules.push(rule("^6!2%2$<+1)JD;97@]=9"));rules.push(rule("W>%1$<(1"));rules.push(rule("_6!6%6$5"));rules.push(rule("_>!6%3$<&Nh|;1"));rules.push(rule("Z2#0-<*3!F^4=<EW0>"));rules.push(rule("^9!5%7$<&MO>3:FcQKbflU}ip36"));rules.push(rule("R5\'<,2&=#=\'EW0<=M[>1"));
rules.push(rule("]4 7):+;"));rules.push(rule("_>!5%3$<&M[>0"));rules.push(rule("U=$8(6\'6\"OZ6?4IY?8"));rules.push(rule("S6\'6,0&=.Bfs<:ii"));rules.push(rule("S;\'1,7&>.AU14"));rules.push(rule("[<#>-<*3,<,@]=:>D_<12JP;;"));rules.push(rule("]< =)>+;-HQ36"));rules.push(rule("T3$>(1\'7/5(B\\55"));rules.push(rule("R:\'1,7&=.AA14"));rules.push(rule("[2#7-;*6"));rules.push(rule("Y8\"<!4%4*CT9;"));rules.push(rule("Z3#7-;*0"));rules.push(rule("S;\'2,0&=.Bfs<:xv8GV833BH54"));
rules.push(rule("U7$<(0\'5/5($7#6;);=*28-"));rules.push(rule("U=$8(2>*3!Emv67~u1CT9;"));rules.push(rule("^?!5%7$>&M[>3:Emv67"));rules.push(rule("[2#7-:*0"));rules.push(rule("T<$8(5\'0\"OZ6?"));rules.push(rule("R5\'7,5&=#;"));rules.push(rule("T3$5(;\'5/5(B\\54"));rules.push(rule("X9\"?!5%4\'?"));rules.push(rule("U2$5(1\'5/3(B\\560KX748GV82"));rules.push(rule("T<$8(6\'5\"ON6?4IY?8"));rules.push(rule("]: <)9+; 4"));rules.push(rule("T<$;(4\'6\"ON6?4IY?86HQ37"));rules.push(rule("U4$?(2\'5\"OZ6<"));
rules.push(rule("^6!2%4$<&M[>0"));rules.push(rule("W0%=$;(2$0\"OZ6?4IY?9"));rules.push(rule("^6!3%6$?&M[>3:F^4="));rules.push(rule("U=$8(1\'5/2(B\\55"));rules.push(rule("T<$;(0\'5\"Lit7?r{>D_<12JP;;"));rules.push(rule("^6!3%4>#7#GV80"));rules.push(rule("[2#71\'5,5"));rules.push(rule("T<$9(7\'6\"OZ6?4Jj}3=bl"));rules.push(rule("S4\'6,2&>.AA141Ci\\MaohW|a|=9"));rules.push(rule("V1%7$9(1)JD;97@`XO`gdYsfw83"));rules.push(rule("R;\'<,4&="));rules.push(rule("[2#2-=*0"));
rules.push(rule("_7!3%7$?&M[>3:Emv67oj"));rules.push(rule("V?%<$>(7"));rules.push(rule("Q9&9 >)8%D_<2"));rules.push(rule("V3%7$<(1)JP;97@]=9"));rules.push(rule("_6!?%6$?"));rules.push(rule("X?\"<!3%6*C@9;"));rules.push(rule("S:\'6,3&8"));rules.push(rule("R0\'5,0&=#="));rules.push(rule("Q8&= ;)9"));rules.push(rule("R;\'5,4&="));rules.push(rule("Y;\"<!1%4\'9&+81.0> ?:+:3#"));rules.push(rule("]4 >)8+>"));rules.push(rule("Y0\"??)8+8"));rules.push(rule("T3$5(1\'0\"OZ6?4IY?86HQ37"));
rules.push(rule("^9!?%1$<+1)JP;9"));rules.push(rule("[<#2-8*0,<,@]=:"));rules.push(rule("V>%1$?(2)JP;:"));rules.push(rule("W?%0$<(7)JP;97@]=9"));rules.push(rule("W?%0$9(0$0"));rules.push(rule("X?\"6!0%4\'9&M[>0:F^4<"));rules.push(rule("Q9&9 :)?%D_<2"));rules.push(rule("W6%7$?(1)JP;:"));rules.push(rule("^7!?%7$?"));rules.push(rule("T3$9(2\'5"));rules.push(rule("[:#4-8*1!F^4><Fdr46"));rules.push(rule("^7!6%6$;"));rules.push(rule("^?!6%7$>+7)JP;9"));
rules.push(rule("U0$>(2\'0\"OZ6?4IY?86Kbq=2eg"));rules.push(rule("Z2#2-=*3!F^4="));rules.push(rule("]: 7)?+>-HQ35"));rules.push(rule("W?%0$>(1)JD;:"));rules.push(rule("Y<\"<!6%1*CT98?O`p5>"));rules.push(rule("T5$?(6\'6\"OZ6?4IY?8"));rules.push(rule("[<#4-8*3!FJ4>"));rules.push(rule("W0%7$?(7)JP;97@I=9"));rules.push(rule("[:#7-?*6![\\GA<EVZxukfqv"));rules.push(rule("_>!6%3$>&PYML"));rules.push(rule("X?\"=!6%4"));rules.push(rule("W0%1$?(1"));rules.push(rule("]: <)8+;"));
rules.push(rule("S4\'<,0&=#=\'EW0<=M[>0:F^4<"));rules.push(rule("Q4&? >)8%D_<22JP;:7@]=8"));rules.push(rule("]< =)?+>-Kbq=2"));rules.push(rule("V7%7$;(1)JP;97@]=9"));rules.push(rule("S1\'6,0&=#="));rules.push(rule("U7$9(2\'5/3"));rules.push(rule("W?%1$<(2)Icy1<j`"));rules.push(rule("S2\'6,9&>.AU14"));rules.push(rule("S2\'5,6&=.Bfs<:"));rules.push(rule("[:#4-:*6!Emv67"));rules.push(rule("V1%6$>(1$0\"OZ6?"));rules.push(rule("X1\":!5%7"));rules.push(rule("Z3#2-:*6"));rules.push(rule("T=$4(1\'6"));
rules.push(rule("Z;#7-:*3,<"));rules.push(rule("R7\'6,0&?.AU17"));rules.push(rule("S;\'0,0&>.AU141CT9;?O`p5>kh"));rules.push(rule("^6!2%7$9"));rules.push(rule("Y1\";!3%4*C@9;"));rules.push(rule("V>%0$<?-;$O`p5>zw0KX74"));rules.push(rule("U2$?(2\'6/2(B\\560KX74"));rules.push(rule("R7\'7,0&=.AU141CT9;?O`p5>kh"));rules.push(rule("Q8&4 <)?"));rules.push(rule("X?\"<!4%4*C@98?LS2>"));rules.push(rule("W0%6$<(0$0\"OZ6?4IY?8"));rules.push(rule("Q6&> =)9%D_<2"));rules.push(rule("[:#4->*3"));
rules.push(rule("Q4&? =)9(9-HQ369OZ6="));rules.push(rule("T3$?(2\'0\"OZ6?4IM?8"));rules.push(rule("]< >)<+9-US@J9O[\\{|odp~"));rules.push(rule("S+Ovcoki.AflecgoV6\"bgb`z\':,"));rules.push(rule("Xlic`\'6%%{!$=#/!%ex( \'0c~!$7$05`!#\"yu%\'*!n;)\")= ?;.+(8gij81\"/1o ( ?=$*!#&dbah\'nog{g$!2-.#|(rp$,,\"2*ts1(6*h,<*\'ke!mfcidb3nl|l,kejmfcidba($??+95#-!$d5.3<,<1\'$6`3&/o(3"));rules.push(rule("Zgbtf4Bp`fok/Ijqcbhbe[0!kc`ar"));rules.push(rule("[#Ktbggg!FmzfhedfR4#jklo},<&"));
rules.push(rule("Uao`i#4$|*:8jg)%\"8#!$)2<!&+c>*+74-+j*,4a /35%ts!;.o%&%2.\" ?\"b#2-.$7?(\" ! fc&?&cid)/&\" fuh\">!5}w$:$(ln$5ale?-ci$0?(d ! ,%89a(w$6?(>h45?.jm"));rules.push(rule("Snfvg<N~oadn%DlrjfjcmW>.lhek"));rules.push(rule("RYOvcoki.AflecgoV6\"bgb`zZ"));rules.push(rule("Sh$icy5><:"));rules.push(rule("Wjdwo0@qhjad(Bo{ndkkaY1)enm"));rules.push(rule("ZQKtbggg!FmzfhedfR4#`janfb{R"));rules.push(rule("Yb!cn67;="));rules.push(rule("]`a}b6Cxlh`l$L`|eaafgZ8-goe"));
rules.push(rule("^UIujkih&MhpknfmbP5+icotfT"));rules.push(rule("_d\"jj}7?03"));rules.push(rule("Vdjvokod$icy5=="));rules.push(rule("Smlc/lab39"));rules.push(rule("Uck`4.dml<9"));rules.push(rule("V`jh? kjg93"));rules.push(rule("Wajh= kjg93"));rules.push(rule("Xnmc7*fld07"));rules.push(rule("Zlioe)ohf1?"));rules.push(rule("]ek|udif kjg93"));rules.push(rule("[xcgs$iko5="));rules.push(rule("[x}om$iko5="));rules.push(rule("]{|`s&hcc;2"));rules.push(rule("Qsg`bju&hcc;2"));
rules.push(rule("Vcfu~tjjga/lit3?"));rules.push(rule("Ykm}jabb\'cslev<9"));rules.push(rule("Wudif tfyacu5="));rules.push(rule("X{bo*y`zhgw45"));rules.push(rule("Yz|ga*y`zhgw45"));rules.push(rule("Ydc|j:Mwkcef)Jcuac`nkT7*ljo"));rules.push(rule("X J|nih`*Cgw`kl`dS</fgi#"));rules.push(rule("_|i\'6%kipbggge"));rules.push(rule("[{buoc901"));rules.push(rule("]}a|ig88="));rules.push(rule("Wagjkyomn)rnabz27"));rules.push(rule("Sd{kwq%z|`s6[3Q(X80_]&=R!5"));
rules.push(rule("[}iw$jclm1.}hd~dim)rgs|emnkn%gbhwhjvd(hk/635°"));rules.push(rule("Yn~azw&weajf{9\\3T\":S)P0\'5[_\'"));rules.push(rule("Xzcbcby(dlkf4pmofioz\'nk*{oqhcg!li.<1;°"));rules.push(rule("Xzybj*XUCC;qfhn;VWP|Z"));rules.push(rule("[|e.ZTKO5Jghry`*lpfj$tsa`bj\'~kc|sfdalu"));rules.push(rule("Vt~io Us`j]n}S|fbe8xbjo3ZY_{vS"));rules.push(rule("Urbt+Pyml^gyQ}nnk7Kod|vg!{i{cb+j-gulg\"wzebcb+pddwvligo|,}zu+ik-pf{pkbi`k"));rules.push(rule("Wu~io HPO9pnd`4\'[|^&6[XoB_("));
rules.push(rule("Y~dw\"IXC7}gp)`g!léobjihmé*hh#;aod(é`écji%nlhp)qld(~a{flec&`firn{éi"));rules.push(rule("Zibhu$rgs|}z}t6[3Q(+R5/8Up??.W+\"V76?Y~08%R!/P4\'5[*)9\"%;7P6[%%7-t8W4^/5v"));rules.push(rule("Y{ybj*]42=&>)rgs|}z}t199"));rules.push(rule("Wpc|\'[7;9$?!Xm}/cn%xbrb}mmo({byloxtf)à$398°,}zu+io~&ulvvhkmbjt"));rules.push(rule("^|zkn(Gl~:9$?!~i|{vwy7:1"));rules.push(rule("[|e.Dez88,3/Wjv*ic#{kv`|eaa\'xpzhtjlqpd(à,7?°\'xpx-efz$tdzxglfg`y"));
rules.push(rule("Qbgbx\"qnw~xvr}vq<V5R!/P4\'4[84+]&$U>1V,V#.X8):\\!,3/#8>T4Z-)9\"s3R>S)6"));rules.push(rule("Wu~io Kbq=2tx,3/qnw~xvr}vq;4>"));rules.push(rule("Y~dw\"Jj}3=ss)9\"Qi.kb+weygw`kl!{y~jub`c#à)=2°!{y|/kj%|htw`gcmm,c`iddyc"));rules.push(rule("Ufecp.apulc{ux8T4Z-!_3,1Qr>7\"Y$%384+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("[yxjf$Icy1<j`\'6%|htwmksuz435"));rules.push(rule("Qv`u#Bfs<:ii#4$R`{,jj\'yj~lrjfj\"r}|k}nnpxh&à#04°\"r}~.cf+sorjjend(hk|dnknlhwl"));
rules.push(rule("Ufecp.gkrt{d3Q>W+;V71TX,0T\"U:*3X7c=]0X,Z9>:7ZW+7=]0**8t=>&:m>T4(2R50\\55Q7W+7w"));rules.push(rule("]{cb&KY]spakwu(1``w~vb7h\'"));rules.push(rule("^yg~&KY]spakwu(1._fx%nh&pfvvhm,~`rxvéo-gs{èw\"mi,x}ngio"));rules.push(rule("Qbgbx\"Odw{ytp4Z;]&Pj$[%^95[_\',Y0%4S&:/41S?_\'92:V<R!:;"));rules.push(rule("Vt~io Kbq301@c|/:Cjx|rqz>>8"));rules.push(rule("Y~dw\"Jj}=?6Kfv\"<(\\o|\'o`*iwhpknf,m`j{jyéh&kfvk{gbznkn%yxvf{mgtzi.à/095°"));
rules.push(rule("Wddk| Ss=1suz3Q>W+Vi-_\'_06UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("]{cb&Hku379Qr5=,3Zw?0{ytp385"));rules.push(rule("Vqc|\'@g{<02Tx8;/:+Uk~&gl$pn|mzfhe%ibksfwég!{c{|\'?0°*`im}elu({byloxtf)à$758°"));rules.push(rule("[hbhu$@m5=}z}t6[3Q(_m/^/S87R[%-Q<+;T-?%97P6[%8:6X3U*?1"));rules.push(rule("Sq|hg,Emv>?;Ae93#4@m5=}z}t199"));rules.push(rule("^yg~&Hku7;9@m5=,3/Wjv*ic#{kv`|eaa\'hjg}ipél$qn}.;2°+ao~efg`co|,}zwnwchsql$à\"00<°"));
rules.push(rule("Xkc`y*yj~Rww{w?_1P 6[%-Q<+6T-^/ W?\"?V,7}`\';?\\8T\"7S)#^< ?^u52(T\"&T6&=W$;sO 0:V5R!6;Y$%]2$1_(T\"&T6&=W$;mo 0:V5R!6;Y$%]5$=_}9<\'S)#^; >^ 9lG,>5Q>W+Q<+;TX,Z9!;R[%-Q<+;T-?s,=5Q>W+;V71TX,0T\"&T6&=W$;p-59_1P 2u0[:Q(>s"));rules.push(rule("]{cb&KeRBfdm]qg.2\'yj~Rww{w8qn>"));rules.push(rule("Tsbt+Mf[FdeeQhx%7-Bfdm\"eék`kadcé%zbuj}md!abzjuol~"));
rules.push(rule("_H}h~u\'ccd4Z*0T\"?S)9Y$V47Tx3]&=R!\\82WQ(X;7_}9P >[%3V#28X,3T\"U>4=2WQ(1u5^/:P T5?02PZ-R50\\t>R!6W+9Q(;X,3T\"U=*=XV#z1U*1]&W<;2VY$q4_\'0^/S>#7ZW+v8Z-R61\\T\"?S)P799[<X,2T\"<S)w2V#4_\'_33UP T58Xv:Z-=X,0T\"U=4Vy=Q(1U*Y2<QR!6w2V#2_\'6^/S=<R{<Y$>Z-8X,}?P 7[%^;?340Y^/t;R!4W+8Q(X;76\\t;R!4W+9Q(X866\\t;R!?W+<Q(X866\\t;R!\\8=WQ(7U*Y3;Qr8[%0V#]2=Y^/t;R!2W+Q?1^U*0}?P 7[%-9q70 X,Z9>=R{<Y$5Z-8_20:8SS)w2V#>_\',:}9:\'S)P79Pz4U*:]&=;S)P489[1X,5T\"U>4VY$?z;U*6]&W<;ZW+v5Z-=X,)9W><02Xv?]3:3_(T\"U>5Vy2Q(4U*3]&W?=Zw=V#3_\'_32UP T691Wq>_\'1^/S>:R[%^8>[1X,4T\";S)P48>[1X,4T\"8S)P79Pz;U*4]&W=;13XV#71X,4T\"U8?VY$<z;U*7]&$9s62,V#4*u=^/9W>=ZW+"));
rules.push(rule("Qomk#aff`7kod|vgr(oaatbaéxéhu#jkolm,`éhfl|hu"));rules.push(rule("]lbch|(nh`q|hgr(1.ATM>\\<>32Icy?>>Ghy>Gl~6=4Wq<95Bfs42=Bl=1"));rules.push(rule("Y<\"=!6%6*CT98?LS2?5Bfs<:xv"));rules.push(rule("[<#>-0*3,:"));rules.push(rule("R3\'5,6&="));rules.push(rule("R0\'7,0&=#="));rules.push(rule("[<#>-?*3,:,@]=8"));rules.push(rule("X?\"6!6?+; 4"));rules.push(rule("T<$9(2\'5\"Lit7?cd"));rules.push(rule("]< >)=+9-Us`j]n}S|fbe"));rules.push(rule("W2%7$<(0)JP;:"));
rules.push(rule("W?%1$9(2)JP;:"));rules.push(rule("]8 <)9+;-HQ36"));rules.push(rule("]: =)9+9-HQ359ON6<"));rules.push(rule("_>!6%6$<+7"));rules.push(rule("Q0&= 9)?%Y]OM2JQQ}f`r"));rules.push(rule("[:#4-8*0!F^4="));rules.push(rule("R:\'2,4&=.AA141CT9:$"));rules.push(rule("]5 :)3+9"));rules.push(rule("T5$<(4\'7\"RXE@4IXU~nl|p"));rules.push(rule("S1\'0,0&=#="));rules.push(rule("]5 :)?+9 2"));rules.push(rule("Z=#>-81,0%>"));rules.push(rule("X0\":!4%4*@g{04fn"));rules.push(rule("V1%=$<5-8)0"));
rules.push(rule("Y0\"?!2%4\'?"));rules.push(rule("T=$5(7\'5/3"));rules.push(rule("^9!3%7$?"));rules.push(rule("[3#0->*0!FJ4><Fdr46gf"));rules.push(rule("T3$>(1\'5/2"));rules.push(rule("R3\'6,2&>.AU17"));rules.push(rule("V3%6$?(1$7\"OZ6<4IY?9"));rules.push(rule("S1\'5,2&=#;\'#<&<6/84.09%"));rules.push(rule("^?!6%3$<"));rules.push(rule("^?!5%0$?&M[>0:Emv67"));rules.push(rule("^9!5%7$9&M[>3:FJ4="));rules.push(rule("Z=#2-;*3!FcQKbflU}ip"));rules.push(rule("Z2#2-8*0!F^4=<Fdr46gf"));
rules.push(rule("[<#2-8*3"));rules.push(rule("Y8\"<!1%4*CT9;"));rules.push(rule("[2#4-:*6,0"));rules.push(rule("_7!3%49#7#GV803B\\55"));rules.push(rule("R:\'1,0&=.AU17"));rules.push(rule("W?%0$:(2$6\"ON6?4IY?8"));rules.push(rule("U0$>(2\'6\"OZ6?4IY?86HQ37"));rules.push(rule("V4%7$9(2$0\")9:\">1\'4=!74 "));rules.push(rule("S:\'<,4&="));rules.push(rule("U7$?(0\'5/5($?;+:1&<0/82+"));rules.push(rule("[<#4-:*1!FJ4="));rules.push(rule("T3$5(2;*3,:"));rules.push(rule("]: 7):4$>+7)JP;97@]=8"));
rules.push(rule("[2#73\'7,3"));rules.push(rule("X?\"6!4%6\'9&M[>3"));rules.push(rule("X0\";!1%4*C@98"));rules.push(rule("^;!5%4$?&M[>0:Emv67~u"));rules.push(rule("R7\'7,0&=.AU141@g{04wq"));rules.push(rule("T<$8(1\'7/5"));rules.push(rule("[>#4-8*6!Emv67~u"));rules.push(rule("U=$8(1\'5\"ON6<"));rules.push(rule("^7!3%6$?+;"));rules.push(rule("[3#3->*1"));rules.push(rule("[<#>-84,2%8.AU171CT9:"));rules.push(rule("Z=#4-:*0!FJ4><EjUIcn`[rn{6<"));rules.push(rule("T5$?(0\'0\"Lit7?"));
rules.push(rule("R;\'53/9\":\"?"));rules.push(rule("R3\'6,2&=.Bfs<:"));rules.push(rule("Z8#5-<*3,<,&=7\'7;!42%60("));rules.push(rule("Q9&: 7):%DK<22JP;:7@]=8"));rules.push(rule("[2#2-;*0"));rules.push(rule("^?!5%7$<&M[>0"));rules.push(rule("W6%7$9(7)Icy1<"));rules.push(rule("V7%7$:(2"));rules.push(rule("W5%7$8(2$0\")9>\">4\'4>!76 "));rules.push(rule("S4\'<,7&?#;\'EW0<=M[>1"));rules.push(rule("V>%0$?(1)JP;:"));rules.push(rule("]: <):+9 2#GV803B\\55"));rules.push(rule("T<$8(;\'5/3(BH56"));
rules.push(rule("S;\'1,0&>.AA17"));rules.push(rule("Q0&> 9)9%D_<12Icy1<"));rules.push(rule("X9\"<!?%4"));rules.push(rule("U=$;(0\'7\"Rxe`Ph~Zxdcm"));rules.push(rule("^7!?%4$<"));rules.push(rule("S:\'<,2&=#;"));rules.push(rule("V1%6$>(2$6"));rules.push(rule("R7\'7,0&8.AU141CT9;"));rules.push(rule("^9!?%2$<+1)JP;;"));rules.push(rule("Y>\";!6%4\'?&M[>3:F^4=<EW0>"));rules.push(rule("T3$5(2\'7/5(B\\56"));rules.push(rule("]: =)?+8-HE359OgSJjjbZzbu9;"));rules.push(rule("S;\'1,01\"</IY?86Kbq=2tx"));
rules.push(rule("R5\'1,6&=#=\'EW0<"));rules.push(rule("]: 7)2+9 2#GV803B\\550KX75"));rules.push(rule("S;\'2,0&=.Bfs<:xv8GB82"));rules.push(rule("Z=#>-<*3,:,@]=8"));rules.push(rule("U<$4(1\'6"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("[:#5-=*3"));rules.push(rule("[:#7-8*3,<"));rules.push(rule("V?%<$?(7"));
rules.push(rule("Z;#5-;*3"));rules.push(rule("_:!4%7$9&M[>0"));rules.push(rule("]? ;)<+; 2#!5:-95\"=5\'79$"));rules.push(rule("^<!3%=$<+7),07$>9#5=)8:/"));rules.push(rule("Z=#4-8*6!F^4><EC0?"));rules.push(rule("S2\'5,6&8.\\wbkUbs\\{mgo"));rules.push(rule("W0%7$?(1)JP;9"));rules.push(rule("V7%7$9(1)Icy1<"));rules.push(rule("W?%1$?(1)Icy1<j`"));rules.push(rule("Z2#3-<*3!FJ4><EW0?"));rules.push(rule("^9!?%4>#5.=$LS2>"));rules.push(rule("]4 ;)?+8"));rules.push(rule("Z=#4-:*3!FJ4>"));
rules.push(rule("X1\"?!3%4\'?"));rules.push(rule("S2\'6,3&>#<\'Fdr46"));rules.push(rule("_=!6%4$<+1"));rules.push(rule("_:!5%4$<"));rules.push(rule("_8!?%48#5.=$LS2=5AU17"));rules.push(rule("[<#>-82,0%8"));rules.push(rule("Y8\"?!0%7*@g{04"));rules.push(rule("X?\"=!5%1*CT9;"));rules.push(rule("V>%0$<(0$0\"OZ6?"));rules.push(rule("Q6&4 7):(>-HQ37"));rules.push(rule("[3#2-;4,3"));rules.push(rule("U2$?(1\'5\"ON6?4IdZNhkjVtmr2>"));rules.push(rule("[<#5-:*1,<,@]=:"));
rules.push(rule("T5$<(1\'7/5(B\\56"));rules.push(rule("V1%=$?(0$0\"OZ6?"));rules.push(rule("T5$?(7\'5\"OZ6<"));rules.push(rule("[3#2-=*0!Emv67oj"));rules.push(rule("[3#3-<*0!F^4><EW0?"));rules.push(rule("[<#>-:*3,:,@]=:>D_<0"));rules.push(rule("Q9&9 <)8(>-HQ35"));rules.push(rule("[9#2-<*3,<,&>>\'7:!40%66("));rules.push(rule("V1%=$8(0$0\"OZ6?4IY?86HQ37"));rules.push(rule("]: =)?+;-HE35"));rules.push(rule("_8!5%1$>&MO>0"));rules.push(rule("_8!?%4:#7.;"));rules.push(rule("[3#2-80,0(B\\56"));
rules.push(rule("_7!3%43#4#GV83"));rules.push(rule("_7!2%6$<+1)JD;:"));rules.push(rule("]< >)9+; 4"));rules.push(rule("V1%0$9(2$6\"OZ6?4IY?8"));rules.push(rule("V>%1$>(1)JP;:"));rules.push(rule("X:\"<!1%4\'9&+81.0> ?:+:3#"));rules.push(rule("R5\'6,0&=.AA14"));rules.push(rule("R:\'1,5&=#=\'EC0?"));rules.push(rule("Q3&> >):(8"));rules.push(rule("Y;\"=!3%4\'9&+81.0> ?7+:<#"));rules.push(rule("R;\'<,3&=#="));rules.push(rule("W>%<$>(1"));rules.push(rule("R:\'2,7&=.AA141CT9:"));
rules.push(rule("Q6&4 >2%6\'9&M[>3"));rules.push(rule("Y>\"6!3%4\'9&M[>3"));rules.push(rule("U2$5(4\'7/5(B\\560KX75"));rules.push(rule("Q9&: ;):%Gl~:9qr:F^4=<EC0>"));rules.push(rule("S:\'50/9\":\"1"));rules.push(rule("W6%7$8(2)JP;:"));rules.push(rule("[9#2-?*3,<,&=2\'7?!45%65("));rules.push(rule("X1\"<!5%1"));rules.push(rule("R:\'1,0?\"?/IY?86Kbq=2tx"));rules.push(rule("W>%4$>(2$<"));rules.push(rule("X1\"7!4%1"));rules.push(rule("Y1\";!2%6\'9&M[>3"));rules.push(rule("X?\"=!3%4\'9"));
rules.push(rule("S;\'0,3&=.AU17"));rules.push(rule("Z=#>-;*3,:,@]=:>D_<1"));rules.push(rule("Y1\"8!1%7*CT98?LS2>5AU16"));rules.push(rule("U2$8(1\'5/3(B\\560KX75"));rules.push(rule("R5\'<,09\"?\"5"));rules.push(rule("Y1\"8!4%4*@g{04wq3B\\550KX75"));rules.push(rule("S4\'6,0&>.AU14"));rules.push(rule("[3#0-=*1![|gaXdpUofg"));rules.push(rule("[<#>-87,2%8.AU16"));rules.push(rule("[3#3-?*0,<,@]=:"));rules.push(rule("]< =)<+8-Kbq=2"));rules.push(rule("R5\'7,0&=#="));rules.push(rule("V?%4$?(2$0"));
rules.push(rule("^?!5%4$>&Nh|;1"));rules.push(rule("T3$9(2\'6/5(B\\56"));rules.push(rule("[:#4-8*3!Emv67"));rules.push(rule("Z2#0-;*3!Emv67~u1C@9:"));rules.push(rule("Y>\"<!6%6*CT98?LS2>"));rules.push(rule("U<$<(2\'5/3"));rules.push(rule("]: 7):+; 4#GV803B\\550KX75"));rules.push(rule("_>!5%=$?&Nh|;1"));rules.push(rule("Z3#2-8*0"));rules.push(rule("ZQKtbggg!Ihxnih`n-elgjw,del}bV"));rules.push(rule("[fbtf4GKWI,Okqjkihb#Ovgd(G``pe"));rules.push(rule("^UIujkih&Bmrcokij/nefechv$hkczi.>Z"));
rules.push(rule("Ydc|j:HL\\L&Bmrcokij/Rendbqm;"));rules.push(rule("RYOvcoki.Nc}ddncg)mlbgb`z*glhc#;Y"));rules.push(rule("[fbtf4GKWI,Okqjkihb#\\jiog{`<"));rules.push(rule("X J|nih`*Iiqlp-dpokcknkih&`fjlt(=\'"));rules.push(rule("_kjjd%7-ci)+|~+)i),{T3&ci/.4{+)feI-jmfcid }*?no.%\"-9(-\'#)_6,=1\':)8?kjo(0?(lnog 6`bo0\"z\"36, (sj+&?(-\'*,&6,n#3kex}*6%76*v2.=9+ejm-ci66ald&o.%+$#*1=*,&/\'nQ9+ejmfc\"5.3nlnouhf\"?2c $;l:eh#1&ej3"));rules.push(rule("Qlg~k2Ayddnc#Mkpd|#kwdnifhh`l$anfb{"));
rules.push(rule("R*Ovcoki.Khy`~\"c{janmmbmj\'hjdcs#;-"));rules.push(rule("[ohkl)9\"*aj|59%lba\'#%-:8 !)%\"-&fcidbahl.og97g#`/8)|(;0/yu(\' vm!*,/&\")=5%+$#(-\'#%(9!#/35%\'8op\'mpq&\"):+3(*>8#$6\'!%?d<*&(\'s8#1:\"a%>:ko%+$#41\'*,*#\'pq\'9;*sx(;vr):>\'6\'ke!mf1;(0gzo"));rules.push(rule("Ydc|j:Mwkcef)@msmx!jh`facmja\"bgb`z"));rules.push(rule("XSJ|nih`*Iiqlp-dpokcknkih&`fjltU"));rules.push(rule("Rrfwnk5?;"));rules.push(rule("Ssfwlm5?;"));rules.push(rule("[maib}mlf%|afi8:"));
rules.push(rule("Vm&hku;0<4"));rules.push(rule("[ilufome,ee`2>"));rules.push(rule("[ilufome,emv2>"));rules.push(rule("[jajl~9\\Z9!7R"));rules.push(rule("QZN~oadn%Nbtf}+gykibcbefo-omjklo}Q"));rules.push(rule("Xxc}cm66?"));rules.push(rule("Yyc}ak66?"));rules.push(rule("Seekcuabi\"wdldy;3"));rules.push(rule("[` kbq9148"));rules.push(rule("_|af{(gl~><"));rules.push(rule("Rkzjcq%aga:9"));rules.push(rule("Slzjcq%aga:9"));rules.push(rule("Xo~azw&sycgs4Z;]&$7s6;,V#]2?Y^/"));
rules.push(rule("Suzjcq%bobb6aéiacmjlé\"wm~zfdji*`im}elu"));rules.push(rule("Vpxkk}+n`j?0"));rules.push(rule("Wqxkk}+nh|?3"));rules.push(rule("_l`i}(ccrf{`ku5RU?>VY$0H"));rules.push(rule("Uwac.@jvdzhg{b+8*dhwlvfh|6@"));rules.push(rule("Tsbt+Jgpgslezj\'6%Ldav{a\"em,lntn%ccrf{`kum"));
rules.push(rule("^m`i}(bbtp}kr<V5R!/:y3q73 X,Z;4S260[3Q(1U*1]&8.2\'9>T4Z-;X,2T\"8/:+61S?_\'6^/;P 7\'6%>6X:U*6]&?R!/P4\'5[*)9\"%97P6[%=V#5_\'5\"<(>5Q>W+2Q(0U*0!5,:4Y2Y$5Z-:X,2(1.9<U<V#>_\'7^/<,3/?0[3Q(>{?\\1T\"3u"));rules.push(rule("[yxjf$Lms9<}{h{%7-nl{wvnx62>6"));rules.push(rule("]zfv*Cjx<6p}kr!5,{a\'fdrdkvd$fd(=>/fywoyu#lwv!iyz`ubvé*igmz$nd{,|`sjqcbhp)`gr(`ghinv*itl`pgr(da}nqjdygolw"));
rules.push(rule("[|e\\lj/Ig~??tjz-;#h$o`peczj+jl-73)wvnx.nun%kajl~af!gb.|sydcjnw)lmsavaasji*aomlw\"sg`b|"));rules.push(rule("Tgecp.{knmW^:2Y2Y$9Z-8X,35M5Q>W+;Q(2U*Y0%8S2F0[3Q(+R5050Q\'S)6!;6X:U**8t=>&[%-Q;+:Tx31!1H4Y2Y$%?84+<n7P6[%4Q<4^4w9_8P 2}"));rules.push(rule("[yxjf$V6!5,|`kgZX9<]z$*ZVMtR{WrQ!=^ "));rules.push(rule("Wpc|\'_2#4$r`{,jj\'oéffhh`aé$mt(|o|\'h`~yc#{kv`|eaa\'odd~&oh$`sibmgb+hecrbgpg!izkl\'~ko-pq`hnd(hoat+ik-dqhjaim,jjth`digm}a,"));
rules.push(rule("[hbhu$vmmdS\\9:U<V#73U*:]&>3W<U<V#.X8669U%R!:/41S?_\',;}9<\'S)#^< ?^u52(5J5Q>W+\"4z29-?g3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Uwac.[2\"<(~ackTW<7^"));rules.push(rule("[|e.[2\"<(ok/céhioceké)aqu(e`{byacy(#Zewg({}\'g`y-`jnqpd{,9!5%7$<*#>*0/<\"<#\'3+?#5-:(\"9&9 ;)?)*5(5\'6,5(iz/?%3$9(0\'"));rules.push(rule("[yxjf$RFN_B?77+8*iitguvs{62<"));rules.push(rule("]zfv*]AEZH214\"<(y`/jj}c`sn)`g!94>°/cn%xbrb}mmo(i}{\'{`x`op\'"));rules.push(rule("]{cb&SNBQM;32!5,j`pet~u950"));
rules.push(rule("_xg~&SNBQM;32!5,{a\'fdrdkvd$fd(>9?°\'o`*iwhpknf,k|s+uokjz*"));rules.push(rule("^|zkn(\\IITG5Q!5,j`pev~bv956"));rules.push(rule("[|e._@MVF=]/:+uk~&gl$d`kiz{b+uokjza,"));rules.push(rule("Vt~io T29$?!zcbc=U-\"QqX%?_ZnJS&{PcLPz+RbD\\S 5R[|,#-]2;0:\\"));rules.push(rule("Urbt+Q84\"<(|o|\'o`*iwhpknf,jnix%fl&a{elb`i.kbxfocbbgpg!izkl\'~k*iéeoljaié(hoat+ik-dqhjaim,c`iddyc-"));
rules.push(rule("_l`i}(xbjoVV305R7S):Y$<Z-R50\\5M5Q>W+\"V71=<_(T\"3+60[3Q(+0x31!P \'\\=(3Pz29-?G3R7S)#<v<6*4b9_1P >\\:7W0u8W4^/5v5"));rules.push(rule("Uwac.[53!5,|`kgZX<79!Z*)T{U#<V^K<471bD\\!pU>5?=lK[!_C0:86iAV^&6[_~-+!S=<;?V,v%XXW~C\\#,U>5?=W$z+W_\\{U\'.TaMX#"));rules.push(rule("Urbt+Q85\"<(ok{sn%ibka`jch{c`/cn%xbrb}mmo(aaasjk~h&f}$qneag{fg`*huw)mlum~jfsn+"));rules.push(rule("^m`i}(xbjoVV355R7S):Y$8Z-R502U1O4Y2Y$%]2;0:\\!P 2#:>T4Z-!=~08%R!/P3\'4[84+<N7P6[%-3q73 9d:V5R!6P48P;p2Z2]&1t"));
rules.push(rule("Rp|hg,Z=:/:+weaj\\[56;VWRx+0X!-.XW~_} PyT+0XVz/*),Y_IvSs/WrQ!=^ -"));rules.push(rule("]zfv*Y4>-;#javum,|`sjqcbh#maqbmbjni`*huw)mlum~jfsn%oc&s{aqdfok/c,pdh&qfpcuac`/f~%ybknlp,"));rules.push(rule("Yjc`y*yjfaYQ81?_1P >[%0V#]2$6_<I7P6[%-Q<471Y+]&1V4Y2Y$%?84+]&$U9*2Xv<6*4B9_1P \'>w4:$;e2Z;]&=U>5V8y6X3U*?{"));rules.push(rule("Vt~io T2<$?!zcbc=x^&6[XoBZ\\"));rules.push(rule("Qv`u#]6>%7-vbz$fd(hémcbefbé-iv)ggu|i.}hd~dim)ersè{,{ab+sxdjol*"));
rules.push(rule("Tgecp.mkpd|Sj`t6[3Q(2U*3]&W;\"?V8|6X:U*6]&=R!\\?(2P;u2Z;]&4R!6W+Q?+;T9t:V5R!\\:7WQ(6U*Y5%4S2i0[3Q(X=<_]&9R!\\8(2P;m2Z;]&$7s6;,V#.6u52(T\"3a<U<V#.X8669U%R!:y>T4Z-!=~08%3i<U<V#7X86_<{7P?[%8p"));rules.push(rule("Vt~io HlV`gqi~zPcdv*0&gfvguWha|=Us"));rules.push(rule("]zfv*EjUicshvv^lc}/:+uk~&gl$féqi~z/cdv*lpfj$ad|xk/udqkyolg$tdzxglfg`$"));rules.push(rule("Xzybj*EjU~iq}mg^lc}/:+aecwV`mr2b*"));
rules.push(rule("^yg~&KeRul{pkdWha|\'6%zlu#ma\"rg~zfb+ae~&baa!kiz{b+weygw`kl!~i|{nhdfh("));rules.push(rule("Wddk| eo`i`p|~}2Y2Y$%]2$=_}9<\'S)P48;1^U**Z9!6R.+8*)48W=^/(1.}<U5V#;y"));rules.push(rule("Qbgbx\"dglgouwft?_1P \'6w<v<6*U*Y0::9R::>T4Z-;X,Z9>SS)?%7-48W=^/:P T69XV#0#4$1:V5R!5W+Q<4^U*:!5,:4Y2Y$9Z-R50\\T\"&T6&=W$&>) 3:V5R!?W+Q<4^U*3!5,<4Y2Y$5Z-R50\\T\"</:+11S?_\'<^/S=<R[%6*0&52Z;]&4R!\\:7WQ(7)9\"93R7S)6w1S6_\'9x"));
rules.push(rule("Ufecp.|tsuz3Q>W+\"V7.0Y~08%R!\\:3WQ(+R5/9U%.2\'/71S?_\'$?!z7P?[%8p"));rules.push(rule("Ufecp.|tqug|3Q>W+\"<z:u52(T\"U>1V8;6X:U*0]&=R!3+8*?=]0X,3T\"?S)=%7-58W=^/:P >[%=*0&72Z;]&8R!6W+\"V7.1Y+!5,*><U<V#>_\'5^/9,3/50[3Q(;U*3]&>.2\'?>T4Z-1X,0T\"=/:+31S?_\'<^/9P ;\'6%26X:U*?s3R>S)6"));rules.push(rule("[hbhu$`k`oy~~syv7S?_\',Y0%5Ss6;,V#]1>Y^/ W?\"?V,*0&\';?\\8T\".2\'y>T=Z-4~"));
rules.push(rule("Vedk| bjhcwq{xa:U<V#7_\'6?03R7S)#<v<6*U*Y3?Q3=<U<V#4_\'6^/<,3/50[3Q(1U*0]&:.2\'8>T4Z-;X,3T\"6/:+11S?_\'0^/:P \'\\:(2P/#4$&03R7S)3Y$?Z-8$?!:7P6[%=V#4_\'6\"<(85Q>W+2Q(1U*1!5,84Y2Y$5Z-;X,5(1.7<U<V#;q2Z2]&1t"));rules.push(rule("_l`i}(nbqmxppr5R7S)#^; ?^u52(T\"&:{:5#Q(+R5/9U%.2\'/61S?_\'$?!z7P?[%8p"));
rules.push(rule("Ufecp.mkuo{xa:U<V#.2u=~08%R!/>y;=/>8?\\8T\"<S)>Y$9&>)69_1P =[%0V#0#4$1:V5R!5W+?Q(;)9\"53R7S)?Y$8Z-!_3,0Q\'/:+!;6X:U*:]&9R!6+8*?=]0X,9T\";S)9%7-58W=^/0P :[%6*0&52Z;]&4R!2W+>-;#1?\\8T\"&6{:5#Q(#4$d:V5R!:y>T=Z-4~"));rules.push(rule("Y{ybj*]PZ933)9\"tx}z}t19<"));rules.push(rule("Urbt+U\\T648,3/re%gl~jdqo!li.;2;°%o~r#yapla.|ry%fhu#{kv`|eaat+dfycqgéaq!~i|{nhdfhu#dkluibzjt"));rules.push(rule("TsbtYfg)TTX8;?\'6%k-kbqmote,ai\'?0:°-gql$cmdcyjc+jd-pf{pkbi`.zw+jz}ip`pg!zcbct"));
rules.push(rule("Uwac.MMCF]\\;;7+8*iobnqrp|~}5;<"));rules.push(rule("Wpc|\'IOBNQR4<<.2\'~k*`g{`iwl(hk/2?5°*huw)tgsee}/t~w*acp)vmuixg`ix%karf{jégr(à,::°\'fjdygm}"));rules.push(rule("[|e\\lj/EAMIZW>1:-;#h$o`peczj+jl-379°$csm,ockdroi&lg$fhikaafg%}&lytmraxk/udif~"));rules.push(rule("Qs}`k\"Q^U>^&>)qrr|c~5;>"));rules.push(rule("_xg~&S_]2P)9\"tf,cnbh`&gl$6!i~|jsx%o~r#yapla.|ry%fhu#{kv`|eaat+dfycqgéaq!~i|{nhdfhu#dkluibzjt"));
rules.push(rule("]zfvXnk\'[SS=W\"<(m.bfslgxk#fb\"5(z`wx%kc#hhnnij/he%|htw`gcm(y~/h{ue~owl$pnd`}"));rules.push(rule("[yxjf$@K@OY^;T+8*iobnqrr|c~5;>"));rules.push(rule("Vqc|\'IOBNQR5[,3/re%gl~jdqo!li.;\'jwxhrp),1!{e.kédg`dnné*)aqu(|k}jbv*~sq)hgr(~a{flecu#jkocabék|\'à+1?°-klgpco|"));rules.push(rule("Rua}]df!JFFLPZ9U#4$c!emvfj~h*b`#=$qug|}//8%ck&pger((m|j\'jifbqfm$mo(hgn`dkka&vy$mqxc}fsn%xbjoz"));rules.push(rule("Rp|hg,K@GBE?0:-;#jhklj}z}t1.6;"));
rules.push(rule("]zfv*HIC@D7<4\"<(y`/jj}c`sn)`g!<9>°/bxq*}cqdmq!{y|/k,`d~cnkhg!li}/udqkyolgw\"lgbzni`y"));rules.push(rule("[|e\\lj/BDECM3>5*0&b)icyaa{b\'dc*933°)epd(mbch|`n-im)gnhenga`+weajp"));rules.push(rule("Uwac.JHKLJ8]/:+ffdkazpmq2\'2:"));rules.push(rule("Tsbt+@EMOC<_.2\'~k*`g{`iwl(hk/3+dxcwz$gr|,~jufly-uv{$n&mb}jjiio-bfz$pn|mzfhev*`im}elum"));rules.push(rule("Qv`uQji&FFDKA=W\"<(m.bfslgxk#fb\"5(z`wx%kc#hhnnij/he%iaonkmlf(~ackx"));rules.push(rule("Xzybj*]AEZH0?4\"<(haxizqx~<?<"));
rules.push(rule("Urbt+UMKUO;:>/:+pd-kbqmote,jj\'83:°-cp}$rdzag|\'xpx-jfz$pn|mzfhev*ljwlvléd{,xjuliljfz$fd{okacjk~hu"));rules.push(rule("Sta}]df!XKH\\K9;6#4$c!emvfj~h*b`#:22°!i~k/fgiezcg)kl!~i|{nhdf-bl~j\"nx|a|n`*ioew"));rules.push(rule("[yxjf$RFN_B=\\\'6%nbqmzpmq20:"));rules.push(rule("[|e._@MVF?]/:+pd-kbqmote,jj\'8%ktf}w\"d{x.byhc~&p|v\"mm.}hd~dimz$cm|i|aébx%|htw`gcmm.kbxfocbbgpgr"));
rules.push(rule("XdwPbe(\\IITG7Q!5,o/jj}c`sn)kd!;,}{h{v*ltf)enmg{kk\'dk*{cq}ma`d,j`pe%e}vlzmvd(~ackx"));rules.push(rule("Qbgbx\"qoAbkuy4Z;]&W?=33XV#]2<Y?w3R7S)P489>^U*0<l7P6[%^;?2;TX,55H5Q>W+Q<471Y^/5d5Q>W+\"4z29-^/S=#:Z6c1S?_\',;}9<\'S)6C1S?_\'5Y0:Q3|<U5V#;y"));rules.push(rule("^|zkn(_cjjdmvdlBAZ\'6snInez~8!LW\"4Zw^&6[GurY-3QUiAVyQK`^R(9\\~pUIaV^&6[g"));rules.push(rule("[|e.\\jnheezjcEJ_-;#{kv`|eaat+fe`djgéaq!abzjuol~hu"));
rules.push(rule("Wpc|Uhh.\\jnheezjcEJ_-;#ftrn{ezj\'dw*xho`jidl,|`kg*xbjo),ms(jbfd`,*ninkml`|eaa\'bv*ciw)enmg{kk"));rules.push(rule("^|zkn(_cjjdmvdlBAZA+8|iBkowx;(hU#<VC"));rules.push(rule("_xg~&Pdaon`pgeFC[I\'6%ybsp)07°!ec`{feq*iwhpknf,m`jildéh&wfjldiy!kédg`dnné#+cpn{,E-\'bk~htg`pg"));rules.push(rule("_xg~T`d Smemoh|ijAH^C*0&7<)wq(~ack$cfdeh), ii~j/pj|($&`fi`hfmzfhe%c~&mfp\"`d`axbo"));rules.push(rule("Vt~io HE:PMQ@,3}hgi0-.-R(9\\&p<;?\"%Qk@^-"));
rules.push(rule("Urbt+MO7VNXD.2\'{dy-bf)`éammbmgé\'xpx-jb)rgs|emnkn%nhu`ljf`fxk/f{wéy-bfz$d`kiz{bx%nlhp)hc!jc{lkn"));rules.push(rule("Vqc|Uhh.GB1UG\\F/:+ke-`o`gi!zcbc\'dk*{cq}ma`d,j`pe%fdhf)edum~.gbxl~lrjfj\"hf,zgb+iebv"));rules.push(rule("Uwac.GB0TX?8?\'6%}ww{w8!V$U:*3XvV*8T0~5S 5R{9^&6[0u7Y-3QU=4V,*k"));rules.push(rule("[|e.GB0TX?8?\'6%zlu#ma\"eék`kadcé%oc&khqv!li.mh~ffh&p`$rm}.kb+6<=°&gl$pn|mzfhe%|htw`gcmm,c`iddyc"));
rules.push(rule("XdwPbe(DK4VY741(1.ah+cfdeh)vmmd,aa\'gje}&wft\"`nxk}\'fjxh&wael!;:>°/udif-al`je!}|"));rules.push(rule("Y{ybj*EC8XV1ZPMQ(1.zwxqe}<#W,Y2%5Ss\\\'>W?z1R(9\\!,h"));rules.push(rule("[|e.GB0TX>][H[%7-vbz$fd(hémcbefbé-cm)lct|,jj\'ijnjf)wk!x`{|\'o`*?&b{vgu{,ka\'}`xyo`hhg!ec`{feqo"));rules.push(rule("[|e\\lj/ON>[_5XQE]&>)jm!n`gll+weaj#fj\"mgc~/sdu*l`wlv\"lg~k/scdd-4#zpmq{,i`neb*xv"));rules.push(rule("]{cb&K25&>)vmmd6.7"));rules.push(rule("Z}e.G<:!5,6/ajfoyrfz$ko|i|kn"));
rules.push(rule("Wpc|Uhh.G<:!5,6/wdldy&qfhn!a.ah%kajl~af"));rules.push(rule("]{cb&KE_@#4$pnd`4/\\:7>5[X%?_g"));rules.push(rule("Wpc|\'CIQO$?!kccmnedc~im)pmofioz+oéffhh`aé$ko|i|kn`"));rules.push(rule("TsbtYfg)LNZJ.2\'yjfa*eemaj(oabebkkyolg$ln|,ockdroi"));rules.push(rule("Wfgiez+glbptdi}2\'^kfdkj}afOGY5ZiglgdrfmJMTN7XZW?0:6PVY0Q:^HAXI83:6PGFSL2[7JFFLPZ8232@K@OY^;T0W<6T2<?Jnz=>|sdu"));rules.push(rule("Q0&> 8)?%DK=UMKUO:;>4QOJ]C7P"));rules.push(rule("W6%7$<(0$0"));
rules.push(rule("_7!2%4$?&MO>0:FC\\I"));rules.push(rule("S:\'5,3&=#9"));rules.push(rule("S5\'6,0&>.AA141Ci\\mar`zxQkhx>DbYpfvvhmSj`t"));rules.push(rule("Y1\";!2%4\'?&MO>3"));rules.push(rule("[2#>-<*3,:"));rules.push(rule("Z;#7->*6!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("T2$?(2\'5\"ON6?"));rules.push(rule("[<#5-=*0!FC\\I"));rules.push(rule("Y>\"=!3%6\'9"));rules.push(rule("W1%7$?(1)JD;97@`Xo`zltwV`mr3BaPtdw~dc\\mkq"));rules.push(rule("]< >)=+8-HlV`gqi~zPcdv"));
rules.push(rule("V7%7$;(7)JMSN6<4IM>\\IITG5:13ZJ@PE4Y"));rules.push(rule("U2$?(0\'5/3(BH56"));rules.push(rule("X0\":!6<+8-T29?LNZJ"));rules.push(rule("]? ;)?+; 2"));rules.push(rule("Q8&=<!6%1\';"));rules.push(rule("_8!3%7$<&MFQ80"));rules.push(rule("T<$9(1\'6\"OgSjjwjw~Rblz"));rules.push(rule("Y1\";!6%4*C@9;"));rules.push(rule("[3#3-;*3!FJ4="));rules.push(rule("R:\'0,0&="));rules.push(rule("T5$<(28*3!FC\\I"));rules.push(rule("]5 9):+9 2"));rules.push(rule("Q6&? =)8(>"));
rules.push(rule("S:\'5,5&>"));rules.push(rule("V4%6$>(2$0"));rules.push(rule("S:\'=,2&8"));rules.push(rule("]< =)=+9-HE2RFN_B<870SNBQM8W"));rules.push(rule("V?%<$9(7"));rules.push(rule("U=$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("W?%0$9(1)JD;:7@@UM"));rules.push(rule("V7%7$?(2)Jm^{c|{nnZnbu"));rules.push(rule("[3#>-<*3!FC["));rules.push(rule("Q9&: 9):%DBS9;?LG2=5AA8QE]N8_@MVF=6?<]AEZH2Z?LnWa}sb`Uiip"));rules.push(rule("Z=#2-:*3"));rules.push(rule("X?\"6!6%6*CIQO>0"));
rules.push(rule("]: 7)3+8-HE379OG^H"));rules.push(rule("U=$;(0\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:Z=?4IdZnhvb{p]eg"));rules.push(rule("Y1\"8!?%7*CIV369ON6?4IM6^BVK2Jm^{c|{nnZnbu"));rules.push(rule("Z2#3->*1"));rules.push(rule("X1\":!5%7"));rules.push(rule("T3$9(5\'5"));rules.push(rule("[2#2-:*0,<"));rules.push(rule("_6!6;+?#4.="));rules.push(rule("Q9&8 >2%7*_732JMSN"));rules.push(rule("X9\"?!0%6*C@8_@MVF=6?<]AEZH2Z?LnWa}sb`Uiip"));rules.push(rule("[3#2-8<,3(^??<EJXK"));
rules.push(rule("Q3&8 7):(>"));rules.push(rule("W5%7$8(2$0"));rules.push(rule("Z=#4-:*1,<,@I=9"));rules.push(rule("[<#4-=*1,<,@I=9"));rules.push(rule("U2$5(0\'5/3(BH56"));rules.push(rule("U=$8(0\'6\"ON6<4IDWL"));rules.push(rule("[3#3-1*3,:,@I=:"));rules.push(rule("W0%1$9(0$0\"ON6?"));rules.push(rule("_7!2%3$>&MFVD;:"));rules.push(rule("U7$?(1\'5/5"));rules.push(rule("T6$>(1\'5/5"));rules.push(rule("V1%7$9(2$6\"ON6?"));rules.push(rule("Y1\"8!3%7*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6HlV`gqi~zPcdv"));
rules.push(rule("]5 :)>+9-HL[B83"));rules.push(rule("U=$8(;\'0\"OG^H55"));rules.push(rule("U4$<(5\'0\"ON7XKH\\K;568_@MVF=]4IdZybtw`a]eg"));rules.push(rule("Q6&? >)9%DBTE35"));rules.push(rule("R:\'1,3&>.AA171CIQO"));rules.push(rule("X0\"8!0%7*CIV369ON6?4IM6^BVK"));rules.push(rule("[3#0-1*1,<"));rules.push(rule("Q9&9 ;):%DK<1"));rules.push(rule("S;\'2,0&=.AH^?86HE379ON>[_4=51C@1\\T0R\\C^4U:4"));rules.push(rule("S2\'6,2&>.AHYC0<=Mf[qnzxgjXojy"));rules.push(rule("^7!5%6$;"));
rules.push(rule("Y0\":!5%1"));rules.push(rule("Y>\"6!6%1*CIQO>1"));rules.push(rule("S;\'0,5&?#;\'Y1"));rules.push(rule("[2#2-=*6"));rules.push(rule("_7!1%7$>+7"));rules.push(rule("T3$5(1\'5/3(BH56"));rules.push(rule("[3#0->*1,<"));rules.push(rule("V?%=$>(1"));rules.push(rule("Y1\"8!2%6\'9&MO>0"));rules.push(rule("[3#>-;*3!FC["));rules.push(rule("W>%=$>(7"));rules.push(rule("Z3#?-<*0,<"));rules.push(rule("X1\"??)8+8"));rules.push(rule("Y0\"??)8+>"));rules.push(rule("V1%=$>(7"));
rules.push(rule("[:#4-;*1,<"));rules.push(rule("]: ;):+;-HL\\>3"));rules.push(rule("[3#3->*3,:,@I=:"));rules.push(rule("X?\"6!2%4*C@9:?LNZJ4="));rules.push(rule("X=\"<!6%4"));rules.push(rule("U2$5(4\'5\"ON6="));rules.push(rule("]4 =)8+>"));rules.push(rule("R3\'5,6&>.AhTao}gq}[fn{"));rules.push(rule("R3\'5,08\"?/IDWL"));rules.push(rule("T3$9(0\'7/5(BH56"));rules.push(rule("W?%3$?(1)JMT2>5AA161C@1\\T1787@I5^U8^RLY?LnWhkfyqUiip"));rules.push(rule("X1\"6!3%7"));rules.push(rule("R;\'=,2&>"));
rules.push(rule("[2#2-=*0"));rules.push(rule("^?!5%1$<&Mf[qnzxgjXojy"));rules.push(rule("T5$?(6\'6\"OgSjjwjw~Rblz"));rules.push(rule("X?\"<!6%6\'9&MO>0"));rules.push(rule("[<#>-;*6!FC\\I=8"));rules.push(rule("T=$5(1\'6"));rules.push(rule("[<#5-;*3"));rules.push(rule("]< >)=+;"));rules.push(rule("V?%4:#4-;"));rules.push(rule("T6$<(0\'5/5"));rules.push(rule("_7!3%4?#5.=$LNZJ"));rules.push(rule("Y1\"8!3%4*CIV369ON6=4IM7_]559?LG:Y^=T_JZ"));rules.push(rule("^6!1%6$>+7"));
rules.push(rule("[2#4-;*6"));rules.push(rule("X9\"<!3%7*CIQO>3"));rules.push(rule("W?%1$<1-:)6!FC\\I"));rules.push(rule("U<$4(7\'6"));rules.push(rule("V7%4$?(1)JMSN"));rules.push(rule("Q3&= =):(>"));rules.push(rule("Z?#4-8*6!FcQkb{dxyYgfw"));rules.push(rule("Z;#4-1*6!FC\\I=9>DK=UMKUO94>4QOJ]C7P"));rules.push(rule("T=$<(0\'5/9"));rules.push(rule("S;\'0,3&=.AhTverjl[fn{"));rules.push(rule("W2%7$<(1)Jm^li~nuZnbu8Gk]rg~zfbTae~"));rules.push(rule("Z<#4-;*6!FJ4><EjUicshvv^lc}"));
rules.push(rule("Q9&8 >?%4"));rules.push(rule("X?\"6!1%6\'9"));rules.push(rule("U4$<(5\'7\"ON7XKH\\K8:68_@MVF=]"));rules.push(rule("U<$<6-1*0"));rules.push(rule("T5$?(;\'5"));rules.push(rule("[2#73\'0,3"));rules.push(rule("Q9&9 =)8(>"));rules.push(rule("S4\'7,3&>.AHYC"));rules.push(rule("U7$?(7\'5/5"));rules.push(rule("Y>\"6!0%6\'9"));rules.push(rule("^6!3%4<#7#[52"));rules.push(rule("Z2#3-?*3,:,@I=:"));rules.push(rule("W0%=$8(0$0"));
rules.push(rule("S;\'2,0&>.AH^?86HE379ON>[_4=51C@1\\T0R\\C^4U:41Ci\\mar`zxQkhx"));rules.push(rule("U2$>(0\'7/5"));rules.push(rule("]5 7)=+;-HL\\"));rules.push(rule("Z=#>-1*1,<"));rules.push(rule("W?%3$?(2)JMT2>5AA161C@1\\T1787@I5^U8^RLY"));rules.push(rule("_6!3%0$?+0"));rules.push(rule("Y1\";!1%1"));rules.push(rule("W>%<$9(5"));rules.push(rule("W>%4:#4-="));rules.push(rule("T=$<6-?*0,<"));rules.push(rule("S4\'0,0&>.AA141CIV35"));rules.push(rule("_>!5%7$?&MFVD;9"));
rules.push(rule("W6%7$:(0)JMSN6<4IM>\\IITG5:13ZJ@PE4Y"));rules.push(rule("R:\'0,0?\"?/U:5"));rules.push(rule("W6%4$>(0$0"));rules.push(rule("Y<\"<!6%6*Ci\\zkpuaiQkhx"));rules.push(rule("Q8&5 >)9(>"));rules.push(rule("[2#73\'52/:!:"));rules.push(rule("T3$?(1\'5/3(BH56"));rules.push(rule("X?\"6!3%1"));rules.push(rule("Y>\"6!2%7*C@9:?LNZJ4>"));rules.push(rule("T<$9(2:*3"));rules.push(rule("[2#73\'0,5"));rules.push(rule("Z2#2-8<,2%8.AHYC"));rules.push(rule("W?%1$9(2)Jm^{c|{nnZnbu"));
rules.push(rule("[<#5-8*1,<"));rules.push(rule("R3\'6,9&?.AA0SNBQM;32:^HAXI:V"));rules.push(rule("S4\'6,0&=#=\'EC0<"));rules.push(rule("X?\"=!4%4*CIQO>0"));rules.push(rule("T3$9(1\'6\"ON6?4IDP0<"));rules.push(rule("W0%1$8(2)JD;9"));rules.push(rule("_>!5%6$>+7"));rules.push(rule("[<#>->*0!FJ4<<EJXK"));rules.push(rule("T5$?(;\'6\"OgSjjwjw~Rblz"));rules.push(rule("Z2#0-?*1,<,@I=9"));rules.push(rule("Q8&> ;)?"));rules.push(rule("Y1\"6!6%4*CIV"));rules.push(rule("T=$5(2\'5/3"));
rules.push(rule("U<$4(29*0,<"));rules.push(rule("[>#5-8*3,<,@I=:>DK<12GNHEN:\\<HIC@D7<4"));rules.push(rule("U2$>(7\'5"));rules.push(rule("R:\'2,4&=.AH^?86HE359ON?Z@WC>X<2"));rules.push(rule("U<$<(7\'2"));rules.push(rule("[<#>-?*0!FJ4<<EJXK<2"));rules.push(rule("W?%0$8(7"));rules.push(rule("S2\'5,2&="));rules.push(rule("Q9&8 >)9%DbYgltcs|Sj`t0KeRul{pkdWha|"));rules.push(rule("Y>\"=!4%7*CIQO>3"));rules.push(rule("^6!2%6$<&MO>0"));rules.push(rule("S2\'6,0&="));rules.push(rule("Q8&5 =)?"));
rules.push(rule("_>!6%7$<"));rules.push(rule("R3\'5,6&="));rules.push(rule("Z8#2-<*3,<"));rules.push(rule("V>%1$>(2"));rules.push(rule("T=$4(0\'2"));rules.push(rule("X?\":!6%6\'9&M[>3:FC[560KL778G<:"));rules.push(rule("^?!5%2$<"));rules.push(rule("Z=#>-?*3!FJ4<<EJXK<1"));rules.push(rule("Y>\"<!5%6\'9&MO>0"));rules.push(rule("_6!>%7$?"));rules.push(rule("[<#>-=*1!FC\\I"));rules.push(rule("Z3#4-8*6"));rules.push(rule("Z=#>-;*1!FC\\I=9"));rules.push(rule("[:#4-<*6!FJ5YCDRD?132RFN_B?\\"));
rules.push(rule("U=$;(0\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:Z=?"));rules.push(rule("T5$<(1\'7/5"));rules.push(rule("Z=#>-:*1!FC\\I"));rules.push(rule("_6!6:+;#2.?"));rules.push(rule("S;\'1,6&8.AHYC0?"));rules.push(rule("V0%7$<(7)JD;97@`Xo`zltwV`mr"));rules.push(rule("S;\'0,0>\"<\"3+KE_@"));rules.push(rule("Y8\"?!4%7*CIQO"));rules.push(rule("V1%=$9(2$6\"ON6?"));rules.push(rule("V>%3$:(2)JMT2>5AA141C@0]KRI3BaPtdw~dc\\mkq"));rules.push(rule("Y1\"8!?%4*CIV369ON6?4IM6^BVK"));
rules.push(rule("X1\":!6%7\'9"));rules.push(rule("R;\'6,4&8"));rules.push(rule("T5$?(6\'5"));rules.push(rule("[3#3-1*1"));rules.push(rule("Y8\"<!1%4"));rules.push(rule("_7!1%0$?&MFQ833BH560KL>RLYL9WLCYA6351[BL^J3R3BaPtdw~dc\\mkq"));rules.push(rule("R:\'0,2&?#;\'Y1"));rules.push(rule("]: ;)?+8-HlV`gqi~zPcdv"));rules.push(rule("Y8\"<!1%7*Ci\\mar`zxQkhx"));rules.push(rule("[9#4-?*3,<"));rules.push(rule("S4\'<,0&=#=\'EC0<"));rules.push(rule("Q9&8 =)8(>-T7"));rules.push(rule("[9#2->*3,<"));
rules.push(rule("Z2#2-81,0(^??"));rules.push(rule("^?!5%2$?&Mf[fdxm|{Xojy"));rules.push(rule("_=!3%3$<+7"));rules.push(rule("T5$?(7\'7/5"));rules.push(rule("[<#2-=*3!FcQ|hyqchYgfw"));rules.push(rule("R:\'1,2&?#;"));rules.push(rule("[:#4-:*3"));rules.push(rule("_7!3%4$>+7)V6"));rules.push(rule("U3$?(2\'7\"ON6?4IdZybtw`a]eg"));rules.push(rule("R;\'5,0&=#:"));rules.push(rule("[>#5-;*3,<,@I=:>DK<12GNHEN:\\<HIC@D7<4"));rules.push(rule("X>\"<!5%4*C@98"));rules.push(rule("_7!2%4$>+7"));
rules.push(rule("T=$<(7\'0"));rules.push(rule("Y;\"=!3%4\'9"));rules.push(rule("Y>\":!4%7*Ci\\mar`zxQkhx>DbYpfvvhmSj`t"));rules.push(rule("Z3#?-?*6"));rules.push(rule("W0%=$5(2)JD;;"));rules.push(rule("Z3#73\'7,7"));rules.push(rule("Y?\"<!5%6*C@98?LnWa}sb`Uiip"));rules.push(rule("^<!4%0$<+7"));rules.push(rule("X0\":!3%7*Ci\\mar`zxQkhx"));rules.push(rule("_6!5%6$5"));rules.push(rule("R5\'0,4&8.AU141CT9;?LG2>"));rules.push(rule("S;\'1,5&?#;"));rules.push(rule("Q9&: ;)8(>"));
rules.push(rule("_8!4%4$<&MFVD;:"));rules.push(rule("U=$9(2=*3"));rules.push(rule("U=$;(5\'6\"OGY4=<EC0<=MO7VNXD5]6?"));rules.push(rule("X:\":!4%4\'9"));rules.push(rule("X1\"?!2%4\'9"));rules.push(rule("Z;#4-8*0!FC\\I=:>DbYpfvvhmSj`t"));rules.push(rule("S1\'6,2&=#;"));rules.push(rule("S2\'6,4&?.AHYC0?=MO?TEG[@>?;>\\IITG5Q"));rules.push(rule("^UIujkih&Vghklaxkk\'hjdcs.em`smQ"));rules.push(rule("_b`un8IDPB)Qlmaag{bo%Lcf)Olnb"));rules.push(rule("XSJ|nih`*Xho`ikumh.fihjdcs.em`smQ"));
rules.push(rule("Xec|j:HL\\L&Vghklaxkk\'MwohSmbjmvf"));
