// OpenAero rulesYY-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####   Régles France 2016 Espoirs à Doret    Version 2016.1.00    ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####      Modifications mineures (commentaires) et connus 2014    ###################
//#####      Corrections, modifications espoirs 2015, connus 2015    ###################
//#####      Ajout de règles (déclenchés) d'inconnu Doret 2015.      ###################
//#####      Prise en compte du distingo entre rotation alternées    ###################
//#####      (,) et rotations même sens (;) dans les régles 2015.    ###################
//#####      Modifications 2016, connus 2016, nouveaux noms.         ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2016 : Espoirs, Desavois, National2, Doret 

//##### (Une partie des) Règles spécifiques à la France.

rules.push(rule("XSJ|nih`*Husfmpr(oaai~X"));rules.push(rule("Znhkl)9\"dl,<h\'bs$*!6z*,/&,c=5&(t-3=)z/2b!#\"*&%\'!4#a*,/&+)/u{.ts&`\'*,/:\" !,kej-fcido7"));rules.push(rule("[` kbq9338"));rules.push(rule("[fbtf4Bp`fok/Bxuedtp)enm"));rules.push(rule("^UIujkih&Fztmhz.fihjdcs^"));rules.push(rule("_d\"jj}7<43"));rules.push(rule("_b`un8Lgmja\"D{|afux%kaj"));rules.push(rule("_TIujkih&Fztmhz.cniwoP"));rules.push(rule("Sh$icy5==?"));rules.push(rule("Ykm}jabb\'`g{450"));rules.push(rule("V`jh? kjg93"));
rules.push(rule("Wajh= kjg93"));rules.push(rule("Xnmc7*fld07"));rules.push(rule("Y{cbc*fld07"));rules.push(rule("Zy}om$iko5="));rules.push(rule("Qde|zvkbko kbq92"));rules.push(rule("Sahwggak#}b{`ky;2"));rules.push(rule("Qsg`b\"unuolr>;"));rules.push(rule("Uweaj.}kvsm|kns64"));rules.push(rule("]`a}b6Cxlh`l$Grxcg}t+dfa"));rules.push(rule("[#Ktbggg!M~`nyv*ljo "));rules.push(rule("Uvl-;#h`t`fokk"));rules.push(rule("Qqgbe::5"));rules.push(rule("Rrfwlm5=>"));rules.push(rule("[maib}mlf%|afi8:"));
rules.push(rule("Zmivy)vtzb~`t6[8Q(X8)6\\T\"?S):"));rules.push(rule("Z~xtmykq,fmcj:+scgdlw\"wmbz}b"));rules.push(rule("[xtmykq,emv26"));rules.push(rule("Tvac.ZTKO5~ack1[QSu^"));rules.push(rule("Xdw\"T[LD0@jnqpd(mxjd+sxdjol$woa}{jjnk~"));rules.push(rule("Xkc`y*yj~Rgo}$?!V5R![o.V#5_\',Y0%4S&\'6%.<=]0X,]l\'R!\\:7>8[_\'_3,0Q.2\'s>T4Z-)9\"x3R>S)6"));rules.push(rule("Sq|hg,FcQnkZ>8&>)vmuWmb{=+}Q!=^"));rules.push(rule("Tvac.Gk]`dxQghy%7-tl}[cm|6.T+0X"));
rules.push(rule("Tsbt+Mf[cm|Sf`u+8*_iwhpknf,ocsnwdéh&jgpgslezj"));rules.push(rule("Wu~io Kbq[cm|S9=7+8*iwVenu2,&7\\\'>Wq]/2Y:}>W\"4Z=y<V*8T0~5S 5R1\""));rules.push(rule("_xg~&HkuYbep]6:<.2\'Yj~lrjfj\"`dxk}ién%fdkj}éa\"à!?>>°"));rules.push(rule("Sbehmv%hkiu~io~&>)Jm^i`zP3>"));rules.push(rule("^?!5%6$<&M[>1"));rules.push(rule("]5 ;)8+;-HQ359OZ6="));rules.push(rule("Y>\"=!5%4"));rules.push(rule("R:\'1,3&8.AhTdfyYkfv"));rules.push(rule("X0\";!4%6*CT98?LnWmb{Xcjx"));
rules.push(rule("_6!6%7$?"));rules.push(rule("Q6&> >)?%D_<22JP;;"));rules.push(rule("V1%=$5(7)JP;;"));rules.push(rule("_8!4%6$>&M[>3"));rules.push(rule("R0\'6,0&=#="));rules.push(rule("Q3&= >):(8"));rules.push(rule("T6$9(2\'5/3"));rules.push(rule("]: ;):+;-HQ35"));rules.push(rule("T=$<(0\'2"));rules.push(rule("]4 >6%4$9+4"));rules.push(rule("_7!2%0$9&M[>3"));rules.push(rule("]8 =):+;-HQ359OZ6="));rules.push(rule("^6!1%4$<&M[>3:F^4=<EW0>"));rules.push(rule("Y1\";!?%7*Ci\\hhv^`c|"));
rules.push(rule("T<$8(7\'5\"OgSocsTme"));rules.push(rule("Q8&= =)?"));rules.push(rule("T1$>(2\'5\"OZ6?4IY?86HQ37"));rules.push(rule("S2\'6,3&?.AU141CT9:"));rules.push(rule("R:\'1,7&8.AU14"));rules.push(rule("W?%0$;(2)Jm^i`zPodw"));rules.push(rule("U=$8(7\'0\"OgSocsTme"));rules.push(rule("V?%4$9(1"));rules.push(rule("_>!5%6$9&M[>1"));rules.push(rule("U=$8(2\'7\"OZ6?4IdZkar\\akp"));rules.push(rule("^?!6%4$<+7)IcyWmb{X<7:"));rules.push(rule("U<$<(0\'<"));rules.push(rule("X1\"<!4%3"));
rules.push(rule("T5$<(0\'0"));rules.push(rule("Q0&= =):"));rules.push(rule("W6%7$;(2)JP;97@]=8"));rules.push(rule("Z2#3-;*3!F^4<"));rules.push(rule("S2\'6,6&=.AU14"));rules.push(rule("W>%7$>(7"));rules.push(rule("U2$5(;\'5\"OZ6="));rules.push(rule("X?\"<!5%4*CT98?LnWmb{Xcjx"));rules.push(rule("S2\'5,2&="));rules.push(rule("Y0\"<!4%="));rules.push(rule("S1\'7,0&=#="));rules.push(rule("Y>\"6!1%6*CT98?LS2?"));rules.push(rule("[:#7->*3!F^4>"));rules.push(rule("V1%7$<(2)JP;97@`Xji~Rnl{"));
rules.push(rule("[3#2-8*3!F^4><EW0>"));rules.push(rule("S:\'5,2&8"));rules.push(rule("[<#5-=*6"));rules.push(rule("[<#5-=*3"));rules.push(rule("R;\'5,2&>"));rules.push(rule("W6%4$?(0)JP;9"));rules.push(rule("S4\'<,5&=.AU14"));rules.push(rule("Q0&> ;)?%D_<0"));rules.push(rule("Z;#7-?*1![\\GA"));rules.push(rule("R3\'6,0&?.AU141CT9:"));rules.push(rule("W\\Mwkcef)@grizaft$uxbkl}mmo(oaai~X"));
rules.push(rule("[ohkl)9\"3`\" \"yu%\'mfcd6/v,;1\'&l|#!jz*,(50/gkn-*47)(6&/|l! ,.j-.3%4+!vrno?,g$#!$\"d\"56,ci*+{\'mf/;6ba%r.>5.%93&cidb,:f<\"gke*s+1=z"));rules.push(rule("_d\"jj}7<13"));rules.push(rule("[fbtf4Bp`fok/Cnvk{ijz+rsgaa{ndk*ljo"));rules.push(rule("]VH}fefo-Bfzetna!udheyolg$kokc`arV"));rules.push(rule("Sh$icy5=;:"));rules.push(rule("^c`un8Lgmja\"Emoyhbv%}tldkvhgb.nkg"));rules.push(rule("^UIujkih&Glwcwge} wyjgbrjfj\"man|jZ"));rules.push(rule("Vm&hku;194"));
rules.push(rule("[ilufome,emv269"));rules.push(rule("Xfii\"jbk78"));rules.push(rule("[ybjolv/lab3>"));rules.push(rule("[mlk6$iko5="));rules.push(rule("[mlk4$iko5="));rules.push(rule("]kob?&hcc;2"));rules.push(rule("^}ne(gdh>8"));rules.push(rule("_y}h(gdh>8"));rules.push(rule("Tphsfw/lit3>"));rules.push(rule("Wbfu~tjjga/lit3?"));rules.push(rule("Ykm}jabb\'cslev<9"));rules.push(rule("Wudif tfyacu5>"));rules.push(rule("[ybjo$pmuzi~jf8;"));rules.push(rule("Yzbo*y`zhgw45"));
rules.push(rule("Zy}om$vgqmmz26"));rules.push(rule("Rofvg<N~oadn%Nhubkkr\'||`jdqcbh#hhn"));rules.push(rule("_\'Iujkih&Glwcwge} wyjgbrjfj\"`d`\'"));rules.push(rule("]~h/:+dn{gmjaf"));rules.push(rule("Yyc}cm64?"));rules.push(rule("Zzbume934"));rules.push(rule("Tbfbgw`je,xcgas65"));rules.push(rule("Sd{kwq%x{}i{jy0X1U*Y0%8SS):Y$<"));rules.push(rule("Sw|vlqg#aff`7-pj{eed{,xjiwo"));rules.push(rule("Qfzc{*}wey;]0X,Z98SS):Y$?"));rules.push(rule("Y~a{*edgh;#{kv`|eaa\'}`xyo`hhg!ec`{feqo-bf)5:1°"));
rules.push(rule("[livy)pnd`k}:U7V#.1U*Y4>Qr<[%1#Q("));rules.push(rule("Zxbjolv/oiak2\'jdccb||\"df,xfujbo"));rules.push(rule("_}zkn(Y]OM4vmmd6PTYxX"));rules.push(rule("Tsbt+PYML<Neizun%k{c`)rphd`k/rel{xcnljv"));rules.push(rule("[yxjf$WrhfSazXyloc;qfhn;VWP|}V"));rules.push(rule("Z}e.ZtkoWc{Pub`d0@jnqpd(kzkn%ex&baa!~~gckn%cor|aodfx.|ry%fl&ulvvhkmbj"));rules.push(rule("Xzybj*ECI0tleh8)T{U#<V^lK[*u,YgNQU#<VY}$"));rules.push(rule("[|e.GBA<xm}/cn%nénjfggjé!lm`|\'g`y-tl}evhgb}/ddhzbuéfz"));
rules.push(rule("[hbhu$rgs|}z}t6[3Q(+R5/8Up??.W+\"V76?Y~08%R!/P4\'5[*)9\"%;7P6[%%7-t8W4^/5v"));rules.push(rule("Zxxjf$R398,3/qnw~|rqz>>2"));rules.push(rule("Xdw\"Q:=:-;#Yeq!li.}hd~dim)wwqm~gjry`*à-7;9°$qtz,bjt+sorjjend{"));rules.push(rule("]{cb&Hku?3)9\"wm~z~syv014"));rules.push(rule("Z}e.Dez88,3/Wjv*ic#{kv`|eaa\'xpzhtjlqpd(à,7?°\'xpx-efz$tdzxglfg`y"));rules.push(rule("^m`i}(|htw|tsuz3Q>W+\"V7.0Y~08%R!/P4<P/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));
rules.push(rule("Uwac.Dez88y~/:+sorvyuvs{62="));rules.push(rule("Wpc|\'@g{04wq(1._fx%nh&qfpcuac`/t~uoof|vg!à(5>°/t~w*ag#apuaoocb+hecrbgpg"));rules.push(rule("Rafjt,~i|{cdt~u>W=^/ W?\">Vy;=/_\',7}9<\'S)#^; >^ $?!,?5Q>W+*0&q2Z2]&1t"));rules.push(rule("Xzybj*Fdr46gf$?!~i|{cdt~u956"));rules.push(rule("]zfv*Fdr46gf$?!Xm}/cn%xbrb}mmo({byloxtf)à$;1°({}\'gd*{cq}ma`di.kbxfocbbgpg"));rules.push(rule("_l`i}(dbvvzl?_1P >\\:7WQ(2U*Y4%4S2i0[3Q(X8669UP 2u0[3#.:u52(5j5Q>%4Q<4^4w9_8P 2}"));
rules.push(rule("Xzybj*EVZxukfqv!5barxm0c\""));rules.push(rule("Y~dw\"IXU~nl|p\"<(\\o|\'o`*~iq}mg!xc{|tén%k}tèp)hc!~~gckn"));
rules.push(rule("ZMivy)ldo1P\'6W+;Q(1U*Y3<Qr>[%4V#]0>Y^/S>=R{:Y$<Z-?X,5t=R!5W+Q?251Y^/:p?S)9Y$8Z-R50\\t>R!6W+9Q(;X,3T\"U=2=XV#z1U*1]&W:R[%y8Q(7U*Y3;QR!{>Y$V40TX,0T\"U=4?Xv8Z-:X,3T\"r8[%^89[_\'_33UP ={<Y$?Z-R76\\T\"?s0W+>Q(1U*3}?P <[%4V#z4U*:]&W?=2<XV#z4U*1]&>R!\\96>Pz4U*1]&?R!\\:7>Pz4U*:]&:R!\\:7>Pz4U*Y20QR!3W+Q?5^u3^/0P <[%^;?[>X,9T\"6S)P79Pz;U*6]&W?<ZW+8q>_\'0^/S>:R[%y2Q(7U*32T\"?s?W+?Q(X87_]&W?=3Vy2Q(6U*Y3<QR!\\96Wq>_\'2^/S?:7ZW+;q>_\'1^/0P >{3Y$8Z-R15\\T\"U>5Vy2Q(X<2_]&:R!5\"y3Q(2R40\\T\""));
rules.push(rule("Ukoj+mhig<=,hf`~wo~&`fjqhlé~ék|\'hjg`c#géccuazk|"));rules.push(rule("Yjc`y*Cjx|rqz9\\8T\"Rk,W+Q>>^U**Z9!6R.6!;6X:U*?13R>S)65"));rules.push(rule("^|zkn(Gl~4;4Jnz,3Ghyt~u95="));rules.push(rule("Rua}/Lit9=7Cjx-;#Yeq!li.}hd~dim)gmlxc}éj\'cjxd|lgpcmm,}zwnwchsql$à\"6:<°"));rules.push(rule("]naaq&Pz93r}vq<V5R![o.V#]1>Y^/ W?\"?V,7)78W=^/5<5Q7W+7="));rules.push(rule("Tvac.Dez2><[3>%7Xv7<uvs{62:"));
rules.push(rule("[|e.Dez2><[3>%7-Vbz$fd(~a{flec&`firn{éi.|h~v*93°#dkluibz/t~uoof|vg!à(?8?°"));rules.push(rule("Qbgbx\"Cd1?|rqz9\\8T\"Rk,W+Q9?^U**Z9!6R.6!;6X:U*?13R>S)65"));rules.push(rule("Wu~io Kbq5:1Lc::\'6Ae93r}vq;4?"));rules.push(rule("Sta}/Lit?77Oj>8&>)Tcr(hk/udqkyolg$ane|a|éb+vexu#=1°\"emmjioddy&p|tgsai{}b+à%;56°"));rules.push(rule("Xi`b`p&aoktveaq!5,@ID0S;568Dez6:<F`u0Hku559Qr5=7Cn:=:Ii7<"));rules.push(rule("V>%1$?(1)JP;97Cn25nb"));rules.push(rule("S:\'<,0&="));
rules.push(rule("R0\'5,2&=#;\'#<&<6/84.09%"));rules.push(rule("Z3#4-:*4"));rules.push(rule("]8 <)9+>-HQ369Lit7?cd"));rules.push(rule("[>#4-8*1!F^4="));rules.push(rule("Y>\"6!6%1*CT98?LS2>5AU16"));rules.push(rule("Y1\"8!6%4*@g{04wq3B\\550KL75"));rules.push(rule("_7!1%7$<&Nh|;1}|5AU171C@9:"));rules.push(rule("S2\'5,6&8.\\WBK"));rules.push(rule("Y1\":!6%7*CT98?LS2>5Bfs<:ii"));rules.push(rule("W?%0$<(0)JP;9"));rules.push(rule("W6%4$?(2$6"));rules.push(rule("V1%6$<(1)JP;9"));
rules.push(rule("U=$8(1\'0"));rules.push(rule("[2#2-8*0"));rules.push(rule("U=$9(2=*3!F^4>"));rules.push(rule("X9\"<!4%4*CT9;"));rules.push(rule("^?!5%3$<&M[>0"));rules.push(rule("V1%7$<(2)JD;9"));rules.push(rule("[3#2-;*3!F^4="));rules.push(rule("Y1\":!68+;-HQ359OZ6<"));rules.push(rule("_6!3%6$9"));rules.push(rule("[<#>-1*3,<,@]=8"));rules.push(rule("Z=#>-8*3,:,@]=:>D_<12JP;;"));rules.push(rule("Q4&> >)9%D_<22JP;:"));rules.push(rule("R0\'7,0&=#="));rules.push(rule("Z3#?-:*6"));
rules.push(rule("_8!4%4$<"));rules.push(rule("^?!6%3$>&PYML"));rules.push(rule("S:\'5,2&8"));rules.push(rule("U<$5(0\'6"));rules.push(rule("[:#4->*3"));rules.push(rule("[3#0-=*1![|gaXdpUofg"));rules.push(rule("^9!5%6$>&M[>0"));rules.push(rule("R;\'5,2&>"));rules.push(rule("[:#4-=*6!Emv67"));rules.push(rule("Q6&> ;)8%DK<1"));rules.push(rule("X1\"<!5%1"));rules.push(rule("Z;#7-?*6![\\GA<EVZxukfqv"));rules.push(rule("]< =)9+9-HQ359Lit7?"));rules.push(rule("[>#5-;*0,;,@]=9>D_<0"));
rules.push(rule("Y>\"=!3%4\'9"));rules.push(rule("[<#>-;*3,:,@]=:>D_<12JP;;"));rules.push(rule("Y>\"6!4%4\'?&M[>3:F^4<"));rules.push(rule("Z?#5-8*0!F^4><EW0?=M[>1"));rules.push(rule("Z2#0->*0!FJ4><EW0?=M[>1"));rules.push(rule("Y0\"7!4%7"));rules.push(rule("]< >)9+9 2#GV80"));rules.push(rule("U2$5(7\'0\"OZ6?"));rules.push(rule("U2$>(1\'5/3"));rules.push(rule("Q8&= >):(8"));rules.push(rule("_6!6%7$?"));rules.push(rule("X0\";!1%4*C@98"));rules.push(rule("^9!4%4$>+7)JP;97@]=9"));
rules.push(rule("[<#5-;*1,<,@]=9"));rules.push(rule("Z2#0-:*3!Emv67~u1CT9;?LS2?"));rules.push(rule("]5 :):+>-HQ359OZ6<"));rules.push(rule("S4\'<,2&8.AU14"));rules.push(rule("Y1\";!1%7*CT98"));rules.push(rule("]4 >7%6$?"));rules.push(rule("R:\'0,2&=.Bfs<:ii"));rules.push(rule("U=$8(2\'5\"OZ6<"));rules.push(rule("Z;#4-:*6!Emv67"));rules.push(rule("U7$?(5\'5/5($?:+:3&<3/82+"));rules.push(rule("S2\'6,4&>.AU141CT9;"));rules.push(rule("U4$?(5\'6\"OZ6?4IY?8"));
rules.push(rule("[>#5-8*1!F^4><EW0?=M[>1"));rules.push(rule("Q8&8 <)="));rules.push(rule("[:#7->*1![\\GA<EVZxukfqv"));rules.push(rule("[>#5-8*3!F^4><EW0?=Nh|;1lc"));rules.push(rule("U2$>(0\'5"));rules.push(rule("]5 :)8+8-HE36"));rules.push(rule("V1%=$9(2$6\"OZ6?"));rules.push(rule("[3#3-;*3,;,@]=9"));rules.push(rule("T1$?(2\'0\"OZ6?4Jj}3="));rules.push(rule("]: =)8+8-HE35"));rules.push(rule("[<#2-8*3"));rules.push(rule("Y0\"<!4%1"));rules.push(rule("]4 ;)9+8"));rules.push(rule("^7!3%6$?"));
rules.push(rule("[2#4-:*:"));rules.push(rule("X1\"7!5%7"));rules.push(rule("V?%=$>(7"));rules.push(rule("Q8&= =)?"));rules.push(rule("W>%4$8(2"));rules.push(rule("[:#4-8*1!F^4><Fdr46"));rules.push(rule("U<$<(0\'<"));rules.push(rule("W?%3$;(1)JP;97@]=9>D_<0"));rules.push(rule("Q3&> >):(8"));rules.push(rule("_=!6%4$<+1"));rules.push(rule("V7%7$?(1)JP;:"));rules.push(rule("S1\'0,0&=#="));rules.push(rule("V7%4$<(2$0"));rules.push(rule("R3\'5,6&=.Bfs<:"));rules.push(rule("R5\'6,2&=.AA141CT9;"));
rules.push(rule("[<#>-;*6!F^4><EW0?=M[>1"));rules.push(rule("Z=#4-;*0!F^4>"));rules.push(rule("U=$9(0\'6\"OZ6?4IY?8"));rules.push(rule("[3#3-8*0!F^4><EW0?"));rules.push(rule("Q9&: ;):%Gl~:9qr:F^4=<EC0>"));rules.push(rule("T5$?(2\'5\"OZ6<"));rules.push(rule("U=$8(4\'5/3(BH560KX74"));rules.push(rule("[3#0-1*3!FJ4><EW0?=M[>1"));rules.push(rule("_:!4%4$9&M[>3:F^4=<Fdr46gf"));rules.push(rule("Q6&8 =):(8"));rules.push(rule("Z;#4-=*0!F^4="));rules.push(rule("T=$5(1\'6"));rules.push(rule("W>%=$8(2"));
rules.push(rule("_6!69+;#2"));rules.push(rule("]: =):+>-HQ359ON6<"));rules.push(rule("]: <)8+8 2#GV80"));rules.push(rule("S4\'<,4&=#;\'EW0<=M[>0:F^4<"));rules.push(rule("R5\'6,5&=#=\'EC0<"));rules.push(rule("U2$9(2\'6/5(B\\56"));rules.push(rule("Z2#2-=*0!F^4><Fdr46gf"));rules.push(rule("Z2#3-<*3!FJ4><EW0?"));rules.push(rule("T=$<(0\'2"));rules.push(rule("[2#73\'6,3"));rules.push(rule("^9!?%3$<+7)JP;97@]=8"));rules.push(rule("Q8&=?!6%1\'5"));rules.push(rule("[:#4-<*3!F^4="));
rules.push(rule("[3#3-<*0!F^4><EW0?"));rules.push(rule("Z2#3-?*6!F^4>"));rules.push(rule("_7!2%1$<&MO>0"));rules.push(rule("Q9&: :):%D_<12JP;;"));rules.push(rule("W?%0$8(7)JP;9"));rules.push(rule("^?!6%3$<&Nh|;1"));rules.push(rule("Q9&9 7):(8-HE35"));rules.push(rule("Q9&8 ;):%D_<1"));rules.push(rule("_8!?%2$<+7)JP;:7@]=8"));rules.push(rule("Y>\"<!5%4*C@98"));rules.push(rule("^9!5%4$?+0)JP;97@]=9"));rules.push(rule("R;\'0,5&>"));rules.push(rule("R3\'6,9&>.AU14"));
rules.push(rule("]8 =):+;-Kbq=2eg"));rules.push(rule("Q6&> =)?%D_<22JD;:"));rules.push(rule("Q9&9 <)8(>-HQ35"));rules.push(rule("[3#3-8=,3(Aow>;pz6HQ36"));rules.push(rule("[>#5-;*3!F^4=<Fdr46gf"));rules.push(rule("]5 :)?+9 2"));rules.push(rule("]5 ;):+;-Kbq=2eg"));rules.push(rule("Y8\"?!4%4\'9"));rules.push(rule("T6$?(6\'5/5($?=+:6&<2/81+"));rules.push(rule("[3#3-83,0(Aow>;pz6HQ36"));rules.push(rule("V?%4$9(1"));rules.push(rule("U-Lgmja\"Oixg`ijiU?&`fjltW=\'"));
rules.push(rule("Xlic`\'6%og&}\"<`,(!\";o?+$*!#<:\"//a=;+>%$#($.wksx>:/o?%(q$;yf,//+#q\'&j89&n8(03%,&\"?\'4>$&5,$ba%>dfh:0*3&/;be"));rules.push(rule("Xec|j:Mwkcef)Jcuac`nkT7*nimgq"));rules.push(rule("X J|nih`*Cgw`kl`dS</ddkdxY1 "));rules.push(rule("Wcnhe-;#7af!hl#>`+ejm--.#q&/e|*+ejm+-`va3%ln//;)?$&.;md-:>.g?%\"*?8#.6rchln;),\"*<5&)dba#lnogkejm*71dbazo%ogkejmfcidba(c:;\'om$#(-\'/)*#rp/35%-*k$.<.2<r.og 6`bo0wz<"));rules.push(rule("[fbtf4Bp`fok/Ijqcbhbe[0!kc`ar"));
rules.push(rule("YRJ|nih`*Cgw`kl`dS</ddkdx["));rules.push(rule("Yb!cn6788"));rules.push(rule("[fbtf4Bp`fok/Ijqcbhbe[0!i`b"));rules.push(rule("^UIujkih&MhpknfmbP5+ldnimgq_"));rules.push(rule("[` kbq9008"));rules.push(rule("_b`un8Lgmja\"Oixg`ijiU?&beh"));rules.push(rule("_TIujkih&MhpknfmbP5+icotfT"));rules.push(rule("_d\"jj}7?06"));rules.push(rule("Vdjvokod$icy5=="));rules.push(rule("Rllc/lab39"));rules.push(rule("Tbk`4.dml<9"));rules.push(rule("Uck`3.dml<9"));rules.push(rule("V`jh= kjg93"));
rules.push(rule("Wajh2 kjg93"));rules.push(rule("Yo~ack&hcc;2"));rules.push(rule("[chuqfhn,ee`26"));rules.push(rule("Zycgs$iko5="));rules.push(rule("[x}om$iko5="));rules.push(rule("[}iw$iko5="));rules.push(rule("_}`kg`x kjg93"));rules.push(rule("Tag}rzemld%aow:;"));rules.push(rule("Vdjvokod$vgqmmz26"));rules.push(rule("Tveaj.{ardix3>"));rules.push(rule("Uvdlv.{ardix3>"));rules.push(rule("Vu{ld tfyacu5="));rules.push(rule("Uhec>Ovcoki.AflecgoV6\"`d`"));
rules.push(rule("S+Ovcoki.AflecgoV6\"`d`\'"));rules.push(rule("Yzj.2\'ja|lh`l`"));rules.push(rule("Uue~ji462"));rules.push(rule("Vvdvda;19"));rules.push(rule("_ichjqcca.ykko|1>"));rules.push(rule("Zmivy)tsgx3Q>W+Q<2^U*3]&>"));rules.push(rule("Su{kv,fmcj:+weygw`kl!~i|{nhdfh&nfjv`fxk/cn%;56°"));rules.push(rule("^i}h~u\'ioeap<V>R!3W+Q8+;TX,"));rules.push(rule("[ybjolv/oiak2sdkdhgv)al!~e|n`n%nh&0?4°"));rules.push(rule("Y{ybj*XUCC;qfhn;VWP|Z"));
rules.push(rule("]zfv*XUCC;E`cwsm,oybh%|ooea\"tfezbf`dy"));rules.push(rule("Uwac.ZtkoWc{Pub`d0tleh8_SR}uZ"));rules.push(rule("Tsbt+Pyml^gyQ}nnk7Kod|vg!{i{cb+j-gulg\"wzebcb+pddwvligo|,}zu+ik-pf{pkbi`k"));rules.push(rule("Tvac.GWD<zcbc=#Y}V*8T_dGU%"));rules.push(rule("Vqc|\'CUE4tcr(hk/céhioceké)al!:icj\'égéhocr#melr(y`j\'yj~lrjfj\"bga~`tén"));rules.push(rule("Ufecp.apuyx||:U<V#.X8);\\t=>&[%-Q<35Tx31!P \'\\:(2P/#4$&23R7S)+8*=]9X,<r"));rules.push(rule("Tvac._5:1(1.ybyq{ytp381"));
rules.push(rule("Rua}/W94>/:+Uk~&gl$pn|mzfhe%yxvf{mgtzi.à/635°*~sq)hgr(zk}sbfkacp"));rules.push(rule("Wu~io Kbq=2!5,xjut~u956"));rules.push(rule("Tsbt+Nh|;1(1._fx%nh&qfpcuac`/t~uoof|vg!à(5>°/t~w*ncp)rgs|emnknv"));rules.push(rule("Xkc`y*}`xyssxppr5R7S)#^; ?^u52(T\"&T6=X#Q(+R5/9U%.2\'/61S?_\'$?!z7P?[%8p"));rules.push(rule("^|zkn(Gl~:9qr!5,xjupz|rqz>>3"));rules.push(rule("Qv`u#Bfs<:xv#4$R`{,jj\'yj~lrjfj\"r}|k}nnpxh&à#04°\"r}~.cf+sorjjend(aaasjk~h"));
rules.push(rule("[hbhu$rgs|ha~syv7S?_\',Y0%5Ss6;,V#.6u52(T\"&T6&=W$&>) 1:V5R!\'6%x6X3U*?{"));rules.push(rule("Rp|hg,Emv67oj*0&ulvveg}z}t198"));rules.push(rule("Wpc|\'@g{04fn(1._fx%nh&qfpcuac`/t~uoof|vg!à(5>°/t~w*ag#apuaoocb+ao~efg`co|i"));rules.push(rule("Yjc`y*ejzxuk4Z;]&=U>5VY$<Z-R1/9U1`4Y2Y$V71=<_]&1|4Y2+\"4z29-?g3R7!6P48P;p2Z2]&1t"));rules.push(rule("Rp|hg,F_^ztcjy&>gkrt{d4a#"));rules.push(rule("Sta}/O[\\{|odp~-;#Yeq!li.|hyqch&sfqqrém,ouèx%fl&u{mnmm"));
rules.push(rule("Qbgbx\"Odw{ytp4Z;]&Pj$[%^95[_\',Y0%4S&:/41S?_\'92:V<R!:;"));rules.push(rule("Vt~io Kbq301@c|/:Cjx|rqz>>8"));rules.push(rule("Y~dw\"Jj}=?6Kfv\"<(\\o|\'o`*iwhpknf,m`j{jyéh&kfvk{gbznkn%yxvf{mgtzi.à/095°"));rules.push(rule("Ufecp.\\t64yx||:U<V#Zg\"X,Z:;SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("[yxjf$Icy=8>Zw?0*0Ss=1suz430"));rules.push(rule("Tsbt+Nh|758Y~;2+8*]gp)`g!zcznsbjd-eldtmrém,}`rx%>8°&nfjv`fx.|r{`xdcv{a\"à!=8>°"));
rules.push(rule("Xkc`y*Oj>8ww{w?_1P Sc Y$V2:TX,)S=#7Z\"8.<=]0X,<87P?[%8:"));rules.push(rule("^|zkn(Gl~214Fn<9.2Cd1?|rqz>>2"));rules.push(rule("Z}e.Dez00<J`3>%7-Vbz$fd(~a{flec&`firn{éi.|h~v*93°#maqbmbjni%yxvf{mgtzi.à/635°"));
rules.push(rule("XO~azw&koj;]!5^/9P =[%^89[8X,0T\"U<0VY$V40Tx3]&=R!1W+>q7_\'6^/S==90VY$?z2U*0]&W<;23XV#]2;Y~3T\"?S)8Y$q4_\'6^/S>#9ZW+v?Z-:X,Z:8;R[%y8Q(7U*Y3%4SS)w0V#]1:Y^/9P T581Wq3_\'7^/:P s0W+8Q(X86_]&W<<Zw2V#2_\'5^/S>=R{<Y$?Z-R76\\T\"?s0W+>Q(1U*Y0:Qr8[%6V#7_\'x5]&4R!\\:7?:?^U*~6T\"=S)9Y$V40=Y~6T\"=S)8Y$V71=Y~6T\"6S)=Y$V71=Y~6T\"U<?VY$9Z-R61\\t;R!2W+Q<2^U*~6T\";S)P7=PZ-;x5]&4R!/8y;>/_\'_33;Qr8[%=V#7X9505UP s0W+2Q(+1x37!P T58Xv:Z-1X,0=P T691Wq>_\'0^/S==R[%7v5Z-=X,Z:8SS)w=V#2_\',3Z8?96Zw7Q=54T-^/S=<R{3Y$:Z-8X,Z9>Ss?W+?Q(X87_]&W?=3Vy2Q(6U*Y3<QR!\\96Wq>_\'1^/=P T696Wq>_\'1^/>P T58Xv5Z-?X,Z;887ZW+;q>_\'1^/S;6R[%4v5Z-<X,)?p?6.W+8$z:U*3Z8>SS)"));
rules.push(rule("Xfii\"ijho00#ometzi}/ddkydbéqélw\"bgacj\'eébkyoulw"));rules.push(rule("Rcehmv%hkiu~io~&>)JQG3Z?770Hku119Lms3Aow2?5_}262Icy94>Kh?0"));rules.push(rule("Y>\"6!6:+9 2#GV803B\\54"));rules.push(rule("^6!2%7$?&M[>0"));rules.push(rule("V>%1$9(1)Icy1<j`"));rules.push(rule("Y1\"8!?%4*C@98?LS2>5Bfs<:ii"));rules.push(rule("Y;\"<!1%4\'9&+81.0> ?:+:3#"));rules.push(rule("]: =)?+; 4#GB80"));rules.push(rule("R5\'7,2&=#="));rules.push(rule("Y<\"=!6%6*CT98?LS2?5Bfs<:xv"));
rules.push(rule("R5\'1,5&=#=\'EW0<=M[>0"));rules.push(rule("T<$8(;\'7"));rules.push(rule("[:#4-1*3"));rules.push(rule("V1%=$?(2$6\"OZ6?4IY?8"));rules.push(rule("U=$;(7\'7\"Rxe`Ph~Zxdcm"));rules.push(rule("_:!5%4$<"));rules.push(rule("]: 7):4$<+1"));rules.push(rule("U4$<(4\'5"));rules.push(rule("T3$>(7\'5/5"));rules.push(rule("V7%7$?(1$7\"Lit7?"));rules.push(rule("[3#3-;*1,<"));rules.push(rule("^6!2%4$>+7)JP;9"));rules.push(rule("X?\":!6%4"));rules.push(rule("T6$>(2\'5/3"));
rules.push(rule("[9#2-<*3,<,&>>\'7:!40%66("));rules.push(rule("[<#2-;*3,:"));rules.push(rule("^7!3%4$?"));rules.push(rule("U2$8(2\'5/3(B\\560KX748GV82"));rules.push(rule("[2#?-:*6"));rules.push(rule("^<!3%2$<+7),39$=7#59)8>/"));rules.push(rule("X1\"7!5%7"));rules.push(rule("T=$<7-8*6,0"));rules.push(rule("Q0&> 8)9%Gl~:9"));rules.push(rule("T6$<(0\'5/5($7#6;);=*28-"));rules.push(rule("^;!5%4$?&M[>0:Emv67~u"));rules.push(rule("S;\'0,2&=.Bfs<:ii"));rules.push(rule("Y>\"=!6%6\'9&M[>3:F^4="));
rules.push(rule("Q6&4 8)8(>-HQ359OZ6="));rules.push(rule("Q8&=>!?%7"));rules.push(rule("]< <)9+;"));rules.push(rule("X?\"6!68+9 2#GV82"));rules.push(rule("_>!6%4$<+7"));rules.push(rule("Q6&> >):%DK<2"));rules.push(rule("[:#4-?*3!F^4="));rules.push(rule("[<#>-81,2%8.AU14"));rules.push(rule("Z2#2-87,0(B\\560KX74"));rules.push(rule("V7%4$:(7)WrhfSazXyloc"));rules.push(rule("U7$9(2\'5/3"));rules.push(rule("R7\'7,0&=.AU141@g{04wq"));rules.push(rule("Z=#>->*3,:,@]=8"));
rules.push(rule("[3#3-8*0!FJ4="));rules.push(rule("S;\'1,4&=.AA141CT9;"));rules.push(rule("[:#7->*0!Emv67"));rules.push(rule("]4 >)>+; 4"));rules.push(rule("Q0&= 9)8%Y}omVkw^zeka"));rules.push(rule("U0$>(2\'6\"OZ6?4IY?86HQ37"));rules.push(rule("Y1\"8!1%4*C@98?LS2?"));rules.push(rule("]? ;)=+; 2#!67-:9\"=1\'7=$"));rules.push(rule("X:\"<!2%4\'9&+86.0; ?;+:0#"));rules.push(rule("R5\'<,3&?#;\'EW0<"));rules.push(rule("V>%0$9(0$0"));rules.push(rule("T<$8(6\'6\"OZ6?4IY?8"));
rules.push(rule("Q0&= =):(8"));rules.push(rule("X0\";!4%4\'?&MO>0"));rules.push(rule("]: <):+; 4"));rules.push(rule("W2%7$<(0)JP;:"));rules.push(rule("X0\":!6<+8-HQ36"));rules.push(rule("R3\'5,7&="));rules.push(rule("U2$5(7\'5/5(B\\56"));rules.push(rule("R:\'0,5&=.AU17"));rules.push(rule("V>%1$<2-8$LS2="));rules.push(rule("U<$<4-8*6,>"));rules.push(rule("Y1\"8!3%4*@g{04wq3B\\550KL75"));rules.push(rule("Z;#4-=*6!Emv67"));rules.push(rule("R5\'6,0&>.AU14"));rules.push(rule("X1\"6!3%4\'?"));
rules.push(rule("W6%4$?(0$0\"OZ6?"));rules.push(rule("T5$?(5\'6\"OZ6<4Jj}3="));rules.push(rule("[3#3-8=,3(B\\550Hku?3|t"));rules.push(rule("V?%=$?(2$6"));rules.push(rule("X?\"6!6=+; 2"));rules.push(rule("S:\'0,2&>#7"));rules.push(rule("]: =)9+>-HQ359ON6<"));rules.push(rule("Z3#?-:*0"));rules.push(rule("_=!3%=$<+7),07$>9#5=)8:/"));rules.push(rule("[<#>-1*3,<,@]=8"));rules.push(rule("Z2#3-1*3,:,@I=:"));rules.push(rule("_6!5%6$9+;"));rules.push(rule("]4 >7%7$?"));rules.push(rule("Y0\"?!6%4\'?"));
rules.push(rule("Y1\";!4%6\'9&M[>3"));rules.push(rule("Y>\"<!6%1*CT98?LG2>"));rules.push(rule("T3$>(1\'0\"OZ6<"));rules.push(rule("_8!4%7$<+0"));rules.push(rule("U=$9(2\'6\"OZ6<4Jj}3=bl"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("Z=#>-80,2%8.AU17"));rules.push(rule("Y0\"7!5%1"));rules.push(rule("V1%7$?(1)JP;9"));
rules.push(rule("_6!3%7$?"));rules.push(rule("V1%=$<3-8)0"));rules.push(rule("Y>\"6!6%4\'?&M[>3:F^4=<EW0>"));rules.push(rule("R:\'0,3&>.Bfs<:ii"));rules.push(rule("V1%=$8(2$6\"OZ6="));rules.push(rule("[<#>-86,2%8.AU141CT9;"));rules.push(rule("[2#7-:*3,0"));rules.push(rule("U4$?(0\'5\"Lit7?"));rules.push(rule("Y>\"6!>%6\'9&M[>3:F^4=<EW0>"));rules.push(rule("R3\'6,3&=.AU17"));rules.push(rule("R:\'2,2&=.Bfs<:xv8GV833B\\54"));rules.push(rule("R3\'6,4&>.AU171@g{04"));
rules.push(rule("]5 ;)9+;-HQ36"));rules.push(rule("W?%1$<3-8$LS2>"));rules.push(rule("R3\'6,0&?.Bfs<:"));rules.push(rule("Z;#4-<*3!F^4="));rules.push(rule("[3#0-8*3!Emv67~u1C@9:"));rules.push(rule("[>#4-8*6!Emv67~u"));rules.push(rule("^6!3%4$<&Nh|;1lc"));rules.push(rule("V4%7$>(2$0\")98\">3\'4<!75 "));rules.push(rule("^7!6;+9#4"));rules.push(rule("R0\'5,0&=#="));rules.push(rule("R:\'1,6&?"));rules.push(rule("S:\'<,0&="));rules.push(rule("W>%=$8(2"));rules.push(rule("U=$9(19*0"));
rules.push(rule("]5 :)<+; 4#GB803B\\55"));rules.push(rule("[<#>-84,0%>"));rules.push(rule("]: :)<+; 4#GV80"));rules.push(rule("R;\'0,5&>"));rules.push(rule("^?!4%1$<"));rules.push(rule("U2$?(1\'5\"ON6?"));rules.push(rule("W0%=$<6-:)6!F^4=<EW0>"));rules.push(rule("_8!?%4$>+7)JP;9"));rules.push(rule("Z=#4-:*1!FJ4="));rules.push(rule("S;\'2,3&=.Bfs<:xv8GB82"));rules.push(rule("_>!5%4$<&Nh|;1"));rules.push(rule("S2\'6,9&>.Bfs<:"));rules.push(rule("Q6&9 =):(8-HQ359OZ6="));
rules.push(rule("]5 9)8+9-Us`j]n}S|fbe"));rules.push(rule("T<$8(5\'6/5(B\\56"));rules.push(rule("[2#7-=*3,:"));rules.push(rule("S1\'6,0&=#="));rules.push(rule("^9!?%3$>+7)JP;97@]=8"));rules.push(rule("Y8\"<!0%4"));rules.push(rule("_>!5%4$?&M[>0"));rules.push(rule("[9#5-<*3,<,&=7\'7;!42%60("));rules.push(rule("_:!4%7$9&M[>0"));rules.push(rule("[<#4-;*1!F^4><EC0?"));rules.push(rule("Q6&8 >)9(>-HQ35"));rules.push(rule("V3%6$?(1$7\"OZ6<4IY?9"));rules.push(rule("X?\"<!6%6*CT98?LS2>"));
rules.push(rule("R5\'<,4&?#;\'EW0<=M[>0:F^4<"));rules.push(rule("Z2#3-=*3,:,@I=9"));rules.push(rule("_6!6;+>#4"));rules.push(rule("W>%=$>(2$0"));rules.push(rule("W6%4$:(0)WRHF7@\\W~vbbsw"));rules.push(rule("X?\"6!1%4\'?&M[>1"));rules.push(rule("X?\"6!>%4\'?"));rules.push(rule("Q9&9 9):%DK<2"));rules.push(rule("W6%7$9(2)JP;:"));rules.push(rule("_8!?%48#7.;"));rules.push(rule("Z8#5-=*3,<,&>2\'4<!7;%5;("));rules.push(rule("Y1\":!62+8-HQ36"));rules.push(rule("T3$5(2=*3,:"));
rules.push(rule("W5%7$9(2$0\")9:\">1\'4=!74 "));rules.push(rule("T3$5(0\'7/5(B\\56"));rules.push(rule("]5 :)9+;-HE36"));rules.push(rule("S2\'5,2&=#;"));rules.push(rule("R7\'7,0&8.AU141CT9;"));rules.push(rule("T5$<(5\'0\"RXE@4IXU~nl|p"));rules.push(rule("[<#4-=*1!FJ4="));rules.push(rule("W6%7$>(7)Icy1<"));rules.push(rule("X?\"6!4%4\'?&M[>3:F^4<"));rules.push(rule("R:\'1,4&?#;\'EW0<"));rules.push(rule("S;\'2,6&>.AA141@g{04fn"));rules.push(rule("[2#4-;*6"));rules.push(rule("Z3#7-;*3,<"));
rules.push(rule("]8 <)9+;-HQ36"));rules.push(rule("Q9&8 <)9%D_<1"));rules.push(rule("Z2#3-8*3!F^4="));rules.push(rule("[3#0-<*3!FJ4><Fdr46gf"));rules.push(rule("R5\'<,0;\"?\"5"));rules.push(rule("U4$?(0\'6\"OZ6<"));rules.push(rule("Y8\"<!3%7*@g{04"));rules.push(rule("Z2#0-?*0!F^4><EW0?"));rules.push(rule("X?\"=!4%6\'9&M[>3"));rules.push(rule("[<#4-:*3,:,@I=:"));rules.push(rule("Z2#3-83,0(B\\550Hku?3|t"));rules.push(rule("T_Lgmja\"@lzoadna*nimgq_"));
rules.push(rule("[fbtf4GKWI,Okqjkihb#Ovgd(G``pe"));rules.push(rule("V]Mwkcef)Efwibmjc+icotfT"));rules.push(rule("Wjdwo0EJ_E\"@lzoadna*ktfl"));rules.push(rule("ZQKtbggg!Ihxnih`n-omjklo}Q"));rules.push(rule("_d\"jj}zhte`c?5="));rules.push(rule("Qlg~k2DBSK-Ggelbmh.zi`kezhbeh"));rules.push(rule("V.Mwkcef)@msmx!jh`facmja\"bgb`zX:,"));
rules.push(rule("Vbnhe-;#ln\"vjf(4,\"\'-+$.5kui\")$gkej-5=)z|o :gi)%+$*!*%</v,;1\'ke\'mfc<mq/anl\'gkejmfci&~#;% #3%[4-*0`bj9&\" /+97g;`/?)\"36,#\"*8o9 +.$)/,vr.>75%\'mf/+x 5/n !  .!3&$%66fh>\"=nm"));rules.push(rule("Ydc|j:Mwkcef)@msmx!jh`facmja\"bgb`z"));rules.push(rule("Y!J|nih`*Iiqlp-dpokcknkih&`fjltW>\'"));
rules.push(rule("Ymic`\'6%oi&/ovfc:8 (,kejmfc)(1c&+=i ,%-**1=pc//+.79+\"&d`cg,,&/ <!)%+$$4c\"$Y1$<S/1xlx}*jo(3,v,nogk(9gij:)|(==1\'&(\'m>ca*,&#\'%q\'8;*#2/:i0->,n$gkejmf/;bbazo)#?3.jmfcidbahl"));rules.push(rule("[fbtf4Bp`fok/Cdwoy)fqggmdi`lb+fechv"));rules.push(rule("ZQKtbggg!Lc|js$`rncoealbm,m`iepW"));rules.push(rule("Ssfwnk58>"));rules.push(rule("Tte~ho402"));rules.push(rule("]kb`fldj+sfmlu5<"));rules.push(rule("Wl&hku;0<4"));rules.push(rule("[ilufome,ee`2>"));
rules.push(rule("]oo|bmlm kbq9;"));rules.push(rule("]lbch|8TV7.0Y"));rules.push(rule("SXOvcoki.Khy`~\"c{janmmbmj\'glhc^"));rules.push(rule("Rqo$?!}bbfjbqoi"));rules.push(rule("[{buoc961"));rules.push(rule("]}a|ig8>="));rules.push(rule("Wagjkyomn)rnabz27"));rules.push(rule("Qj%aow:80:"));rules.push(rule("Vdjvokod$icy55"));rules.push(rule("Wejvokod$iko55"));rules.push(rule("QFzc{*}pziw4=^/ W?=33<Wq73 X,Z9:SS)"));rules.push(rule("X~y~}h(dlkf4vmuixg`ix%|htw`gcmm.bheqkcrfz"));
rules.push(rule("Yy~}h(gdh>;"));rules.push(rule("^lntnccj+qltg`|1?"));rules.push(rule("[ybjo$vgqmmz26"));rules.push(rule("]~`nw&wo}cb}93"));rules.push(rule("^}ne(xhvfhp?0"));rules.push(rule("Tcxbss$vmmdi|2Y9Y$%4_\'_1,>Qr<[%^8 3^u0^/S>#7Z\"Y$"));rules.push(rule("Sqfhndz!`njn8^bhmlewy(i`/qbwkjc/)bcla`bj\'9+8#5#à)6,3&:.`r+7$>(1)à$0/;\";/h~%8#2-;$à\"3&8 7"));rules.push(rule("^hnj:(gdh>8"));rules.push(rule("Rpfhndz!cfi64"));rules.push(rule("Qgia;\"jbk7<"));rules.push(rule("Rdhi4,ee`26"));
rules.push(rule("Sehi5,ee`26"));rules.push(rule("Tbk`>.dml<9"));rules.push(rule("Uvzdh.dml<9"));rules.push(rule("Wnxkk}+n`j?3"));rules.push(rule("Xg`nw&hcc;1"));rules.push(rule("[d}vlzmvd%aga::"));rules.push(rule("[jajl~9\\Z9!7R"));rules.push(rule("SXOvcoki.Khy`~\"c{janmmbmj\'bkibhm|Y"));rules.push(rule("Yyc}cm61:"));rules.push(rule("Zzbume961"));rules.push(rule("Tbfbgw`je,xcgas65"));rules.push(rule("]f#bfs8986"));rules.push(rule("_|af{(gl~><"));rules.push(rule("Rkzjcq%aga:9"));
rules.push(rule("Slzjcq%aga:9"));rules.push(rule("Xo~azw&sycgs4Z;]&$7s6;,V#]2?Y^/"));rules.push(rule("Suzjcq%bobb6aéiacmjlé\"wm~zfdji*`im}elu"));rules.push(rule("Vpxkk}+n`j?0"));rules.push(rule("Wqxkk}+nh|?3"));rules.push(rule("Ufecp.`jvdzhg{:U^:4[_\'9L"));rules.push(rule("Zxxjf$Mlum~jfsn%7-om}apeax4A"));rules.push(rule("Y~dw\"Neqobj}a\"<(Jghry`*ic#keqd(e`{byacyc"));
rules.push(rule("Rafjt,`c||sdu7S?_\',3}1p??.W+Q>>^459_1P =[%6V#2#4$0:V5R!5W+9Q(5)9\"23R7S)9Y$>Z-1$?!<7P6[%1V#5_\',Y0%4S&\'6%.<=]0X,9T\"=S):%7-48W=^/0P <[%7*0&72Z;]&4R!4W+9-;#??\\8T\"6S)8Y$9&>)<9_1P 2u0[:Q(>s"));rules.push(rule("^|zkn(Bbt29wvnx,3/odwyyis3830"));rules.push(rule("Qv`u#Ghy4:~rly$?!}b.bfslgxk#ma\"08,o}unqy-cp}$ct|c|fté+akcu#eaq!zcznsbjd~&glw\"mak`jt+axbowlw\"ig~guheqkacp"));rules.push(rule("_xg~T`d Nl{52r|c~/:+d*`g{`iwl(ch/6;%yyisz$csm,ockdroi&lg$quzmgho%bbtjsklui`.cne`y-tlehq"));
rules.push(rule("Vedk| tleh]S<1P6[%1V#7_\'6?@3R7S):Y$<Z-R5/5U1O4Y2Y$%]2;0:\\!P 2#:>T4Z-!=~08%R!/P3\'4[84+<N7P6[%-3q73 9d:V5R!6P48P;p2Z2]&1t"));rules.push(rule("]{cb&W>-;#{knmW^:5Yx%\"VXBsY~]W\"4Z\""));rules.push(rule("Xdw\"U?%7-vbz$fd(hémcbefbé-iv)tcr(ok{sn%xbrb}mmo(hoat+ik-dqhjaim,c`iddyc#hrgb(y`j\'}wcajf)`co{,bn\'iwkcekl$fd{okacjk~h("));rules.push(rule("Vedk| tleh]S>1P6[%4:Q(;U*0<P7P6[%-Q<471Y+]&1*><U<V#.:u52(T\"&T1&<Wq73 9D:V5R!/2y;=/>o?\\8T\"?T69X7~=]9X,<r"));
rules.push(rule("^|zkn(X;&>)vmmdS\\9=S"));rules.push(rule("Urbt+Q?$?!ki.kédg`dnné#lwv!abzjuol~#&Phqd!{y|/knv*kod|vgr(; =)9+;!&4\'6,5&>\"/?%0$>(0%$:/=\":!3\'%2#0-;*6!mx.7)=+>#5-"));rules.push(rule("[yxjf$RFN_B?77+8*iitguvs{62<"));rules.push(rule("]zfv*]AEZH214\"<(y`/jj}c`sn)`g!94>°/cn%xbrb}mmo(i}{\'{`x`op\'"));rules.push(rule("]{cb&SNBQM;32!5,j`pet~u950"));rules.push(rule("_xg~&SNBQM;32!5,{a\'fdrdkvd$fd(>9?°\'o`*iwhpknf,k|s+uokjz*"));rules.push(rule("^|zkn(\\IITG5Q!5,j`pev~bv956"));
rules.push(rule("[|e._@MVF=]/:+uk~&gl$d`kiz{b+uokjza,"));rules.push(rule("Rp|hg,Z=>/:+weaj9W,*]W\"4ZPcLP/RbD\\t$UiAV^&6[_~-+!S=<;?V"));rules.push(rule("Qv`u#]6;%7-vbz$fd(~a{flec&ghjq!dm.mujkiec#maqbmbjni`*lpfj$wo(hémcbefbé-bbgw\"mi,l}fefbh&nfjv`fxk!"));rules.push(rule("Ufecp.{knmW^?>:U<V#7_\'5^/S=<R:J>T4Z-!_33<4S&[%8.<=]0X,)1p??.W+\"V0.0Y~08%3I<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q>"));
rules.push(rule("Wu~io T28$?!zcbcXY4;7.]!,^vS 5R\\J489>eOY+}S=<;?mCWq.XH5050jHR\\\'>WQq* $Y0:86R.w-TVXyHY)!S=<;?V,v%XXW~_*(WhIZ\""));rules.push(rule("Wpc|\'_72)9\"bmxzj\'hjgoomhmqnf,jj\'yj~lrjfj\"lgbzni`*hr#zkolaxocb+`yy&jgpgslezj)"));rules.push(rule("[hbhu$vmmdS\\>36[3Q(2U*7]&W?=4V8K6X:U**Z9>:7Z\"Y$0\"22Z;]&$7s6;,V#.X?);\\t=>&:M>T4Z-!=~08%3i<U<V#7X86_<{7P?[%8p"));rules.push(rule("_}zkn(X<2#4$pnd`Q]6??TVZt%?_*($UQ}Vy\"QqX%?_]%\'//P[Kw[!XuZ$7S&."));
rules.push(rule("[|e.[56!5,mjs`*iwhpknf,jjth`digm}a\"d{x.fi`xiowl$go(||jtnkih&g.qld(~a{flec&b|$qneak{)"));rules.push(rule("S`fjt,zcbcXY4?0X:U*3]&9R!\\:(8P;B2Z;]&$U>5?=W$Z-4\\9_1P \'>w4:$Z-!_4,1Qr>7\"8L6X:U**8t=>&:m>T4Z-8_33U1}4Y;Y$0|"));rules.push(rule("_}zkn(X<3#4$pnd`4|\\\'>WV`EQY"));rules.push(rule("Z}e.[57!5,~nt+ao-bé`ealb`é,az\'h`~yc#{kv`|eaa\'juxè~&vga\"wzebcb%"));
rules.push(rule("Xkc`y*ojxhr\\mkq<V5R!6W+;Q(X<):\\5z5Q>W+>Q(2U*Y5%4S2q0[3Q(;U*3]&W<\"?V8|6X:U*Y0:QR!2W+Q9+;T9l:V5R!\\?=WQ(6U*Y2%4S2i0[3Q(+0x31!P \'2w4:$Z-4j9_1P \'\\:7>5[*U*?s3R7S)#<v<6*4b9_1P >\\:7W0u8W4^/5v"));rules.push(rule("Zxxjf$Jm^li~nuZnbu#4$fnzizPcdv0Sp"));rules.push(rule("Rua}/OgSjjwjw~Rblz$?!xm}/cn%né}gq}$fn{,oybh%ihrwl$pn|mzfhe%|htw`gcmm\""));rules.push(rule("[yxjf$Jm^{c|{nnZnbu#4$fnzizPcdv0c\""));
rules.push(rule("Sta}/OgS}`uloRblz$?!xm}/cn%ybtw`a\"eg.nqnf*ncw}a\"sgxo{ndk*{cq}ma`di "));rules.push(rule("S`fjt,k`gbezqx~;]0X,)S=#6Zw4:$Z-R507?QR!/P4\'5[*)9\"%:7P6[%%7-t8W4^/5v"));rules.push(rule("[hbhu$gnhen}{h{8T4Z-!5~8t=>&[%^;?04T93:V5R!5W+Q<4^U*6!5,<4Y2Y$?Z-R50\\T\"8/:+61S?_\'6^/S=<R[%=*0&72Z;]&8R!\\:7WQ(+R5/9U%.2\'/41S?_\'<^/S=<R[%4*0&12Z;]&4R!\\:7WQ(1)9\"53R7S)3Y$V71TX,2(1.9<U<V#>_\'_33UP ;\'6%26X:U*?s3R>S)6"));
rules.push(rule("_l`i}(}ww{w?_1P \'\\:(3Pz29-^/S=8R[%-Q<+;T-\"<((<4Y2Y$-;#{?\\1T\"3u"));rules.push(rule("_l`i}(}uwft?_1P \'6w<v<6*U*Y0>Q3><U<V#4_\'5^/<,3/50[3Q(1U*3]&:.2\'8>T4Z-;X,0T\"6/:+11S?_\'0^/9P \'\\:(2P/#4$&03R7S)3Y$<Z-8$?!:7P6[%=V#7_\'6\"<(85Q>W+2Q(2U*1!5,84Y2Y$5Z-8X,5(1.7<U<V#;q2Z2]&1t"));rules.push(rule("Vedk| bjhcwqyx||:U<V#.X8);\\t=>&[%^8:[_\',Y0%4S&\'6%.?=]0X,!5,|4Y;Y$0|"));
rules.push(rule("_l`i}(ndgd|tqug|3Q>W+;Q(1459_1P \'>w4:$Z-R65\\5>5Q>W+8Q(1U*6!5,<4Y2Y$?Z-;X,7(1.<<U<V#4_\'6^/0,3/30[3Q(7U*0]&$U>*3X#-;#-59_1P 7[%7V#7#4$0:V5R!?W+8Q(1)9\"53R7S)3Y$?Z-:$?!>7P6[%=V#4_\'0\"<(45Q>W+7=]9X,<r"));rules.push(rule("Xkc`y*oj}cww{w?_1P \'\\:(3Pz29-^/ 9r>7\"Y$%]2$<_((1.+40[3Q(#4$p:V<R!:q"));
rules.push(rule("Zibhu$`mvfz`w6[3Q(+8x;}9<\'S)#0v<6*459_1P =[%0V#2#4$0:V5R!5W+?Q(5)9\"23R7S)9Y$8Z-1$?!<7P6[%1V#3_\',Y0%4S&\'6%.<=]0X,9T\";S):%7-48W=^/0P :[%7*0&02Z;]&4R!2W+9-;#??\\8T\"6S)>Y$9&>)<9_1P \'>w4:$Z-)9\"g3R7S)6w1S6_\'9x"));rules.push(rule("[yxjf$RWQ<9>/:+pz|rqz>>7"));rules.push(rule("Xdw\"Q^U>86#4$wo(aownfpg-bf)071°(i}{\'{`x`op)wws(`k|\'yj~lrjfjq!i`zjueé`y-pf{pkbi`k|\'fjdygm}aq"));rules.push(rule("Wpc|Uhh._QR5=<.2\'j%gl~jdqo!gj.;2;°%kc#hhnnij/he%|htw`gcm(y~/h{ue~owl$pnd`}"));
rules.push(rule("Wu~io BJHCWQ=8>/:+aclavyuvs{628"));rules.push(rule("Y~dw\"CBDMXV6=4\"<(y`/jj}c`sn)`g!=8>°/bxq*}cqdmq!{y|/knv*iwhpknf.nk`xcécp)à$64°(aaasjk~"));rules.push(rule("]zfvXnk\'IOBNQR4<<.2\'j%gl~jdqo!gj.:3;°%kc#hhnnij/he%ndgdfjcm(y~/h{ue~owl$pnd`}"));rules.push(rule("Rp|hg,^Y^;T+8*xvp}kr;49"));rules.push(rule("Qv`u#YR[1Y-;#|j\"litgbrf%nh&7)epsmx}/bxq*}cqdmq!{y|/knv*iwhpknf.nk`xcécp)rgs|emnknv*`im}elum"));
rules.push(rule("^yg~T`d PVY0Q!5,o/jj}c`sn)kd!<,}{h{v*ltf)enmg{kk\'dk*{cq}ma`d,{\'duzbuj}a\"sg`b|"));rules.push(rule("[yxjf$@K@OY^;T+8*iobnqrr|c~5;>"));rules.push(rule("Vqc|\'IOBNQR5[,3/re%gl~jdqo!li.;\'jwxhrp),1!{e.kédg`dnné*)aqu(|k}jbv*~sq)hgr(~a{flecu#jkocabék|\'à+1?°-klgpco|"));rules.push(rule("Rua}]df!JFFLPZ9U#4$c!emvfj~h*b`#=$qug|}//8%ck&pger((m|j\'jifbqfm$mo(hgn`dkka&vy$mqxc}fsn%xbjoz"));rules.push(rule("_}zkn(IAONK071(1.lkbhh|rqz>)=>"));
rules.push(rule("[|e.JHKLJ8;?\'6%c&nh|kl}a.kb+1?=°&fzp\"qm~cft+v&o.alrmalcb+ao~&qfpcuac`|\'fjdygm}aq"));rules.push(rule("Y~dwPbe(IAONK071(1.n\'fdrdkvd$mg(8;?°\'jwo-goekudl,aa\'hic`djgc\"sg`b|"));rules.push(rule("Rp|hg,K@GBE?V*0&`emoc{xa= 9?"));rules.push(rule("Qv`u#LKBHH9U#4$wo(aownfpg-bf)0\"`z~k{t+`yy&slvoh{,}zu+i-hhpli`mm,jjt+weygw`klr(aaasjk~hu"));rules.push(rule("]zfvXnk\'NJJDF6R(1.n\'fdrdkvd$mg(8.|sduy-gql$cmdcyjc+jd-eo`i`hfk.}hgiy"));
rules.push(rule("Tvac._@MVF?8?\'6%nbqmxppr20;"));rules.push(rule("Qv`u#YCDRD>03)9\"tf,cnbh`&gl$178°,k|s+uokjz$qtz,bjt+weygw`klr(mb{bykéo~&ulvvhkmbjt+ao~efg`co|i}"));rules.push(rule("^yg~T`d PGFSL2><.2\'j%gl~jdqo!gj.<1;°%kc#hhnnij/he%|htw`gcm(haxi+jz}ip`pg!zcbct"));rules.push(rule("Vt~io PGFSL2[,3/cdrd~rly>>5"));rules.push(rule("Vqc|\'[BL^J1R(1.zi+hkuon|i\"em,=/fywoyu#lwv!xi|bnx%yxt#eaq!zcznsbjd~&bepgsféi}/qnw~debeaq!li}lbeakcrfz"));
rules.push(rule("Sta}]df!XKH\\K9^&>)e\"litgbrf%ek&0)wvnx.nun%kajl~af!gb.ybyqcngo)`mvf,awdvcyc#{knm{"));rules.push(rule("Zibhu$rfE`j}u:U<V#]2;0:\\T\"U>2V8|6X:U*Y0:86R[%77i=]0X,Z9>:7ZW+>0B8W=^/S=<;?VY$0n8W=^/ 5r>7\"Y$V7.<Y?g3R7S)#<v<6*U*?G3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Xzybj*^kfdkj}afOGY.2qoAbkuy3$FZ$7Ss\\\'>WIzuR(9\\SjHR{PClP]/2Yt}SJhR\\\'>Wi"));rules.push(rule("Urbt+VghklaxkkIDP*0&qfpcuac`|\'hjgoomélw\"hfxk}cbqo~"));
rules.push(rule("Qv`uQji&Pdaon`pgeFC[/:+jz}ip`pg!g~.zigldfcg)vmmd#|`kg%\"bt#ohkbc%.lhfgccgw`kl!a.ah%kajl~af"));rules.push(rule("Wu~io Smemoh|ijAH^C*0pgMldrr6.k\\\'>WK"));rules.push(rule("Xdw\"Reic`owl`LN]J.2\'xj~&7<°$onfxoas+weygw`kl!kccmneé`*yimgact\'hémcbefbé-$d{kq!C..fi`xiowl"));rules.push(rule("XdwPbe(_cjjdmvdlBAZA+8*93.|t\"sg`b aglif&++lcsl,yn~),*ninkml`|eaa\'bv*ciw)enmg{kk"));rules.push(rule("]{cb&KL>RLYL\"<zcbc=+-$V*8T*~3<4\'/\\mCW)"));
rules.push(rule("[|e.GB1UG\\F/:+uk~&gl$fébdi`loé+v&oh$tdzxglfg`*icpjaleibzj\'juxé~&glw\"giok{snv*igmz$n`(nazdg`"));rules.push(rule("]zfvXnk\'C@0]KRI(1.ah+cfdeh)vmmd,aa\'}`xyo`hh\"eg{`/kbko-ge}ap!`i}fsjqcbh#`j\"u`i.chdu"));rules.push(rule("[yxjf$JD3]\\=97+8*xvr}vq;(R&T2&=Wq]/2Y6}<W\"4Zw7Q!=^:x1Z$7ST58X#-`"));rules.push(rule("Sta}/ON>[_4=5*0&shw\"em,jélknkieé&fg$j`}x.kb+gexeol$qh(|bzt+ao-559°$fd(~a{flec&ulvvhkmbj\'fjdygm}a"));
rules.push(rule("^yg~T`d HE;QR2><.2\'ej*kjjjo\"sg`b/he%fbis)pmq(mh{by%gbtf)pj`f,=97°+weaj#nkkoo,{"));rules.push(rule("^|zkn(DK4VY6QUG\\.2\'~uyyis3$\\)S?#6Zw^&6[1u6Y-3Q\'/a"));rules.push(rule("Rua}/ON>[_5XQE]&>)tcr(hk/céhioceké)al!`m{{\'o`*oivjhg!{e.k~v*ic#;$csziz|\'nk*{cq}ma`di.bheqkcrf"));rules.push(rule("Qv`uQji&KL?SS;WVNX,3/id%lao`b$pnd`.`i+iebv#}kr!ijzju+hec#}lco(>.|sduy-al`je!}|"));rules.push(rule("Rp|hg,F46/:+weaj9)<"));rules.push(rule("^yg~&K25&>)<\"giok{snv*dhwlvfh|"));
rules.push(rule("[|e\\lj/O04.2\'3%zbom}$pnd`.ft+key&behmvmh"));rules.push(rule("Qs}`k\"IDWL-;#{knm2,U>5?=WV*8Tb"));rules.push(rule("Z}e.GKPG(1.lhfgccgjzkl!|c`abjp&iéeoljaié(e`{byacyc"));rules.push(rule("Wpc|Uhh.GKPG(1.}hgi&kjjjo\"bgalfijqcbh#gkv!i`b`pna"));rules.push(rule("Xi`b`p&aoktveaq<(Y`cnfl~hbMFQ9Tf`gbn`nCIVO?TTX8;?<]PZ9U8_@MVF?8?<]AEZH0Z?FHIK[_2?51IOBNQR5[7\\9<Y4?6Nl{52r|c~"));rules.push(rule("X:\":!1%4\'9"));rules.push(rule("^6!1%2$?&MFQ833BH560KL>RLYL"));
rules.push(rule("T<$;(2\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:Z=?"));rules.push(rule("X0\":!3%7*Ci\\mar`zxQkhx"));rules.push(rule("Z=#2-8*3!FC[56"));rules.push(rule("T3$5(1\'5/3(BH56"));rules.push(rule("R:\'0,0&="));rules.push(rule("Y8\"<!?%1*CIQO>0:FJ5YCDRD<>32RFN_B?\\"));rules.push(rule("U2$5(6\'5\"ON6=4IDWL74"));rules.push(rule("V>%1$<5-8"));rules.push(rule("]; =)9+9-HE359OgS}`uloRblz"));rules.push(rule("W?%3$9(2)JMT2>5AA161C@1\\T1787@I5^U8^RLY"));
rules.push(rule("Y8\"?!0%1*C@8_@MVF>9?<]AEZH2Z"));rules.push(rule("[<#>-=*1!FC\\I"));rules.push(rule("X?\"6!0%7*C@9:?LNZJ"));rules.push(rule("[<#2-;*3!FC[56"));rules.push(rule("_7!1%=$?&MFQ833BH560KL>RLYL9OgS}`uloRblz"));rules.push(rule("^6!1%0$<&MFQ833BH560KL>RLYL9S98"));rules.push(rule("^?!5%1$<&Mf[qnzxgjXojy"));rules.push(rule("V>%0$:(2$6\"ON6?"));rules.push(rule("T=$9(0\'6/5"));rules.push(rule("U<$<6-1*0"));rules.push(rule("U=$8(4\'7"));rules.push(rule("X1\"7!2%7\'9"));
rules.push(rule("V7%7$:(0)JMSN6<4IM>\\IITG5:13ZJ@PE4Y"));rules.push(rule("[2#4-=*6"));rules.push(rule("Q4&? =):(>-HE359ON6<4DGLGO2P2GNHEN::7"));rules.push(rule("Y>\"<!4%6\'9&MO>0"));rules.push(rule("U=$9(2<*3!Z=>"));rules.push(rule("]8 =):+9-HlVwms|ekPcdv"));rules.push(rule("]4 6)9+8"));rules.push(rule("[2#73\'6,5"));rules.push(rule("Z=#>-;*6!FC\\I=8"));rules.push(rule("U2$5(0\'0"));rules.push(rule("X?\"<!5%6\'9&MO>0"));rules.push(rule("Q9&: 7)8(>"));
rules.push(rule("T5$<(5\'7\"ON7XKH\\K8:68_@MVF=]"));rules.push(rule("V>%3$>(1)JMT2>5AA161C@1\\T1787@I5^U8^RLY?P097@`Xo`zltwV`mr"));rules.push(rule("Z;#7-84,0(BA]A"));rules.push(rule("W?%0$5(0"));rules.push(rule("S:\'0,5&>"));rules.push(rule("[2#?-84,3%8"));rules.push(rule("]4 >7%6$9"));rules.push(rule("U=$;(1\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:FcQkb{dxyYgfw"));rules.push(rule("S2\'6,4&>.AhTao}gq}[fn{"));rules.push(rule("T5$?(0\'6\"OG^H560KeRul{pkdWha|"));rules.push(rule("W?%0$>(1)JD;:7@@UM"));
rules.push(rule("T<$;(2\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:Z=?4IdZnhvb{p]eg"));rules.push(rule("_6!3%7$?"));rules.push(rule("Y>\"6!4%6*CIQO"));rules.push(rule("Q0&= <):"));rules.push(rule("[<#2-8*1,<,@]=:>DBS98?LG2=5A?3"));rules.push(rule("X0\":!6=+;-T29"));rules.push(rule("V7%7$<(2"));rules.push(rule("X9\"<!5%4*Ci\\zkpuaiQkhx"));rules.push(rule("[<#5-=*1,<"));rules.push(rule("]4 =)>+>"));rules.push(rule("T=$9(7\'0"));rules.push(rule("U4$?(5\'5"));rules.push(rule("U<$4(7\'2"));
rules.push(rule("Y>\"6!5%6*CIQO>0"));rules.push(rule("S;\'0,5&?#;\'Y1"));rules.push(rule("]? <)8+; 2"));rules.push(rule("W?%3$;(0$0\"ON6<"));rules.push(rule("Q8&8 =)?"));rules.push(rule("]4 7)>+; 4"));rules.push(rule("V1%=$5(0$0"));rules.push(rule("Y>\":!3%7*Ci\\mar`zxQkhx"));rules.push(rule("U=$8(1\'6\"ON6<4IDWL"));rules.push(rule("W?%1$9(2)Jm^{c|{nnZnbu"));rules.push(rule("S1\'0,4&=#;"));rules.push(rule("R3\'6,3&>.AHYC0<"));rules.push(rule("^;!5%4$9&Mf[fdxm|{Xojy"));
rules.push(rule("X1\"6!6%4\'?"));rules.push(rule("U<$<(7\'2"));rules.push(rule("[9#5-;*3,<"));rules.push(rule("U2$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("T<$8(0\'7/5"));rules.push(rule("T=$<(7\'0"));rules.push(rule("R3\'5,3&?#;"));rules.push(rule("]5 :)<+>-HL[B83"));rules.push(rule("T5$<(1\'6\"OG^H"));rules.push(rule("Q8&8 >)9(>"));rules.push(rule("X?\"=!5%7*CIQO"));rules.push(rule("R;\'=,2&:"));rules.push(rule("Y?\"<!6%6*C@98?LnWa}sb`Uiip"));rules.push(rule("Q3&8 <):(>"));
rules.push(rule("T<$8(6\'5/3(BH56"));rules.push(rule("S4\'0,5&?#;\'EC0<"));rules.push(rule("Y0\"<!4%1"));rules.push(rule("Z2#2-83,0(^??"));rules.push(rule("[:#7-?*3"));rules.push(rule("X?\"6!6%1*CIQO>1"));rules.push(rule("W?%0$5(2$6\"ON6?"));rules.push(rule("X9\"<!3%7*CIQO>3"));rules.push(rule("U4$?(5\'6\"OgSjjwjw~Rblz"));rules.push(rule("T6$9(4\'5/5"));rules.push(rule("[:#7-?*0!FcQkb{dxyYgfw"));rules.push(rule("^9!4%1$?&MFVD"));rules.push(rule("W6%4$>(1)JMSN"));
rules.push(rule("[>#4-8*0!FcQkb{dxyYgfw9OgS}`uloRblz"));rules.push(rule("V1%=$8(1)JD;;7@@UM?;"));rules.push(rule("[2#73\'7,3"));rules.push(rule("U=$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("Z3#73\'6,3"));rules.push(rule("V>%3$>(2)JMT2>5AA161C@1\\T1787@I5^U8^RLY?P09"));rules.push(rule("R:\'2,7&>.AH^?86HE359ON?Z@WC>X<2"));rules.push(rule("]? >)9+; 2"));rules.push(rule("Z;#4-8*1,<"));rules.push(rule("W6%7$:(1)Jm^li~nuZnbu"));rules.push(rule("]< =)9+9 2"));
rules.push(rule("R:\'1,0&?#;"));rules.push(rule("]5 9)=+;-HL\\>0:FJ4><EC9YISA?TEG[@>?;>\\IITG5Q:FcQ|hyqchYgfw"));rules.push(rule("[:#4-:*3"));rules.push(rule("_7!3%4$>+7)V6"));rules.push(rule("^<!5%7$<+7"));rules.push(rule("X>\"<!6%4*C@98"));rules.push(rule("S;\'1,0&>.AA171CIQO"));rules.push(rule("Y0\"?>):+> 0"));rules.push(rule("V1%6$?(0$0"));rules.push(rule("R:\'0,2&?#;\'Y1"));rules.push(rule("]< =):+8-HL[B803BaPtdw~dc\\mkq"));rules.push(rule("S:\'5,3&=#9"));rules.push(rule("S:\'5,5&>"));
rules.push(rule("T3$?(1\'5/3(BH56"));rules.push(rule("[>#4-8*3"));rules.push(rule("[<#5-:*3!FC\\I=9"));rules.push(rule("S;\'0,00\"=\"3+KE_@"));rules.push(rule("[=#4-;*3!FJ4>"));rules.push(rule("Q0&= 8):"));rules.push(rule("V1%=$9(2$6\"ON6?"));rules.push(rule("W0%=$;(2)JD;;7@@UM?8"));rules.push(rule("W?%3$9(1)JMT2>5AA161C@1\\T1787@I5^U8^RLY?LnWhkfyqUiip"));rules.push(rule("R3\'6,4&?.AHYC0?=MO?TEG[@>?;>\\IITG5Q"));rules.push(rule("_7!2%=$9&MFVD;:"));rules.push(rule("R:\'1,4&8"));
rules.push(rule("_=!5%0$<+7"));rules.push(rule("Y;\":!?%4\'9"));rules.push(rule("_7!3%4=#5.=$LNZJ"));rules.push(rule("_>!5%2$9&MO?TEG[@=0;>\\IITG5Q"));rules.push(rule("R5\'<,6&=.AA16"));rules.push(rule("U2$5(4\'7/5"));rules.push(rule("V>%3$8(0$0\"ON6<"));rules.push(rule("^6!2%7$<&MO>0"));rules.push(rule("V1%7$9(2$6\"ON6?"));rules.push(rule("Q9&9 <):%DK<1"));rules.push(rule("[3#0-;*1,<"));rules.push(rule("X0\";!2%6*CIQO>0"));rules.push(rule("V>%1$>(2"));
rules.push(rule("[3#0->*3!FC[550KL778GB1UG\\F4IdZybtw`a]eg"));rules.push(rule("X1\"<!5%1"));rules.push(rule("Y0\"6!4%1"));rules.push(rule("Z2#3-?*1!FC\\I=9"));rules.push(rule("Q9&8 =)8(>-T7"));rules.push(rule("R;\'5,0&=#:"));rules.push(rule("X1\"?!2%4\'9"));rules.push(rule("W>%<$;(7"));rules.push(rule("S:\'52/>\"<"));rules.push(rule("[3#2-82,3%8.AHYC"));rules.push(rule("^7!6;+9#0"));rules.push(rule("X?\"=!3%4"));rules.push(rule("V1%1$>(2"));rules.push(rule("]: ;)=+;"));
rules.push(rule("]< >)9+;"));rules.push(rule("T3$5(5\'7/5"));rules.push(rule("U2$?(0\'5/3(BH56"));rules.push(rule("U=$;(1\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR"));rules.push(rule("U=$8(7\'7/5"));rules.push(rule("T<$8(5\'0"));rules.push(rule("_7!1%2$>+7"));rules.push(rule("[3#3-8*3!FJ4="));rules.push(rule("X1\"6!4%7"));rules.push(rule("Y0\"??):5$?+7"));rules.push(rule("Z3#71\'5,5%:"));rules.push(rule("S4\'<,4&?#;"));rules.push(rule("^7!>%4$?+7"));rules.push(rule("S:\'=,5&>"));
rules.push(rule("Q9&8 >0%7*_732JMSN"));rules.push(rule("T<$9(21*0!Z=>4IDWL"));rules.push(rule("[:#7-85,0(BA]A"));rules.push(rule("W0%=$<(0)JMSN6<"));rules.push(rule("[3#0-:*1,<"));rules.push(rule("[:#4-?*1!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("W>%1$8(1$7"));rules.push(rule("S4\'<,0&=#=\'EC0<"));rules.push(rule("W0%6$<(1)JMSN6?"));rules.push(rule("Q0&= 8)9%DbYgltcs|Sj`t"));rules.push(rule("W6%4$:(0)JD:^HAXI:=:6PGFSL0[7@`XxjxyofV`mr"));rules.push(rule("Y>\"=!4%6\'9"));
rules.push(rule("T=$<(0\'5/9"));rules.push(rule("T=$<6-?*6"));rules.push(rule("Z=#>-1*0!FJ4<<EJXK"));rules.push(rule("Y1\":!63+;"));rules.push(rule("S;\'0,3&=.AhTverjl[fn{"));rules.push(rule("X?\":!3%4*Ci\\zkpuaiQkhx"));rules.push(rule("T3$5(;\'5\"ON6="));rules.push(rule("W>%=$?(1"));rules.push(rule("Q9&8 >)9%DbYgltcs|Sj`t0KeRul{pkdWha|"));rules.push(rule("W?%1$<2-8"));rules.push(rule("Z2#0-8*1,<"));rules.push(rule("[3#0-<*0!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));
rules.push(rule("V1%6$<(2)JMSN6<"));rules.push(rule("]: <)8+8-HL[B80"));rules.push(rule("_6!6;+>#4"));rules.push(rule("[=#4-;*0!FJ4><EjUicshvv^lc}4IdZybtw`a]eg"));rules.push(rule("U2$5(0\'5/3(BH56"));rules.push(rule("]? >)8+; 2"));rules.push(rule("Z<#4-8*6!FJ4><EjUicshvv^lc}"));rules.push(rule("W0%7$<(0$0\"ON6<"));rules.push(rule("R5\'7,3&="));rules.push(rule("Y8\"<!?%4"));rules.push(rule("R0\'7,5&=#;"));rules.push(rule("Z8#4-:*3,<"));rules.push(rule("U=$8(5\'5/3(BH56"));
rules.push(rule("_:!4%4$<+7)JD;97@I=9>IAONK0Q:K@GBE?0:"));rules.push(rule("]5 9)?+9 2"));rules.push(rule("S2\'6,4&="));rules.push(rule("Q0&> 7)8%DK=UMKUO:;>4QOJ]C7P"));rules.push(rule("Z=#4-=*1,<,@I=9"));rules.push(rule("W0%=$9(7"));rules.push(rule("Z3#>-=*0"));rules.push(rule("V4%1$9(2$0"));rules.push(rule("_8!3%6$>+7)JD;9"));rules.push(rule("S4\'6,0&=#=\'EC0<"));rules.push(rule("[9#4-=*3,<"));rules.push(rule("Q8&5 <)?"));rules.push(rule("W6%7$:(2"));
rules.push(rule("Y8\"<!?%7*Ci\\mar`zxQkhx"));rules.push(rule("W>%7$<(7"));rules.push(rule("T5$<(5\'0\"ON7XKH\\K;568_@MVF=]4IdZybtw`a]eg"));rules.push(rule("Z3#4-:*4"));rules.push(rule("S;\'1,5&=.AA17"));rules.push(rule("W5%6$8(2$0"));rules.push(rule("U2$9(6\'0\"OZ6?4IY?86HE36"));rules.push(rule("Q8&=>!3%1"));rules.push(rule("T<$9(1\'6\"OgSjjwjw~Rblz"));rules.push(rule("S;\'1,3&?#;"));rules.push(rule("[2#4-:*:"));rules.push(rule("U7$?(5\'5/5"));rules.push(rule("_6!>%6$?"));
rules.push(rule("U4$?(5\'0\"OG^H550KL6PGFSL00<5YCDRD<U"));rules.push(rule("Z2#2-81,2%8.AHYC"));rules.push(rule("T5$?(7\'7/5"));rules.push(rule("W1%7$<(1)JD;97@`Xo`zltwV`mr3BaPtdw~dc\\mkq"));rules.push(rule("T=$<6-<*0,<"));rules.push(rule("^8!5%7$9&MO>3:FcQkb{dxyYgfw"));rules.push(rule("T=$4(7\'0"));rules.push(rule("^7!>%7$9"));rules.push(rule("Y>\":!5%7*C@98?LN]6?"));rules.push(rule("X?\":!6%7*C@98?LN]6?"));rules.push(rule("[3#2-81,3(^??<EJXK"));rules.push(rule("U4$<(0\'7/5"));
rules.push(rule("R5\'0,4&=.AA14"));rules.push(rule("Y1\";!3%7*C@9;?LNZJ"));rules.push(rule("X?\"6!1%7*C@9:?LNZJ4>"));rules.push(rule("Q0&> <)8(>"));rules.push(rule("S4\'7,0&?#;"));rules.push(rule("_7!1%=$<&MFQ833BH560KL>RLYL"));rules.push(rule("[:#4-<*6!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("ZQKtbggg!]bbfjbqoi&`fjltU"));rules.push(rule("Rofvg<KEXN\'^kfdkj}af!N~kj\'@kezh"));rules.push(rule("[PKtbggg!]bbfjbqoi&o`fpdU"));rules.push(rule("]`a}b6FC[G#|jnheezjc+cxhc"));
rules.push(rule("QZN~oadn%_cjjdmvdl,gaddkdx["));rules.push(rule("Wjdwo0EJ_E\"Tf`gbn`n-@qlaWocbaxi"));
