// OpenAero rulesYY-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####   Régles France 2018 Espoirs à Doret    Version 2018.0.10    ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####      Modifications mineures (commentaires) et connus 2014    ###################
//#####      Corrections, modifications espoirs 2015, connus 2015    ###################
//#####      Ajout de règles (déclenchés) d'inconnu Doret 2015.      ###################
//#####      Prise en compte du distingo entre rotation alternées    ###################
//#####      (,) et rotations même sens (;) dans les régles 2015.    ###################
//#####      Modifications 2016, connus 2016, nouveaux noms.         ###################
//#####      Modifications 2017, connus 2017, connu_x -> connu x.    ###################
//#####      Modifications 2018, connus 2018, noms (in)connu-libre   ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2018 : Espoirs, Desavois, National2 et Doret.

//##### (Une partie des) Règles spécifiques à la France.

rules.push(rule("XSJ|nih`*Husfmpr(oaai~X"));rules.push(rule("^jjjd%7-cg)6e!az;|)%+T-k.wz\"66,p\"*&(\'>l.7$*3$=<&\'&ej?e$.6,&/,f!)%+--i#:!\"l:,<*\'9ot3&1;"));rules.push(rule("_d\"jj}7<43"));rules.push(rule("Qlg~k2Ayddnc#Lwrna~}/fgi"));rules.push(rule("T_Lgmja\"D{|afux%ccelgjw\\"));rules.push(rule("Vm&hku;2;4"));rules.push(rule("Wjdwo0@qhjad(I}hbwy-goe"));rules.push(rule("XSJ|nih`*Husfmpr(`gmunX"));rules.push(rule("[` kbq9328"));rules.push(rule("Sahwggak#bfs8;?"));
rules.push(rule("Qgia;\"jbk7<"));rules.push(rule("Rdhi5,ee`26"));rules.push(rule("Sehi:,ee`26"));rules.push(rule("Tveaj.dml<9"));rules.push(rule("Uvzdh.dml<9"));rules.push(rule("[n`vwphkom!cn65"));rules.push(rule("_mntnccj+qltg`|1?"));rules.push(rule("[fbtf4Bp`fok/Bxuedtp)enm"));rules.push(rule("[#Ktbggg!M~`nyv*ljo "));rules.push(rule("Vum%7-ggelbmh"));rules.push(rule("Ssfwnk5=>"));rules.push(rule("Tte~ho452"));rules.push(rule("]kb`fldj+sfmlu5<"));
rules.push(rule("^i}h~u\'ysqgtmr5R<S)P4\'9[_\'5^/9"));rules.push(rule("Qu}~`hx(dlkf4$thzmijt+socrql"));rules.push(rule("Rv|vlqg#bfs8;"));rules.push(rule("[yxjf$WRHF1|`kg?TVXpT"));rules.push(rule("Qv`u#\\WBK7Kod|vg!izkl\'}wcajf)qlhyykbbeq"));rules.push(rule("Ufecp.{kv^i`z/:+[3Q(_m/^/;P \'\\:(2P/#4$&03R7S)Wa!Q(X8664UP T6&=W-;#q?\\8T\".2\'r>T=Z-4~"));rules.push(rule("_}zkn(DbYbep]5=,3/udqUljw3$zZ$7S"));rules.push(rule("Wpc|\'Ci\\hhv^<9.2\'Yj~lrjfj\"`dxk}ién%ccrf{`kum,}zu+io~&o`cld{,à.;2°"));
rules.push(rule("Sq|hg,FcQnkZbbt#4$pn|Socs1%Q!=^"));rules.push(rule("Sta}/OgSocsTme&>)Vmuixg`i+dfycqgéa\"hfxk}cbqo"));rules.push(rule("Wu~io Kbq[cm|S9=7+8*iwVenu2,&7\\\'>Wq]/2Y:}>W\"4Z=y<V*8T0~5S 5R1\""));rules.push(rule("_xg~&HkuYbep]6:<.2\'Yj~lrjfj\"`dxk}ién%fdkj}éa\"à!?>>°"));rules.push(rule("Tefait$`ggzybjt+8*Ci\\hhv^<9"));rules.push(rule("Y1\":!6%4*CT98?LS2?"));rules.push(rule("Y8\"?!4%4"));rules.push(rule("U4$<(2\'5/5(AowXji~R119"));rules.push(rule("^6!2%7$9&Mf[cm|Sf`u"));
rules.push(rule("^;!4%4$<&M[>3:F^4=<EW0>"));rules.push(rule("[:#4-;*1!F^4><EW0>"));rules.push(rule("R5\'6,0&=.AU141Ci\\hhv^`c|"));rules.push(rule("T<$8(5\'5\"OgSocsTme"));rules.push(rule("[3#0-8*3!F^4><EW0?=M[>1"));rules.push(rule("V>%0$5(1)Jm^i`zPodw"));rules.push(rule("W>%7$>(;"));rules.push(rule("[3#3-<*6!F^4>"));rules.push(rule("Q6&4 7):%D_<0"));rules.push(rule("Z;#4-8*1!F^4><EW0>"));rules.push(rule("[:#4->*3!F^4>"));rules.push(rule("Z;#7-:*6"));rules.push(rule("U2$>(1\'5"));
rules.push(rule("S2\'5,6&=.AU14"));rules.push(rule("^9!?%1$<&M[>3"));rules.push(rule("U2$5(5\'7\"OZ6?4IY?9"));rules.push(rule("R:\'1,0&?.AU141Ci\\hhv^`c|"));rules.push(rule("R;\'5,2&:"));rules.push(rule("S:\'5,2&4"));rules.push(rule("^7!6%7$9"));rules.push(rule("X9\"<!4%1*CT9:"));rules.push(rule("W?%0$?(2)JP;;"));rules.push(rule("Z2#2-:*3!F^4><EW0>"));rules.push(rule("U=$8(0\'7\"OZ6?4IdZkar\\akp"));rules.push(rule("X=\"<!6%4*CT98?LS2?"));rules.push(rule("R5\'<,9&8.AU16"));
rules.push(rule("^6!2%3$9&M[>3"));rules.push(rule("]< >)9+9-HQ35"));rules.push(rule("Z8#7-8*3,:"));rules.push(rule("X?\"=!3%1"));rules.push(rule("Y>\":!6%4*CT98"));rules.push(rule("Q8&= <)?"));rules.push(rule("T=$<(7\'6"));rules.push(rule("V?%7$>(5"));rules.push(rule("[9#5-8*3,:"));rules.push(rule("_6!6%6$?"));rules.push(rule("_>!5%3$<&M[>3:F^4<"));rules.push(rule("]4 >6%4$9+4"));rules.push(rule("R:\'1,5&8.AhTdfyYkfv"));rules.push(rule("Q9&9 ;):%DbYbep]ig~"));rules.push(rule("Y8\"<!3%1*CT9:"));
rules.push(rule("R3\'5,7&?.\\WBK"));rules.push(rule("W6%7$>(2)JP;;"));rules.push(rule("]4 >)9+8"));rules.push(rule("]? ;):+; 4"));rules.push(rule("W6%4$?(2"));rules.push(rule("U<$?(0\'0"));rules.push(rule("W0%6$9(2"));rules.push(rule("[<#4-8*6!F^4><EW0>"));rules.push(rule("[9#4-8*3,:"));rules.push(rule("T3$?(1\'5\"OZ6?4IdZkar\\akp"));rules.push(rule("[<#5-:*1!F^4>"));rules.push(rule("XSJ|nih`*Icphrmh{#~}hfj~dim)gmofyS"));
rules.push(rule("^jjjd%7-ci)+|# <( c\">#x}7$5?(\"c>*+74-+j*,&a ! +*2o(-./ba(>0/yu1amf.id\"ah!a=,k%jm-ga,,(&\" !),.!&x#;!\"36, !jm(* 0#idb*9fa>,kej"));rules.push(rule("Vm&hku;2>4"));rules.push(rule("Snfvg<N~oadn%Nhubkkr\'||`jdqcbh#hhn"));rules.push(rule("V]Mwkcef)@grizaft$uxbkl}mmo(e`lhekP"));rules.push(rule("[` kbq934="));rules.push(rule("Ydc|j:Mwkcef)@grizaft$uxbkl}mmo(mbc"));rules.push(rule("ZQKtbggg!Li}nqdly\"vqfimuac`/kbgxh["));rules.push(rule("Sh$icy5>>?"));
rules.push(rule("Ykm}jabb\'`g{450"));rules.push(rule("Xnmc:*fld07"));rules.push(rule("Yomc8*fld07"));rules.push(rule("Zllk;$iko5="));rules.push(rule("[x}om$iko5="));rules.push(rule("[}iw$iko5="));rules.push(rule("Qu}~`hx(gl~>8"));rules.push(rule("U`g}rzemld%aow:;"));rules.push(rule("Xjm}jabb\'cslev<9"));rules.push(rule("X{bo*y`zhgw45"));rules.push(rule("Yz|ga*y`zhgw45"));rules.push(rule("Rofvg<N~oadn%Nhubkkr\'||`jdqcbh#hhn"));rules.push(rule("Q)N~oadn%Nhubkkr\'||`jdqcbh#hhn("));
rules.push(rule("_|i\'6%kipbggge"));rules.push(rule("[{buoc934"));rules.push(rule("]}a|ig8;8"));rules.push(rule("Wagjkyomn)rnabz27"));rules.push(rule("Xo~azw&qhsfw?_:P T6&1WQ(2U*3"));rules.push(rule("Z~xtmykq,fmcj:+scgdlw\"wmbz}b"));rules.push(rule("Yn~azw&sxbr>W=^/S=:R[%4V#4"));rules.push(rule("Rt{kv,fmcj:+weygw`kl!~i|{nhdfh&nfjv`fxk/cn%;56°"));rules.push(rule("Vayj}+qfhndz1P=[%-8Q(X<2_};P ;.W+"));rules.push(rule("Wudifht.geod5,z`ie`kx~#lj\"wa~ohb"));
rules.push(rule("Y{ybj*XUCC;qfhn;VWP|Z"));rules.push(rule("]zfv*XUCC;E`cwsm,oybh%|ooea\"tfezbf`dy"));rules.push(rule("Wu~io Us`j]n}S|fbe8xbjo3ZY_{vS"));rules.push(rule("Vqc|\'^vjg[mtW~gji6Ccjsql$qd}`k/h~%k{c`)rphd`k/rel{xcnljv!{y|/kj%|htw`gcmm"));rules.push(rule("Vt~io HEJ9pnd`4\'[|^&6[XoB_(t$UiAV^&6[_~-"));rules.push(rule("Y~dw\"IMF7}gp)`g!léobjihmé*igmz$nd{,|`sjqcbhp)gmlxc}éjt"));rules.push(rule("[hbhu$rgs|}z}t6[3Q(+R5/8Up??.W+\"V76?Y~08%R!/P4\'5[*)9\"%;7P6[%%7-t8W4^/5v"));
rules.push(rule("Zxxjf$R398,3/qnw~|rqz>>2"));rules.push(rule("Xdw\"Q:=:-;#Yeq!li.}hd~dim)wwqm~gjry`*à-7;9°$qtz,bjt+sorjjend{"));rules.push(rule("_}zkn(Gl~:9$?!~i|{vwy7:1"));rules.push(rule("[|e.Dez88,3/Wjv*ic#{kv`|eaa\'xpzhtjlqpd(à,7?°\'xpx-efz$tdzxglfg`y"));rules.push(rule("Rafjt,~i|{r{t~u>W=^/ W?\">Vy;=/_\',Y0>Q\'S)#^; >^ $?!,?5Q>W+*0&q2Z2]&1t"));rules.push(rule("Xzybj*Fdr46vy$?!~i|{r{t~u956"));
rules.push(rule("Z}e.Dez88y~/:+Uk~&gl$pn|mzfhe%yxvf{mgtzi.à/>;°%yxt#ee\"wm~zfdjio-klgpco|i"));rules.push(rule("Vedk| pf{pfnyx||:U<V#.X8);\\t=>&[%-?q73 X,)S=#7Z\"%7-\"02Z;]&,3/u0[:Q(>s"));rules.push(rule("[yxjf$Icy1<j`\'6%|htwmksuz435"));rules.push(rule("Rua}/Lit7?cd%7-Vbz$fd(~a{flec&p|tgsai{}b+à%3=°&p|v\"mi,xjuliljf)`grki`kfeqo"));rules.push(rule("Vedk| hlyqqi5R7S):^;?[_\'5^/S9#7Z6k1S?_\'_33<4SS)6w1S?-!=~08%3i<U<$<]2;Y?r3R>S)6"));rules.push(rule("^|zkn(D^Vvzlmt|,3ah{pye<m-"));
rules.push(rule("_xg~&KY]spakwu(1._fx%nh&pfvvhm,~`rxvéo-gs{èw\"mi,x}ngio"));rules.push(rule("Tjoj+mhig<neizunv*nimzmfésém.lhfho-hédhpkwm"));rules.push(rule("]naaq&Meww{w?_1P Sc Y$V5;TX,)S=#7Z\"8.<=]0X,<87P?[%8:"));rules.push(rule("Sq|hg,Emv85;Me&>Akpp|~}5;2"));rules.push(rule("Vqc|\'@g{>62Ig~.2\'[dy-bf)vmuixg`i+fe`vlzéa\"ig~guheqkac#zqrdzekzun%à*:43°"));rules.push(rule("Tgecp.\\t64yx||:U<V#Zg\"X,Z:;SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("Zxxjf$Icy;:>Zw?0*0Ss=1suz432"));
rules.push(rule("Sta}/Lit=97^u>8&>)Tcr(hk/udqkyolg$ane|a|éb+vexu#=1°\"lgbzni%yxvf{mgtzi.à/4=5°"));rules.push(rule("Yjc`y*Oj>8ww{w?_1P Sc Y$V2:TX,)S=#7Z\"8.<=]0X,<87P?[%8:"));rules.push(rule("_}zkn(Gl~214Fn<9.2Cd1?|rqz>>2"));rules.push(rule("[|e.Dez00<J`3>%7-Vbz$fd(~a{flec&`firn{éi.|h~v*93°#maqbmbjni%yxvf{mgtzi.à/635°"));
rules.push(rule("Ufecp.{kv^yx||:U<V#?_\',Y0%9S&[%-Q<+;T-?qn(<4Y2Y$4Z-!_4,1Qr>7\"Y$%]2$<_(5|H+50[3Q(29X,)S=#:Z\"Y$%]2$<_(5bh+50[3Q(29X,)S:#6Zw4:$Z-!_3,0Q\'2iM!86X:U*Y0%4SS)P4\'8[_\',Y0%4S&:y!;6X:U*3Z9>SS):Y$%]2$<_(5*><U<V#;q2Z2]&1t"));rules.push(rule("Zxxjf$Jm^LicfX{jy-;#{kv^yx||={c8"));rules.push(rule("Qv`u#AhTAo`o\\ykq!5,Jjjb%nénjfggjé!xc}fsbc*dhwlvfh|"));rules.push(rule("Yh`b`p&aoktveaq!5,@ID0S;568Dez6:<F`u0Hku559Qr5=7Cn:=:Ii7<"));rules.push(rule("Zkajl~9\\Z?47R"));
rules.push(rule("Q9&9 ;):%DK<1"));rules.push(rule("Z=#>-8*3,:,@]=:>D_<12JP;;"));rules.push(rule("X0\"8!1%7*CT98?LS2>5AU16"));rules.push(rule("^6!3%4$<&Nh|;1lc"));rules.push(rule("]8 =):+8-HQ359OZ6<"));rules.push(rule("U7$?(2\'5/3"));rules.push(rule("[3#0-:*3!Emv67~u1CT9;?LS2?"));rules.push(rule("V7%7$8(1)JP;97@]=9"));rules.push(rule("T3$?(2\'5\"ON6?"));rules.push(rule("R:\'1,9&=#=\'EC0<"));rules.push(rule("^7!3%4$?"));rules.push(rule("Q0&> =)8%D_<22Icy1<"));rules.push(rule("[<#4-:*1!F^4="));
rules.push(rule("]< >)=+>-US@J9O[\\{|odp~"));rules.push(rule("U<$5(2\'5"));rules.push(rule("S:\'5,3&8"));rules.push(rule("V1%7$?(2)JD;97@`XO`gdYsfw83"));rules.push(rule("]5 ;)9+;-HQ36"));rules.push(rule("]: =)?+8-HE359OgSJjjbZzbu9;"));rules.push(rule("R:\'2,4&=.AU171CT9:"));rules.push(rule("R;\'0,2&8"));rules.push(rule("^<!6%6$<+7"));rules.push(rule("^9!?%3$<+7)JP;97@]=8"));rules.push(rule("[3#3-<*3!FJ4><EW0?"));rules.push(rule("_>!5%1$9&Nh|;1"));rules.push(rule("_8!5%6$<&MO>3:F^4="));
rules.push(rule("V?%4$>(5"));rules.push(rule("V>%0$?(7"));rules.push(rule("S4\'<,2&8.AU14"));rules.push(rule("]4 =)8+2"));rules.push(rule("[<#>-;*6!F^4><EW0?=M[>1"));rules.push(rule("V1%6$<(1)JP;9"));rules.push(rule("V>%0$:(2$6\"ON6?4IY?8"));rules.push(rule("S:\'0,2&:"));rules.push(rule("W6%7$<(2)JP;:"));rules.push(rule("Y8\"?!6%4\'9"));rules.push(rule("W5%1$<(2$6"));rules.push(rule("X9\"<!1%7*CT98?LS2>"));rules.push(rule("X=\"=!5%4*CT9;?O`p5>kh"));rules.push(rule("[<#4-8*6!F^4><EC0?"));
rules.push(rule("]: =)?+;-HE35"));rules.push(rule("R3\'5,7&?.\\WBK"));rules.push(rule("^9!4%4$>+7)JP;97@]=9"));rules.push(rule("]< =)8+>-Kbq=2"));rules.push(rule("[3#2-=*0!F^4><Fdr46gf"));rules.push(rule("Z2#0-8*3!Emv67~u1CT9;?LG2?"));rules.push(rule("Y1\";!1%4*C@98"));rules.push(rule("[2#?-:*0"));rules.push(rule("V1%=$9(2$6\"OZ6?"));rules.push(rule("^6!2%6$?&MO>0"));rules.push(rule("T=$<4-8*6"));rules.push(rule("U4$<(4\'5\"Lit7?"));rules.push(rule("]< =)?+8-HQ36"));
rules.push(rule("[<#>-1*3,<,@]=8"));rules.push(rule("R:\'1,2&?#;\'EW0<"));rules.push(rule("_=!5%0$<+7"));rules.push(rule("Q3&> 9):(>"));rules.push(rule("Q0&= =)8(>-HQ35"));rules.push(rule("^?!5%4$>&M[>3:Emv67"));rules.push(rule("U2$>(0\'5"));rules.push(rule("W?%1$?(1)JP;97Cn25nb"));rules.push(rule("V>%1$>(1)JP;97@]=9"));rules.push(rule("Z?#4-8*3!Emv67oj"));rules.push(rule("T3$9(2\'6/5(B\\56"));rules.push(rule("U2$5(7\'0\"OZ6?"));rules.push(rule("V>%1$<2-8$LS2="));
rules.push(rule("V>%0$<(2)JP;:"));rules.push(rule("[<#4-8*0,;,@]=:>D_<1"));rules.push(rule("^6!2%4$9&M[>3:F^4="));rules.push(rule("Q4&> >)?%D_<22Icy1<"));rules.push(rule("Z3#4-;*6"));rules.push(rule("Z?#5-;*6!F^4=<Fdr46gf"));rules.push(rule("R3\'5,7&=.Bfs<:"));rules.push(rule("^9!3%7$?"));rules.push(rule("U2$>(1\'5/3"));rules.push(rule("]5 :):<$?&Nh|;1}|5AU17"));rules.push(rule("[3#3-83,0(Aow>;pz6HQ36"));rules.push(rule("[>#5-8*6!F^4><EW0?=Nh|;1lc"));rules.push(rule("Y>\"6!4%4\'?&M[>3:F^4<"));
rules.push(rule("S4\'<,4&=#;\'EW0<=M[>0:F^4<"));rules.push(rule("[:#7-:*3,<"));rules.push(rule("X?\"<!5%7*CT98"));rules.push(rule("[3#3-?*6!F^4>"));rules.push(rule("[3#0-1*3!FJ4><EW0?=M[>1"));rules.push(rule("S;\'0,2&=.Bfs<:ii"));rules.push(rule("Y>\"=!3%4\'9"));rules.push(rule("V4%6$<(2$6"));rules.push(rule("R3\'6,7&=.AU17"));rules.push(rule("X0\";!2%1*CT98"));rules.push(rule("_6!3%7$?"));rules.push(rule("X0\";!6%6*CT98"));rules.push(rule("Q8&8 <)9"));rules.push(rule("T6$<(2\'5/3"));
rules.push(rule("Y<\"=!6%4*CT98?LS2>5Bfs<:ii"));rules.push(rule("X=\"=!6%6*CT98?LS2>5AU16"));rules.push(rule("R:\'0,5&=.AU17"));rules.push(rule("[<#>-;*3,:,@]=:>D_<12JP;;"));rules.push(rule("]5 9)?+9-Us`j]n}S|fbe"));rules.push(rule("[:#4-:*3!F^4="));rules.push(rule("U<$<(0\'0"));rules.push(rule("Y8\"<!5%7*CT9;"));rules.push(rule("Z2#2-8*0!F^4><EW0?=Nh|;1lc"));rules.push(rule("^9!5%7$9&M[>3:FJ4="));rules.push(rule("[<#2-8*3"));rules.push(rule("X=\"=!5%7\'>&M[>0:F^4<"));
rules.push(rule("Z2#3-?*0!F^4>"));rules.push(rule("Q8&=>!4%7"));rules.push(rule("Z2#2-87,0(B\\560KX74"));rules.push(rule("[2#4-:*4"));rules.push(rule("R:\'2,5&=.Bfs<:xv8GV833BH54"));rules.push(rule("^?!5%2$<"));rules.push(rule("S:\'5,0&=#="));rules.push(rule("Q9&: =):%Gl~:9qr:F^4=<EC0>"));rules.push(rule("[3#3-<*0!F^4><EW0?"));rules.push(rule("T=$<(0\'6"));rules.push(rule("Y0\"6!2%4"));rules.push(rule("[2#?-;*0"));rules.push(rule("U4$?(;\'6\"OZ6?"));rules.push(rule("Y>\"6!6%1*CT98?LS2>5AU16"));
rules.push(rule("T=$9(7\'6"));rules.push(rule("]4 6)8+>"));rules.push(rule("X1\"?!3%7"));rules.push(rule("X1\"6!4%1"));rules.push(rule("_8!5%1$>&MO>0"));rules.push(rule("_8!4%4$<"));rules.push(rule("W>%4$>(;"));rules.push(rule("Z=#4-:*0!FJ4><EjUIcn`[rn{6<"));rules.push(rule("_>!5%0$<&M[>0"));rules.push(rule("[3#0->*0!FJ4><EW0?=M[>1"));rules.push(rule("V?%=$?(1"));rules.push(rule("[3#3-8*0!F^4><EW0?"));rules.push(rule("W>%=$>(1"));rules.push(rule("W2%6$<(1)JP;97@]=9>D_<0"));
rules.push(rule("^6!2%1$>+7"));rules.push(rule("[<#5-;*1,<,@]=9"));rules.push(rule("]: <)8+8 2#GV80"));rules.push(rule("_8!?%2$<+7)JP;:7@]=8"));rules.push(rule("Z;#7-;*3,:"));rules.push(rule("_>!6%2$>&PYML:F_^ztcjy"));rules.push(rule("Y<\"<!6%6*CT9;"));rules.push(rule("[3#3-;*3,;,@]=9"));rules.push(rule("V7%4$:(7)WRHF"));rules.push(rule("R;\'5,3&>"));rules.push(rule("Z=#2-;*3!FcQKbflU}ip"));rules.push(rule("Y0\"?!2%4"));rules.push(rule("[2#4-:*6"));rules.push(rule("U<$<7-8*6,0"));
rules.push(rule("[#Ktbggg!FmzfhedfR4#jklo},?&"));rules.push(rule("Rflim!5,!y ,1- &.`r%&$9g| ,;*?2k$)/v,#( f7\'-.6%56((!<ehb4?-(:j*%&<4 ( +*jmfc\"dbaxn #3%\"-sx#wz)*/+6(u{=&9-c)6\'!hl%ogkejm4eiva*hlnogkejmf#!52-:<\'/ ,h;!47)6<!\'?d1\'\'c&<"));rules.push(rule("Tiec>Ovcoki.AflecgoV6\"bgb`z"));rules.push(rule("U-Lgmja\"Oixg`ijiU?&`fjlt(>\'"));
rules.push(rule("^jjjd%7-x(;0fi&\")=),\"*;8#\'#o0%,<1\'&l|#(6`w,!<2.qy,=-f!$$:\",/8)g)?+--3=)*,//ah#5+ejm--\'*,hzo);+8{t->&)db*:fg`5 ej-4=)l,//+.=3l.t-2=)6d::8%og"));rules.push(rule("[fbtf4Bp`fok/Ijqcbhbe[0!kc`ar"));rules.push(rule("[PKtbggg!FmzfhedfR4#jklo}Q"));rules.push(rule("[` kbq903="));rules.push(rule("Qlg~k2Ayddnc#GevhgbocX9%kaj"));rules.push(rule("T_Lgmja\"Oixg`ijiU?&jggmofyS"));rules.push(rule("Sh$icy5>??"));rules.push(rule("Wjdwo0@qhjad(Bo{ndkkaY1)enm"));
rules.push(rule("XSJ|nih`*Cgw`kl`dS</kbgxh["));rules.push(rule("Yb!cn67<="));rules.push(rule("_mntnccj+nh|?0;"));rules.push(rule("^hnj9(gdh>8"));rules.push(rule("_inj>(gdh>8"));rules.push(rule("Qgia9\"jbk7<"));rules.push(rule("Rdhi:,ee`26"));rules.push(rule("Tbxbjo$iko5="));rules.push(rule("Wonvxbjo$iko5="));rules.push(rule("Uvdlv.dml<9"));rules.push(rule("Vu{ld kjg93"));rules.push(rule("Wqyj~ kjg93"));rules.push(rule("Zxbjolv/lab3>"));rules.push(rule("_jbw|fdhf$icy5<"));
rules.push(rule("Sahwggak#}b{`ky;2"));rules.push(rule("Rqger,zi~jf8;"));rules.push(rule("Spyml,zi~jf8;"));rules.push(rule("Snfvg<N~oadn%DlrjfjcmW>.nkg"));rules.push(rule("R*Ovcoki.AflecgoV6\"`d`\'"));rules.push(rule("Yzj.2\'ja|lh`l`"));rules.push(rule("Vvdvfg;19"));rules.push(rule("Wwdvda;19"));rules.push(rule("Qgdco{neb\'}ijgp?1"));rules.push(rule("[livy)tsgx3Q>W+Q<2^U*3]&>"));rules.push(rule("Usxbr.geod5,|`sjqcbh#apuaoocb+hecrbgpg!li.>?;°"));
rules.push(rule("Sd{kwq%~acknw7S4_\'0^/S9#7ZW+"));rules.push(rule("Rpfhndz!`njn8~bhmlew!mb.ynydmh&gl$178°"));rules.push(rule("Rp|hg,[\\GA:yjfa<]RZq\\"));rules.push(rule("Vqc|\'^VJG9Dhoy|j\'json&u{mnmm,{anzpo`cm}"));rules.push(rule("_}zkn(Y}omVkw^zeka:yjfa<]RZq{U"));rules.push(rule("^yg~&Vzdh\\fq]sai`2Abbc#zawmm,az\'json&u{mnmm,{anzpo`cm}$qtz,bn\'}`xyo`hhg"));rules.push(rule("Qs}`k\"IXC7ioe>*]W\"4ZPcLP/"));
rules.push(rule("Sta}/O[J3fx%nh&géjhgokdé.ji+7o`c#éeéigo|,jnix%cc#{kv`|eaa\'hjg}ipél"));rules.push(rule("Tgecp.apuyx||:U<V#.X8);\\t=>&[%-Q<35Tx31!P \'\\:(2P/#4$&23R7S)+8*=]9X,<r"));rules.push(rule("Sq|hg,^=6?\'6%|htwxppr20="));rules.push(rule("Qv`u#Y635*0&Shw\"em,|`sjqcbh#zqrdzekzun%à*<>3°)wws(`k|\'}`xyo`hhgr"));rules.push(rule("Xzybj*Fdr46#4$tdzx{ux?6?"));rules.push(rule("Urbt+Nh|;1(1._fx%nh&qfpcuac`/t~uoof|vg!à(5>°/t~w*ncp)rgs|emnknv"));
rules.push(rule("Zibhu$rgs|y~~syv7S?_\',Y0%5Ss6;,V#.X82_(T\"&T6&=W$&>) 1:V5R!\'6%x6X3U*?{"));rules.push(rule("Qs}`k\"Jj}3=ss)9\"wm~zzwzqx~<?;"));rules.push(rule("Sta}/Lit7?r{%7-Vbz$fd(~a{flec&p|tgsai{}b+à%3=°&p|v\"mi,xjuliljf)imo|m`{b"));rules.push(rule("^m`i}(|htwmksuz3Q>W+\"V7.0Y~08%R!/>y;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Uwac.Dez88ha/:+sorgfuvs{62="));rules.push(rule("Z}e.Dez88ha/:+Uk~&gl$pn|mzfhe%yxvf{mgtzi.à/>;°%yxt#ee\"wm~zfdjio-bfzggolm`{b"));
rules.push(rule("^m`i}(dbvvzl?_1P >\\:7WQ(2U*Y4%4S2i0[3Q(X8669UP 2u0[3#.:u52(5j5Q>%4Q<4^4w9_8P 2}"));rules.push(rule("Wu~io HPYqqigyz/:ejzxuk3j&"));rules.push(rule("Xdw\"IXU~nl|p\"<(\\o|\'o`*~iq}mg!xc{|tén%k}tèp)hc!~~gckn"));rules.push(rule("Zibhu$Lmsyx||:U<V#Zg\"X,Z;4SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("_}zkn(Gl~4;4Jnz,3Ghyt~u95="));rules.push(rule("Sta}/Lit9=7Cjx-;#Yeq!li.}hd~dim)gmlxc}éj\'cjxd|lgpcmm,}zwnwchsql$à\"6:<°"));
rules.push(rule("Qbgbx\"R{1?|rqz9\\8T\"Rk,W+Q?1^U**Z9!6R.6!;6X:U*?13R>S)65"));rules.push(rule("Wu~io Kbq161]|::\'6Pz93r}vq;4;"));rules.push(rule("_xg~&Hku379Qr5=,3/Wjv*ic#{kv`|eaa\'hjg}ipél$qn}.;2°+hecrbgp\"r}|k}nnpxh&à#<02°"));rules.push(rule("Vedk| Bl=1suz3Q>W+Vi-_\'_68UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("[yxjf$Icy94>Kh?0*0Bl=1suz434"));rules.push(rule("Xdw\"Jj};56Gf07!5,^nt+ao-tl}evhgb.lhfue~éc#zkwr(8;°/cnvihhghjv!{y~jub`c#à)5:1°"));
rules.push(rule("Rafjt,zczPvwy0X:U*;]&$U>*>X#Q(+R5/9U%3a/71S?_\'=^/ W8\">Vy;=/_\',Y0%4S&:{C.?=]0X,08P \'\\:(?P/_\',Y0%4S&:ec.?=]0X,08P \'\\=(3Pz29-^/ W?\"?V,7c@\';?\\8T\"U>*3XV#]2$1_]&$U>*3X#0t\'8?\\8T\"?T69XV#7_\',Y0%4S&:x!;6X:U*?s3R>S)6"));rules.push(rule("Wu~io HlV@glaS~`t+8*iwVuvs{6~i5"));rules.push(rule("]zfv*EjUIcn`[rn{,3/Cnhc-bé`ealb`é,~`tbqck&jgpgslez"));rules.push(rule("Zdha.geod5jghry`y-elgwkeézéi}/ddhgh&ménevh~i}"));
rules.push(rule("Wfgiez+glbptdi}/:+KYK=U8<2:Emv85;Me=Nh|758Y~;20Hku7;9@m5="));rules.push(rule("Rcehmv5RU>2<=3P"));rules.push(rule("R0\'7,5&=#;"));rules.push(rule("W5%1$5(2$0"));rules.push(rule("U2$?(0\'7\"ON6<"));rules.push(rule("]< =)8+>-Kbq=2"));rules.push(rule("R5\'1,0&=#=\'EW0<=M[>0:F^4<"));rules.push(rule("Z=#>-85,0%>"));rules.push(rule("V1%=$4(0$0\"OZ6?4IY?86HQ37"));rules.push(rule("U4$>(7\'5"));rules.push(rule("U2$5(2?*3,<"));rules.push(rule("]? =)8+; 2"));
rules.push(rule("]5 9)8+9-Us`j]n}S|fbe"));rules.push(rule("[:#4-;*0,;,Cn25"));rules.push(rule("S4\'<,3&=#=\'EW0<=M[>0"));rules.push(rule("_6!>%6$?"));rules.push(rule("^<!5%1$<+7"));rules.push(rule("Z2#0-<*3!FJ4><EW0>&"));rules.push(rule("X0\":!62+8-HQ36"));rules.push(rule("_7!3%1$<&M[>0"));rules.push(rule("[3#3-8=,3(B\\550Hku?3|t"));rules.push(rule("V>%0$9(0$0"));rules.push(rule("X9\"<!6%6*@g{04"));rules.push(rule("U=$9(19*0"));rules.push(rule("V7%7$<(1)JP;:"));
rules.push(rule("W6%4$;(0)WrhfSazXyloc"));rules.push(rule("X0\":!68+;-HQ359OZ6<"));rules.push(rule("S;\'0,0&>.AU171@g{04fn"));rules.push(rule("Z2#3-=*3,:,@I=9"));rules.push(rule("^9!?%49#7.;"));rules.push(rule("[3#2-;*3!F^4="));rules.push(rule("[3#2-8*3!Emv67oj"));rules.push(rule("^7!>%7$9"));rules.push(rule("Y1\";!4%6\'9&M[>3"));rules.push(rule("X9\"<!5%4*CT9;"));rules.push(rule("V1%7$9(1)JD;97@`XO`gdYsfw83"));rules.push(rule("Z;#7-?*6![\\GA<EVZxukfqv"));rules.push(rule("R5\'<,5&=#;\'EW0<"));
rules.push(rule("Y1\"8!?%4*C@98?LS2>5AU16"));rules.push(rule("T1$?(2\'0\"Lit7?r{"));rules.push(rule("[2#71\'5,5%:"));rules.push(rule("Q9&9 9):%DK<2"));rules.push(rule("Z=#5-8*3,:"));rules.push(rule("S1\'7,4&=#;"));rules.push(rule("V4%1$:(2$0"));rules.push(rule("T=$<6-:*0"));rules.push(rule("^9!?%0$>+7)JP;97@]=9>D_<0"));rules.push(rule("R5\'6,0&?.AU141CT9;"));rules.push(rule("U2$5(5\'5/3(B\\54"));rules.push(rule("]: 7)<+9 2#GV803B\\54"));rules.push(rule("[3#3-8*0!FJ4="));
rules.push(rule("W0%7$?(7)JP;97@I=9"));rules.push(rule("Z3#>-;*3,:"));rules.push(rule("U2$5(2:*1,<,@]=8"));rules.push(rule("Z2#3-83,0(B\\550Hku?3|t"));rules.push(rule("[<#>-86,0%>"));rules.push(rule("[3#3-1*3,:,@I=:"));rules.push(rule("V1%=$<(2$6\"OZ6?4IY?86HQ37"));rules.push(rule("Z?#5-8*6!F^4><EW0?"));rules.push(rule("T=$9(1\'6"));rules.push(rule("S4\'<,4&=#=\'EW0>"));rules.push(rule("Q8&5 <)?"));rules.push(rule("^;!4%7$?+0)JP;:7@]=8"));rules.push(rule("^6!3%6$?&M[>0"));
rules.push(rule("_>!5%1$?&Nh|;1"));rules.push(rule("U=$;(4\'6\"ON6?4Jj}3=bl"));rules.push(rule("S;\'2,3&=.Bfs<:xv8GB82"));rules.push(rule("]: =)9+;-HE359OgSJjjbZzbu9;"));rules.push(rule("Z2#0-?*3!FJ4><EW0>"));rules.push(rule("V7%4$<(2$0"));rules.push(rule("[2#>-=*3,:"));rules.push(rule("Q6&4 <)8(>-HQ35"));rules.push(rule("]4 >):+; 4"));rules.push(rule("_=!5%0$<+7"));rules.push(rule("W0%=$<2-:)6!F^4="));rules.push(rule("Q8&> =)?"));rules.push(rule("]< =)?+;-HQ36"));
rules.push(rule("V1%=$<7-:)6!F^4><EW0>"));rules.push(rule("T<$8(5\'6/5(B\\56"));rules.push(rule("^9!?%7$>+7)JP;9"));rules.push(rule("T5$>(1\'5"));rules.push(rule("Z8#4-8*3,:"));rules.push(rule("_7!3%7$?&Nh|;1lc"));rules.push(rule("[:#7->*6![|gaXdpUofg"));rules.push(rule("[:#4-:*3!Emv67"));rules.push(rule("Y>\"6!6>+9 2#GV80"));rules.push(rule("V7%7$<(2)Icy1<"));rules.push(rule("W2%7$<(1)JP;:7Cn25}"));rules.push(rule("W0%=$:(2$6\"OZ6="));rules.push(rule("X?\"6!6;+; 4"));
rules.push(rule("]< >)<+9-US@J9O[\\{|odp~"));rules.push(rule("Y;\"?!6%4\'?"));rules.push(rule("U7$9(5\'5/5"));rules.push(rule("X?\"6!69+9 2#GV803B\\55"));rules.push(rule("S4\'<,0=\"?\"5"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("T<$9(2=*3!F^4>"));rules.push(rule("X9\"?!1%4"));rules.push(rule("]< >)9+9 2#GV80"));
rules.push(rule("_:!5%4$>&M[>0"));rules.push(rule("X=\"=!5%1*CT9;"));rules.push(rule("V1%6$<(0$0\"OZ6?4IY?8"));rules.push(rule("[<#>-?*1,<,@]=:>D_<0"));rules.push(rule("T6$9(6\'5/5"));rules.push(rule("R:\'2,7&>.AU141CT9;?LS2?"));rules.push(rule("V?%1$9(1"));rules.push(rule("U2$5(0\'5/3(B\\560KX75"));rules.push(rule("V1%7$9(2)JD;9"));rules.push(rule("Z;#4-?*0!F^4=<Fdr46"));rules.push(rule("_6!6%6$<+;"));rules.push(rule("R;\'5,4&=#="));rules.push(rule("Q3&> 9):(>"));
rules.push(rule("Z?#5-8*3!F^4><Fdr46vy"));rules.push(rule("[3#3-;*1,<"));rules.push(rule("Z=#3->*3,:,@]=:"));rules.push(rule("[9#2-8*3,:"));rules.push(rule("Q9&8 <):%Gl~:9`m"));rules.push(rule("X0\";!4%4\'?&MO>0"));rules.push(rule("[2#>-<*3"));rules.push(rule("V3%6$?(2)JP;:"));rules.push(rule("S:\'0,0&>"));rules.push(rule("Z=#4-8*3!FJ4>"));rules.push(rule("Z3#72\'5,5%4"));rules.push(rule("[<#2-8*0,<,@]=:"));rules.push(rule("Q0&> ;)?%Gl~:9"));rules.push(rule("^9!2%1$<+1)JP;97@]=9"));
rules.push(rule("S4\'0,3&=.AhTAo`o\\ykq"));rules.push(rule("^6!2%4$>+7)JP;9"));rules.push(rule("Q0&> :):%D_<1"));rules.push(rule("]5 :)9+;-HE36"));rules.push(rule("R3\'6,9&="));rules.push(rule("T3$9(2\'5"));rules.push(rule("_>!5%2$<"));rules.push(rule("^9!4%6$<+1"));rules.push(rule("[<#>-8*1,<,@]=:"));rules.push(rule("Q6&? ;):(>"));rules.push(rule("Q8&= ;):(8"));rules.push(rule("T3$5(29*1,<,@]=9>D_<0"));rules.push(rule("[9#7-:*3,<"));rules.push(rule("W>%=$<(2"));
rules.push(rule("Y1\"8!3%4*@g{04wq3B\\550KL75"));rules.push(rule("S;\'1,4&=.AA141CT9;"));rules.push(rule("S4\'6,2&>.AA141Ci\\MaohW|a|=9"));rules.push(rule("_7!2%2$<+1)JD;97@]=9"));rules.push(rule("[<#4-8*0!F^4>"));rules.push(rule("Y>\"6!?%4\'9&M[>1"));rules.push(rule("Y8\"?!4%4\'9"));rules.push(rule("R:\'2,2&=.Bfs<:xv8GV833B\\54"));rules.push(rule("T=$?(0\'0/9"));rules.push(rule("U2$5(:\'5/3"));rules.push(rule("U=$;(7\'7\"Rxe`Ph~Zxdcm"));rules.push(rule("Y8\"<!?%7*@g{04"));
rules.push(rule("[<#5-;*3,;"));rules.push(rule("T<$8(6\'6\"OZ6?4IY?8"));rules.push(rule("S4\'6,2&=.AA14"));rules.push(rule("X?\"<!3%6*C@9;"));rules.push(rule("V>%0$5(0"));rules.push(rule("W>%1$>(1$<"));rules.push(rule("_8!5%7$?&M[>3"));rules.push(rule("R7\'7,0&?.AU141CT9:?O`p5>zw"));rules.push(rule("W0%1$?(1"));rules.push(rule("[9#5-8*3,:"));rules.push(rule("]8 <):+8-HQ359OZ6<4IY?9"));rules.push(rule("Q6&? =)?%D_<1"));rules.push(rule("W6%7$:(1)Icy1<"));rules.push(rule("U2$>(0\'7/5(B\\56"));
rules.push(rule("^7!6%7$<+7"));rules.push(rule("]4 6)9+8"));rules.push(rule("[3#0-8*3!Emv67~u1C@9:"));rules.push(rule("Z2#3-8*3!F^4="));rules.push(rule("T<$8(4\'7"));rules.push(rule("S4\'6,0&8.AU141C@9;"));rules.push(rule("X=\"<!6%4"));rules.push(rule("S2\'5,6&>.Bfs<:"));rules.push(rule("[:#4-:*0!F^4="));rules.push(rule("W6%4$?(2$6"));rules.push(rule("^6!2%7$?&M[>0"));rules.push(rule("Q6&4 >3%4\'?"));rules.push(rule("T<$9(7\'6\"Lit7?cd"));rules.push(rule("R:\'1,4&?#;\'EW0<"));
rules.push(rule("[2#>-:*3,<"));rules.push(rule("]: :)9+; 4#GV803B\\54"));rules.push(rule("[:#7->*3"));rules.push(rule("V1%7$?(0)JP;97@I=9"));rules.push(rule("S2\'6,7&=.AU17"));rules.push(rule("X9\"<!2%7*CT9;?O`p5>"));rules.push(rule("U^Lgmja\"@lzoadna*nimgq/man|jZ"));rules.push(rule("Vkdwo0EJ_E\"@lzoadna*Ktfl$Iog{`"));rules.push(rule("YRJ|nih`*Lbuhjadl,gaddkdx+o`fpd(=S"));rules.push(rule("Tiec>JMT@(Mjyfefoi&Vgolnb?"));rules.push(rule("[PKtbggg!Ihxnih`n-omjklo}!bfey`*?["));
rules.push(rule("Wjdwo0EJ_E\"@lzoadna*Xhhgkuo:"));rules.push(rule("_TIujkih&Bmrcokij/nefechv$hkczi.<Z"));rules.push(rule("Zgbtf4GKWI,Okqjkihb#\\jiog{`<"));rules.push(rule("S+Ovcoki.Khy`~\"c{janmmbmj\'hjdcs#8-"));rules.push(rule("Znhkl)9\"db,!qy}\"-k($wZ<!hl%#2x\"-ddA!dbahln-{)6jm/-.#6/&\")$Y5%93&2%60laj\"=9+ejmf(:nmh;\'p/55%$*rb\'(0/&\" ! 5%j!2civr-= =;,u;*?8#idb*hl<;gom\"m/-\'*,-:8 ! ,.jS8#idbah\'?#5mejmt`j,05h%.6j9ll!0.id<"));rules.push(rule("[fbtf4Bp`fok/Cdwoy)fqggmdi`lb+fechv"));
rules.push(rule("[#Ktbggg!Lc|js$`rncoealbm,m`iep*?/"));rules.push(rule("Wcnhe-;#\"mdsx></ayah#!$%66/&\" (  ejmfcidb!hl<=j%c&<+}w$5?(rp\"*&ud%(-\'*,&:> !)%+$#!$ 5/,(80/*>ly#oqy*,&= 6\"\'8;* 4&))1k;!#\"*u;*58#i)05ld !)%78#(-\"/)v,<1\'u{!?ts!60(1,no,ke8?*1ova"));rules.push(rule("Tiec>Ovcoki.Khy`~\"c{janmmbmj\'hjdcs"));rules.push(rule("SXOvcoki.Khy`~\"c{janmmbmj\'hjdcs^"));rules.push(rule("[{buoc914"));rules.push(rule("]}a|ig898"));rules.push(rule("Wagjkyomn)rnabz27"));
rules.push(rule("Qj%aow:80:"));rules.push(rule("Vdjvokod$iko55"));rules.push(rule("Wejvokod$icy55"));rules.push(rule("Wfgiez;]R5/8U"));rules.push(rule("[PKtbggg!Lc|js$`rncoealbm,gaddkdx["));rules.push(rule("Ssfwnk5?;"));rules.push(rule("Tte~ho477"));rules.push(rule("]kb`fldj+sfmlu5<"));rules.push(rule("Wl&hku;0<4"));rules.push(rule("Zycgs$icy59"));rules.push(rule("[b~hby)ohf1<"));rules.push(rule("]b}af{(gdh>;"));rules.push(rule("Sd{kwq%z}af{8T4Z-!=~08%R!\\:3WQ("));
rules.push(rule("]{}af{(dlkf4`éammbmgé\'}`xyo`hh\"lgbzni"));rules.push(rule("Qw{bo*fld07"));rules.push(rule("Rtzjcq%aow:9"));rules.push(rule("Zibhu$mlum~jfs6[Q=?^U*?O"));rules.push(rule("_}zkn(Ccrf{`kum,3/neqobj}>L"));rules.push(rule("^yg~&Ldycqmmvd(1.Inlpxh&gl$``{i.fi`xiowl"));rules.push(rule("Yjc`y*cjx~rly9\\8T\"&>{2y;=/_\'_19U1?4Y2Y$?Z-:X,5(1.=<U<V#4_\'7^/>,3/40[3Q(1U*1]&4.2\'?>T4Z-=X,2T\"&T6&=W$&>) 3:V5R!?W+9Q(2)9\"33R7S)3Y$>Z-;$?!<7P6[%=V#5_\'7\"<(:5Q>W+2Q(0U*6!5,64Y2Y$0t8W4^/5v"));
rules.push(rule("Vt~io Nl{52r|c~/:+meuwft8=9="));rules.push(rule("Xdw\"Odw;=uwft\"<(y`/jj}c`sn)`g!9<.nuy`~~&fzp\"`}xa}nxé%nlhp)hgr(~a{flecu#maq!deiabx%nij}aq!`c|f}dk~ljfz"));rules.push(rule("Wpc|Uhh.Akp08z`w+8*l&nh|kl}a.`a+4:-uwftq!i~k/fgiezcg)kl!{x|nnlm~-nl{mxnfxoc\'gldhu#{knm{"));rules.push(rule("^m`i}(xbjoVV6<V5R!3W+;Q(14E9_1P >[%4V#]2$0_<I7P6[%-Q<471Y+]&1*><U<V#.:u52(T\"&T1&<Wq73 9D:V5R!/2y;=/>o?\\8T\"?T69X7~=]9X,<r"));rules.push(rule("Wu~io T7)9\"sg`bPU??T~&+RZC{UpRx\\\'>W$"));
rules.push(rule("Rua}/S<,3/wjv*ic#mégndfofé/h~%zlu#javum,|`sjqcbh#melr(`o/eyddnnf)imo|m`{b+d|he#|jg!~~gckn%nlhp)hc!j~oadc`*icpjaleibzj)"));rules.push(rule("Wddk| tleh]S>1P6[%4:Q(;U*0<P7P6[%-Q<471Y+]&1*><U<V#.:u52(T\"&T1&<Wq73 9D:V5R!/2y;=/>o?\\8T\"?T69X7~=]9X,<r"));rules.push(rule("_}zkn(X;&>)vmmdS\\9=S"));rules.push(rule("Vqc|\'_0#4$ad(hémcbefbé-cp}$ko|i|kn+*^gvo$qtz,bjt+ccjsqlw\"6&> =):)*:(1\'0,3$,6!2%6$>*#1*7/<\":#\'3+<#4-=$gu(4 9)?+9#"));
rules.push(rule("Vt~io PGFSL00<.2\'oj}cww{w8=;"));rules.push(rule("Xdw\"QOJ]C7;9$?!}b.bfslgxk#ma\"00<°.kb+weygw`kl!mz/wnwgdu-"));rules.push(rule("Xzybj*]AEZH1>4\"<(haxizqx~<?="));rules.push(rule("Z}e._@MVF>9?\'6%c&nh|kl}a.kb+7==°&gl$pn|mzfhe%o~r#yapla "));rules.push(rule("Y{ybj*]AEZH2Z$?!lcyatjz7:1"));rules.push(rule("Vqc|\'[BL^J3R(1.fx%nh&ehggu|i.byhc~c-"));rules.push(rule("Qs}`k\"U:5*0&qfhn;V$&SpP)1P]eOY+}SjHR{#^lK[X%?_]%\'/\\:7>5["));
rules.push(rule("_xg~&W;=&>)tcr(hk/udqkyolg$f`f.cf+gxlh`aa\"emmjioddyc#hrgb(y`/céhioceké)`co{,bn\'iwkcekl$onfxoasn+"));rules.push(rule("Zibhu$vmmdS\\>66[3Q(2U*3]&W?=Z6D1S?_\',Y0:86R.W+7)78W=^/ 5r>7\"Y$%]5$=_}9<\'2A0[3Q(+0x31!1h4Y2Y$<]2;Y?r3R>S)61"));rules.push(rule("_}zkn(X<7#4$pnd`Q]6:?\"S.+UsY-3QUN6912k@^ xY0:86iAVy\"VG2;0:gNQU#<VY}$/#R5050Q\'s/U^TwG^\"$Y0:86R.w-TVXyT/\"ZnJS&"));rules.push(rule("_xg~&W;<&>)ggu|i.lhfgccgjzkl!li.}hd~dim)imo|m`{b+`~-uldikui`k/bxq*dhwlvfh|i "));
rules.push(rule("Yjc`y*yjfaYQ80?_1P >[%0V#]2;7_<I7P6[%-Q<471Y+]&1*><U<V#.:u52(T\"&T1&<Wq73 9D:V5R!/2y;=/>o?\\8T\"?T69X7~=]9X,<r"));rules.push(rule("[yxjf$V35(1.}hgiU_773ZY] 5R,+-QS|^u,^vS 5R[|,#-.XWEx\\t$Rx\\\'>W$/"));rules.push(rule("Xdw\"U:1*0&`lpvd(~a{flec&glwadfhoasn%o~r#`jvdzhg{b+`d-vqlwgoki.k ~ko-tl}evhgb.nr+ve`kf}*"));rules.push(rule("Tgecp.{knmW^?::U<V#7_\'1^/S=#=Z6D1S?_\',Y0:86R.W+7U=]0X,)1p??.W+\"V0.0Y~08%3I<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q"));
rules.push(rule("Qs}`k\"U:0*0&qfhn;{W\"4ZPcLU["));rules.push(rule("[|e.[57!5,~nt+ao-bé`ealb`é,az\'h`~yc#{kv`|eaa\'juxè~&vga\"wzebcb%"));rules.push(rule("^m`i}(nbtf}[fn{1P6[%4V#7_\'_7,0Q3y<U<V#2_\'5^/S8#7Z6s1S?_\'<^/9P T5&=W0p8W=^/S=<R[%0V#]7$<_<f7P6[%^>5[_\'1^/S?#7Z6k1S?_\',;}9<\'S)#0v<6*U*?o3R7S)#^;?2;T-^/5~5Q>W+\"4z29-?g3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Qs}`k\"IdZnhvb{p]eg.2\'ojxhr\\mkq;Vz"));
rules.push(rule("Xdw\"IdZnhvb{p]eg.2\'{dy-bf)`ér`zx.khx%k{c`)ggu|i.}hd~dim)rgs|emnkn+"));rules.push(rule("Sq|hg,FcQ|hyqchYgfw\"<(ha}bZnbu9g "));rules.push(rule("Y~dw\"IdZybtw`a]eg.2\'{dy-bf)wms|ek/cdv*lpfj$ad|xk/udqkyolg$tdzxglfg`$"));rules.push(rule("Rafjt,k`gbezqx~;]0X,)S=#6Zw4:$Z-R507?QR!/P4\'5[*)9\"%:7P6[%%7-t8W4^/5v"));
rules.push(rule("[hbhu$gnhen}{h{8T4Z-!5~8t=>&[%^;?04T93:V5R!5W+Q<4^U*6!5,<4Y2Y$?Z-R50\\T\"8/:+61S?_\'6^/S=<R[%=*0&72Z;]&8R!\\:7WQ(+R5/9U%.2\'/41S?_\'<^/S=<R[%4*0&12Z;]&4R!\\:7WQ(1)9\"53R7S)3Y$V71TX,2(1.9<U<V#>_\'_33UP ;\'6%26X:U*?s3R>S)6"));rules.push(rule("_l`i}(}ww{w?_1P \'\\:(3Pz29-^/S=8R[%-Q<+;T-\"<((<4Y2Y$-;#{?\\1T\"3u"));
rules.push(rule("_l`i}(}uwft?_1P \'6w<v<6*U*Y0>Q3><U<V#4_\'5^/<,3/50[3Q(1U*3]&:.2\'8>T4Z-;X,0T\"6/:+11S?_\'0^/9P \'\\:(2P/#4$&03R7S)3Y$<Z-8$?!:7P6[%=V#7_\'6\"<(85Q>W+2Q(2U*1!5,84Y2Y$5Z-8X,5(1.7<U<V#;q2Z2]&1t"));rules.push(rule("Wddk| bjhcwqyx||:U<V#.X8);\\t=>&[%^8:[_\',Y0%4S&\'6%.?=]0X,!5,|4Y;Y$0|"));
rules.push(rule("Qbgbx\"cbdmxvp}kr<V5R!6W+8078W=^/ 5r>7\"Y$V44T90:V5R!5W+8Q(7)9\"33R7S)9Y$?Z-?$?!;7P6[%7V#4_\'<\"<(85Q>W+>Q(1U**Z9!6R.+8*)78W=^/0P =[%4*0&12Z;]&4R!5W+8-;#=?\\8T\"6S)9Y$>&>)29_1P 7[%7V#2#4$::V5R!:y>T=Z-4~"));rules.push(rule("Zibhu$`mvf}z}t6[3Q(+R5/8Up??.W+\"8z29-^/ W?\"?V,*0&\':?\\8T\".2\'y>T=Z-4~"));
rules.push(rule("_l`i}(nbqmzpmq5R7S)#4v4z29-^/ 9r>7\"8;6X:U*0]&9R!3+8*?=]0X,3T\";S)=%7-58W=^/:P :[%=*0&72Z;]&8R!2W+\"V7.1Y+!5,*><U<V#>_\'1^/9,3/50[3Q(;U*7]&>.2\'8>T4Z-1X,4T\"=/:+31S?_\'<^/=P ;\'6%26X:U**8t=>&[%%7-`8W=^/5~5Q7W+7w"));rules.push(rule("Tvac._QR5=<.2\'~u{ytp384"));rules.push(rule("_xg~&S_]269$?!}b.bfslgxk#ma\"5=<°.jt%zhtn`w\"r}~.cbx%xbrb}mmo{,ocsnwdéhu#apuaoocbx%gbhwhjvd{"));rules.push(rule("^yg~T`d PVY071(1.n\'fdrdkvd$mg(8;?°\'jwo-goekudl,aa\'}`xyo`hh\"tx,awdvcyc#{knm{"));
rules.push(rule("_}zkn(NDGD\\T758,3/cbdmxvr}vq;4;"));rules.push(rule("Rua}/EAMIZW>1:-;#|j\"litgbrf%nh&6=4°\"d{x.byhc~&p|v\"mm.}hd~dimz$cm|i|aébx%à*93°#dkluibz"));rules.push(rule("Vqc|Uhh.MMCF]\\;;7+8*l&nh|kl}a.`a+0>=°&b{a\"`d`axbo%ec&g`eenfmb/r{%e}vlzmvd(~ackx"));rules.push(rule("[yxjf$RWQ<_.2\'~uyyis387"));rules.push(rule("Z}e._QR5[,3/re%gl~jdqo!li.;\'jwxhrp)aqu(|k}jbv*~sq)hgr(~a{flecu#hhvdzbék|\'}`xyo`hhgr(aaasjk~hu"));
rules.push(rule("XdwPbe(\\XV7Z$?!i,cnbh`&lo$6!{xat+dxh&behmvmh.`i+sorjjen!}|.`w{jydrf)vmmd"));rules.push(rule("Wu~io BJHCWQ<_.2\'olkjsszpmq20;"));rules.push(rule("Qv`u#KNJB_]2P)9\"tf,cnbh`&gl$6!i~|jsx%\">&p`$fébdi`loé\"%o~r#yapla.|ry%fhu#{kv`|eaat+fe`djgéaq!à(8;°/jdk~lhw"));rules.push(rule("[|e\\lj/EAMIZW?V*0&b)icyaa{b\'dc*9&p}krr($=/nm%ycgs $csm,ockdroi&lg$fhikaafg%}&lytmraxk/udif~"));rules.push(rule("[yxjf$GNHEN::7+8*njjdfsuz4$;="));
rules.push(rule("Xdw\"DGLGO269$?!}b.bfslgxk#ma\"5=<°.jt%zhtn`w\"r}~.c nkyhkaea\"em.}hd~dimz$onfxoasnv"));rules.push(rule("Vqc|Uhh.JHKLJ8;?\'6%k-kbqmote,ai\'?0:°-gql$cmdcyjc+jd-eo`i`hfk.}hgiy"));rules.push(rule("_}zkn(IAONK0Q!5,mcnfgyyis3/>4"));rules.push(rule("^yg~&FFDKA=W\"<(y`/jj}c`sn)`g!<,o}unqy-cp}$rdzag|\'xpx-j$ljqdenbj\'o`y-tl}evhgb}/jdk~lhwlw"));rules.push(rule("[|e\\lj/BDECM3X%7-g#dezheyc/hm%>-uwftq!i~k/fgiezcg)kl!k`gbebkm-tlehq"));
rules.push(rule("Sq|hg,^HAXI83:-;#mkuoyx||=70"));rules.push(rule("_xg~&SNBQM:22!5,{a\'fdrdkvd$fd(?8?°\'nv~-vf{ikr({}\'g`y-tl}evhgb}/fgqohéfz$tdzxglfg`y-bfzggolm`{bx"));rules.push(rule("]zfvXnk\'[BL^J178,3/f+hkuon|i\"nn,=97°+dxh&behmvmh.`i+sorjjen!lcya\'duzbuj}a\"sg`b|"));rules.push(rule("Vt~io PGFSL2[,3/cdrd~rly>>5"));rules.push(rule("Vqc|\'[BL^J1R(1.zi+hkuon|i\"em,=/fywoyu#lwv!xi|bnx%yxt#eaq!zcznsbjd~&bepgsféi}/qnw~debeaq!li}lbeakcrfz"));
rules.push(rule("Sta}]df!XKH\\K9^&>)e\"litgbrf%ek&0)wvnx.nun%kajl~af!gb.ybyqcngo)`mvf,awdvcyc#{knm{"));rules.push(rule("[hbhu$rfE`j}u:U<V#]2;0:\\T\"U>2V8|6X:U*Y0:86R[%77i=]0X,Z9>:7ZW+>0B8W=^/S=<;?VY$0n8W=^/ 5r>7\"Y$V7.<Y?g3R7S)#<v<6*U*?G3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Y{ybj*^kfdkj}afOGY.2qoAbkuy3$FZ$7Ss\\\'>WIzuR(9\\SjHR{PClP]/2Yt}SJhR\\\'>Wi"));rules.push(rule("Vqc|\'Xho`ikumh@@R+8*iwhpknf.lhfgccécp)mlum~jfsnv"));
rules.push(rule("Rua}]df![akbhcycgGKW!5,awdvcyc#fv\"tf`galna*ioe+pnd`.\'hy%lao`b-\"bgalfijqcbh#`w\"ogx.nkgj}hb"));rules.push(rule("Y{ybj*^kfdkj}afOGYH/:}aNe`ps>\"eS 5RA"));rules.push(rule("Z}e.\\jnheezjcEJ_K&>)wmt{,::°\'fjdygm}$pn|mzfhe%ibka`jég!|c`abjp%iéeoljaié(.i}hx%A/&jgpgslezj"));rules.push(rule("Z}e\\lj/Tf`gbn`nCIVO$?!<9#zw+weaj,ohkbc,&-ojwn-qbp&+!kccmned~dim)mq!fcz/fgiezcg"));rules.push(rule("Qs}`k\"IM6^BVK)9pnd`4//%^&6[-u669!,UiAV!"));
rules.push(rule("_xg~&KL>RLYL\"<(|o|\'o`*iéeoljaié({}\'gd*{cq}ma`di.kbxfocbbgpg!i||é|\'o`y-`bjavum.kfev*ag#kkwbdi"));rules.push(rule("Qv`uQji&KL>RLYL\"<(ba/aglif&qfhn!gb.ybyqcngo)`mvf,bfin%kkrf{$jd{eznsbjd-om)pjd(`a`w"));rules.push(rule("_}zkn(DK4VY741(1.zwzqx~<#W,Y4%4Ss\\\'>W9z7R(9\\t>U#<V6v>]/2YY3;Q\'/a"));rules.push(rule("Wpc|\'C@1\\T178,3/wjv*ic#mégndfofé/be%blsw)`g!jc{lkn%yd&seqq!li.<1;°%nh&qfpcuac`/qnw~debea\"lgbzni`"));
rules.push(rule("Sta}]df!@I5^U9;6#4$ln(jbfd`%xbjo)kl!dca\'jz-ge}ap!ec|j\'mkc&0?4°\"sg`b/`dldj&vy"));rules.push(rule("Tvac.GB0TX>][H[%7-sszpmq2,P\'\\8(3PzX%?_3t>U#<V,*k"));rules.push(rule("Wpc|\'C@1\\T0R\\C^/:+uk~&gl$fébdi`loé+`d-nb|p\"em,l`rhio-uj)tnt{,jj\'9%ktf}w\"df,xjuliljf)imo|m`{b"));rules.push(rule("Vqc|Uhh.GB0TX>][H[%7-hl)bnhkg.}hgi*bh#ekmq(xa\'jc~ht#dkpd(xfni+7*~rlyw\"fge`h\'~u"));rules.push(rule("Xzybj*E=2-;#{knm2,6"));rules.push(rule("Urbt+M1<\"<(4.ifh`~ycp)mlum~jfs"));
rules.push(rule("Rua}]df!@7?+8*5&sfmlu(~ack+ly-hl}$cmdcyjc"));rules.push(rule("Xzybj*EJXK&>)vmmd6.T6912P]/2Yd"));rules.push(rule("Rua}/OG^H/:+fe`djgekrgb.{hekols/mégndfofé/neqobj}a"));rules.push(rule("^yg~T`d HL[B\"<(~ack\'cfdeh)gmlje`nsbjd-hl}$cmdcyjc"));rules.push(rule("_nckdr7S]2$=_"));rules.push(rule("W>%4:#73\'6/5"));rules.push(rule("Z;#7-;*3"));rules.push(rule("]5 9):+8-HL\\>0:FJ4<<EC8XV0?49ON>[_5XQE]=Q859OgSjjwjw~Rblz"));rules.push(rule("S4\'0,0&?#;\'EW0<=MFQ803BH560K25"));
rules.push(rule("_7!2%6$?&MO>0:FC\\I"));rules.push(rule("T5$?(5\'6\"OgSjjwjw~Rblz"));rules.push(rule("V3%6$<(2$0\"ON6?4IM?86EO@I@5[7MCNFG>86"));rules.push(rule("W0%1$9(2)Jm^{c|{nnZnbu"));rules.push(rule("_6!>%4:#4.="));rules.push(rule("U4$?(;\'0\"OG^H550KL6PGFSL00<5YCDRD<U"));rules.push(rule("U=$8(4\'7"));rules.push(rule("X1\"<!4%1"));rules.push(rule("R;\'=,5&:"));rules.push(rule("S2\'5,6&?.AA0SNBQM8<2:^HAXI:V1Ci\\zkpuaiQkhx"));rules.push(rule("U4$<(4\'0\"ON7XKH\\K8:68_@MVF=]"));
rules.push(rule("^?!5%=$?&Mf[fdxm|{Xojy"));rules.push(rule("[:#4-1*1!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("[3#3-;*0!FJ4=<EJXK"));rules.push(rule("[2#7-8*3,="));rules.push(rule("[9#7-;*3,<"));rules.push(rule("T3$5(4\'7/5"));rules.push(rule("_6!>%1$?"));rules.push(rule("R5\'0,5&?#;\'EC0<"));rules.push(rule("Z;#4-;*0!FC\\I=:"));rules.push(rule("_8!5%6$<+1)JD;9"));rules.push(rule("V7%7$?(0$0"));rules.push(rule("_7!3%4>#7"));rules.push(rule("]: <)9+8-HL[B"));rules.push(rule("^<!4%7$<+7"));
rules.push(rule("S:\'52/;\"<"));rules.push(rule("U3$?(1\'0\"ON6?4IdZnhvb{p]eg"));rules.push(rule("R;\'<,2&8"));rules.push(rule("_6!6%1$;"));rules.push(rule("U2$5(1\'7\"OG^H55"));rules.push(rule("S:\'0,3&>"));rules.push(rule("X:\":!3%4\'9"));rules.push(rule("R:\'2,3&>.AH^?86HE379ON>[_4=51C@1\\T0R\\C^4IdZnhvb{p]eg"));rules.push(rule("Q3&? <):(>"));rules.push(rule("W?%3$5(0$0"));rules.push(rule("S:\'5,4&=#;"));rules.push(rule("^6!3%7$?&Mf[fdxm|{Xojy"));rules.push(rule("^?!6%7$>+7"));
rules.push(rule("[9#2-1*3,<"));rules.push(rule("^9!3%3$<"));rules.push(rule("U<$4(6\'6/5"));rules.push(rule("R:\'0,5&=.AhTverjl[fn{"));rules.push(rule("^<!6%6$<+7"));rules.push(rule("W>%1$>(1$0"));rules.push(rule("Z8#2-?*3,<"));rules.push(rule("]4 >)?+8"));rules.push(rule("S:\'<,5&>"));rules.push(rule("W6%7$8(7)JD:^HAXI92:6PGFSL0["));rules.push(rule("^7!6%1$9"));rules.push(rule("V4%1$:(2$0"));rules.push(rule("[:#7->*3"));rules.push(rule("[3#2-8<,0"));
rules.push(rule("W2%6$?(2$0\"ON6?4IM?86EO@I@5[7MCNFG>86"));rules.push(rule("[3#2-8*3"));rules.push(rule("R5\'0,4&=.AA14"));rules.push(rule("T3$>(7\'7/5"));rules.push(rule("W?%=$8(2)JMT"));rules.push(rule("^6!3%49#7"));rules.push(rule("R:\'2,3&=.AH^?86HE379ON>[_4=51C@1\\T0R\\C^"));rules.push(rule("]4 6)8+>"));rules.push(rule("R5\'<,9&=.AA16"));rules.push(rule("[2#?-:*0"));rules.push(rule("V>%0$:(2$6\"ON6?"));rules.push(rule("S4\'7,2&=.AHYC0?"));rules.push(rule("Z3#72\'5,5%:"));
rules.push(rule("T=$9(1\'0"));rules.push(rule("Q9&: 8):%DBS9;?LG2=5AA8QE]N8Gk]rg~zfbTae~"));rules.push(rule("S4\'<,4&=.AA161CIQO>0"));rules.push(rule("[3#2-81,3(^??<EJXK"));rules.push(rule("Q8&4 <)9"));rules.push(rule("V1%=$;(1)JD;;7@@UM?;"));rules.push(rule("]? =)8+; 2"));rules.push(rule("Z2#2-8*1,<,\\;"));rules.push(rule("^7!?%7$?"));rules.push(rule("Y1\";!4%4*C@9;"));rules.push(rule("X0\"8!6%6\'9"));rules.push(rule("_>!6%3$9&MO?TEG[@>?;>\\IITG5Q:FcQ|hyqchYgfw"));
rules.push(rule("[3#0-=*1,<"));rules.push(rule("U=$8(5\'5/3(BH56"));rules.push(rule("[3#2-8*0!FcQkb{dxyYgfw9OgS}`uloRblz"));rules.push(rule("Q8&=>!5%7"));rules.push(rule("R3\'5,2&?#;"));rules.push(rule("^?!5%0$?&Mf[fdxm|{Xojy"));rules.push(rule("^?!5%0$<"));rules.push(rule("Z=#2-;*3!FC[56"));rules.push(rule("_6!6;+2#4"));rules.push(rule("V1%6$9(1)JMSN"));rules.push(rule("X9\"?!1%4"));rules.push(rule("^9!?%7$<+1)JD;9"));rules.push(rule("R3\'6,6&?.AHYC0?=MO?TEG[@>?;>\\IITG5Q"));
rules.push(rule("[3#3-=*3!FJ4="));rules.push(rule("X?\":!6%4*CIV35"));rules.push(rule("]5 :)<+>-HL[B83"));rules.push(rule("X0\";!2%6*CIQO>0"));rules.push(rule("T6$>(7\'5/5"));rules.push(rule("U2$5(5\'5\"ON6=4IDWL74"));rules.push(rule("T5$?(5\'5"));rules.push(rule("W0%=$9(0)JMSN"));rules.push(rule("Z;#4-:*1,<"));rules.push(rule("Q7&> >)?%DK<22Jm^li~nuZnbu"));rules.push(rule("Z2#3-?*1!FC\\I=9"));rules.push(rule("]4 >)9+; 0"));rules.push(rule("U0$?(2\'0\"OgSjjwjw~Rblz"));
rules.push(rule("Z2#0-<*0!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));rules.push(rule("]5 ;)?+9 2#[0"));rules.push(rule("V1%=$?(7)JMSN6="));rules.push(rule("S4\'<,5&8"));rules.push(rule("_9!5%4$>&MO>3:FcQ|hyqchYgfw"));rules.push(rule("T3$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("]5 9):+;-HL\\>0:FJ4<<EC8XV0?49ON>[_5XQE]=Q85"));rules.push(rule("_8!4%1$<"));rules.push(rule("Z3#2-<*0,;"));rules.push(rule("_7!3%6$?&Mf[fdxm|{Xojy6HlVwms|ekPcdv"));
rules.push(rule("^8!5%4$<&MO>3"));rules.push(rule("R4\'6,3&>.AA141Ci\\mar`zxQkhx>DbYpfvvhmSj`t"));rules.push(rule("T2$?(1\'7\"ON6?4IdZybtw`a]eg"));rules.push(rule("S4\'6,0&?#;\'EC0?"));rules.push(rule("V1%=$:(1)JD;;7@@UM"));rules.push(rule("^?!5%1$>+7"));rules.push(rule("V>%3$:(0$0"));rules.push(rule("X9\"<!1%6*C@8_@MVF>9?<]AEZH2Z"));rules.push(rule("S4\'<,0&?.AHYC0?"));rules.push(rule("Q6&4 ;):(8-HE35"));rules.push(rule("R:\'0,0?\"=\"3+KE_@"));rules.push(rule("U<$?(2\'0"));
rules.push(rule("[3#2-:*1,<,\\;"));rules.push(rule("R0\'6,4&=#;"));rules.push(rule("_7!1%6$?&MFQ833BH540KL?SS:22:FJ<ZW9V^BV8[53:FcQkb{dxyYgfw"));rules.push(rule("R3\'6,0&?#;"));rules.push(rule("Z=#5-8*3!FC\\I=9"));rules.push(rule("T<$8(5\'0"));rules.push(rule("T<$8(6\'5/3(BH56"));rules.push(rule("V?%7$?(7"));rules.push(rule("[<#2-<*6!F^4><EW0?=MO>0"));rules.push(rule("Z3#4-:*:"));rules.push(rule("T<$;(6\'7/5(BH55"));rules.push(rule("V?%=$8(2$6"));rules.push(rule("U<$4(5\'0"));
rules.push(rule("T=$<6-:*6"));rules.push(rule("W>%4:#2-="));rules.push(rule("V?%1$9(1"));rules.push(rule("]: ;):+8-HE359OGY4>"));rules.push(rule("Z2#0-;*1,<"));rules.push(rule("Z3#?-;*0"));rules.push(rule("U2$9(0\'5"));eval(rule("^|zknvFbal\'bp`fok2 glhc\\knuakk(<"));rules.push(rule("T<$;(;\'5\"OGY4=<EC0<=MO7VNXD"));rules.push(rule("^9!3%7$?&MO>3:FC[56"));rules.push(rule("Y0\"<!4%3"));rules.push(rule("V>%=$?(2)JMT"));rules.push(rule("[2#4-<*6"));rules.push(rule("W0%6$?(2"));
rules.push(rule("R:\'1,5&>.AA171CIQO"));rules.push(rule("Z2#3-8*1,<"));rules.push(rule("_=!5%1$<+7"));rules.push(rule("]< =)8+8-HL[B803BaPtdw~dc\\mkq"));rules.push(rule("Y8\"<!3%4*Ci\\zkpuaiQkhx"));rules.push(rule("Q9&8 <):"));rules.push(rule("[<#5-;*1,<"));rules.push(rule("Z2#2-81,2%8.AHYC"));rules.push(rule("X9\"?!1%7*Ci\\mar`zxQkhx"));rules.push(rule("W>%1$9(7"));rules.push(rule("[3#2-;*1,<,\\;"));rules.push(rule("^9!3%6$>+7)JD;9"));rules.push(rule("Z2#3-8*0!FJ4=<EJXK"));
rules.push(rule("[:#7->*0!FcQkb{dxyYgfw"));rules.push(rule("]: 7):+; 4#GB80"));rules.push(rule("T<$5(2\'5\"OGY"));rules.push(rule("V1%7$9(0$0\"ON6<"));rules.push(rule("^?!6%4;#7#GKPG"));rules.push(rule("T<$;(;\'6\"OGY4=<EC0<=MO7VNXD5AhTverjl[fn{"));rules.push(rule("T3$5(2\'0\"OG^H54"));rules.push(rule("[2#?-8*0,<"));rules.push(rule("^7!>%6$;"));rules.push(rule("[2#?-;*6"));rules.push(rule("U2$?(0\'7/5(BH55"));rules.push(rule("[3#0-<*3!FC[550KL778GB1UG\\F4U:1"));rules.push(rule("^?!5%=$<"));
rules.push(rule("[3#0-?*3!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));rules.push(rule("X?\":!3%7*Ci\\mar`zxQkhx"));rules.push(rule("V7%7$>(2"));rules.push(rule("T<$8(2\'5\"ON6<"));rules.push(rule("U2$5(;\'7/5"));rules.push(rule("]; =):+8-HE359OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("W5%7$;(2$0"));rules.push(rule("[2#71\'5,5%:"));rules.push(rule("_8!?%2$<&MO>1"));rules.push(rule("_7!2%=$9&MFVD;:"));rules.push(rule("Z3#73\'1,3%8"));rules.push(rule("T5$<(0\'6\"OG^H"));
rules.push(rule("U7$9(6\'5/5"));rules.push(rule("R7\'6,0&>.AhTao}gq}[fn{7@`XxjxyofV`mr"));rules.push(rule("W?%0$5(2$6\"ON6?"));rules.push(rule("]5 :)?+9 2"));rules.push(rule("S2\'6,5&>.AHYC0<"));rules.push(rule("T3$5(6\'6\"ON6=4IDWL77"));rules.push(rule("R:\'1,4&8"));rules.push(rule("U<$<6-:*4"));rules.push(rule("[:#7-84,0(BA]A"));rules.push(rule("X?\"6!?%7*C@9:?LNZJ"));rules.push(rule("S;\'0,5&>.AhTao}gq}[fn{"));rules.push(rule("_7!1%3$?&MFQ833BH560KL>RLYL9S98"));
rules.push(rule("Q0&> =):%DbYpfvvhmSj`t"));rules.push(rule("Y;\"=!2%4\'9"));rules.push(rule("V>%1$<>-;$P087@@UM"));rules.push(rule("]5 ;):3$?+7)JMSN"));rules.push(rule("]< =):+;"));rules.push(rule("^7!6%6$<+;"));rules.push(rule("S:\'0,0&>#;"));rules.push(rule("Q8&5 ;)?"));rules.push(rule("_=!5%7$<+7"));rules.push(rule("_8!?%6$<+1)JD;9"));rules.push(rule("[2#4-=*6"));rules.push(rule("V?%4:#2-;"));rules.push(rule("Q6&> ;):(8-HE35"));rules.push(rule("T3$?(1\'7/5(BH55"));
rules.push(rule("[3#3-;*1,<"));rules.push(rule("S5\'6,3&=.AA14"));rules.push(rule("X0\"6!1%4*CIV"));rules.push(rule("U=$9(21*1,<,@@UM"));rules.push(rule("]: =):+; 4#GB80"));rules.push(rule("W0%6$<(0$0"));rules.push(rule("Y1\"8!4%6\'9"));rules.push(rule("V>%0$?(2)JD;:"));rules.push(rule("U=$9(2<*3!Z=>"));rules.push(rule("Q0&= =)9%DBTE"));rules.push(rule("[:#4->*6!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("U=$;(5\'7/5(BH55"));rules.push(rule("Y8\"<!0%4"));rules.push(rule("[3#3-:*1,<"));
rules.push(rule("T<$;(7\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:FcQkb{dxyYgfw"));rules.push(rule("Q0&> 9)?%DBTE369ON7XKH\\K;568_@MVF=]"));rules.push(rule("T3$>(0\'6\"OG^H56"));rules.push(rule("U4$?(2\'6\"OG^H560KeRul{pkdWha|"));rules.push(rule("Q6&4 <)?"));rules.push(rule("W?%0$5(0"));rules.push(rule("R;\'52/:\":"));rules.push(rule("^7!6;+<#4.="));rules.push(rule("S1\'0,2&=#;"));rules.push(rule("Y1\":!6=+;-T29"));rules.push(rule("]5 ;)9+;-HlVwms|ekPcdv"));
rules.push(rule("T<$;(7\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR"));rules.push(rule("[3#2-83,0(^??"));rules.push(rule("Y8\"<!0%7*Ci\\mar`zxQkhx"));rules.push(rule("[<#5-8*0!FC\\I=:"));rules.push(rule("R5\'<,4&?#;"));rules.push(rule("U2$5(0\'7\"OG^H"));rules.push(rule("T1$?(2\'7\"OgS}`uloRblz"));rules.push(rule("_8!4%6$>+7"));rules.push(rule("_7!1%6$<&MFQ833BH540KL?SS:22:FJ<ZW9V^BV8[53"));rules.push(rule("S6\'6,0&="));rules.push(rule("]< >)8+;"));rules.push(rule("_>!6%3$>&MO?TEG[@=0;>\\IITG5Q"));
rules.push(rule("S;\'0,0?\"</U:51CIQO"));rules.push(rule("S4\'<,7&?#;"));rules.push(rule("]< =)>+9-HL[B833BH4QOJ]C7;9?TEG[@>T"));rules.push(rule("^9!5%7$<+1)JD;9"));rules.push(rule("S;\'2,6&>.AH^?86HE359ON?Z@WC"));rules.push(rule("^7!?%4$<+1"));rules.push(rule("[PKtbggg!]bbfjbqoi&`fjlt%`gmunX"));rules.push(rule("[fbtf4GKWI,[akbhcycg)Bpdm,Eah|k"));rules.push(rule("U^Lgmja\"Tf`gbn`n-omjklo}!bfey`W"));rules.push(rule("Uhec>JMT@(Y`cnfl~hb#Ovgd]beah|k"));
