// OpenAero rules13-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####      Regles France 2013      Espoirs à Doret 2013  Olan 6.0  ###################
//#####      Regles France 2013      Version 2013_PN.1.00            ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2013 : Espoirs, Desavois, National2, Doret

//##### (Une partie des) Regles specifiques à la France.

rules.push(rule("SXOvcoki.jt{jcu#jklo}Q"));rules.push(rule("Sglim<mh.=`+l|8u-\'#%_(!<*\'f)8&x#=:\"*;fp/*8 *n!$;#%*hln//&7&<4*)k\"ah\'f! ,.*;8#d)|(r#=m&%\">*4 $/0%"));rules.push(rule("Wl&hku;2;4"));rules.push(rule("Wjdwo0@qhjad(i}hbwy-goe"));rules.push(rule("YRJ|nih`*husfmpr(e`lhekP"));rules.push(rule("Za kbq9338"));rules.push(rule("Zgbtf4Bp`fok/bxuedtp)enm"));rules.push(rule("ZQKtbggg!m~`nyv*aoa{a_"));rules.push(rule("]f#bfs8;>6"));rules.push(rule("Tfk~ce`c/lit3>5"));
rules.push(rule("Qgia;\"jbk7<"));rules.push(rule("Rdhi5,ee`26"));rules.push(rule("Sehi:,ee`26"));rules.push(rule("Tveaj.dml<9"));rules.push(rule("Uvzdh.dml<9"));rules.push(rule("[n`vwphkom!cn65"));rules.push(rule("]oo|bmlm tfyacu5="));rules.push(rule("[ybjo$vgqmmz25"));rules.push(rule("_}`kg(~brqltg`|1?"));rules.push(rule("Xec|j:Mwkcef)aqqge||\'jif"));rules.push(rule("V.Mwkcef)aqqge||\'jif$"));rules.push(rule("Zzbuoc931"));rules.push(rule("[{bume931"));rules.push(rule("Ucfbgw`je,xcgas65"));
rules.push(rule("Re{kwq%x{}i{jy0X1U*Y0%8S>[%4"));rules.push(rule("Tphsfw/oiak2\'}lxlafz$tdfx|j"));rules.push(rule("Uqhsfw/lit3>"));rules.push(rule("]{cb&VZDH>{knm2RUQtV"));rules.push(rule("Rua}/RXE@2Abbc#hrgb(z|fkg`*xhjxqglmbz"));rules.push(rule("Rafjt,zczPfgq*0&]0X,]l\'R!4W+\"V7.1Y+!5,*><U<V#Zg\"X,Z9>::ZW+Q<+;T$?!p7P6[%%7-8W4^/5v"));rules.push(rule("Y{ybj*EjUljwV07!5,|`sTdfy<#q("));rules.push(rule("Wpc|\'Ci\\hhv^<9.2\'Yj~lrjfj\"`dxk}in`*dhwlvfh|i.|ry%fhu#emeom.n\'?0*icd{aq"));
rules.push(rule("[yxjf$Jm^i`zPodw*0&qfp]`dx4/+"));rules.push(rule("]zfv*EjUljwVlms(1.]hd~dim)enum~`jb+ldycqmmvd"));rules.push(rule("Rp|hg,EmvPfgqU:43)9\"sgxQnk?*%>/u(:}> 8s1\'1v9*5 "));rules.push(rule("[|e.Dez^i`zP095*0&Qfpcuac`/fgqohfl$nheezjb+d*:43)`gfzi}"));rules.push(rule("]lbch|(nh`q|hgr(1.AhTdfyY7<"));rules.push(rule("]< =)9+9-HQ359OZ6="));rules.push(rule("[<#4-8*6!F^4><EW0>"));rules.push(rule("[9#7-8*3,:"));rules.push(rule("W0%6$9(7"));rules.push(rule("X?\":!6%4*CT98"));
rules.push(rule("[3#3-;*6!FcQnkZbbt"));rules.push(rule("^6!2%1$<&Mf[cm|Sf`u"));rules.push(rule("_7!2%4$>&M[>3:FcQnkZbbt"));rules.push(rule("T3$5(5\'7\"OZ6?4IY?9"));rules.push(rule("S;\'1,2&?.AU141Ci\\hhv^`c|"));rules.push(rule("]? <):+; 4"));rules.push(rule("Z3#7-;*0"));rules.push(rule("[2#7-:*0"));rules.push(rule("Q6&4 7)?%D_<0"));rules.push(rule("R;\'6,2&8"));rules.push(rule("[3#3-?*6!F^4>"));rules.push(rule("]4 >)8+>"));rules.push(rule("Z2#3-<*6!F^4>"));rules.push(rule("V7%4$;(0)WRHF"));
rules.push(rule("_8!?%=$<&M[>1"));rules.push(rule("_6!6%6$5"));rules.push(rule("^<!3%4$<+1"));rules.push(rule("U4$<(5\'5\"OZ6?"));rules.push(rule("X0\":!4%4*CT98?LS2?"));rules.push(rule("T=$?(0\'<"));rules.push(rule("]< =)<+;-HQ35"));rules.push(rule("]< >)8+;"));rules.push(rule("Y8\"?!6%4\'9&Nh|]`dxQ85;"));rules.push(rule("^?!6%6$9"));rules.push(rule("^7!6%6$;"));rules.push(rule("[:#7-;*3"));rules.push(rule("[:#4-8*1!F^4><EW0>"));rules.push(rule("]: 7)?+;-HQ35"));
rules.push(rule("X1\"?>):+> 1"));rules.push(rule("Y8\"<!4%4*CT9:"));rules.push(rule("Z;#4-:*6!F^4<"));rules.push(rule("_7!2%1$9&Mf[cm|Sf`u"));rules.push(rule("T<$8(;\'6\"OgSocsTme"));rules.push(rule("Q6&> >):%D_<22Jm^i`zPodw"));rules.push(rule("S4\'6,3&=.AU141Ci\\hhv^`c|"));rules.push(rule("Y1\"8!6%4*CT98?LS2>5AU16"));rules.push(rule("[:#4-=*6!F^4<"));rules.push(rule("R3\'5,3&?.AU14"));rules.push(rule("V1%6$9(2"));rules.push(rule("^;!4%4$<&M[>3:F^4=<EW0>"));rules.push(rule("[9#4-8*3,:"));
rules.push(rule("U=$8(1\'5\"OZ6="));rules.push(rule("R:\'1,7&=.AhTdfyYkfv"));rules.push(rule("Z=#5-:*1!F^4>"));rules.push(rule("[2#7-;*6"));rules.push(rule("T3$>(1\'5"));rules.push(rule("R3\'6,7&=.AU141CT9:"));rules.push(rule("Q8&= ;)9"));rules.push(rule("X=\"<!6%4*CT98?LS2?"));rules.push(rule("S:\'6,2&:"));rules.push(rule("W?%1$<(2)JP;97@]=8"));rules.push(rule("W\\Mwkcef)`grizaft+fechvT"));
rules.push(rule("^jjjd8n?2.))kw/e}( +7b#+#$7\'!%a%qy+3/-5=)6h3($<#1\"%\'>##id)3$>m=)%+-*-ci$bahl%#3{g!mfci$0?(\':d),7---n;$0g%"));rules.push(rule("Za kbq936="));rules.push(rule("[fbtf4Bp`fok/cnvk{ijz$cmd"));rules.push(rule("]VH}fefo-bfzetna.fihjdcs^"));rules.push(rule("]f#bfs8;;6"));rules.push(rule("^c`un8Lgmja\"emoyhbv*ljo"));rules.push(rule("^UIujkih&glwcwge}/kbgxh["));rules.push(rule("Qj%aow:95?"));rules.push(rule("Wejvokod$icy5=<"));rules.push(rule("Smlc/lab3:"));
rules.push(rule("Wudifht.dml<9"));rules.push(rule("V`jh? kjg93"));rules.push(rule("Wajh= kjg93"));rules.push(rule("Xnmc7*fld07"));rules.push(rule("Yz|ga*fld07"));rules.push(rule("Z|iw$iko5="));rules.push(rule("^zzueue~+nh|?0"));rules.push(rule("Rgdtvxde`j*fdr06"));rules.push(rule("Tfk~ce`c/sm|kns64"));rules.push(rule("Rpfhn,zi~jf88"));rules.push(rule("Vtdif rl}vgqmmz26"));rules.push(rule("Twdlv.{ardix3>"));rules.push(rule("Uvzdh.{ardix3>"));rules.push(rule("Rofvg<N~oadn%nhubkkr(mbc"));
rules.push(rule("_\'Iujkih&glwcwge}/fgi#"));rules.push(rule("Ssfwnk5=;"));rules.push(rule("Tte~ho457"));rules.push(rule("]kb`fldj+sfmlu5<"));rules.push(rule("Zmivy)vtzb~`t6[8Q(X8)6\\9P >"));rules.push(rule("[xtmykq,fmcj:+scgdlw\"wmbz}b"));rules.push(rule("Zmivy)tsgx3Q>W+Q<2^U*3]&>"));rules.push(rule("^x}h(dlkf4$pn|mzfhe%|htw`gcmm,jj\':=:-bfnvgr"));rules.push(rule("Qfzc{*yjfacq4Z0]&$<T2=Xv>2*U*"));rules.push(rule("Tveajf{)l`ei3/sdkdhgvq$go(zg}fl`"));
rules.push(rule("Y{ybj*XUCC;qfhn;VWP|Z"));rules.push(rule("]zfv*XUCC;E`cwsm,oybh%|ooea\"tfezbf`dy"));rules.push(rule("Uwac.ZtkoWc{Pub`d0tleh8_SR}uZ"));rules.push(rule("Tsbt+Pyml^gyQ}nnk7Kod|vg!{i{cb+j-gulg\"wzebcb+pddwvligo|,}zu+ik-pf{pkbi`k"));rules.push(rule("[yxjf$JDB5~ack1-Vz*XoB_(t$UiAV)Vz/"));rules.push(rule("Rua}/ONO3fx%nh&glgndfofj\'odd~&olw\"sgxo{ndky-eldtmrmi}"));rules.push(rule("Ufecp.apuyx||:U<V#.X8);\\t=>&[%-Q<35Tx31!P \'\\:(2P/#4$&23R7S)+8*=]9X,<r"));
rules.push(rule("Tvac._5:1(1.ybyq{ytp381"));rules.push(rule("^yg~&S;56#4$R`{,jj\'yj~lrjfj\"r}|k}nnpxh&b)5:1({}\'g`y-pf{pkbi`k|"));rules.push(rule("Wu~io Kbq=2!5,xjut~u956"));rules.push(rule("Qv`u#Bfs<:-;#Yeq!li.}hd~dim)wwqm~gjry`*l&:9$qtz,mjt+sorjjend{"));rules.push(rule("Xkc`y*}`xyssxppr5R7S)#^; ?^u52(T\"&T6=X#Q(+R5/9U%.2\'/61S?_\'$?!z7P?[%8p"));rules.push(rule("^|zkn(Gl~:9qr!5,xjupz|rqz>>3"));rules.push(rule("]zfv*Fdr46vy$?!Xm}/cn%xbrb}mmo({byloxtf)e\"88,}zu+ik-pf{pkbi`k/jdk~lhwl"));
rules.push(rule("[hbhu$rgs|ha~syv7S?_\',Y0%5Ss6;,V#.6u52(T\"&T6&=W$&>) 1:V5R!\'6%x6X3U*?{"));rules.push(rule("Rp|hg,Emv67oj*0&ulvveg}z}t198"));rules.push(rule("Tsbt+Nh|;1lc.2\'[dy-bf)vmuixg`i+v}cq`awsm,o/>;%yxt#ee\"wm~zfdjio-bfzggolm`{b"));rules.push(rule("Yjc`y*ejzxuk4Z;]&=U>5VY$<Z-R1/9U1`4Y2Y$V71=<_]&1|4Y2+\"4z29-?g3R7!6P48P;p2Z2]&1t"));rules.push(rule("Rp|hg,F_^ztcjy&>gkrt{d4a#"));rules.push(rule("Rua}/O[\\{|odp~-;#Yeq!li.|hyqch&sfqqrém,ounv*ag#vkmdi"));
rules.push(rule("RE{kwq%bkh:U-;Q(2;X,Z:8Ss6W+;V54TX,Z:?Ss6W+;;Z-=x3]&>U=3==WQ(1u5^/:9R!\\:7Wq4_\'51]&p<S)9^880^U*~3T\"=T3VY$q4_\'0Y3;QR!{>Y$V40T5^/S>=;Zw0V#51U*~6T\"U=3V^;?[_\'6~6T\"<T4?XV#7>X,5:P >{<Y$>7_\'x5]&4U>5>2WQ(>X,2:P T581Wq1_\'71]&W?=3Vy=Q(;?X,Z9>:R{<Y$V5;T0^/S>=R{<Y$55_\'_33Up9S)3=V#]1:Y~9T\":T68XV#41X,5S>:R[%y2Q(787^/9p6S)>^;>[_\'_33<Qr7[%0Q?2^U*Y3;Qr7[%3Q>2;TX,0t4R!23Y$<z;U*7Z=;SS)P48Pz;U*Y4>Q8S)9,v4Z-8_23UP "));
rules.push(rule("[eha.geod59.inlpxhu#jklrahk}bnv*ninda\"omko{n}`y"));rules.push(rule("S`fjt,@c|~syv7S?_\'Xf*T\"U<?VY$%]2$<_(5(?4Y2Y$068W4^/5<"));rules.push(rule("Xzybj*Fdr:43Akp!5Da}vwy7::"));rules.push(rule("^yg~&Hku119Lms(1._fx%nh&qfpcuac`/ddhzbufl$jnzet`idfh&p|tgsai{}b+d*:43)`gfzi}"));rules.push(rule("Wddk| Ss=1suz3Q>W+Vi-_\'_06UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("]{cb&Hku559Qr5=,3Zw?0{ytp387"));
rules.push(rule("Wpc|\'@g{:22Tx8;/:+Uk~&gl$pn|mzfhe%ibksfwgd(azt+1?-klgpco|,}zwnwchsql$c!;:>/cnbxhu"));rules.push(rule("Zibhu$@m5=}z}t6[3Q(_m/^/S87R[%-Q<+;T-?%97P6[%8:6X3U*?1"));rules.push(rule("Qs}`k\"Jj};56Gf07!5Ha;2zqx~<?:"));rules.push(rule("]zfv*Fdr<>3Mk64(1._fx%nh&qfpcuac`/ddhzbufl$qn}.;2+ao~efg`co|,}zwnwchsql$c!94>/cnbxhu"));rules.push(rule("Rcehmv%hkiu~io~&>)JDB3Z?770Hku119Lms3Aow4=5_}262Icy94>Kh?0"));rules.push(rule("S4\'<,2&=#=\'EW0<=M[>1"));rules.push(rule("U4$?(4\'5"));
rules.push(rule("S:\'6,2&8"));rules.push(rule("Z?#4-8*0!F^4><EW0?"));rules.push(rule("Q9&: 9)9%D_<22JP;:7@]=8"));rules.push(rule("W0%7$<(7)JP;97@I=9"));rules.push(rule("Y>\"=!6%4"));rules.push(rule("V>%0$<?-;$O`p5>zw0KX74"));rules.push(rule("V3%7$<(0)JP;:"));rules.push(rule("X1\":!4%7"));rules.push(rule("[<#4-:*3!FJ4><EW0?"));rules.push(rule("S4\'7,5&=#;"));rules.push(rule("S;\'0,0&>.AU141CT9;?O`p5>kh"));rules.push(rule("]4 >)8+<"));rules.push(rule("U0$>(1\'5\"OZ6<4Jj}3=bl"));
rules.push(rule("T=$4(0\'0"));rules.push(rule("Q9&9 >)8%D_<2"));rules.push(rule("V?%4:#4-;"));rules.push(rule("U2$>(1\'7/5(B\\55"));rules.push(rule("Y0\":!4%1"));rules.push(rule("X9\"?!1%6*^VJG"));rules.push(rule("^<!5%0$<+7"));rules.push(rule("U=$8(1\'5/2(B\\55"));rules.push(rule("X?\"<!4%6*CT9;"));rules.push(rule("S4\'<,0&8.AU141CT9;?LS2?"));rules.push(rule("U2$5(;\'5/5(B\\54"));rules.push(rule("^6!3%4>#7#GV80"));rules.push(rule("_6!6%1$?"));rules.push(rule("^6!3%6$?&M[>3:F^4="));
rules.push(rule("]4 7)9+8"));rules.push(rule("S:\'=,2&>"));rules.push(rule("W0%7$>(1)JD;9"));rules.push(rule("R;\'6,3&8"));rules.push(rule("T=$?(0\'2"));rules.push(rule("U<$?(0\'<"));rules.push(rule("S;\'2,0&=.Bfs<:xv8GV833BH54"));rules.push(rule("^7!?%6$?"));rules.push(rule("Z3#7-;*6"));rules.push(rule("T5$<(5\'0\"RXE@4IXU~nl|p"));rules.push(rule("W?%0$<(7)JP;97@]=9"));rules.push(rule("V7%4$:(0)WRHF7@\\W~vbbsw"));rules.push(rule("_>!6%4$<+7"));rules.push(rule("^9!4%6$<"));
rules.push(rule("V1%=$?(2$6\"OZ6?4IY?86HQ37"));rules.push(rule("_>!5%7$?&M[>0"));rules.push(rule("W?%0$>(1)JD;:"));rules.push(rule("Z2#0-=*3!Emv67~u1CT9;?LG2?"));rules.push(rule("T3$5(2\'5/3(B\\560KX748GV82"));rules.push(rule("Z3#72\'5,5%4"));rules.push(rule("U=$;(;\'5\"ON6?4IY?86HQ37"));rules.push(rule("[<#>-:*6!F^4>"));rules.push(rule("[:#4-1*0!F^4>"));rules.push(rule("Z=#2-;*3,:"));rules.push(rule("Z2#3-1*3,:,@I=:"));rules.push(rule("Q8&4 :):"));rules.push(rule("R;\'=,3&>"));
rules.push(rule("Y;\"?!6%4\'?"));rules.push(rule("Z8#4-8*3,:"));rules.push(rule("W6%4$?(0$0\"OZ6?"));rules.push(rule("Y>\"6!0%4\'9&M[>0:F^4<"));rules.push(rule("_8!4%4$?&M[>3"));rules.push(rule("[<#4-=*3,:,@I=:"));rules.push(rule("^6!2%7$9"));rules.push(rule("T3$?(1\'6\"OZ6?"));rules.push(rule("U0$>(1\'6/2(B\\550KX75"));rules.push(rule("^9!3%4$?+7)JP;9"));rules.push(rule("U2$5(1\'0\"OZ6?4IY?86HQ37"));rules.push(rule("Z3#7-8*3,:"));rules.push(rule("Z3#2-:*4"));rules.push(rule("Z=#4-=*1!FJ4="));
rules.push(rule("[2#>-8*3"));rules.push(rule("[2#7-:*6"));rules.push(rule("]< =):+;-HQ36"));rules.push(rule("W?%1$<(2)Icy1<j`"));rules.push(rule("_7!3%7$?&M[>3:Emv67oj"));rules.push(rule("R:\'1,7&=.AA14"));rules.push(rule("T5$?(0\'0\"Lit7?"));rules.push(rule("^6!2%2$<+1)JD;97@]=9"));rules.push(rule("V?%1$<(1"));rules.push(rule("X?\"=!6%6\'9&M[>3:F^4="));rules.push(rule("T<$;(4\'6\"ON6?4IY?86HQ37"));rules.push(rule("W>%4:#5-;"));rules.push(rule("Y0\"?=):+>"));rules.push(rule("S4\'6,3&=.AA14"));
rules.push(rule("]? >)8+; 2"));rules.push(rule("_8!?%1$<+1)JP;9"));rules.push(rule("V1%1$<(2"));rules.push(rule("W2%7$<(2)Icy1<j`"));rules.push(rule("V3%6$<(2)JP;97@]=9>Gl~:9`m"));rules.push(rule("T1$>(2\'6\"OZ6?4IY?86HQ37"));rules.push(rule("X?\"6!1%4\'9&M[>3:F^4<"));rules.push(rule("U4$?(2\'7\"OZ6?4Jj}3="));rules.push(rule("[2#7-:*0"));rules.push(rule("^7!6%6$5"));rules.push(rule("[2#2-=*0"));rules.push(rule("U=$8(2\'6\"OZ6?4IY?8"));rules.push(rule("]8 =):+>-HQ359Lit7?"));
rules.push(rule("U=$8(2>*3!Emv67~u1CT9;"));rules.push(rule("S;\'0,0;\"?/IY?;6HQ36"));rules.push(rule("[:#7->*3!Emv67"));rules.push(rule("_8!5%4$<&MO>3"));rules.push(rule("X?\"<!6%7\'>&M[>3:F^4="));rules.push(rule("Y1\"8!5%4*@g{04wq3B\\550KL75"));rules.push(rule("W2%6$?(7)JP;:7Cn25nb"));rules.push(rule("Q0&= =):(8"));rules.push(rule("V>%3$9(0)WrhfSazXyloc"));rules.push(rule("U=$8(6\'6\"OZ6?4IY?8"));rules.push(rule("Q8&= :):"));rules.push(rule("S2\'5,2&=#;"));rules.push(rule("V>%1$?(2)JP;:"));
rules.push(rule("T<$8(6\'5\"ON6?4IY?8"));rules.push(rule("Z2#0-<*3!F^4=<EW0>"));rules.push(rule("V7%7$8(2)JP;:"));rules.push(rule("^9!4%7$<+1"));rules.push(rule("X9\"<!1%4*CT9;"));rules.push(rule("U0$>(2\'7\"OZ6?4IY?86HQ37"));rules.push(rule("Q9&9 :)?%D_<2"));rules.push(rule("Y<\"=!6%1*CT98?LS2>5Bfs<:ii"));rules.push(rule("T<$8(5\'0\"OZ6?"));rules.push(rule("[3#2-:*3!Emv67oj"));rules.push(rule("W0%6$>(1$0\"OZ6?"));rules.push(rule("T5$?(7\'6\"OZ6<"));rules.push(rule("_6!?%6$9"));
rules.push(rule("Z2#3-:*1,<,@]=:"));rules.push(rule("[9#2-8*3,:"));rules.push(rule("R3\'6,2&=.AU17"));rules.push(rule("W?%0$9(0$0"));rules.push(rule("S;\'1,7&>.AU14"));rules.push(rule("^?!5%3$?&M[>3:F^4="));rules.push(rule("[:#7->*6![\\GA"));rules.push(rule("_=!5%3$<+7"));rules.push(rule("[:#4-<*0!F^4><EW0?"));rules.push(rule("[<#>-<*3,<,@]=:>D_<12JP;;"));rules.push(rule("X9\"?!1%4*@g{04"));rules.push(rule("Z2#2-=*3!F^4="));rules.push(rule("^6!2%4$<&M[>0"));rules.push(rule("Y0\"?!5%7"));
rules.push(rule("W>%1$?(1"));rules.push(rule("Z=#4-;*6!F^4><EC0?"));rules.push(rule("^9!?%1$9&M[>3"));rules.push(rule("T<$;(0\'5\"Lit7?r{>D_<12JP;;"));rules.push(rule("[9#5-8*3,:"));rules.push(rule("W6%7$?(0)JP;97Cn25"));rules.push(rule("T<$9(7\'6\"OZ6?4Jj}3=bl"));rules.push(rule("V7%7$9(7)Icy1<"));rules.push(rule("Y1\";!3%4*C@9;"));rules.push(rule("]%H}fefo-hb}mmoi`</ddkdxY2 "));
rules.push(rule("Ymic`:&a; &.`r7h{#.#3c%e<&17$|*/g)(5bc$#($./bah,nog 7ljfc;)\")%4\"<.+48(&cid/3bcg=*kej-+7%7\".hlf; +{t5d(\"/\"*#a<#3?"));rules.push(rule("Qlg~k2Ayddnc#gevhgboc5+fechv"));rules.push(rule("Q)N~oadn%dlrjfjcm:,m`iepU?/"));rules.push(rule("_kjjd8|*2$&$5r/+g}w9{t-fci0.4k\" !),(jm&ci)0e`\" !,k%in-cid\"36,ci<9.jm&+;(32!,=*\'9oed4#&z)ahle=3%+-&fc)db*g8:$gk%?(&cid)ahlnogke>5fciva!6,%$,yu8!47"));rules.push(rule("Tiec>Ovcoki.aflecgo;$anfb{"));
rules.push(rule("RYOvcoki.aflecgo;$anfb{R"));rules.push(rule("Sh$icy5>=:"));rules.push(rule("Uhec>Ovcoki.aflecgo;$cmd"));rules.push(rule("W\\Mwkcef)jcuac`nk9%ccelgjw\\"));rules.push(rule("Vm&hku;1;4"));rules.push(rule("Xec|j:Mwkcef)jcuac`nk9%kaj"));rules.push(rule("XSJ|nih`*cgw`kl`d>.cniwoP"));rules.push(rule("Yb!cn67<8"));rules.push(rule("_mntnccj+nh|?0;"));rules.push(rule("[eha.dml<>"));rules.push(rule("]kob5&hcc;2"));rules.push(rule("^hnj>(gdh>8"));rules.push(rule("_inj<(gdh>8"));
rules.push(rule("Qgia6\"jbk7<"));rules.push(rule("Se{knm%aga::"));rules.push(rule("Vnnvxbjo$iko5="));rules.push(rule("Twdlv.dml<9"));rules.push(rule("Uvzdh.dml<9"));rules.push(rule("Vpyj~ kjg93"));rules.push(rule("Y{cbcby(gdh>8"));rules.push(rule("]hcsriccc.dez<8"));rules.push(rule("_mntnccj+qltg`|1?"));rules.push(rule("]ack&wo}cb}93"));rules.push(rule("^}af{(xhvfhp?0"));rules.push(rule("_|ne(xhvfhp?0"));rules.push(rule("]`a}b6Cxlh`l$l`|eaafg7*ljo"));
rules.push(rule("[#Ktbggg!fmzfhedf?&beh+"));rules.push(rule("]}a|ka88="));rules.push(rule("^~`tei7?6"));rules.push(rule("Xn`ansbkm vl`jv<8"));rules.push(rule("Sd{kwq%z|`s6[3Q(X80_]&=R!5"));rules.push(rule("Wqyj~ hbda?!zcznsbjd-pf{pkbi`k/cn%;56#maesm"));rules.push(rule("Ubxbss$vmmdi|2Y9Y$9]6$<_]&"));rules.push(rule("Y{cbcby(dlkf4pmofioz\'nk*{oqhcg!li.<1;%nhaqlw"));rules.push(rule("Rp|hg,[\\GA:yjfa<]RZq\\"));rules.push(rule("Vqc|\'^VJG9Dhoy|j\'json&u{mnmm,{anzpo`cm}"));
rules.push(rule("]{cb&Vzdh\\fq]sai`2udif7XXWwx\\"));rules.push(rule("[|e.ZtkoWc{Pub`d0@jnqpd(kzkn%ex&baa!~~gckn%cor|aodfx.|ry%fl&ulvvhkmbj"));rules.push(rule("Y{ybj*EVL0tleh8)T{\"TaMX#"));rules.push(rule("Y~dw\"IXC7}gp)`g!limcbefbh&fg$0dei.jknhocr#melr(y`j\'yj~lrjfj\"bga~`tn`"));rules.push(rule("]naaq&sorr}vq<V5R!/P4\'4[84+]&$U>2=Xv<6*U**Z9!6R.+8*)58W=^/(1.}<U5V#;y"));rules.push(rule("[yxjf$R398,3/qnw~|rqz>>2"));
rules.push(rule("Wpc|\'[7;9$?!Xm}/cn%xbrb}mmo({byloxtf)e\"00<.|ry%fhu#apuaoocbx"));rules.push(rule("_}zkn(Gl~:9$?!~i|{vwy7:1"));rules.push(rule("Y~dw\"Jj}3=&>)Tcr(hk/udqkyolg$qtxi|fb~wo-g#04\"r}~.lbx%|htw`gcmm"));rules.push(rule("Qbgbx\"qnw~xvr}vq<V5R!/P4\'4[84+]&$U>1V,V#.X8):\\!,3/#8>T4Z-)9\"s3R>S)6"));rules.push(rule("Wu~io Kbq=2tx,3/qnw~xvr}vq;4>"));rules.push(rule("Vqc|\'@g{04wq(1._fx%nh&qfpcuac`/t~uoof|vg!i,7?\'xpx-jb)rgs|emnkn%gbhwhjvd"));
rules.push(rule("Tgecp.apulc{ux8T4Z-!_3,1Qr>7\"Y$%384+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("Zxxjf$Icy1<j`\'6%|htwmksuz435"));rules.push(rule("[|e.Dez88ha/:+Uk~&gl$pn|mzfhe%yxvf{mgtzi.n\'25*~sq)hc!~i|{nhdfh&glwadfhoasn"));rules.push(rule("Rafjt,fc~ztc8T4Z-8_33UP >[%^? >^4j9_1P T6912PZ-4v9_1\"&6{:5#0`8W=,0S=<R:x>T=Z-4~"));rules.push(rule("Zxxjf$JQQ}f`r%7cis|wj;f("));rules.push(rule("Z}e.GWRt{dazs+8*]gp)`g!{c|{nn%zbspzéa\"`x~k|\'gd*{tjehg"));
rules.push(rule("Yjc`y*Cjx|rqz9\\8T\"Rk,W+Q>>^U**Z9!6R.6!;6X:U*?13R>S)65"));rules.push(rule("^|zkn(Gl~4;4Jnz,3Ghyt~u95="));rules.push(rule("Urbt+Nh|538Da}\'6%Zlu#ma\"sgxo{ndk*ninykqdm,f`ubecrbea\"r}|k}nnpxh&b)301(hkhunv"));rules.push(rule("]naaq&Pz93r}vq<V5R![o.V#]1>Y^/ W?\"?V,7)78W=^/5<5Q7W+7="));rules.push(rule("Tvac.Dez4<<[3>%7Xv7<uvs{628"));rules.push(rule("]zfv*Fdr823\\t64(1._fx%nh&qfpcuac`/ddhzbufl$qn}.;2+hecrbgp\"r}|k}nnpxh&b)161(hkhunv"));
rules.push(rule("Qbgbx\"Cd1?|rqz9\\8T\"Rk,W+Q9?^U**Z9!6R.6!;6X:U*?13R>S)65"));rules.push(rule("Wu~io Kbq5:1Lc::\'6Ae93r}vq;4?"));rules.push(rule("Tsbt+Nh|398Ha;2+8*]gp)`g!zcznsbjd-eldtmrmi.|h~v*93#maqbmbjni%yxvf{mgtzi.n\':=:-bfnvgr"));
rules.push(rule("SD{kwq%bkh:U-;Q(2;X,Z:8Ss6W+;V54TX,Z:?Ss6W+;;Z-=x3]&>U>4=2WQ(1u5^/:W<;23XV#]2;Y~3T\"?<[%y8Q(1R6/7UP s5W+9V47<Y^/t>R!3P7\'5[_\'x7]&W<<Z:Y$V40=Y~4T\"==[%y=Q(1R50\\T\"U=4Vy=Q(78X,Z:?Ss0W+8V57TX,0t;R!39Y$V71Tx5]&??S)w2V#>X8676UP s0W+9?Z-R615Up9S)86V#]2;0_}?P 71W+Q<47Tx5]&W=7Z?Y$V40Tx5]&9U>3VY$q1_\'1Y3?QR!5w2V#>+:x32!P T696Wq1_\'<*8t=U?691W$Z-u3^/0$6s6=,V#]1:Y~6T\"6>2W+Q<47Tx:]&8U>4VY$?z;U*6Z:8SS)w=V#2+8_22?5Ss5P59:[*U*Y0:Qr7[%2;Q(X86_}0P :\\:6WQ(X866\\t4R!2P7>PZ-R61\\t4R!2>Y$V71:Y~9T\";9[%^8>[1X,7S?:9?VY$<z;U*7Z?4SS):y2Q(6!3~01%R!5\"y3Q(2R40\\T\""));
rules.push(rule("]ckh*edgh;5)bkf}~k|\'hjd~oglvgd{,m`jf`*ccdhpkwm"));rules.push(rule("Zkajl~)fdn~{cbx%7-HPO?T00<5Bfs28=Nl{?O`p9:?R{1?6Kbq5:1Lc::"));rules.push(rule("^<!6%6$<+7"));rules.push(rule("Q6&> >)8%D_<22JP;:"));rules.push(rule("Z;#4-8*1!Emv67"));rules.push(rule("Z=#>-;*1,<,@]=:"));rules.push(rule("U4$<(4\'6\"Lit7?"));rules.push(rule("]: =)9+;-HE35"));rules.push(rule("V1%7$9(2$6\"ON6?"));rules.push(rule("U2$?(1\'7\"OZ6?4IM?8"));rules.push(rule("Q3&? ;):(>"));
rules.push(rule("Y>\"<!6%4*C@98"));rules.push(rule("Q6&8 >):"));rules.push(rule("Z=#3-=*3,:,@]=:>D_<1"));rules.push(rule("S4\'<,6&=#=\'EW0>"));rules.push(rule("U2$5(2<*1,<,@]=:"));rules.push(rule("Y>\";!5%4\'?&M[>3:F^4<"));rules.push(rule("U2$9(1\'5/3"));rules.push(rule("T<$;(2\'5\"Lit7?r{>DK<0"));rules.push(rule("T<$;(6\'5\"ON6?4Jj}3=bl"));rules.push(rule("Z2#3->*1"));rules.push(rule("[2#>-8*3"));rules.push(rule("_=!5%0$<+7"));rules.push(rule("]< =)8+8-HQ36"));rules.push(rule("]5 ;)95$?"));
rules.push(rule("W2%7$<(1)JP;:7Cn25}"));rules.push(rule("^9!5%7$?&M[>3"));rules.push(rule("T5$?(;\'5"));rules.push(rule("R:\'0,01\"</IY?8"));rules.push(rule("^6!2%1$>+7"));rules.push(rule("[<#5-=*3,<"));rules.push(rule("R;\'5,0&=#="));rules.push(rule("^?!6%2$9&Pyml^gyQ}nnk"));rules.push(rule("T=$<(0\'5/9"));rules.push(rule("V1%0$:(2$6\"OZ6?"));rules.push(rule("X?\"6!6%6\'9&M[>3"));rules.push(rule("[:#4-?*0!F^4=<Fdr46"));rules.push(rule("X?\"=!5%4\'>"));rules.push(rule("V4%1$;(2$0"));
rules.push(rule("[3#2-:*3!Emv67oj"));rules.push(rule("Q9&9 <):(8-HE36"));rules.push(rule("[3#3-?*0,<,@]=:"));rules.push(rule("W?%1$<(2)Icy1<j`"));rules.push(rule("U<$<(7\'5/3"));rules.push(rule("[2#72\'5,5%4"));rules.push(rule("Y;\"<!3%4\'9"));rules.push(rule("V7%6$?(2"));rules.push(rule("W5%1$5(2$0"));rules.push(rule("^;!4%7$?+0)JP;:7@]=8"));rules.push(rule("_>!5%1$<&M[>0"));rules.push(rule("X:\"<!4%4\'9"));rules.push(rule("U2$?(7\'7\"ON6<"));rules.push(rule("Y1\":!4%7*CT9;"));
rules.push(rule("S:\'5,3&=#;"));rules.push(rule("]5 9)?+9-Us`j]n}S|fbe"));rules.push(rule("R5\'7,0&?#;\'EW0<=M[>0"));rules.push(rule("^6!3%4>#7#GV80"));rules.push(rule("X9\"?!6%4\'9"));rules.push(rule("Q6&4 <):(8-HQ359OZ6="));rules.push(rule("Z=#>-<*1,<,@]=:>D_<12JP;;"));rules.push(rule("S;\'0,0;\"?/IY?;6HQ36"));rules.push(rule("V>%3$>(0)WrhfSazXyloc"));rules.push(rule("S;\'1,0?\"?/IY?86Kbq=2tx"));rules.push(rule("V3%6$?(2)JP;:"));rules.push(rule("[9#4-8*3,:"));
rules.push(rule("U4$?(5\'5\"OZ6<"));rules.push(rule("R5\'<,8&?#;\'EW0<=M[>0:F^4<"));rules.push(rule("_8!?%4:#5.=$LS2>5AU16"));rules.push(rule("Z8#7-8*3,:"));rules.push(rule("X9\"<!6%7*CT9;"));rules.push(rule("X1\"??)?+8"));rules.push(rule("V1%6$<(2$6"));rules.push(rule("S;\'1,9&=#=\'EC0<"));rules.push(rule("S:\'=,2&>"));rules.push(rule("Z2#3-<*1,<,@]=:"));rules.push(rule("]8 <):+8-HQ359OZ6<4IY?9"));rules.push(rule("S1\'0,6&=#;"));rules.push(rule("Y0\"??)3+8"));rules.push(rule("W>%4:#5-;"));
rules.push(rule("U7$>(6\'5/5"));rules.push(rule("X1\":!5%7"));rules.push(rule("V?%4:#4-;"));rules.push(rule("Y8\"?!5%4\'?"));rules.push(rule("Z;#4-;*3!F^4="));rules.push(rule("Z3#2-=*0"));rules.push(rule("Q8&5 =)9"));rules.push(rule("R3\'6,5&>.Bfs<:"));rules.push(rule("_>!5%6$9&Nh|;1"));rules.push(rule("Q6&4 >4%6\'9&M[>1"));rules.push(rule("^9!?%4?#7.;"));rules.push(rule("U=$8(1\'7/5"));rules.push(rule("_>!6%7$>+7)JP;9"));rules.push(rule("Z2#0-:*3!Emv67~u1CT9;?LS2?"));
rules.push(rule("X=\"<!6%4"));rules.push(rule("R7\'7,0&?.AU141CT9:?O`p5>zw"));rules.push(rule("[3#3-<*3!FJ4><EW0?"));rules.push(rule("S2\'6,5&8.Bfs<:"));rules.push(rule("Z=#4-8*0!F^4>"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("Q6&4 9):(8-HQ37"));rules.push(rule("_6!?%0$<"));rules.push(rule("_6!?%6$<+7"));
rules.push(rule("[3#3-1*1"));rules.push(rule("Z?#5-8*3!F^4><Fdr46vy"));rules.push(rule("[:#7-:*3,<"));rules.push(rule("V1%=$<7-8)0"));rules.push(rule("R:\'2,7&=.AA141CT9:"));rules.push(rule("R5\'<,0&=#=\'EW0<=M[>0:F^4<"));rules.push(rule("U<$?(1\'0"));rules.push(rule("^7!?%7$<+1"));rules.push(rule("R5\'6,0&8.AU141C@9;"));rules.push(rule("S4\'6,2&?.AA17"));rules.push(rule("Y8\"<!0%7*@g{04"));rules.push(rule("[<#5-;*6!F^4="));rules.push(rule("Y>\":!6%7\'9&M[>3"));
rules.push(rule("[3#0-;*3!Emv67~u1C@9:"));rules.push(rule("X1\"<!4%1\'5"));rules.push(rule("T6$?(5\'5/5"));rules.push(rule("Z?#5-8*6!F^4><EW0?"));rules.push(rule("Y1\";!1%4*C@98"));rules.push(rule("]4 >5%4$9+5"));rules.push(rule("]5 ;):+8-HQ369Lit7?cd"));rules.push(rule("Z;#4-<*0!F^4=<Fdr46"));rules.push(rule("[<#>-:*1,<,@]=:"));rules.push(rule("Z=#5-:*3,:"));rules.push(rule("T<$8(20*0!F^4=<Fdr46vy"));rules.push(rule("V>%0$?(2)JD;:"));rules.push(rule("]: :):+; 4#GV803B\\550KX75"));
rules.push(rule("_:!5%4$>&M[>0"));rules.push(rule("^9!?%7$<+1)JP;97@]=9"));rules.push(rule("]? ;):+; 4"));rules.push(rule("S;\'2,7&>.AU141CT9;"));rules.push(rule("R5\'<,09\"=\"3+KX778GV82"));rules.push(rule("Q6&? <)8(>-HQ35"));rules.push(rule("T3$5(29*3,:"));rules.push(rule("S2\'6,4&=.AU17"));rules.push(rule("Z2#2-;*0!Emv67oj"));rules.push(rule("[3#0->*0!FJ4><Fdr46gf"));rules.push(rule("S4\'<,0<\"=\"3+KX74"));rules.push(rule("[3#3-<*0!F^4><EW0?"));rules.push(rule("W?%0$?(1)JP;:"));
rules.push(rule("R3\'6,6&="));rules.push(rule("V>%1$?(2)JP;:"));rules.push(rule("W?%0$<(0$0\"OZ6?"));rules.push(rule("T1$?(2\'0\"Lit7?r{"));rules.push(rule("Q6&4 6):(8"));rules.push(rule("Z=#>-87,0%>"));rules.push(rule("[9#5-8*3,:"));rules.push(rule("R:\'1,2&?#;\'EW0<"));rules.push(rule("W0%=$;(0$0\"OZ6?4IY?9"));rules.push(rule("^?!5%7$?+0)Icy1<"));rules.push(rule("W>%1$<(1"));rules.push(rule("Q6&4 >1%4\'9"));rules.push(rule("X9\"<!6%4*@g{04"));rules.push(rule("Q8&4 ;):(8"));
rules.push(rule("U2$5(;\'5/5(B\\54"));rules.push(rule("Z;#7-?*3"));rules.push(rule("V1%7$?(7)JP;97@I=9"));rules.push(rule("]< =)8+;-Kbq=2"));rules.push(rule("[<#>-80,0%>"));rules.push(rule("^6!3%1$?&Nh|;1lc"));rules.push(rule("S;\'1,0&=.AU17"));rules.push(rule("R:\'2,9&=.AA141CT9;?O`p5>kh"));rules.push(rule("T=$4(0\'0"));rules.push(rule("]< >)<+;"));rules.push(rule("X=\"=!5%1*CT9;"));rules.push(rule("Q9&8 >0%7*CT9;"));rules.push(rule("R:\'2,5&=.Bfs<:xv8GV833BH54"));
rules.push(rule("Z2#2-=*3!F^4="));rules.push(rule("Y8\"?!1%6*^vjg[mtW~gji"));rules.push(rule("]: 7)?+; 2#GV80"));rules.push(rule("X?\"6!69+; 4"));rules.push(rule("R;\'=,3&8"));rules.push(rule("^9!?%0$<+1)JP;;"));rules.push(rule("T3$5(2;*1,<,@]=:>D_<1"));rules.push(rule("_>!6%2$>&PYML:F_^ztcjy"));rules.push(rule("[:#7-?*6![\\GA<EVZxukfqv"));rules.push(rule("R0\'0,4&=#;"));rules.push(rule("[:#4-1*0!Emv67"));rules.push(rule("W6%6$9(2"));rules.push(rule("T3$?(0\'5/3(BH56"));
rules.push(rule("Y>\"6!0%6\'9&M[>3:F^4<"));rules.push(rule("_7!3%4?#7#GV83"));rules.push(rule("T<$8(2\'6\"ON6<"));rules.push(rule("S;\'1,5&=#=\'EC0?"));rules.push(rule("V>%0$:(2$6\"ON6?4IY?8"));rules.push(rule("V?%4$8(2$6"));rules.push(rule("[2#2-:*0,0"));rules.push(rule("[PKtbggg!ihxnih`n-elgjw\\"));rules.push(rule("Vkdwo0@qhjad(ogyf+dn{gmjaf!cbaxi"));rules.push(rule("^UIujkih&bmrcokij/kbgxh["));rules.push(rule("Wjdwo0@qhjad(ogyf+dn{gmjaf!n~kj"));rules.push(rule("SXOvcoki.nc}ddncg)mlbgb`zZ"));
rules.push(rule("Xc!cn{`xkod407"));rules.push(rule("Rofvg<N~oadn%idpb)efwibmjc+pdfhl~j`n|d"));rules.push(rule("S+Ovcoki.khy`~-elgjw^9%"));rules.push(rule("Uao`i>wz/-n|lo+9\"--!$%66h|m (,kejmf#1:\".f$ ( =ll#($.-.#t.:(\'ke=~(-`oba:jnog&%;9##w)69i?:#4&ejm&cidba%>ol/9,<k*5$dbahln//&0&<5*))1$(r#<md6\' +}&$|%+)7 c\"!&-=)/)ah>:! lej?*jo#/"));rules.push(rule("Vkdwo0@qhjad(ha}b%ibhm|"));rules.push(rule("V.Mwkcef)`msmx.lhekR4*"));
rules.push(rule("^jjjd8og&0ad0g/+.(?kqk!2-$$/3-,#(+bc$ba\'#03&\")(,kejmf#<:\"*aj`\')\'7$#(- dbah!.\"5.%93&..2kr&\"g}w,\"l*!/0)\",;fg`4&{t\"&+84.0<%.\"4.%t +..#6sx?\":*&(4-2=))/,%!#\"gkn$#!e\'#)ahl.\"6.%j&7/;0o90"));rules.push(rule("Ydc|j:Mwkcef)`msmx.lhek"));rules.push(rule("W\\Mwkcef)`msmx.lhekP"));rules.push(rule("[{buoc961"));rules.push(rule("[{bume961"));rules.push(rule("V`gjkyomn)rnabz27"));rules.push(rule("_d\"jj}7>33"));rules.push(rule("Ugk~ce`c/lab36"));
rules.push(rule("Vdjvokod$icy55"));rules.push(rule("Vggiez;]R5/8U"));rules.push(rule("_TIujkih&gfvgu(`gmunX"));rules.push(rule("Tte~ji402"));rules.push(rule("Uue~ho402"));rules.push(rule("^hchjqcca.ykko|1>"));rules.push(rule("Xc!cn66?="));rules.push(rule("]oo|bmlm kbq9;"));rules.push(rule("^lntnccj+n`j?8"));rules.push(rule("XO~azw&s}tl}9;]&$U>5?=3Pz29-^/S=8R[%"));rules.push(rule("_yzwyj~ hbda?sgxo{ndky-pf{pkbi`k|\'fjdygm}aq"));rules.push(rule("Qw}||`s&hcc;1"));
rules.push(rule("Vdjvokod$vgqmmz26"));rules.push(rule("Tveaj.{ardix3>"));rules.push(rule("Uvdlv.{ardix3>"));rules.push(rule("Vu{ld tfyacu5="));rules.push(rule("Ubxbss$vmmdi|2Y9Y$%4X:)4\\t?U=*>Xv9]1$<_(T\""));rules.push(rule("Y{cbcby(dlkf4Vmmde`h\'pxc*#oeohdu.=)9+9 4-;*4!gy.=)8+8 4-:*7!gy.=)?+8 4-=*:"));rules.push(rule("V`jh; kjg93"));rules.push(rule("Y{cbcby(gdh>8"));rules.push(rule("Xnmc:*fld07"));rules.push(rule("Yomc9*fld07"));rules.push(rule("Zllk4$iko5="));rules.push(rule("[mlk;$iko5="));
rules.push(rule("[x}om$iko5="));rules.push(rule("^g|iju\'`om46"));rules.push(rule("_`|iju\'`om46"));rules.push(rule("Tkz}ip`pg,ee`26"));rules.push(rule("Sbehmv5RU>*2X"));rules.push(rule("^UIujkih&gfvgu(e`lhekP"));rules.push(rule("Qqgbe:?5"));rules.push(rule("Rrfwlm58>"));rules.push(rule("[maib}mlf%|afi8:"));rules.push(rule("Un\'`g{4771"));rules.push(rule("Ufecp.`jvdzhg{:U^:4[_\'9L"));rules.push(rule("Zxxjf$Mlum~jfsn%7-om}apeax4A"));
rules.push(rule("Y~dw\"Neqobj}a\"<(Jghry`*ic#keqd(e`{byacyc"));rules.push(rule("Rafjt,`c||sdu7S?_\',3}1p??.W+Q>>^459_1P =[%6V#2#4$0:V5R!5W+9Q(5)9\"23R7S)9Y$>Z-1$?!<7P6[%1V#5_\',Y0%4S&\'6%.<=]0X,9T\"=S):%7-48W=^/0P <[%7*0&72Z;]&4R!4W+9-;#??\\8T\"6S)8Y$9&>)<9_1P 2u0[:Q(>s"));rules.push(rule("^|zkn(Bbt29wvnx,3/odwyyis3830"));rules.push(rule("[|e.Akp08z`w+8*l&nh|kl}a.`a+4:-uwftq!i~k/fgiezcg)kl!{x|nnlm~-nl{mxnfxoc\'gldhu#{knm{"));
rules.push(rule("Ufecp.{knmW^:2Y2Y$9Z-8X,35M5Q>W+;Q(2U*Y0%8S2F0[3Q(+R5050Q\'S)6!;6X:U**8t=>&[%-Q;+:Tx31!1H4Y2Y$%?84+<n7P6[%4Q<4^4w9_8P 2}"));rules.push(rule("Y{ybj*Y1*0&qfhn^Z84Qt+-QSGyTx^v$%"));rules.push(rule("Urbt+Q=$?!xm}/cn%nheoljaim,az\'{dy-ef}pg!zcznsbjd-bbgw\"mi,l}fefbh&nfjv`fxk/f}`i-sml$tsa`bj\'odd~&oh$`sibmgb+ao~efg`co|i "));rules.push(rule("Ufecp.{knmW^82Y2Y$<6_\'<^/:1V4Y2Y$%]2;0:\\!P 2#:>T4Z-!=~08%R!/P3\'4[84+<N7P6[%-3q73 9d:V5R!6P48P;p2Z2]&1t"));
rules.push(rule("]{cb&W<-;#{knmW^85_"));rules.push(rule("Rua}/S>,3/dn%nheoljaim,k|s+ldycqmmv/(_oza+v&olw\"gak{}bx%=#4-;*3-(; =)?+8!&;\'1,2&?\"/?%0$9(7%$:/>\"<!3+`~->-?*6/;\""));rules.push(rule("Zxxjf$RFN_B?77+8*iitguvs{62<"));rules.push(rule("^yg~&SNBQM8<2!5,{a\'fdrdkvd$398,jj`y`y-bf)vmuixg`i+`yy&slvoh{\""));rules.push(rule("[yxjf$RFN_B<87+8*iitguvs{62;"));rules.push(rule("Qv`u#YCDRD?13)9\"tf,cnbh`&1>4\"emk|jt+ao-tl}evhgb.jt%zhtn`w,"));rules.push(rule("]{cb&SNBQM8W\"<(haxixqe}<?;"));
rules.push(rule("Z}e._@MVF=]/:+uk~&gl$d`kiz{b+uokjza,"));rules.push(rule("Zxxjf$V31(1.}hgi0S.+Us.ZnJS&{PcLPz+RbD\\$Py&.+^;?2;T"));rules.push(rule("]zfv*Y4:-;#yeq!li.}hd~dim)`co{,bn\'iwkcekl$fd{okacjk~h&baa!}b.kbhiocekl$f`f.cf+gxlh`aa\"lgbzni`$"));rules.push(rule("Tgecp.{knmW^?>:U<V#7_\'5^/S=<R:J>T4Z-!_33<4S&[%8.<=]0X,)1p??.W+\"V0.0Y~08%3I<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q>"));
rules.push(rule("_}zkn(X<7#4$pnd`Q]6:?\"S.+Us.ZI=<;?mCW$zX8669nJSs/PD;?2;oB_-T{\'&\'P489>^ x*_SRtNZ %Q<471Y+} RUQ}V.*V`ET-"));rules.push(rule("Vqc|\'_72)9\"bmxzj\'hjgoomhmqnf,jj\'yj~lrjfj\"lgbzni`*hr#zkolaxocb+`yy&jgpgslezj)"));rules.push(rule("[hbhu$vmmdS\\>36[3Q(2U*7]&W?=4V8K6X:U**Z9>:7Z\"Y$0\"22Z;]&$7s6;,V#.X?);\\t=>&:M>T4Z-!=~08%3i<U<V#7X86_<{7P?[%8p"));rules.push(rule("Wu~io T2=$?!zcbcXY4>7XXUs.\\#,&TYqXv%Zt%Xu(!,&TYJWq._~(+("));
rules.push(rule("Z}e.[56!5,mjs`*iwhpknf,jjth`digm}a\"d{x.fi`xiowl$go(||jtnkih&g.qld(~a{flec&b|$qneak{)"));rules.push(rule("Rafjt,zcbcXY4?0X:U*3]&9R!\\:(8P;B2Z;]&$U>5?=W$Z-4\\9_1P \'>w4:$Z-!_4,1Qr>7\"8L6X:U**8t=>&:m>T4Z-8_33U1}4Y;Y$0|"));rules.push(rule("[yxjf$V34(1.}hgi0~*XoBZ\\"));rules.push(rule("Vqc|\'_76)9\"qi.kb+aonjfggjd(c{/dnq~h&qfpcuac`/f{wo~&vga\"wzebcb%"));
rules.push(rule("Wddk| bl{av^lc}2Y2Y$<Z-8X,Z=!6R:}>T4Z-=X,0T\"U;*3X7{=]0X,9T\"?S)P7\'5[>?\\8T\"U>5VY$8Z-R0/9U1`4Y2Y$V2;TX,4T\"U<*3X7c=]0X,)1p??.W+\"8z29-^/5b5Q>W+\"V71=<_(T\"3}<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q"));rules.push(rule("Y{ybj*EjUicshvv^lc}/:+aecwV`mr2Rx"));rules.push(rule("_xg~&KeRbfyepuWha|\'6%zlu#ma\"em|o}s+ae~&baa!kiz{b+weygw`kl!~i|{nhdfh("));rules.push(rule("[yxjf$Jm^{c|{nnZnbu#4$fnzizPcdv0c\""));
rules.push(rule("Rua}/OgS}`uloRblz$?!xm}/cn%ybtw`a\"eg.nqnf*ncw}a\"sgxo{ndk*{cq}ma`di "));rules.push(rule("Rafjt,k`gbezqx~;]0X,)S=#6Zw4:$Z-R507?QR!/P4\'5[*)9\"%:7P6[%%7-t8W4^/5v"));rules.push(rule("[hbhu$gnhen}{h{8T4Z-!5~8t=>&[%^;?04T93:V5R!5W+Q<4^U*6!5,<4Y2Y$?Z-R50\\T\"8/:+61S?_\'6^/S=<R[%=*0&72Z;]&8R!\\:7WQ(+R5/9U%.2\'/41S?_\'<^/S=<R[%4*0&12Z;]&4R!\\:7WQ(1)9\"53R7S)3Y$V71TX,2(1.9<U<V#>_\'_33UP ;\'6%26X:U*?s3R>S)6"));
rules.push(rule("^m`i}(}ww{w?_1P \'\\:(3Pz29-^/S=8R[%-Q<+;T-\"<((<4Y2Y$-;#{?\\1T\"3u"));rules.push(rule("^m`i}(}uwft?_1P \'6w<v<6*U*Y0>Q3><U<V#4_\'5^/<,3/50[3Q(1U*3]&:.2\'8>T4Z-;X,0T\"6/:+11S?_\'0^/9P \'\\:(2P/#4$&03R7S)3Y$<Z-8$?!:7P6[%=V#7_\'6\"<(85Q>W+2Q(2U*1!5,84Y2Y$5Z-8X,5(1.7<U<V#;q2Z2]&1t"));rules.push(rule("Ufecp.mmcf}|{ux8T4Z-!_3,1Qr>7\"Y$V44TX,)S=#7Z\"%7-\"12Z;]&,3/u0[:Q(>s"));
rules.push(rule("^m`i}(ndgd|tqug|3Q>W+;Q(1459_1P \'>w4:$Z-R65\\5>5Q>W+8Q(1U*6!5,<4Y2Y$?Z-;X,7(1.<<U<V#4_\'6^/0,3/30[3Q(7U*0]&$U>*3X#-;#-59_1P 7[%7V#7#4$0:V5R!?W+8Q(1)9\"53R7S)3Y$?Z-:$?!>7P6[%=V#4_\'0\"<(45Q>W+7=]9X,<r"));rules.push(rule("Wddk| bl~jsuz3Q>W+\"V7.0Y~08%R!/>y;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));
rules.push(rule("Wddk| bl~jqug|3Q>W+\"<z:u52(T\"&:{:5#078W=^/:P :[%1*0&12Z;]&>R!2W+<-;#:?\\8T\"<S)>Y$5&>)09_1P ;[%0V#.X8):\\!,3/#:>T4Z-1X,4T\"?/:+71S?_\'<^/=P =\'6%>6X:U*:]&9R!4+8*;=]0X,9T\";S)?%7->8W=^/5~5Q7W+7w"));rules.push(rule("[yxjf$RWQ<9>/:+pz|rqz>>7"));rules.push(rule("Xdw\"Q^U>86#4$c!emvfj~h*b`#=12!lii}bnv*ltf)enmg{kk\'dk*{cq}ma`d,{\'duzbuj}a\"sg`b|"));rules.push(rule("Uwac.MMCF]\\;;7+8*iobnqrp|~}5;<"));
rules.push(rule("]zfv*OLKJSS<02!5,o/jj}c`sn)kd!=8>/cnbxhcp)epd(mbch|`n-im)`k`oc`nk+pz-isykqh|i.}hgiy"));rules.push(rule("^|zkn(\\XV7Z$?!}|}{h{?68"));rules.push(rule("Wpc|\'[SS=W\"<(m.bfslgxk#fb\"5(z`wx%kc#hhnnij/he%|htw`gcm(y~/h{ue~owl$pnd`}"));rules.push(rule("Xzybj*OLKJSS=W\"<(hgn`~uyyis387"));rules.push(rule("Y~dw\"CBDMXV7Z$?!i,cnbh`&lo$6!{xat+-9-oe)wl`x%.nun%kajl~af!gb.knjbecgo)qr!g|~`tbqo-tlehq"));rules.push(rule("Zxxjf$GNHEN::7+8*njjdfsuz4$;="));
rules.push(rule("Vqc|\'NJJDF648,3/f+hkuon|i\"nn,::7+aojtflw\"`zi.nkgj}hb#fj\"bdecmneb*ioew"));rules.push(rule("[yxjf$GNHEN:\\\'6%iaonkwvnx6%32"));rules.push(rule("Rua}/BDECM3X%7-g#dezheyc/hm%>-uwftq!i~k/fgiezcg)kl!k`gbebkm-ioew"));rules.push(rule("[yxjf$RFN_B=97+8*iitguvs{62:"));rules.push(rule("Y~dw\"QOJ]C559$?!i,cnbh`&lo$178,jj`y`o~&b{a\"`d`axbo%ec&ulvvhkmb/cdrd-isykqh|i.}hgiy"));rules.push(rule("]{cb&SNBQM:W\"<(haxixqe}<?="));
rules.push(rule("Vqc|\'[BL^J1R(1.n\'fdrdkvd$mg(?.|sduy-gql$cmdcyjc+jd-pf{pkbi`.kh|k*bvsfwkum,|`kgv"));rules.push(rule("Qbgbx\"qoAbkuy4Z;]&W?=33XV#]2<Y?w3R7S)P489>^U*0<l7P6[%^;?2;TX,55H5Q>W+Q<471Y^/5d5Q>W+\"4z29-^/S=#:Z6c1S?_\',;}9<\'S)6C1S?_\'5Y0:Q3|<U5V#;y"));rules.push(rule("^|zkn(_cjjdmvdlBAZ\'6snInez~8!L r#Cws&V`ETxYGnQ\"y{PClP*g"));rules.push(rule("Sta}/Tf`gbn`nCIV)9\"nx|a|n`*bt#|jnhfgkk\'yjfa)qfhn! c|/aglif/#jkocabo{ndk*du#gkv!i`b`pna"));
rules.push(rule("Y{ybj*^kfdkj}afOGYH/:}aNe`ps>\"e$J"));rules.push(rule("Y~dw\"Reic`owl`LN]J.2\'?0\'xv#{knm\'jbfd`%\"/nb{`\"viu,&\'hjgoomhpknf,g|\'ej~-goekudl"));rules.push(rule("^|zkn(DK5WFTJ!5~ack1%\"#*-u669!,UiAV!"));rules.push(rule("]zfv*EC9YISA$?!fc.ikbfa-tleh\"nf,xjulilj#mkuo(`gab+dlycq)lgraxo{ndk*dh#}lg!dca"));rules.push(rule("Rp|hg,FJ<ZW83:-;#|tsuz4/Y#^? >^u(6}< r=+8y9!]1:Y+!n"));rules.push(rule("[|e.GB0TX?8?\'6%db&eemaj(~ack+jd-jlft\"ug|.na`x-kl{a\"u`m`/4=5*ioe$enabi/r{"));
rules.push(rule("Zxxjf$JD3]\\<\\SDU*0&vywvnx6.Q/P6\'4[%6~3$%.i"));rules.push(rule("^yg~&KL?SS;WVNX,3/id%lao`b$pnd`.`i+iebv#}kr!ijzju+hec#}lco(>.|sduy-al`je!}|"));rules.push(rule("Sq|hg,F46/:+weaj9)<"));rules.push(rule("Xdw\"I3=*0&;)tmhfx.}hgi*du#gkv!i`b`pna"));rules.push(rule("]{cb&KE_@#4$pnd`4/\\:7>5[/o"));rules.push(rule("Sta}/OG^H/:+weaj/ohkbc,m`jildlrjfj\"ogx.nkgj}hb"));
rules.push(rule("Wfgiez+glbptdi}2\'^kfdkj}afOGY5ZiglgdrfmJMTN7XZW?0:6PVY0Q:^HAXI83:6PGFSL2[7JFFLPZ8232@K@OY^;T0W<6T2<?Jnz=>|sdu"));rules.push(rule("Q9&: 9)9%DBS9;?LG2=5AA8QE]N8[56"));rules.push(rule("S4\'<,7&?#;"));rules.push(rule("_7!1%=$>+7"));rules.push(rule("X1\"??):5$?+7"));rules.push(rule("U=$9(2:*3"));rules.push(rule("X?\"<!4%6\'9&MO>0"));rules.push(rule("Z?#4-8*0!FcQkb{dxyYgfw9OgS}`uloRblz"));rules.push(rule("X9\"<!?%1*CIQO>0:FJ5YCDRD<>32RFN_B?\\"));rules.push(rule("R5\'<,4&?#;"));
rules.push(rule("[3#3-8*3!FJ4="));rules.push(rule("X0\";!3%7*C@9;?LNZJ"));rules.push(rule("^6!1%=$<&MFQ833BH560KL>RLYL"));rules.push(rule("W>%<$8(1$0"));rules.push(rule("V?%<$;(7"));rules.push(rule("U4$?(2\'5"));rules.push(rule("Y0\"?=):+> 0"));rules.push(rule("W>%4$8(2$0"));rules.push(rule("V>%3$;(0$0\"ON6="));rules.push(rule("S2\'6,5&?#;"));rules.push(rule("[>#4-8*3"));rules.push(rule("^7!6;+>#4"));rules.push(rule("W6%7$?(2)Jm^{c|{nnZnbu"));rules.push(rule("_>!5%6$>+7"));
rules.push(rule("T<$8(4\'7"));rules.push(rule("U2$9(0\'5"));rules.push(rule("U2$5(7\'5/3(BH56"));rules.push(rule("X?\":!5%7*C@98?LN]6?"));rules.push(rule("R:\'1,5&=.AA17"));rules.push(rule("Q9&8 <)8(>-T7"));rules.push(rule("T5$?(5\'0\"OG^H550KL6PGFSL00<5YCDRD<U"));rules.push(rule("Q9&9 :)?"));rules.push(rule("Q3&? ;):(>"));rules.push(rule("Q8&= >):(?"));rules.push(rule("Y;\"<!4%4\'9"));rules.push(rule("_>!6%6$<"));rules.push(rule("T6$?(5\'5/5"));
rules.push(rule("Z=#2-8*1,<,@]=:>DBS98?LG2=5A?3"));rules.push(rule("T5$?(5\'5"));rules.push(rule("_7!2%6$<&MO>0"));rules.push(rule("V1%=$;(2)JD;;7@@UM?8"));rules.push(rule("T=$<(7\'2"));rules.push(rule("S:\'0,5&8"));rules.push(rule("[:#4-?*1!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("W0%7$?(0$0\"ON6<"));rules.push(rule("]5 9)<+8-HL\\>0:FJ4><EC9YISA"));rules.push(rule("[9#7-;*3,<"));rules.push(rule("[:#4-:*3"));rules.push(rule("T3$5(4\'7/5"));
rules.push(rule("[3#0-<*0!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));rules.push(rule("[3#0->*3!FC[550KL778GB1UG\\F4IdZybtw`a]eg"));rules.push(rule("[2#4-<*6"));rules.push(rule("[2#73\'7,3"));rules.push(rule("V7%7$:(2"));rules.push(rule("_>!5%=$>&MO?TEG[@=0;>\\IITG5Q"));rules.push(rule("V?%1$8(1$7"));rules.push(rule("Y0\"6!3%7"));rules.push(rule("S;\'2,0&=.AH^?86HE379ON>[_4=51C@1\\T0R\\C^4U:4"));rules.push(rule("[:#7-?*0!FcQkb{dxyYgfw"));rules.push(rule("[3#0-;*1,<"));
rules.push(rule("W0%1$<(1)JD;97@@R14"));rules.push(rule("S2\'5,7&?.AA0SNBQM;32:^HAXI:V"));rules.push(rule("V0%7$<(1)JD;97@`Xo`zltwV`mr3BaPtdw~dc\\mkq"));rules.push(rule("^6!3%4=#5.=$LNZJ"));rules.push(rule("Z2#0-:*1,<"));rules.push(rule("[3#0-=*1,<"));rules.push(rule("Y8\"<!6%6\'9"));rules.push(rule("Z3#4-:*:"));rules.push(rule("W>%=$<(2$6"));rules.push(rule("[2#>-<*3,:"));rules.push(rule("X>\"<!6%6*C@98?LnWa}sb`Uiip"));rules.push(rule("T3$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));
rules.push(rule("S;\'0,3&>.AhTao}gq}[fn{"));rules.push(rule("]4 6)9+>"));rules.push(rule("S:\'=,5&8"));rules.push(rule("T=$4(7\'2"));rules.push(rule("X?\"=!4%6\'9"));rules.push(rule("Q9&9 >)8(>"));rules.push(rule("V1%6$<(1)JMSN6?"));rules.push(rule("_:!4%7$<+7)JD;97@I=9>IAONK0Q:K@GBE?0:"));rules.push(rule("_6!>%6$9"));rules.push(rule("W5%1$;(2$0"));rules.push(rule("Y>\"6!?%7*C@9:?LNZJ"));rules.push(rule("[3#2-82,3%8.AHYC"));rules.push(rule("T3$5(6\'5\"ON6=4IDWL74"));
rules.push(rule("[<#5-:*3!FC\\I=9"));rules.push(rule("T=$<6-1*0"));rules.push(rule("W0%1$9(2)Jm^{c|{nnZnbu"));rules.push(rule("T<$;(1\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:FcQkb{dxyYgfw"));rules.push(rule("S;\'1,2&?#;"));rules.push(rule("V>%3$9(2)JMT2>5AA161C@1\\T1787@I5^U8^RLY"));rules.push(rule("T<$9(2<*3!Z=>"));rules.push(rule("R;\'5,3&=#9"));rules.push(rule("X1\"<!4%1"));rules.push(rule("S4\'6,3&=#=\'EC0<"));rules.push(rule("V1%=$9(7"));rules.push(rule("[:#4-8*0!FC\\I=:>DbYpfvvhmSj`t"));
rules.push(rule("W0%6$?(1)JMSN"));rules.push(rule("[=#4-;*3!FJ4>"));rules.push(rule("U=$;(0\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:Z=?4IdZnhvb{p]eg"));rules.push(rule("W6%7$9(1)JMSN6?"));rules.push(rule("U=$9(0\'5"));rules.push(rule("R:\'0,5&?#;\'Y1"));rules.push(rule("S;\'0,00\"</U:51CIQO"));rules.push(rule("^6!2%=$9&MFVD;:"));rules.push(rule("X0\":!63+;"));rules.push(rule("S:\'0,2&>#;"));rules.push(rule("[2#?-;*0"));rules.push(rule("U=$;(0\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:Z=?"));
rules.push(rule("^6!1%=$?&MFQ833BH560KL>RLYL9OgS}`uloRblz"));rules.push(rule("T3$5(0\'5/3(BH56"));rules.push(rule("W0%=$;(1)JD;;7@@UM?;"));rules.push(rule("V>%0$5(2$6\"ON6?"));rules.push(rule("S:\'5,2&=#7"));rules.push(rule("X9\"?!0%1*C@8_@MVF>9?<]AEZH2Z"));rules.push(rule("Q6&8 :):%DK<2"));rules.push(rule("[:#4-;*1,<"));rules.push(rule("[2#73\'7,5"));rules.push(rule("Z3#?-84,3%8"));rules.push(rule("U4$?(4\'7\"OG^H550KL6PGFSL00<5YCDRD<U"));rules.push(rule("]8 =):+>-HlV`gqi~zPcdv"));
rules.push(rule("T3$5(0\'0"));rules.push(rule("Z<#4-;*0!FJ4><EjUicshvv^lc}4IdZybtw`a]eg"));rules.push(rule("W0%=$<(7)JMSN6="));rules.push(rule("R0\'0,4&=#;"));rules.push(rule("Y?\"<!6%1*C@98?LnWhkfyqUiip"));rules.push(rule("Q6&4 8):%DK<0"));rules.push(rule("R:\'0,00\"=\"3+KE_@"));rules.push(rule("Q9&8 >):"));rules.push(rule("S;\'1,4&=#=\'EC0<"));rules.push(rule("[<#5-:*0!FC\\I=:"));rules.push(rule("R:\'1,3&?#;"));rules.push(rule("V?%7$<(7"));rules.push(rule("_>!6%2$?&Mf[fdxm|{Xojy"));
rules.push(rule("[3#3->*6!FC\\I=9"));rules.push(rule("^?!5%2$9&MO?TEG[@=0;>\\IITG5Q"));rules.push(rule("[>#4-8*1!FcQ|hyqchYgfw"));rules.push(rule("S;\'2,0&>.AH^?86HE379ON>[_4=51C@1\\T0R\\C^4U:41Ci\\mar`zxQkhx"));rules.push(rule("]< =)?+;-HlVwms|ekPcdv"));rules.push(rule("V>%0$>(1)JD;:7@@UM"));rules.push(rule("]4 6):+8 2"));rules.push(rule("U2$5(6\'6\"ON6=4IDWL77"));rules.push(rule("U=$8(4\'5/3(BH56"));rules.push(rule("[:#7-;*3"));rules.push(rule("Q6&? =):"));
rules.push(rule("T<$8(1\'6\"ON6<4IDWL"));rules.push(rule("X1\"?>):+> 0"));rules.push(rule("V>%1$9(2)Jm^{c|{nnZnbu"));rules.push(rule("W?%1$9(1)Jm^li~nuZnbu"));rules.push(rule("R3\'6,4&>.AhTao}gq}[fn{"));rules.push(rule("S:\'52/>\":"));rules.push(rule("S2\'6,2&>.AHYC0<=Mf[qnzxgjXojy"));rules.push(rule("R5\'6,0&=#=\'EC0<"));rules.push(rule("U2$>(2\'5\"OG^H55"));rules.push(rule("Y>\"<!3%6\'9&MO>0"));rules.push(rule("R5\'<,0&=#=\'EC0<"));rules.push(rule("X?\"6!5%6*CIQO>0"));
rules.push(rule("T<$;(1\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR"));rules.push(rule("T5$?(5\'6\"OgSjjwjw~Rblz"));rules.push(rule("W?%0$8(0)JMSN6<"));rules.push(rule("V?%=$?(1"));rules.push(rule("X1\"6!4%1"));rules.push(rule("R;\'=,5&>"));rules.push(rule("Y>\":!6%4*CIV35"));rules.push(rule("Y1\":!6<+;-T29"));rules.push(rule("R:\'0,3&=.AhTverjl[fn{"));rules.push(rule("Y1\":!6>+9 2#GKPG"));rules.push(rule("Z;#7-85,0(BA]A"));rules.push(rule("T<$8(5\'5/3(BH56"));rules.push(rule("R;\'5,5&>"));
rules.push(rule("W0%=$:(1)JD;;7@@UM"));rules.push(rule("]4 >7%6$;"));rules.push(rule("_6!6;+>#2"));rules.push(rule("]? =)9+; 2"));rules.push(rule("_7!3%4$?&Mf[fdxm|{Xojy6HlVwms|ekPcdv"));rules.push(rule("_6!3%7$9"));rules.push(rule("Q0&> =)9%DBTE35"));rules.push(rule("W0%6$9(2"));rules.push(rule("R:\'1,0&>.AA171CIQO"));rules.push(rule("V7%7$:(1)Jm^li~nuZnbu"));rules.push(rule("T3$?(0\'5/3(BH56"));rules.push(rule("^<!5%0$<+7"));rules.push(rule("V1%7$<(0$0\"ON6<"));rules.push(rule("W>%7$?(7"));
rules.push(rule("_7!3%4=#4#[52:FC\\I"));rules.push(rule("V>%0$5(0"));rules.push(rule("Z=#2-;*3!FC[56"));rules.push(rule("^7!>%6$?"));rules.push(rule("_>!6%2$<"));rules.push(rule("U=$;(6\'7/5(BH54"));rules.push(rule("]; =)9+>-HE359OgSjjwjw~Rblz"));rules.push(rule("_=!3%6$<+7"));rules.push(rule("Q0&> :)8%DBTE369ON7XKH\\K;568_@MVF=]"));rules.push(rule("V7%4$:(0)JD:^HAXI:=:6PGFSL0[7@`XxjxyofV`mr"));rules.push(rule("]: <)?+8-HL[B"));rules.push(rule("[9#4-=*3,<"));rules.push(rule("S2\'5,3&>.AHYC"));
rules.push(rule("[=#4-;*1!FJ4><EjU~iq}mg^lc}"));rules.push(rule("S4\'<,9&=.AA16"));rules.push(rule("T<$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("V4%6$8(2$0"));rules.push(rule("R5\'7,0&?#;"));rules.push(rule("W?%1$<0-8$P08"));rules.push(rule("V>%3$9(1)JMT2>5AA161C@1\\T1787@I5^U8^RLY?LnWhkfyqUiip"));rules.push(rule("^6!1%2$>+7"));rules.push(rule("Y0\"<!4%3"));rules.push(rule("_7!3%7$>+7)V6"));rules.push(rule("T5$<(0\'7/5"));rules.push(rule("R;\'0,5&>"));
rules.push(rule("[9#5-:*3,<"));rules.push(rule("R3\'6,4&="));rules.push(rule("[3#0-?*3!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));rules.push(rule("S1\'0,6&=#;"));rules.push(rule("S:\'52/=\"<\"3"));rules.push(rule("]5 :)9+;-HE36"));rules.push(rule("]5 9)>+;-HL\\>0:FJ4><EC9YISA?P0<"));rules.push(rule("Y8\"?!6;+;-HL[B"));rules.push(rule("V1%=$<(0)JMSN6<"));rules.push(rule("U2$5(;\'7/5"));rules.push(rule("_6!3%4$?+7"));rules.push(rule("Q8&5 <)="));rules.push(rule("Z2#2-81,3(^??<EJXK"));
rules.push(rule("X?\"6!4%6*CIQO"));rules.push(rule("X9\"<!?%7*Ci\\mar`zxQkhx"));rules.push(rule("Z8#5-;*3,<"));rules.push(rule("T3$9(6\'0\"OZ6?4IY?86HE36"));rules.push(rule("X?\":!3%7*Ci\\mar`zxQkhx"));rules.push(rule("[<#5-=*1,<"));rules.push(rule("[2#4-=*6"));rules.push(rule("X9\"<!?%4"));rules.push(rule("W1%7$<(2)JD;9"));rules.push(rule("V7%4$>(1)JMSN"));rules.push(rule("U2$>(1\'7/5"));rules.push(rule("Y0\"??)9+8"));rules.push(rule("Z=#>-=*1!FC\\I"));rules.push(rule("^7!3%7$?"));
rules.push(rule("[9#7-:*3,<"));rules.push(rule("X:\":!?%4\'9"));rules.push(rule("^9!3%6$>+7)JD;9"));rules.push(rule("[:#7-?*3"));rules.push(rule("U2$?(7\'5/3(BH56"));rules.push(rule("Y1\";!1%6*CIQO>0"));rules.push(rule("Z;#4-<*6!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("[<#2-?*3"));rules.push(rule("Y1\"8!6%6\'9"));rules.push(rule("T<$8(7\'7/5"));rules.push(rule("W>%=$>(1"));rules.push(rule("R5\'0,5&?#;\'EC0<"));rules.push(rule("R;\'52/>\"<"));rules.push(rule("V>%1$<2-8"));
rules.push(rule("U7$9(7\'5/5"));rules.push(rule("Q0&= =)8(>"));rules.push(rule("S2\'5,7&8.AA0SNBQM8<2:^HAXI:V1Ci\\zkpuaiQkhx"));rules.push(rule("^;!4%4$<+7)JD;97@I=9>IAONK0Q:K@GBE?0:"));rules.push(rule("S4\'<,3&=#=\'EC0<"));rules.push(rule("^6!3%4$>+7)V6"));rules.push(rule("Y>\"6!5%1*CIQO>1"));rules.push(rule("S:\'5,5&8"));rules.push(rule("S;\'1,7&8"));rules.push(rule("Z3#73\'6,5"));rules.push(rule("YRJ|nih`*xho`ikumh.lhekP"));rules.push(rule("[fbtf4GKWI,[akbhcycg)Olnb"));
rules.push(rule("[PKtbggg!}bbfjbqoi&o`fpdU"));rules.push(rule("[fbtf4GKWI,[akbhcycg)Bpdm"));rules.push(rule("_TIujkih&vghklaxkk\'bkibhm|Y"));rules.push(rule("Rofvg<KEXN\'^kfdkj}af!]beah|k"));
