// OpenAero rulesYY-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####      Regles France 2015      Espoirs à Doret 2015  Olan 6.0  ###################
//#####      Regles France 2015      Version 2015_PN.1.05            ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####      Modifications mineures (commentaires) et connus 2014    ###################
//#####      Corrections, modifications espoirs 2015, connus 2015    ###################
//#####      Ajout de règles (déclenchés) d'inconnu Doret 2015.      ###################
//#####      Prise en compte du distingo entre rotation alternées    ###################
//#####      (,) et rotations même sens (;) dans les régles 2015.    ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2015 : Espoirs, Desavois, National2, Doret 

//##### (Une partie des) Regles specifiques à la France.

rules.push(rule("XSJ|nih`*husfmpr(oaai~X"));rules.push(rule("T`o`i#4$f!az)9t%+-&-()/j/&,a/yf(*%6/87+!%><\"\'9 * 4i$$/3(:+/5a{*s-`;*,//\'no\'8 *mfc\"dbahlno5kexnfcidba#r.99+h8"));rules.push(rule("[` kbq9338"));rules.push(rule("[fbtf4Bp`fok/bxuedtp)enm"));rules.push(rule("^UIujkih&fztmhz.fihjdcs^"));rules.push(rule("_d\"jj}7<43"));rules.push(rule("_b`un8Lgmja\"d{|afux%kaj"));rules.push(rule("_TIujkih&fztmhz.cniwoP"));rules.push(rule("Sh$icy5==?"));rules.push(rule("Ykm}jabb\'`g{450"));
rules.push(rule("V`jh? kjg93"));rules.push(rule("Wajh= kjg93"));rules.push(rule("Xnmc7*fld07"));rules.push(rule("Y{cbc*fld07"));rules.push(rule("Zy}om$iko5="));rules.push(rule("Qde|zvkbko kbq92"));rules.push(rule("Sahwggak#}b{`ky;2"));rules.push(rule("Qsg`b\"unuolr>;"));rules.push(rule("Uweaj.}kvsm|kns64"));rules.push(rule("]`a}b6Cxlh`l$grxcg}t+dfa"));rules.push(rule("[#Ktbggg!m~`nyv*ljo "));rules.push(rule("Uvl-;#h`t`fokk"));rules.push(rule("Qqgbe::5"));rules.push(rule("Rrfwlm5=>"));
rules.push(rule("[maib}mlf%|afi8:"));rules.push(rule("Zmivy)vtzb~`t6[8Q(X8)6\\T\"?S):"));rules.push(rule("Z~xtmykq,fmcj:+scgdlw\"wmbz}b"));rules.push(rule("[xtmykq,emv26"));rules.push(rule("Tvac.ZTKO5~ack1[QSu^"));rules.push(rule("Xdw\"T[LD0@jnqpd(mxjd+sxdjol$woa}{jjnk~"));rules.push(rule("Xkc`y*yj~Rgo}$?!V5R![o.V#5_\',Y0%4S&\'6%.<=]0X,]l\'R!\\:7>8[_\'_3,0Q.2\'s>T4Z-)9\"x3R>S)6"));rules.push(rule("Sq|hg,FcQnkZ>8&>)vmuWmb{=+}Q!=^"));rules.push(rule("Tvac.Gk]`dxQghy%7-tl}[cm|6.T+0X"));
rules.push(rule("Tsbt+Mf[cm|Sf`u+8*_iwhpknf,ocsnwdéh&jgpgslezj"));rules.push(rule("Wu~io Kbq[cm|S9=7+8*iwVenu2,&7\\\'>Wq]/2Y:}>W\"4Z=y<V*8T0~5S 5R1\""));rules.push(rule("_xg~&HkuYbep]6:<.2\'Yj~lrjfj\"`dxk}ién%fdkj}éa\"à!?>>°"));rules.push(rule("Sbehmv%hkiu~io~&>)Jm^i`zP3>"));rules.push(rule("W6%4$?(0)JP;9"));rules.push(rule("R:\'1,3&8.AhTdfyYkfv"));rules.push(rule("Q8&= =)?"));rules.push(rule("T1$>(2\'5\"OZ6?4IY?86HQ37"));rules.push(rule("V1%=$5(7)JP;;"));rules.push(rule("_6!6%7$?"));
rules.push(rule("Y1\";!?%7*Ci\\hhv^`c|"));rules.push(rule("Z;#7-?*1![\\GA"));rules.push(rule("Y>\"=!5%4"));rules.push(rule("S4\'<,5&=.AU14"));rules.push(rule("Q0&> ;)?%D_<0"));rules.push(rule("X?\"<!5%4*CT98?LnWmb{Xcjx"));rules.push(rule("_>!5%6$9&M[>1"));rules.push(rule("_6!6:+;#2.>"));rules.push(rule("S2\'6,3&?.AU141CT9:"));rules.push(rule("S2\'6,6&=.AU14"));rules.push(rule("U=$8(7\'0\"OgSocsTme"));rules.push(rule("W>%7$>(7"));rules.push(rule("U2$5(;\'5\"OZ6="));
rules.push(rule("R;\'5,2&>"));rules.push(rule("]5 ;)8+;-HQ359OZ6="));rules.push(rule("W6%7$;(2)JP;97@]=8"));rules.push(rule("[:#7->*3!F^4>"));rules.push(rule("Y>\"6!1%6*CT98?LS2?"));rules.push(rule("V?%4$9(1"));rules.push(rule("V1%7$<(2)JP;97@`Xji~Rnl{"));rules.push(rule("R0\'6,0&=#="));rules.push(rule("]8 =):+;-HQ359OZ6="));rules.push(rule("W?%0$;(2)Jm^i`zPodw"));rules.push(rule("Y0\"<!4%="));rules.push(rule("Z2#3-;*3!F^4<"));rules.push(rule("_8!4%6$>&M[>3"));rules.push(rule("X1\"<!4%3"));
rules.push(rule("U<$<(0\'<"));rules.push(rule("^6!1%4$<&M[>3:F^4=<EW0>"));rules.push(rule("T=$<(0\'2"));rules.push(rule("R:\'1,7&8.AU14"));rules.push(rule("T5$<(0\'0"));rules.push(rule("S:\'5,2&8"));rules.push(rule("R3\'6,0&?.AU141CT9:"));rules.push(rule("Q3&= >):(8"));rules.push(rule("S2\'5,2&="));rules.push(rule("T<$8(7\'5\"OgSocsTme"));rules.push(rule("_7!2%0$9&M[>3"));rules.push(rule("X0\";!4%6*CT98?LnWmb{Xcjx"));rules.push(rule("^?!6%4$<+7)IcyWmb{X<7:"));
rules.push(rule("U=$8(2\'7\"OZ6?4IdZkar\\akp"));rules.push(rule("T6$9(2\'5/3"));rules.push(rule("Q0&= =):"));rules.push(rule("Q6&> >)?%D_<22JP;;"));rules.push(rule("[<#5-=*3"));rules.push(rule("[3#2-8*3!F^4><EW0>"));rules.push(rule("]: ;):+;-HQ35"));rules.push(rule("S1\'7,0&=#="));rules.push(rule("Z3#2-:*0"));rules.push(rule("[2#2-:*6"));rules.push(rule("[<#5-=*6"));rules.push(rule("^?!5%6$<&M[>1"));rules.push(rule("^UIujkih&glwcwge}/ddkdx["));
rules.push(rule("^jjjd%7-cg)mpbn!.\"n}+-du-)0<!:8f! ,(*mf.j#%-:+)\"gk%83&.yf,/(:0/?i+$#-cid\"?(l%o+?nj?f(idb!:).o,f7&<-ci$/5-,no,:oe<"));rules.push(rule("Ri$icy5=9:"));rules.push(rule("Snfvg<N~oadn%nhubkkr(mbc"));rules.push(rule("U^Lgmja\"emoyhbv*dh`fjltU"));rules.push(rule("Un\'`g{4541"));rules.push(rule("Vkdwo0@qhjad(hk|f}jc~&beh"));rules.push(rule("V]Mwkcef)`grizaft+icotfT"));rules.push(rule("Xc!cn67:8"));rules.push(rule("^lntnccj+nh|?0:"));rules.push(rule("Zdha.dml<="));
rules.push(rule("^|`kg`x kjg93"));rules.push(rule("]kob2&hcc;2"));rules.push(rule("^hnj<(gdh>8"));rules.push(rule("_inj3(gdh>8"));rules.push(rule("Qrxe`\"jbk7<"));rules.push(rule("Rt{kv,ee`26"));rules.push(rule("Vr~wd}ip$icy5="));rules.push(rule("Yla~{~gldh+nh|?1"));rules.push(rule("[ilufome,zi~jf8;"));rules.push(rule("Y{cbc*y`zhgw46"));rules.push(rule("]ack&qeytfyacu5="));rules.push(rule("[xcgs$vgqmmz26"));rules.push(rule("[x}om$vgqmmz26"));rules.push(rule("Ydc|j:Mwkcef)`grizaft+dfa"));
rules.push(rule("W/Mwkcef)`grizaft+dfa/"));rules.push(rule("_|i\'6%kipbggge"));rules.push(rule("[{buoc934"));rules.push(rule("[{bume934"));rules.push(rule("V`gjkyomn)rnabz27"));rules.push(rule("Ubxbss$pwsf|a|:U7V#]2$0_]&=R!6"));rules.push(rule("Uqhsfw/oiak2\'}lxlafz$tdfx|j"));rules.push(rule("Sd{kwq%z|`s6[3Q(X80_]&=R!5"));rules.push(rule("[}iw$jclm1.}hd~dim)rgs|emnkn%gbhwhjvd(hk/635°"));rules.push(rule("]j|`r{(xbjolv?_:P \'5W+Q80^u7^/<%R!"));
rules.push(rule("[ybjolv/oiak2\'jdccb||\"df,xfujbo"));rules.push(rule("Rp|hg,[\\GA:yjfa<]RZq\\"));rules.push(rule("Vqc|\'^VJG9Dhoy|j\'json&u{mnmm,{anzpo`cm}"));rules.push(rule("]{cb&Vzdh\\fq]sai`2udif7XXWwx\\"));rules.push(rule("[|e.ZtkoWc{Pub`d0@jnqpd(kzkn%ex&baa!~~gckn%cor|aodfx.|ry%fl&ulvvhkmbj"));rules.push(rule("Zxxjf$JDB5~ack1-Vz]/2YYgNQ\'s/PcLP]/2Y^v!"));rules.push(rule("]zfv*ECI0vbz$fd(hémcbefbé-bbgw\"mm.}hd~dimz$ane|a|ébx"));
rules.push(rule("]naaq&sorr}vq<V5R!/P4\'4[84+]&$U>2=Xv<6*U**Z9!6R.+8*)58W=^/(1.}<U5V#;y"));rules.push(rule("[yxjf$R398,3/qnw~|rqz>>2"));rules.push(rule("Z}e._5:1(1._fx%nh&qfpcuac`/t~uoof|vg!à(=6?°\'xpx-jfz$tdzxglfg`y"));rules.push(rule("_}zkn(Gl~:9$?!~i|{vwy7:1"));rules.push(rule("[|e.Dez88,3/Wjv*ic#{kv`|eaa\'xpzhtjlqpd(à,7?°\'xpx-efz$tdzxglfg`y"));rules.push(rule("Qbgbx\"qnw~xvr}vq<V5R!/P4\'4[84+]&$U>1V,V#.X8):\\!,3/#8>T4Z-)9\"s3R>S)6"));
rules.push(rule("Wu~io Kbq=2tx,3/qnw~xvr}vq;4>"));rules.push(rule("Y~dw\"Jj}3=ss)9\"Qi.kb+weygw`kl!{y~jub`c#à)=2°!{y|/kj%|htw`gcmm,c`iddyc"));rules.push(rule("Tgecp.apulc{ux8T4Z-!_3,1Qr>7\"Y$%384+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("Zxxjf$Icy1<j`\'6%|htwmksuz435"));rules.push(rule("_xg~&Hku?3mk\"<(\\o|\'o`*iwhpknf,}zwnwchsql$à\"88°,}zu+ik-pf{pkbi`k/cnvihhghjvd"));rules.push(rule("Rafjt,fc~ztc8T4Z-8_33UP >[%^? >^4j9_1P T6912PZ-4v9_1\"&6{:5#0`8W=,0S=<R:x>T=Z-4~"));
rules.push(rule("Zxxjf$JQQ}f`r%7cis|wj;f("));rules.push(rule("[|e.GWRt{dazs+8*]gp)`g!{c|{nn%zbspzéa\"`x~è}/kj%|ooea"));
rules.push(rule("[Livy)ldo1P\'6W+;Q(1U*Y3<Qr>[%4V#]0>Y^/S>=R{:Y$<Z-?X,5t=R!5W+Q?251Y^/:p?S)9Y$8Z-R50\\t>R!6W+9Q(;X,3T\"U=2=XV#z1U*1]&W:R[%y8Q(7U*Y3;QR!{>Y$V40TX,0T\"U=4?Xv8Z-:X,3T\"r8[%^89[_\'_33UP ={<Y$?Z-R76\\T\"?s0W+>Q(1U*3}?P <[%4V#z4U*:]&W?=2<XV#z4U*1]&>R!\\96>Pz4U*1]&?R!\\:7>Pz4U*:]&:R!\\:7>Pz4U*Y20QR!3W+Q?5^u3^/0P <[%^;?[>X,9T\"6S)P79Pz;U*6]&W?<ZW+8q>_\'0^/S>:R[%y2Q(7U*32T\"?s?W+?Q(X87_]&W?=3Vy2Q(6U*Y3<QR!\\96Wq>_\'2^/S?:7ZW+;q>_\'1^/0P >{3Y$8Z-R15\\T\"U>5Vy2Q(X<2_]&:R!5\"y3Q(2R40\\T\""));
rules.push(rule("Winb\'cgnl97!neizunv*nimzmfésém.lhfho-hédhpkwm"));rules.push(rule("[hbhu$Lmsyx||:U<V#Zg\"X,Z;4SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("Qs}`k\"Jj}=?6Kfv\"<@c|~syv01?"));rules.push(rule("Tsbt+Nh|538Da}\'6%Zlu#ma\"sgxo{ndk*ninykqéd(da}nqjdygol$qtxi|fb~wo-à&4;4°"));rules.push(rule("_l`i}(_}26xppr5R7S)Wa!Q(X;3_]&$U>*3X#0\"22Z;]&1>4Y;Y$06"));rules.push(rule("Vt~io Kbq741]|::\'6Pz93r}vq;49"));
rules.push(rule("^yg~&Hku559Qr5=,3/Wjv*ic#{kv`|eaa\'hjg}ipél$qn}.;2°+hecrbgp\"r}|k}nnpxh&à#:22°"));rules.push(rule("S`fjt,Lc::vwy0X:U*^e#P T32XV#.X8):\\!1*><U<V#;32Z2]&1>"));rules.push(rule("Y{ybj*Fdr<>3Mk64(1J`3>t~u957"));rules.push(rule("Urbt+Nh|398Ha;2+8*]gp)`g!zcznsbjd-eldtmrém,}`rx%>8°&glwadfhoas+v}cq`awsm,à.>?;°"));rules.push(rule("Zkajl~)fdn~{cbx%7-HEJ?T00<5Bfs28=Nl{?O`p?8?R{1?6Kbq5:1Lc::"));rules.push(rule("W5%7$8(2$0"));rules.push(rule("Y0\"6!2%4"));
rules.push(rule("U2$5(6\'5/5(B\\560KX748GV82"));rules.push(rule("R5\'<,6&=#;\'EW0?=M[>1"));rules.push(rule("T3$?(0\'5\"ON6?4IY?8"));rules.push(rule("[>#5-8*0!F^4><EW0?=M[>1"));rules.push(rule("^6!1%1$>&Pyml^gyQ}nnk"));rules.push(rule("Z2#3-?*3!FJ4>"));rules.push(rule("Q6&4 9):(>-HQ359OZ6="));rules.push(rule("]< =):+9-HQ359Lit7?"));rules.push(rule("_8!5%4$9&M[>3:FJ4="));rules.push(rule("R;\'50/9\":"));rules.push(rule("R0\'5,0&=#="));rules.push(rule("X?\"<!6%4*C@98"));
rules.push(rule("^?!6%2$>&PYML:F_^ztcjy"));rules.push(rule("]: 7)9+>-HQ359OZ6<4IY?9"));rules.push(rule("S;\'2,5&=.Bfs<:xv8GV833BH54"));rules.push(rule("Q6&> <)8%D_<1"));rules.push(rule("^7!3%4$?"));rules.push(rule("W6%7$;(1)JP;97@]=9"));rules.push(rule("]5 :)9+; 5#GV83"));rules.push(rule("R;\'0,2&8"));rules.push(rule("Q0&= 9):%Gl~:9"));rules.push(rule("S1\'6,0&=#="));rules.push(rule("Q0&> 9):%D_<1"));rules.push(rule("T5$?(;\'6\"OZ6?"));rules.push(rule("T5$<(4\'5\"Lit7?"));
rules.push(rule("^;!5%4$>&M[>0"));rules.push(rule("[<#>-8*6!F^4><EW0?=M[>1"));rules.push(rule("^7!6;+8#4"));rules.push(rule("[3#2-8*0!F^4><EW0?=Nh|;1lc"));rules.push(rule("[:#4-:*6!Emv67"));rules.push(rule("Y8\"?!5%4\'?"));rules.push(rule("Q0&= 9)8%Y]OM"));rules.push(rule("T3$?(7\'5/3(BH56"));rules.push(rule("[<#>-8*3,:,@]=:>D_<12JP;;"));rules.push(rule("Y1\";!6%6*CT98"));rules.push(rule("[3#0-8*3!Emv67~u1CT9;?LG2?"));rules.push(rule("S:\'53/9\":\"?"));rules.push(rule("U4$<(4\'0\"RXE@"));
rules.push(rule("V7%7$<(2)JP;:"));rules.push(rule("X0\":!5%7*CT98?O`p5>kh"));rules.push(rule("Y1\"8!1%7*CT98?LS2>5AU16"));rules.push(rule("Z;#4-:*3!F^4="));rules.push(rule("W?%0$<(2)JP;:"));rules.push(rule("_7!2%4$9&M[>3:F^4="));rules.push(rule("_6!3%7$?"));rules.push(rule("V4%4$>(2$0"));rules.push(rule("Z3#?-;*0"));rules.push(rule("_8!5%6$?&MO>3"));rules.push(rule("^?!5%0$<&M[>0"));rules.push(rule("Q6&? >)8(>-HQ359OZ6<"));rules.push(rule("^9!?%7$<+1)JP;97@]=9>D_<0"));
rules.push(rule("U7$9(2\'5/3"));rules.push(rule("_:!5%4$<&Nh|;1lc"));rules.push(rule("V3%7$<(7)JP;97Cn25"));rules.push(rule("^6!3%7$<&M[>0"));rules.push(rule("W?%1$<2-8$LS2="));rules.push(rule("X9\"<!5%7*CT9;"));rules.push(rule("S4\'6,5&?.AA17"));rules.push(rule("S;\'1,2&?#;\'EW0<"));rules.push(rule("S;\'2,4&=.AU171CT9:"));rules.push(rule("V?%4$>(5"));rules.push(rule("]5 9)3+;-HE359OZ6<4IY?9"));rules.push(rule("R5\'7,0&="));rules.push(rule("W>%4$>(;"));rules.push(rule("_>!6%7$>+7)JP;9"));
rules.push(rule("[3#0-:*3!Emv67~u1CT9;?LS2?"));rules.push(rule("S:\'0,2&:"));rules.push(rule("Y0\"?!2%4"));rules.push(rule("U<$5(2\'5"));rules.push(rule("]: <)9+9 2#GV83"));rules.push(rule("W0%1$<(1$0\"OZ6?"));rules.push(rule("W?%0$?(7"));rules.push(rule("S;\'0,5&=.AU17"));rules.push(rule("]8 <)9+8 5#GV833B\\54"));rules.push(rule("R;\'5,3&>"));rules.push(rule("[<#4-;*3!FJ4>"));rules.push(rule("R7\'7,0&8.AU141CT9;?O`p5>kh"));rules.push(rule("]: 7)3+; 2#GV82"));rules.push(rule("X1\"?!3%7"));
rules.push(rule("U4$?(6\'6\"OZ6?4IY?8"));rules.push(rule("[3#3-<*3!FJ4><EW0?"));rules.push(rule("_>!5%7$>&M[>3:Emv67"));rules.push(rule("X1\"6!4%1"));rules.push(rule("X9\"?!6%4\'9"));rules.push(rule("]< =)<+;"));rules.push(rule("]5 :):+8-HQ359OZ6<"));rules.push(rule("[<#>-:*3,:,@]=:>D_<0"));rules.push(rule("Y1\";!2%1*CT98"));rules.push(rule("W0%=$9(7)JP;9"));rules.push(rule("[:#7-:*3,<"));rules.push(rule("_7!3%4$<&Nh|;1lc"));rules.push(rule("]5 :):2$<&Nh|;1}|5AU17"));
rules.push(rule("T=$9(7\'6"));rules.push(rule("Q6&> >)9(9-HQ359OZ6<"));rules.push(rule("[<#4-;*0!F^4>"));rules.push(rule("[2#?-:*6"));rules.push(rule("_7!2%6$?&MO>0"));rules.push(rule("S4\'0,3&=#="));rules.push(rule("S:\'5,3&8"));rules.push(rule("U<$<(0\'0"));rules.push(rule("T=$<(0\'6"));rules.push(rule("X?\"6!3%4\'?&M[>3"));rules.push(rule("]5 :)>+8-HQ359OZ6<"));rules.push(rule("[3#3-?*0!F^4>"));rules.push(rule("W0%6$?(2$6"));rules.push(rule("W?%0$:(2$6\"ON6?4IY?8"));
rules.push(rule("W?%1$>(1)JP;97@]=9"));rules.push(rule("[2#4-:*6"));rules.push(rule("]4 =)8+2"));rules.push(rule("[3#2-87,0(B\\560KX74"));rules.push(rule("[:#4-=*0!F^4="));rules.push(rule("S;\'1,9&=#=\'EC0<"));rules.push(rule("[:#7-?*6![\\GA<EVZxukfqv"));rules.push(rule("R:\'2,3&=.Bfs<:xv8GV833BH54"));rules.push(rule("W>%=$>(1"));rules.push(rule("^;!4%4$<&M[>3:F^4=<Fdr46gf"));rules.push(rule("[<#5-=*3,<"));rules.push(rule("[2#?-:*0"));rules.push(rule("]8 <)9+;-HQ369Lit7?cd"));
rules.push(rule("_8!4%6$?+7)JP;9"));rules.push(rule("S4\'6,3&8.AU141C@9;"));rules.push(rule("W0%6$>(2"));rules.push(rule("[3#2-=*0!F^4><Fdr46gf"));rules.push(rule("[3#0->*0!FJ4><EW0?=M[>1"));rules.push(rule("_7!2%1$>+7"));rules.push(rule("[3#3-?*6!F^4>"));rules.push(rule("S:\'5,0&=#="));rules.push(rule("U2$5(0\'0\"OZ6?"));rules.push(rule("]8 <):+9-HQ359OZ6<4IY?9"));rules.push(rule("_:!4%7$9&M[>0:Emv67oj"));rules.push(rule("_6!6;+9#4"));rules.push(rule("Q8&8 <)9"));
rules.push(rule("R:\'1,5&=.AA17"));rules.push(rule("T6$>(2\'5/3"));rules.push(rule("T<$9(0\'5\"Lit7?cd"));rules.push(rule("V?%=$?(1"));rules.push(rule("[2#4-:*4"));rules.push(rule("Z3#4-;*6"));rules.push(rule("^6!2%43#4#Dez88y~4IY?8"));rules.push(rule("^9!3%4$<"));rules.push(rule("S6\'6,0&>.AU141CT9;"));rules.push(rule("^?!5%1$9&Nh|;1"));rules.push(rule("X:\"<!1%4\'9"));rules.push(rule("X?\"=!6%7*CT98"));rules.push(rule("V.Mwkcef)jcuac`nk9%ibhm|[3("));
rules.push(rule("^jjjd%7-b1%66!hl%fqx+- &+$53-?%.\"l9(* fc=f,&(>:g3++-``.),/4$==&\'&e2!3.i$0$(ln\"5ale<3(id\",:).:9+ej&27j#%-:\")$gk%\" 7/>-\"-<|l( +64-(/=#%sx><q9"));rules.push(rule("Ydc|j:Mwkcef)jcuac`nk9%ibhm|"));rules.push(rule("Y!J|nih`*cgw`kl`d>.lhekR4*"));rules.push(rule("Rflim!5,ke\',7>*n$=*<!vz); &(* +j*7h{\")q\'d78-!1.`j/&\" ( &(\'-767$/l:!.og&+$#($`va*hl.;+8(*;##idba%>d`n:0!mfc)1\'!6,nog ejmfcidb3nlnouhe!mfcidb!:2.qy ejmm-.#.3<+%og+e!i47%6"));
rules.push(rule("[fbtf4Bp`fok/ijqcbhbe6\"bgb`z"));rules.push(rule("ZQKtbggg!fmzfhedf?&`fjltU"));rules.push(rule("[` kbq902="));rules.push(rule("]`a}b6Cxlh`l$l`|eaafg7*ljo"));rules.push(rule("_TIujkih&mhpknfmb=\'bkibhm|Y"));rules.push(rule("^e\"jj}7?43"));rules.push(rule("Qlg~k2Ayddnc#gevhgboc5+dfa"));rules.push(rule("QZN~oadn%dlrjfjcm:,bfey`W"));rules.push(rule("Ri$icy5>8:"));rules.push(rule("Xjm}jabb\'`g{451"));rules.push(rule("Tjoj+n`j?7"));rules.push(rule("V`jh8 kjg93"));
rules.push(rule("Wajh? kjg93"));rules.push(rule("Xnmc8*fld07"));rules.push(rule("Yomc7*fld07"));rules.push(rule("[mioe)ohf1?"));rules.push(rule("^fjtyjfa+n`j?0"));rules.push(rule("[xcgs$iko5="));rules.push(rule("]~~fi&hcc;2"));rules.push(rule("^x}h(gdh>8"));rules.push(rule("Rpfhndz!cfi64"));rules.push(rule("Vcfu~tjjga/lit3?"));rules.push(rule("Xjm}jabb\'cslev<9"));rules.push(rule("Vtdif tfyacu5="));rules.push(rule("Wtedz tfyacu5="));rules.push(rule("X{|ga*y`zhgw45"));
rules.push(rule("Vkdwo0@qhjad(bo{ndkka4#hhn"));rules.push(rule("T,Lgmja\"oixg`iji8-goe-"));rules.push(rule("[xk&>)efwibmjc"));rules.push(rule("Wwdvfg;19"));rules.push(rule("Xxc}ak67:"));rules.push(rule("Rdekcuabi\"wdldy;3"));rules.push(rule("[livy)tsgx3Q>W+Q<2^U*3]&>"));rules.push(rule("Usxbr.geod5,|`sjqcbh#apuaoocb+hecrbgpg!li.>?;°"));rules.push(rule("Qfzc{*yjfacq4Z0]&8R!\\>(2PZ-"));rules.push(rule("]acknw\'cgnl9vnfbknr+`d-pj{eed(hk/4=5°"));rules.push(rule("[yxjf$WRHF1|`kg?TVXpT"));
rules.push(rule("_xg~&VZDH>Ometzi.nqnf*{tjehg!}bg~rnhocr"));rules.push(rule("Wu~io Us`j]n}S|fbe8xbjo3ZY_{vS"));rules.push(rule("Vqc|\'^vjg[mtW~gji6Ccjsql$qd}`k/h~%k{c`)rphd`k/rel{xcnljv!{y|/kj%|htw`gcmm"));rules.push(rule("Vt~io HPO9pnd`4\'[|^&6[XoB_("));rules.push(rule("Xdw\"IXC7}gp)`g!léobjihmé*hh#;aod(é`écji%nlhp)qld(~a{flec&`firn{éi"));rules.push(rule("Wddk| pf{psuz3Q>W+\"V7.0Y~08%R!/P4?;[84+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("Vt~io P214\"<(zk}szqx~<?:"));
rules.push(rule("Tsbt+U8<2!5,^nt+ao-tl}evhgb.|r{`xdcv{a\"à!94>°/t~w*acp)rgs|emnknv"));rules.push(rule("Y{ybj*Fdr46#4$tdzx{ux?6?"));rules.push(rule("Vqc|\'@g{04\"<(\\o|\'o`*iwhpknf,}zwnwchsql$à\"88°,}zu+fo~&ulvvhkmbjt"));rules.push(rule("Zibhu$rgs|y~~syv7S?_\',Y0%5Ss6;,V#.X82_(T\"&T6&=W$&>) 1:V5R!\'6%x6X3U*?{"));rules.push(rule("Qs}`k\"Jj}3=ss)9\"wm~zzwzqx~<?;"));rules.push(rule("Sta}/Lit7?r{%7-Vbz$fd(~a{flec&p|tgsai{}b+à%3=°&p|v\"mi,xjuliljf)imo|m`{b"));
rules.push(rule("]naaq&sorgfuvs{1P6[%-Q<+:Tx31!P \'2w4:$Z-!_3,0Q\'/:+!96X:U*\"<(~5Q7W+7w"));rules.push(rule("Tvac.Dez88ha/:+sorgfuvs{62="));rules.push(rule("Y~dw\"Jj}3=bl)9\"Qi.kb+weygw`kl!{y~jub`c#à)=2°!{y|/kj%|htw`gcmm,jjth`digm}a"));rules.push(rule("[hbhu$jmq}f2Y2Y$<]2;Y^/9P T2&=W0h8W=^/S=<;?VY$0t8W=,)1p??.6c1S?-8_33U1}4Y;Y$0|"));rules.push(rule("Tvac.GWRt{dazs+8dbvvzl8o,"));rules.push(rule("Urbt+MZTwr`c{{\'6%Zlu#ma\"rg~zfb+uexupél$cqzè.cf+sxdjol"));
rules.push(rule("S`fjt,@c|~syv7S?_\'Xf*T\"U<?VY$%]2$<_(5(?4Y2Y$068W4^/5<"));rules.push(rule("Xzybj*Fdr:43Akp!5Da}vwy7::"));rules.push(rule("[|e.Dez6:<F`u+8*]gp)`g!zcznsbjd-eldtmrém,f`ubecrbea\"r}|k}nnpxh&à#>62°"));rules.push(rule("Wddk| Ss=1suz3Q>W+Vi-_\'_06UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("]{cb&Hku379Qr5=,3Zw?0{ytp385"));rules.push(rule("Vqc|\'@g{<02Tx8;/:+Uk~&gl$pn|mzfhe%ibksfwég!{c{|\'?0°*`im}elu({byloxtf)à$758°"));
rules.push(rule("Zibhu$@m5=}z}t6[3Q(_m/^/S87R[%-Q<+;T-?%97P6[%8:6X3U*?1"));rules.push(rule("Qs}`k\"Jj};56Gf07!5Ha;2zqx~<?:"));rules.push(rule("[|e.Dez00<J`3>%7-Vbz$fd(~a{flec&`firn{éi.|h~v*93°#maqbmbjni%yxvf{mgtzi.à/635°"));
rules.push(rule("ZMivy)ldo1P\'6W+;Q(1U*Y3<Qr>[%4V#]0>Y^/S>=R{:Y$<Z-?X,5t=R!5W+Q<55>Y^/:p?S)9Y$V47<<_]&W?=Zw7V#7_\'7^/t>R!5W+Q?+5TX,}:P <[%^893^U*~3T\":S)P7\'5[_\'x7]&W<<ZW+;Q(X;76\\t9R!4W+8Q(>X,3T\"U>5VY$V40Tx5]&8R!6W+Q?5^u3^/:P T4?XV#7>X,5T\"<S)P48Pz4U*1]&=R!{<Y$5Z-R504?5SS)w2V#5_\'6^/S>=;Zw2V#5_\'7^/S=<;Zw2V#>_\'2^/S=<;Zw2V#]01Y^/<P T58Xv:Z-<X,Z98SS)w2V#3_\'_06UP ={<Y$5Z-!7~0;%R!\\:79Pz4U*:]&=U?691WQ(>X,9T\"&7{:3#Q(X;7_}?P 7[%4?Q(X866\\t4R!3W+Q<5^U*0}0P ;[%^89[_\'x:]&8R!/:^:>1:Tx0Z8?9R.W+Q<4^u<^/?P >[%^;?[1X,4T\"U>4VY$V71=Y~9T\";S)P7>PZ-R61\\t4R!2W+?Q(X861\\t4R!2W+<Q(X;7_}0P 9[%^990;TX,0t4R!2W+Q:>^U*3}0P :[%-=q7: X,3!p7S):^:?[_\'"));
rules.push(rule("Zdha.geod5:.inlpxhu#jklrahé|éjt+fe`kf)jée`|exjt"));rules.push(rule("Tefait$`ggzybjt+8*CUE2R3987Cn<7:Eiq2Icy=8>Zw?01@g{8<2Eg8;"));rules.push(rule("R0\'6,2&=#;"));rules.push(rule("[3#2-87,0(B\\560KX74"));rules.push(rule("^7!6%1$<+1"));rules.push(rule("Z=#>-?*3,:,@]=8"));rules.push(rule("S2\'5,7&?.\\wbkUbs\\{mgo"));rules.push(rule("R3\'6,0&=.Bfs<:"));rules.push(rule("Q9&8 >):%Gl~:9`m"));rules.push(rule("S1\'6,5&=#;"));rules.push(rule("X0\":!3%7*@g{04fn"));
rules.push(rule("^9!5%1$>&MO>0"));rules.push(rule("R5\'7,3&=#<"));rules.push(rule("V4%6$<(2$6"));rules.push(rule("T6$<(2\'5/3"));rules.push(rule("]4 6)8+>"));rules.push(rule("Z=#>-87,2%8.AU16"));rules.push(rule("T5$?(6\'6\"OZ6<4Jj}3="));rules.push(rule("[3#2-8=,3(B\\55"));rules.push(rule("[:#4->*3"));rules.push(rule("[9#2-<*3,<"));rules.push(rule("_8!5%7$9&M[>3:FJ4="));rules.push(rule("T3$>(0\'5/3"));rules.push(rule("[3#3-:*1,<,@]=:"));rules.push(rule("[:#4-=*0!Emv67"));
rules.push(rule("X:\"?!4%4\'9"));rules.push(rule("[>#5-8*1!F^4><EW0>=Nh|;1}|"));rules.push(rule("]: =)8+; 4#GB80"));rules.push(rule("V7%4$;(7)WRHF7@\\W~vbbsw"));rules.push(rule("Q9&9 =)9%D_<1"));rules.push(rule("T<$;(0\'5\"Lit7?r{>D_<12JP;;"));rules.push(rule("T3$8(7\'5/3(B\\560KX74"));rules.push(rule("U=$;(4\'6\"ON6?4Jj}3=bl"));rules.push(rule("[3#0-1*3!FJ4><EW0?=Nh|;1lc"));rules.push(rule("W?%3$9(0)WrhfSazXyloc"));rules.push(rule("[3#3-8*3!F^4="));rules.push(rule("^7!5%7$9"));
rules.push(rule("W0%0$<(2$6\"OZ6?4IY?86HQ37"));rules.push(rule("_=!3%3$<+7"));rules.push(rule("Y0\"6!2%4"));rules.push(rule("]4 >)8+; >"));rules.push(rule("W>%48#7-=)4"));rules.push(rule("]8 =):+>-Kbq=2tx"));rules.push(rule("T5$<(5\'5"));rules.push(rule("Z8#5-=*3,<"));rules.push(rule("S4\'6,0&=.AA14"));rules.push(rule("_7!3%7$<&M[>0"));rules.push(rule("V?%4;#7-=):"));rules.push(rule("S2\'6,6&>.Bfs<:"));rules.push(rule("X?\"6!6>+; 4"));rules.push(rule("R;\'6,2&8#7"));
rules.push(rule("^9!5%7$>&M[>3:FJ4="));rules.push(rule("T<$8(6\'7/5(B\\56"));rules.push(rule("X?\"6!2%4\'?&M[>1"));rules.push(rule("[3#3-83,0(B\\550Hku?3|t"));rules.push(rule("V>%0$;(1$0\"OZ6?"));rules.push(rule("_8!2%2$<+1)JP;9"));rules.push(rule("Y>\"6!6;+9 2#GV833B\\54"));rules.push(rule("U4$?(;\'6\"Lit7?"));rules.push(rule("R3\'6,0&>.AU17"));rules.push(rule("[<#>-8*3,:,@]=:>D_<12JP;;"));rules.push(rule("T3$5(6\'7/5(B\\560KX748GV82"));rules.push(rule("]5 :):<$?&M[>0:Emv67~u"));
rules.push(rule("X0\";!3%6\'9"));rules.push(rule("U=$9(0\'5\"Lit7?cd"));rules.push(rule("Q4&> >)9%D_<12Icy1<{"));rules.push(rule("]5 9):+;-Kbq=2tx7@I=8"));rules.push(rule("Q8&8 >)9"));rules.push(rule("[2#?-;*6"));rules.push(rule("[2#7-;*3,<"));rules.push(rule("[2#?-:*0"));rules.push(rule("^<!4%0$<+7"));rules.push(rule("T5$?(2\'7\"Lit7?"));rules.push(rule("_6!6;+8#4"));rules.push(rule("Q8&=>!4%7"));rules.push(rule("Z=#>-:*3,:,@]=:>D_<0"));rules.push(rule("X?\"<!5%7*CT98"));
rules.push(rule("_:!4%7$<&M[>0"));rules.push(rule("[<#>-0*1,<,@]=:>D_<12JP;;"));rules.push(rule("^?!6%2$?&Nh|;1"));rules.push(rule("X?\"6!5%4\'?&M[>3:F^4="));rules.push(rule("^9!?%4?#5.=$LS2="));rules.push(rule("]5 9)>+;-HE359Lit7?cd"));rules.push(rule("R5\'<,0&?#;\'EW0<"));rules.push(rule("Y0\"6!4%4\'9"));rules.push(rule("^?!5%3$<&M[>0"));rules.push(rule("_>!4%7$<"));rules.push(rule("Z2#3-:*3,:,@I=9"));rules.push(rule("Y8\"<!3%4*CT9;"));rules.push(rule("Z2#2-83,3(B\\55"));
rules.push(rule("W0%7$?(2)JD;9"));rules.push(rule("U4$<(0\'5/5"));rules.push(rule("W2%6$<(1)JP;97@]=9>D_<0"));rules.push(rule("]? =)=+; 2"));rules.push(rule("R3\'5,0&=#;"));rules.push(rule("W0%=$9(2$0\"OZ6?"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("U=$8(6\'5\"ON6?4IY?8"));rules.push(rule("U<$9(0\'6/9"));
rules.push(rule("[<#>->*3,:,@]=8"));rules.push(rule("[3#0-=*3!Emv67~u1CT9;?LG2?"));rules.push(rule("[<#5-8*1,<,@]=:>D_<1"));rules.push(rule("Z=#5-:*1,<,@]=:"));rules.push(rule("]5 :):+8-HE36"));rules.push(rule("[3#3-=*3,:,@I=9"));rules.push(rule("R7\'7,3&8.AU17"));rules.push(rule("T3$?(2\'6\"OZ6?"));rules.push(rule("Y8\"<!4%1*@g{04"));rules.push(rule("[3#0-?*0!F^4><EW0?"));rules.push(rule("U<$5(2\'5"));rules.push(rule("[<#>-80,2%8.AU17"));rules.push(rule("V1%=$<2-8)0"));
rules.push(rule("Z3#?-;*0"));rules.push(rule("X1\"6!5%4\'?"));rules.push(rule("T<$9(7\'5\"OZ6<"));rules.push(rule("T<$9(1\'6\"Lit7?cd"));rules.push(rule("Q3&8 7):(>"));rules.push(rule("[<#4-8*6!F^4><EC0?"));rules.push(rule("^9!?%=$<+7)JP;;"));rules.push(rule("_7!2%2$<+1)JD;97@]=9"));rules.push(rule("W6%4$:(2"));rules.push(rule("T1$>(2\'5\"OZ6?4Jj}3=ss"));rules.push(rule("X9\"?!0%1*^vjg[mtW~gji"));rules.push(rule("W?%1$<(1)JP;:7Cn25nb"));rules.push(rule("]: 7):7$>+7)JP;97@]=9"));
rules.push(rule("U7$?(2\'5/3"));rules.push(rule("R7\'6,0&="));rules.push(rule("_8!?%4;#7.;"));rules.push(rule("[<#>-85,2%8.AU141CT9:"));rules.push(rule("X0\":!6?+;-HQ35"));rules.push(rule("Z=#2-8*3"));rules.push(rule("Q6&4 9)8(>-HQ359OZ6="));rules.push(rule("Y1\":!6>+;-HQ36"));rules.push(rule("Z=#>-0*3,:"));rules.push(rule("_7!2%7$<&MO>0"));rules.push(rule("Y8\"?!0%6*^VJG?LRXy}gh~q"));rules.push(rule("Q9&9 >)8(>-HQ35"));rules.push(rule("_7!1%6$>&Pyml^gyQ}nnk"));
rules.push(rule("W6%7$>(2)Icy1<"));rules.push(rule("R5\'<,0:\"?\"5"));rules.push(rule("S4\'<,6&?#;\'EW0<=M[>1"));rules.push(rule("_8!5%1$<+1)JD;9"));rules.push(rule("T=$9(7\'6"));rules.push(rule("_6!6%0$<+1"));rules.push(rule("R;\'0,3&>"));rules.push(rule("V1%6$9(2$0"));rules.push(rule("Z=#>-82,0%8"));rules.push(rule("_8!4%4$<+1"));rules.push(rule("T1$>(2\'0\"OZ6?4IY?8"));rules.push(rule("V1%6$?(7)JP;:"));rules.push(rule("S:\'52/0\"<"));rules.push(rule("S4\'1,3&=#=\'EW0<=M[>1"));
rules.push(rule("X=\"=!5%7\'>&M[>0:F^4<"));rules.push(rule("[3#3-1*3,:,@I=:"));rules.push(rule("T<$8(4\'7"));rules.push(rule("Y;\"<!2%4\'9"));rules.push(rule("Y<\"<!6%6*CT9;"));rules.push(rule("^9!3%7$<+1"));rules.push(rule("S2\'5,3&=#="));rules.push(rule("X9\"<!5%7\'>&Nh|;1"));rules.push(rule("V>%0$8(1)JP;97@]=9"));rules.push(rule("R;\'52/<\"<"));rules.push(rule("Y8\"?!5%6\'9&M[>3"));rules.push(rule("]< =)3+;"));rules.push(rule("[:#4-<*3!F^4="));rules.push(rule("W5%1$<(2$6"));
rules.push(rule("V7%7$;(1)JP;:7Cn25"));rules.push(rule("Q0&? ;):"));rules.push(rule("[9#2->*3,<"));rules.push(rule("S4\'0,0&>#;\'EW0<"));rules.push(rule("T3$5(1\'7/5(B\\56"));rules.push(rule("Z=#4-8*1!F^4><EW0?"));rules.push(rule("[2#7-8*3,:"));rules.push(rule("W6%7$>(1)JP;:"));rules.push(rule("S;\'0,2&>.AU17"));rules.push(rule("S;\'1,7&=.AA14"));rules.push(rule("T5$?(1\'5\"OZ6<"));rules.push(rule("[:#4-=*6!Emv67"));rules.push(rule("[<#4-:*1!FJ4="));rules.push(rule("W?%1$?6-;"));
rules.push(rule("V1%=$>(0$0\"OZ6?"));rules.push(rule("]: 7):5$<+1"));rules.push(rule("T3$5(2:*3,:"));rules.push(rule("^6!2%7$>+7"));rules.push(rule("U=$;(1\'5\"Lit7?r{>DK<0"));rules.push(rule("[3#0-?*3!FJ4><EW0>"));rules.push(rule("V>%0$5(0"));rules.push(rule("Z3#>-=*3,:"));rules.push(rule("V]Mwkcef)efwibmjc+fechvT"));rules.push(rule("Xec|j:HL\\L&bmrcokij/lej}c"));rules.push(rule("XSJ|nih`*lbuhjadl,bfey`W"));rules.push(rule("Ydc|j:HL\\L&bmrcokij/ay`o"));
rules.push(rule("[PKtbggg!ihxnih`n-omjklo}Q"));rules.push(rule("Ri$icyxi|inl8>8"));rules.push(rule("Tiec>JMT@(mjyfefoi&vgolnbl`sc"));rules.push(rule("[#Ktbggg!lc|js+fechvV5+"));rules.push(rule("]ikbh+8* owhdb-:8%ogke*>2k.7kg/+pq\':54-`ak,b-<+)&4&;* 4&))kr/e|1bc!mf#$6\'!#\'=eh:0\' +.$)|!12.q*&(zo($.(:*hlno9+e!ne+8-d*hlnog+ej&*7.(0&/n !),\">#&ci/3-:j|l4\'6>"));rules.push(rule("_b`un8Lgmja\"eg~k{\'hjdcs"));rules.push(rule("_\'Iujkih&gfvgu(oaai~Z8$"));
rules.push(rule("[ohkl)9\"db, (+8qk<!$)mdc&\"<;),.jmf#=:\"v=`\')?=$#(-.#+-0\'.<9+ejm1pimiahl<;gke\'mf#idb,$>o;+8.jm&+$7.0;%.ogk.kn.1 2d->!nogkejmfc),/7$=8&\'kejm+0ckk2%!#q\'8;*s+.=l0hn\")/+?=m!`"));rules.push(rule("Snfvg<N~oadn%nbtf}$anfb{"));rules.push(rule("QZN~oadn%nbtf}$anfb{R"));rules.push(rule("Uue~ji402"));rules.push(rule("Vvdvda;79"));rules.push(rule("_ichjqcca.ykko|1>"));rules.push(rule("Yb!cn66?="));rules.push(rule("^lntnccj+n`j?8"));rules.push(rule("_mntnccj+nh|?8"));
rules.push(rule("_nckdr7S]2$=_"));rules.push(rule("YRJ|nih`*iiqlp\"man|jZ"));rules.push(rule("Twl-;#|jnheezjc"));rules.push(rule("^~`tgo796"));rules.push(rule("_`tei796"));rules.push(rule("Yo`ansbkm vl`jv<8"));rules.push(rule("Sh$icy5?;?"));rules.push(rule("Xjm}jabb\'`g{4="));rules.push(rule("Ykm}jabb\'`om4="));rules.push(rule("SD{kwq%z{udq74Z-!_33<47R{:5#Q(X82_]&"));rules.push(rule("Z|xvqfp/oiak2udqkyolgw\"wm~zfdjio~&nfjv`fxk|"));rules.push(rule("[}xvqfp/lab3="));
rules.push(rule("Qcikinl(xhvfhp?0"));rules.push(rule("^|`kg(xhvfhp?0"));rules.push(rule("_|af{(xhvfhp?0"));rules.push(rule("Qrxe`\"unuolr>8"));rules.push(rule("Vayj}+qfhndz1P=[%-8Q(X:)4\\t?R!\\9(?Pz7U*Y3%4S&[%"));rules.push(rule("Uweajf{)l`ei3[hekols{)al!~e|n`n)*kgn`hnd(> =)8%à*?(1\'2\"n},<!4%7*à-4-:*7!gy.=)?+8-à&1\'0,9"));rules.push(rule("Qgia?\"jbk7<"));rules.push(rule("Tveajf{)ohf1?"));rules.push(rule("Sehi7,ee`26"));rules.push(rule("Tbk`0.dml<9"));rules.push(rule("Uck`1.dml<9"));
rules.push(rule("V`jh2 kjg93"));rules.push(rule("Wt{ld kjg93"));rules.push(rule("Y``nw&hcc;1"));rules.push(rule("Ze~hby)ohf1<"));rules.push(rule("^awdvcyc.dml<9"));rules.push(rule("]lbch|8TV7.0Y"));rules.push(rule("YRJ|nih`*iiqlp\"hfoaai~X"));rules.push(rule("[{buoc961"));rules.push(rule("[{bume961"));rules.push(rule("V`gjkyomn)rnabz27"));rules.push(rule("_d\"jj}7>33"));rules.push(rule("Rqger,emv22"));rules.push(rule("Tmycgs$iko5>"));rules.push(rule("Ujycgs$iko5>"));
rules.push(rule("Zmivy)trfm~2Y2Y$%?84+]&W?9ZW+"));rules.push(rule("Usycgs$jclm1jélknkieé&ulvvhkmb/jdk~lhw"));rules.push(rule("X~`nw&hcc;2"));rules.push(rule("Y`nw&hku;1"));rules.push(rule("Wddk| om}apeax3Q\\;<WQ(>G"));rules.push(rule("[yxjf$Mlum~jfsn%7-om}apeax4A"));rules.push(rule("[|e.@jvdzhg{b+8*Kod|vg!li.mfx`*dhwlvfh|i"));
rules.push(rule("Tgecp.akpr|c~2Y2Y$%70x31!P T43X7<=]0X,3T\"=S)?%7-48W=^/:P <[%3*0&02Z;]&>R!4W+2-;#=?\\8T\":S)8Y$%]2$<_((1.+60[3Q(;U*1]&=.2\'9>T4Z-1X,2T\"</:+11S?_\'<^/;P <\'6%<6X:U*:]&?R!3+8*5=]0X,<z7P?[%8p"));rules.push(rule("Qs}`k\"Odw;=uwft\"<(da}tjz7:28"));rules.push(rule("Sta}/Ig~??tjz-;#|j\"litgbrf%nh&29$csziz|\'nv~-gv}kph{é,jnix%fhu#{kv`|eaat+ao~&o`cld{,j}hbqo~&kfvk{gbznknv"));
rules.push(rule("Rua}]df!F`u:5yyis)9\"`(aownfpg-ie)52!{xat+dxh&behmvmh.`i+v~gjnlv!`c|f}dk~lj#emld{,|`kgv"));rules.push(rule("Xkc`y*yjfaYQ=9\\8T\":S):Y$?;B2Z;]&=R!6W+Q<+7T9C:V5R!/P489>^ X,<,=5Q>W+\"4z29-^/ W8\">Vy;=/>O?\\8T\"&6{:5#0`8W=^/9W?=Z6v1S6_\'9x"));rules.push(rule("_}zkn(X9&>)vmmdS\\;=Uv*%]]H~_}T{U#<V,"));rules.push(rule("Z}e.[0\"<(|o|\'o`*iéeoljaié(c{/wjv*ncw}a\"sgxo{ndk*igmz$n`(n|nihmo-klgpco|i.nqnf*xhf)rphd`k/cjky-jb)fp`fofj\'o`yncmmelum\""));
rules.push(rule("Xkc`y*yjfaYQ?9\\8T\"??[%=V#4>Q?\\8T\"&T6912P/_\'9&03R7S)#<v<6*U**Z>!7R{:5#0@8W=^/ 5r>7\"8l6X:U*3Z9>S2t0[:Q(>s"));rules.push(rule("Qs}`k\"U=%7-tleh]S>6V"));rules.push(rule("Wpc|\'_0#4$ad(hémcbefbé-cp}$ko|i|kn+*^gvo$qtz,bjt+ccjsqlw\"6&> =):)*:(1\'0,3$,6!2%6$>*#1*7/<\":#\'3+<#4-=$gu(4 9)?+9#"));rules.push(rule("]{cb&SNBQM8<2!5,j`pet~u957"));rules.push(rule("_xg~&SNBQM8<2!5,{a\'fdrdkvd$fd(=6?°\'o`*iwhpknf,k|s+uokjz*"));rules.push(rule("_}zkn(\\IITG651(1.kh|k{ytp386"));
rules.push(rule("Rua}/WLCYA5<5*0&vg$o`peczj+ao-449°$fd(~a{flec&fzp\"qm~cft%"));rules.push(rule("Qs}`k\"QOJ]C7P)9\"eg{`|sdu014"));rules.push(rule("]zfv*]AEZH2Z$?!xm}/cn%llef}pg!xi|bnx`$"));rules.push(rule("Tvac.[52!5,|`kg?T%._~_.:UWhIZ\"yQk@^u,YgNQU#<VY}$/#R5050Q"));rules.push(rule("Sta}/S9<.2\'{dy-bf)vmuixg`i+akcu#ee\"czm`lon%nhu`ljf`fxk/f}`i-sm)`éammbmgé\'odd~&oh$`sibmgb+hecrbgpg/"));
rules.push(rule("Wddk| tleh]S9=3Q>W+;Q(2U*Y0:Q3N<U<V#.X8669U%R!:/41S?_\',;}9<\'S)#^< ?^u52(5J5Q>W+\"4z29-?g3R7S):^;?[>z?\\1T\"3u<"));rules.push(rule("Y{ybj*Y4;-;#{knmW^?>=#[\"%ZtR(9\\SM?=33cLP/R5050jHR{#^K<471bD\\S 5R[|,#-]2;0:\\!p&Q\\UKP-#R5050Q\'s/U^Tw[()_dGU%"));rules.push(rule("Y~dw\"U:4*0&`lpvd(oabebkkdulg$fd(~a{flec&nfjv`fxk/b%ybkn`pcmm,k|s+ldycqmmvd&"));rules.push(rule("^m`i}(xbjoVV355R7S):Y$8Z-R502U1O4Y2Y$%]2;0:\\!P 2#:>T4Z-!=~08%R!/P3\'4[84+<N7P6[%-3q73 9d:V5R!6P48P;p2Z2]&1t"));
rules.push(rule("Rp|hg,Z=:/:+weaj\\[56;VWRx+0X!-.XW~_} PyT+0XVz/*),Y_IvSs/WrQ!=^ -"));rules.push(rule("]zfv*Y4>-;#javum,|`sjqcbh#maqbmbjni`*huw)mlum~jfsn%oc&s{aqdfok/c,pdh&qfpcuac`/f~%ybknlp,"));rules.push(rule("Ufecp.{knmW^?::U<V#7_\'1^/S=#=Z6D1S?_\',Y0:86R.W+7U=]0X,)1p??.W+\"V0.0Y~08%3I<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q"));rules.push(rule("Rp|hg,Z=;/:+weaj9z_.:UWhI_V"));rules.push(rule("[|e.[57!5,~nt+ao-bé`ealb`é,az\'h`~yc#{kv`|eaa\'juxè~&vga\"wzebcb%"));
rules.push(rule("Zibhu$`msmxQkhx8T4Z-8X,0T\"U:*3X7{=]0X,5T\"?S)P1\'5[>?\\8T\"6S):Y$V4.1Y?w3R7S)P48PZ-<X,Z<!6R:e>T4Z-R0:\\T\";S)P6\'5[>g?\\8T\"&6{:5#Q(+<x31!P 2i0[3Q(+R5050Q\'S)6w1S?_\',;}9<\'2a0[3Q(2R50\\55Q7W+7w"));rules.push(rule("[yxjf$Jm^li~nuZnbu#4$fnzizPcdv0Sp"));rules.push(rule("Tsbt+Mf[fdxm|{Xojy-;#yeq!li.kéwjw~-blz$cwmo.lbqo-tl}evhgb.ybyqcngol*"));rules.push(rule("^|zkn(DbYpfvvhmSj`t+8*iiqlp]eg4a#"));
rules.push(rule("Urbt+Mf[qnzxgjXojy-;#yeq!li.|hyqch&gfw\"`~im/dnq~h&qfpcuac`/qnw~debea,"));rules.push(rule("Ufecp.jhklj}z}t6[3Q(+R5/8Up??.W+Q<45>Y^/ W?\"?V,*0&\';?\\8T\".2\'y>T=Z-4~"));rules.push(rule("^m`i}(iaonkwvnx1P6[%-;q?84+]&W?=1<X7<=]0X,3T\"U>5VY$9&>)69_1P =[%^;?[_\'2\"<(?5Q>W+8Q(X86_]&4.2\'?>T4Z-=X,Z9>SS)#^; >^ $?!,=5Q>W+2Q(X86_]&=.2\'9>T4Z-1X,Z9>SS)9%7-28W=^/0P T69XV#5#4$4:V5R!?W+Q<4^U*6!5,64Y2Y$0t8W4^/5v"));
rules.push(rule("Rafjt,}|{ux8T4Z-!_3,1Qr>7\"Y$V75TX,)S=#7Z\"%7-\"12Z;]&,3/u0[:Q(>s"));rules.push(rule("Rafjt,}|}{h{8T4Z-!5~8t=>&[%^;;[>8?\\8T\"<S):Y$9&>)69_1P =[%4V#0#4$1:V5R!5W+;Q(;)9\"53R7S)?Y$<Z-!_3,0Q\'/:+!;6X:U*:]&=R!6+8*?=]0X,9T\"?S)9%7-28W=^/0P >[%6*0&52Z;]&4R!6W+>-;#1?\\8T\"3}<U5V#;y"));rules.push(rule("Xkc`y*olkjssxppr5R7S)#^; ?^u52(T\"U=0VY$%]2$<_((1.+50[3Q(#4$p:V<R!:q"));
rules.push(rule("Rafjt,leohr{v~bv>W=^/9P =::>T4Z-!=~08%R!\\92W048W=^/:P =[%1*0&12Z;]&>R!5W+<-;#:?\\8T\"<S)9Y$5&>)09_1P ;[%7V#.X8):\\!,3/#:>T4Z-1X,3T\"?/:+71S?_\'<^/:P =\'6%>6X:U*:]&>R!4+8*;=]0X,9T\"<S)?%7->8W=^/5~5Q7W+7w"));rules.push(rule("Zibhu$`mvf}z}t6[3Q(+R5/8Up??.W+\"8z29-^/ W?\"?V,*0&\':?\\8T\".2\'y>T=Z-4~"));
rules.push(rule("[hbhu$`mvfz`w6[3Q(+8x;}9<\'S)#0v<6*459_1P =[%0V#2#4$0:V5R!5W+?Q(5)9\"23R7S)9Y$8Z-1$?!<7P6[%1V#3_\',Y0%4S&\'6%.<=]0X,9T\";S):%7-48W=^/0P :[%7*0&02Z;]&4R!2W+9-;#??\\8T\"6S)>Y$9&>)<9_1P \'>w4:$Z-)9\"g3R7S)6w1S6_\'9x"));rules.push(rule("^|zkn(\\XV7<4\"<(y~~syv010"));rules.push(rule("Z}e._QR5=<.2\'~k*`g{`iwl(hk/3>5°*huw)tgsee}/t~w*acp)vmuixg`ix%karf{jégr(zk}sbfkacp)imo|m`{bx"));rules.push(rule("Y~dwPbe(\\XV7<4\"<(m.bfslgxk#fb\"5=<°.nun%kajl~af!gb.ybyqcngo)qr!g|~`tbqo-tlehq"));
rules.push(rule("Y{ybj*OLKJSS<02!5,jfflpz|rqz>>6"));rules.push(rule("[|e.MMCF]\\;;7+8*xh#dezheyc/cn%?96°#lwv!xi|bnx%yxt#eaq!zcznsbjd~&bepgsféi}/à\'?0°*`im}elu"));rules.push(rule("_xg~T`d BJHCWQ=8>/:+d*`g{`iwl(ch/2?5°*ltf)enmg{kk\'dk*iobnkl`d,{\'duzbuj}a\"sg`b|"));rules.push(rule("Tvac._QR5[,3/r{v~bv951"));rules.push(rule("Sta}/W]\\:\\\'6%c&nh|kl}a.kb+1*ltqlpq!mz/wnwgdu#zqp!di}/udqkyolgw\"`dxk}iénv*{cq}ma`di}/jdk~lhwlw"));
rules.push(rule("Qv`uQji&S_]2P)9\"`(aownfpg-ie)0\"r|c~|\'jwo-goekudl,aa\'}`xyo`hh\"tx,awdvcyc#{knm{"));rules.push(rule("^|zkn(NDGD\\T6R(1.knjb}uwft8=="));rules.push(rule("Xdw\"CBDMXV7Z$?!}b.bfslgxk#ma\"5(m|}bv*%5#zm\"eék`kadcé,*huw)tgsee}/t~w*acp)vmuixg`ix%ibka`jégr(à,::°\'fjdygm}"));rules.push(rule("TsbtYfg)FHIK[_3X%7-g#dezheyc/hm%>-uwftq! ?.fa+vdlv*)epd(mbch|`n-im)`k`oc`nk+pz-isykqh|i.}hgiy"));rules.push(rule("Rp|hg,K@GBE?0:-;#jhklj}z}t1.6;"));
rules.push(rule("]zfv*HIC@D7<4\"<(y`/jj}c`sn)`g!<9>°/bxq*}cqdmq!{y|/k,`d~cnkhg!li}/udqkyolgw\"lgbzni`y"));rules.push(rule("[|e\\lj/BDECM3>5*0&b)icyaa{b\'dc*933°)epd(mbch|`n-im)gnhenga`+weajp"));rules.push(rule("Tvac.JHKLJ8]/:+ffdkazpmq2\'2:"));rules.push(rule("Sta}/BDECM3X%7-sm)icyaa{b\'o`*9&b{vgu{,k|s+uokjz$qtz,b(bevo`dol$fd{,|`sjqcbhp)imo|m`{bx"));rules.push(rule("_xg~T`d EO@I@5[,3/f+hkuon|i\"nn,:/tjz~&b{a\"`d`axbo%ec&`emocabi/udif~"));rules.push(rule("Vt~io PGFSL2><.2\'oj}cww{w8=="));
rules.push(rule("Sta}/WLCYA4=5*0&vg$o`peczj+ao-559°$gr|,~jufly-uv{$nd{,|`sjqcbhp)enum~`éjt+sorjjend{,jjth`digm}aq"));rules.push(rule("Qv`uQji&SNBQM:22!5,o/jj}c`sn)kd!;:>°/fy`*ljofsge(c`/qnw~debe$fnb.`w{jydrf)vmmd"));rules.push(rule("Xzybj*]AEZH0Z$?!lcyatjz7:7"));rules.push(rule("Xdw\"QOJ]C5P)9\"tf,cnbh`&gl$1!i~|jsx%o~r#yapla.|ry%fhu#{kv`|eaat+dfycqgéaq!~i|{nhdfhu#maqbmbjni`y"));rules.push(rule("UrbtYfg)TEG[@<T+8*l&nh|kl}a.`a+6*~rlyw\"`zi.nkgj}hb#fj\"wm~zfdji*iitg$mqxc}fsn%xbjoz"));
rules.push(rule("[hbhu$rfE`j}u:U<V#]2;0:\\T\"U>2V8|6X:U*Y0:86R[%77i=]0X,Z9>:7ZW+>0B8W=^/S=<;?VY$0n8W=^/ 5r>7\"Y$V7.<Y?g3R7S)#<v<6*U*?G3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Zxxjf$Qlmaag{boKEX&>`Fint5\'O^&6[R(9\\LpxT+0XQk@^u_DgUW\"4Z}yQK`^R(9\\l"));rules.push(rule("Wpc|\'Xho`ikumh@@R+8*iwhpknf.lhfgccécp)mlum~jfsnv"));rules.push(rule("Sta}]df![akbhcycgGKW!5,awdvcyc#fv\"tf`galna*ioe+pnd`.\'hy%lao`b-\"bgalfijqcbh#`w\"ogx.nkgj}hb"));
rules.push(rule("Y{ybj*^kfdkj}afOGYH/:}aNe`ps>\"eS 5RA"));rules.push(rule("Z}e.\\jnheezjcEJ_K&>)wmt{,::°\'fjdygm}$pn|mzfhe%ibka`jég!|c`abjp%iéeoljaié(.i}hx%A/&jgpgslezj"));rules.push(rule("Z}e\\lj/Tf`gbn`nCIVO$?!<9#zw+weaj,ohkbc,&-ojwn-qbp&+!kccmned~dim)mq!fcz/fgiezcg"));rules.push(rule("_}zkn(DK5WFTJ!5~ack1%\"#]/2Y,}:86&\'PcLP\""));rules.push(rule("^yg~&KL>RLYL\"<(|o|\'o`*iéeoljaié({}\'gd*{cq}ma`di.kbxfocbbgpg!i||é|\'o`y-`bjavum.kfev*ag#kkwbdi"));
rules.push(rule("_xg~T`d HE:PMQ@,3/id%lao`b$pnd`.`i+sorjjen!lcya\'gldh&bopgs(dk|nd~dim)ml!|dk/kdjz"));rules.push(rule("]{cb&KL?SS:22!5,{vwy7&]!_7,0QrT+0X>q2X%?_}:W\"4Z8y9V*8T_02U%.i"));rules.push(rule("Urbt+MO6WQ;:>/:+uk~&gl$fébdi`loé+`d-nb|p\"em,l`rhio-uj)tnt{,jj\'83:°-bf)vmuixg`i+sorjjend(aaasjk~h"));rules.push(rule("Qv`uQji&KL?SS:22!5,``\'micnm#{knm(c`/kdjz-rly$cg|i|/jdwo-rkhj\"2><°.}hgi*jijgc\"tx"));rules.push(rule("Qs}`k\"IM7_]4P]KR!5,{tjz7&]!_1,1QrT+0X8q4X%?_((j"));
rules.push(rule("Tsbt+MO6WQ:_Z@W+8*}gp)`g!léobjihmé*hh#aewu(hk/edpiac#zm\"qdy}/cn%8-gq{avr(i`/qnw~debea\"lgbzni`"));rules.push(rule("Sta}]df!@I5^U8^RLY$?!fc.ikbfa-tleh\"nf,b`h{%~bv#hbvdz,c`un%~egm)6\"r|c~|\'ljcca#|t"));rules.push(rule("Tvac.G<:!5,|`kg?*5"));rules.push(rule("Qv`u#A?3%7->#oead|xk|\'bk~htg`p"));rules.push(rule("]zfvXnk\'C>;)9\"9(|afi%xbjo)mq!fcz/fgiezcg"));rules.push(rule("Sq|hg,FC\\I\'6%xbjo3$Y0:86R\\\'>Wk"));
rules.push(rule("[|e.GKPG(1.lhfgccgjzkl!|c`abjp&iéeoljaié(e`{byacyc"));rules.push(rule("Y~dwPbe(DBTE)9\"sg`b#aglif&`fi`hfmzfhe%dbr#hhnnij"));rules.push(rule("Zkajl~)fdn~{cbx8*Xho`ikumh@@R0Pdaon`pgeFC[I<]PZ9332RWQ<_5YCDRD>032RFN_B=\\<OLKJSS<02:LEOHR[1Y6T52V343Da}6;v~bv"));rules.push(rule("V7%4$;(0)JD:^HAXI92:6PGFSL0["));rules.push(rule("Y1\";!4%7*C@9;?LNZJ"));rules.push(rule("S;\'2,9&?#;"));rules.push(rule("Q9&: 8)9%DBS9;?LG2=5AA8QE]N"));rules.push(rule("T5$<(1\'7/5"));
rules.push(rule("U2$5(2\'5/3(BH56"));rules.push(rule("]4 6):5$?+7"));rules.push(rule("X?\"6!2%7*C@9:?LNZJ4>"));rules.push(rule("_>!6%7$<"));rules.push(rule("[3#2-8<,0"));rules.push(rule("_6!>%7$?"));rules.push(rule("V7%7$9(0$0"));rules.push(rule("Q8&=>!4%3"));rules.push(rule("[2#72\'5,5%:"));rules.push(rule("V>%3$<(1)JMT2>5AA161C@1\\T1787@I5^U8^RLY?P097@`Xo`zltwV`mr"));rules.push(rule("W0%=$:(0$0"));rules.push(rule("T<$8(2\'7/5"));rules.push(rule("R:\'1,9&8.AHYC0?"));
rules.push(rule("^9!4%6$<&MFVD;:"));rules.push(rule("U=$9(21*1,<,@@UM"));rules.push(rule("X0\"8!4%7*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6T28?LnWhkfyqUiip"));rules.push(rule("[2#4-:*6"));rules.push(rule("Z<#4-8*3!FJ4>"));rules.push(rule("[3#3-=*0!FJ4=<EJXK"));rules.push(rule("T<$;(5\'6\"OGY4=<EC0<=MO7VNXD5]6?"));rules.push(rule("Y0\":!2%7\'>"));rules.push(rule("V>%1$?(1)Jm^li~nuZnbu"));rules.push(rule("_>!5%4$?&MFVD;97@`XxjxyofV`mr"));rules.push(rule("Y8\"?!4%7*CIQO"));
rules.push(rule("Z=#>-8*6!FC\\I=8"));rules.push(rule("W>%4$9(5"));rules.push(rule("V?%1$>(1$0"));rules.push(rule("Z3#>-:*0"));rules.push(rule("W?%0$?(1)JD;:7@@UM"));rules.push(rule("Y>\"6!3%1"));rules.push(rule("Y8\"<!0%7*Ci\\mar`zxQkhx"));rules.push(rule("Z3#>-8*3,:"));rules.push(rule("[:#7-84,0(BA]A"));rules.push(rule("W?%3$?(2)JMT2>5AA161C@1\\T1787@I5^U8^RLY"));rules.push(rule("_6!?%0$<+1"));rules.push(rule("^<!5%1$<+7"));rules.push(rule("V1%=$?(2$6\"ON6?"));rules.push(rule("[2#4-:*4"));
rules.push(rule("[:#4-1*0!FcQkb{dxyYgfw"));rules.push(rule("^6!1%7$>+7"));rules.push(rule("[=#4-8*6!FJ4><EjUicshvv^lc}"));rules.push(rule("_8!3%3$<"));rules.push(rule("^;!5%4$<"));rules.push(rule("Z2#2-=*0!FcQkb{dxyYgfw"));rules.push(rule("Z2#3-<*1!FC\\I=9"));rules.push(rule("]8 =):+8-HlV`gqi~zPcdv1Ci\\zkpuaiQkhx"));rules.push(rule("Z=#5-;*0!FC\\I"));rules.push(rule("[<#>-;*6!FC\\I=8"));rules.push(rule("Q9&: :):%DBS9;?LG2=5AA8QE]N8[56"));rules.push(rule("X?\"=!5%6\'9"));
rules.push(rule("Y>\"6!6%6*CIQO>0"));rules.push(rule("U2$5(6\'7/5"));rules.push(rule("[9#4-:*3,<"));rules.push(rule("^7!6;+9#4"));rules.push(rule("T6$>(7\'5/5"));rules.push(rule("U4$?(6\'5"));rules.push(rule("Z=#5-=*3"));rules.push(rule("[2#>-=*0"));rules.push(rule("T<$8(6\'0"));rules.push(rule("R5\'0,2&?#;\'EC0<"));rules.push(rule("_>!5%7$>+7"));rules.push(rule("U<$<(7\'6"));rules.push(rule("Z=#2-=*3!FcQ|hyqchYgfw"));rules.push(rule("X0\";!0%4\'?&MO>3"));
rules.push(rule("X0\"8!4%4*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6T28"));rules.push(rule("Y0\"<!6%1"));rules.push(rule("Z8#2-?*3,<"));rules.push(rule("[3#0-8*1,<"));rules.push(rule("]: ;)9+;-HL\\>3"));rules.push(rule("^9!4%1$>+7"));rules.push(rule("[2#73\'52/:!:"));rules.push(rule("Y;\"=!2%4\'9"));rules.push(rule("V7%4$?(1)JMSN"));rules.push(rule("Z3#?-<*0,<"));rules.push(rule("_=!4%6$<+7"));rules.push(rule("[2#73\'6,3"));rules.push(rule("]5 ;):0$?&Q849OG^H"));
rules.push(rule("_7!1%3$<&MFQ833BH560KL>RLYL9WLCYA6351[BL^J3R3BaPtdw~dc\\mkq"));rules.push(rule("[=#4-8*1!FJ4><EjU~iq}mg^lc}"));rules.push(rule("Y>\"<!6%6\'9&MO>0"));rules.push(rule("_=!6%7$<+7"));rules.push(rule("[<#4-:*1,<,@I=9"));rules.push(rule("R:\'2,6&?#;"));rules.push(rule("]: ;):+9 2#GV803BAZ=:>DK<22J:9"));rules.push(rule("Y8\"<!0%4"));rules.push(rule("R:\'0,0?\"=\"3+KE_@"));rules.push(rule("Y?\"<!6%7*C@98?LnWhkfyqUiip2Jm^{c|{nnZnbu"));rules.push(rule("V1%7$?(2$6\"ON6?"));
rules.push(rule("W?%0$:(0"));rules.push(rule("^7!5%1$9"));rules.push(rule("W0%7$>(2$6\"ON6?"));rules.push(rule("_6!5%0$9"));rules.push(rule("T<$9(0\'7/5(^:"));rules.push(rule("V?%1$9(7"));rules.push(rule("[<#>-1*0!FJ4<<EJXK"));rules.push(rule("]4 >7%7$9"));rules.push(rule("Q8&5 >)9(>"));rules.push(rule("^6!2%4$<&MO>0"));rules.push(rule("W?%0$;(2$6\"ON6?"));rules.push(rule("S:\'0,0&>#;"));rules.push(rule("T<$9(2\'5"));rules.push(rule("[<#4-=*1,<,@I=9"));
rules.push(rule("S;\'0,0&>.AhTao}gq}[fn{7@`XxjxyofV`mr"));rules.push(rule("X9\"<!6%4"));rules.push(rule("R;\'=,2&>"));rules.push(rule("Q4&> >)?%DbYgltcs|Sj`t"));rules.push(rule("[<#2-=*0!FcQkb{dxyYgfw"));rules.push(rule("Q9&9 =):%DK<1"));rules.push(rule("R7\'7,0&=#;\'EC0<=MO>0:K@GBE?V1NJJDF648"));rules.push(rule("[<#2-;*0!FJ4><EJ_77"));rules.push(rule("W6%7$;(7)JMSN6<4IM>\\IITG5:13ZJ@PE4Y"));rules.push(rule("]< >):4$<&MFVD"));rules.push(rule("Y1\";!?%4\'?&MO>3"));
rules.push(rule("R:\'0,0&?#;\'Y1"));rules.push(rule("X9\"<!0%6*CIQO>0:FJ5YCDRD<>32RFN_B?\\"));rules.push(rule("V7%4$;(7)JD:^HAXI:=:6PGFSL0[7@`XxjxyofV`mr"));rules.push(rule("Q0&> ;):%DbYpfvvhmSj`t"));rules.push(rule("U<$<6-?*0"));rules.push(rule("[2#71\'5,5%:"));rules.push(rule("S1\'0,2&=#;"));rules.push(rule("W?%1$>(1)Jm^li~nuZnbu8Gk]rg~zfbTae~"));rules.push(rule("W6%7$;(2"));rules.push(rule("Y8\"?!0%6*C@8_@MVF=6?<]AEZH2Z?LnWa}sb`Uiip"));rules.push(rule("X?\"6!3%4\'?&MO>3"));
rules.push(rule("U=$8(7\'5\"ON6<"));rules.push(rule("]? <)9+; 2"));rules.push(rule("_7!1%1$>+7"));rules.push(rule("X?\"=!6%4*CIQO>0"));rules.push(rule("T3$5(4\'5\"ON6="));rules.push(rule("V>%0$8(2$6\"ON6?"));rules.push(rule("U<$9(7\'6"));rules.push(rule("V?%4$9(7"));rules.push(rule("]4 =)8+2"));rules.push(rule("T=$4(0\'2"));rules.push(rule("U=$9(7\'7/5(^:"));rules.push(rule("S2\'5,6&="));rules.push(rule("Y0\"7!1%1"));rules.push(rule("R;\'52/<\"<"));rules.push(rule("S:\'52/<\":"));
rules.push(rule("V?%4:#3-;)6"));rules.push(rule("U=$9(1\'5\"OgS}`uloRblz"));rules.push(rule("[3#3-?*1!FC\\I=9"));rules.push(rule("Y0\"6!5%7"));rules.push(rule("W0%1$>(1)Jm^li~nuZnbu8Gk]rg~zfbTae~"));rules.push(rule("V1%=$;(0$0"));rules.push(rule("^6!1%2$<&MFQ833BH560KL>RLYL9OgS}`uloRblz"));rules.push(rule("V1%=$5(2)JD;;"));rules.push(rule("Y1\"8!1%6\'9&MO>0"));rules.push(rule("S2\'5,6&>.AhTao}gq}[fn{"));rules.push(rule("V>%0$;(7"));rules.push(rule("Q8&5 =)?"));rules.push(rule("Y1\";!?%6"));
rules.push(rule("R:\'2,9&>.AH^?86HE359ON?Z@WC>DbYpfvvhmSj`t"));rules.push(rule("]< =)>+>-HE2RFN_B<870SNBQM8W"));rules.push(rule("S;\'0,0?\"</U:51CIQO"));rules.push(rule("S6\'7,3&=#;\'EC0<=MO>0:K@GBE?V1NJJDF648"));rules.push(rule("V>%0$>(0$0"));rules.push(rule("T=$<(2\'5/4"));rules.push(rule("V4%1$:(2$0"));rules.push(rule("S:\'=,2&8"));rules.push(rule("[:#4-1*3"));rules.push(rule("]5 9)8+9 2"));rules.push(rule("_8!4%6$?&MFVD;9"));rules.push(rule("[<#>-:*1!FC\\I"));
rules.push(rule("W?%1$<3-8$P08"));rules.push(rule("X:\":!3%4\'9"));rules.push(rule("X0\"8!2%6\'9&MO>0"));rules.push(rule("V?%4$>(2$<"));rules.push(rule("Z3#4-;*6"));rules.push(rule("[:#4-1*6!FC\\I=9>DK=UMKUO94>4QOJ]C7P"));rules.push(rule("Y1\":!3%4*Ci\\zkpuaiQkhx"));rules.push(rule("[3#2-81,2%8.AHYC"));rules.push(rule("R3\'6,6&8.AA0SNBQM;32:^HAXI:V"));rules.push(rule("V>%1$<>-;$P087@@UM"));rules.push(rule("_=!6%6$<+7"));rules.push(rule("X0\":!68+;"));
rules.push(rule("R:\'2,9&=.AH^?86HE359ON?Z@WC"));rules.push(rule("[:#7->*6!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("V7%7$>(1)JMSN6?4IdZybtw`a]eg"));rules.push(rule("^8!5%7$<&MO>3"));rules.push(rule("_9!5%7$>&MO>3:FcQ|hyqchYgfw"));rules.push(rule("Y>\"=!6%7*CIQO>3"));rules.push(rule("Z2#2-82,0(^??"));rules.push(rule("X0\":!4%4"));rules.push(rule("Z=#4-;*1,<,@I=9"));rules.push(rule("U2$>(2\'7/5"));rules.push(rule("T3$9(6\'5\"ON6?"));rules.push(rule("Q6&? ;)9%DBTE"));
rules.push(rule("U4$?(6\'6\"OgSjjwjw~Rblz"));rules.push(rule("V>%3$<(2)JMT2>5AA161C@1\\T1787@I5^U8^RLY?P09"));rules.push(rule("U=$8(2\'6\"ON6<4IDWL"));rules.push(rule("Z=#>-?*0!FJ4<<EJXK<2"));rules.push(rule("W>%<$9(5"));rules.push(rule("S;\'0,3&?#;\'Y1"));rules.push(rule("^6!1%0$?&MFQ833BH560KL>RLYL9WLCYA6351[BL^J3R3BaPtdw~dc\\mkq"));rules.push(rule("Z;#4-=*0!FC\\I=:"));rules.push(rule("W5%7$;(2$0"));rules.push(rule("U2$?(2\'5/3(BH56"));rules.push(rule("^?!6%3$?&Mf[fdxm|{Xojy"));
rules.push(rule("]; =)9+8-HE359OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("X?\"6!?%6\'9"));rules.push(rule("S2\'5,2&="));rules.push(rule("U=$8(1\'7/5"));rules.push(rule("Y1\"8!3%7*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6HlV`gqi~zPcdv"));rules.push(rule("_7!2%2$9&MFVD;:"));rules.push(rule("U<$<(1\'5/7"));rules.push(rule("Z3#7-<*3,<"));rules.push(rule("[2#>-:*6"));rules.push(rule("S2\'6,2&?#;"));rules.push(rule("W0%=$8(2)JD;;7@@UM?8"));rules.push(rule("]: 7)?+9-HL[B"));
rules.push(rule("_:!5%4$>&Mf[qnzxgjXojy"));rules.push(rule("Y1\":!6?+;"));rules.push(rule("^?!5%6$<"));rules.push(rule("S;\'1,2&=.AA17"));rules.push(rule("Z=#2-8*0!FJ4><EJ_77"));rules.push(rule("Z;#4-;*3!FcQ|hyqchYgfw"));rules.push(rule("Q7&> =)?%DK<22Jm^li~nuZnbu"));rules.push(rule("V?%4:#0-="));rules.push(rule("^?!6%3$<"));rules.push(rule("T5$?(1\'6\"OG^H56"));rules.push(rule("W?%0$9(0$0"));rules.push(rule("U<$4(7\'6"));rules.push(rule("Y1\"8!3%4*CIV369ON6=4IM7_]559?LG:Y^=T_JZ"));
rules.push(rule("T5$?(6\'7\"OG^H550KL6PGFSL00<5YCDRD<U"));rules.push(rule("W6%4$>(0$0"));rules.push(rule("Q3&> =):(>"));rules.push(rule("[:#4-8*1,<"));rules.push(rule("S:\'0,3&8"));rules.push(rule("W6%7$;(1)Jm^li~nuZnbu"));rules.push(rule("Z=#>->*0!FJ4<<EJXK"));rules.push(rule("[<#2-8*3!FC[56"));rules.push(rule("W?%3$?(1)JMT2>5AA161C@1\\T1787@I5^U8^RLY?LnWhkfyqUiip"));rules.push(rule("^6!3%4<#4.=$LNZJ"));rules.push(rule("Y>\"6!1%4*C@9:?LNZJ4="));rules.push(rule("V?%<$9(7"));
rules.push(rule("R;\'0,3&>"));rules.push(rule("[9#2-1*3,<"));rules.push(rule("R0\'6,4&=#;"));rules.push(rule("_6!6;+9#2"));rules.push(rule("W0%=$>(7"));rules.push(rule("W>%4:#>-;"));rules.push(rule("X?\"<!3%4\'?&MO>3"));rules.push(rule("X?\":!4%4"));rules.push(rule("U7$9(6\'5/5"));rules.push(rule("W0%=$>(2$6\"ON6?"));rules.push(rule("U2$9(7\'7/5(BH56"));rules.push(rule("^?!5%3$>&MO?TEG[@=0;>\\IITG5Q"));rules.push(rule("S2\'6,9&?.AA0SNBQM;32:^HAXI:V"));rules.push(rule("[<#5-:*1,<"));
rules.push(rule("W0%1$8(7)JP;97@]=9>DK<1"));rules.push(rule("[3#2-83,0(^??"));rules.push(rule("T3$>(1\'5"));rules.push(rule("[<#>-;*1!FC\\I=9"));rules.push(rule("[PKtbggg!}bbfjbqoi&`fjltU"));rules.push(rule("^c`un8IDPB)qlmaag{bo%acitg"));rules.push(rule("^UIujkih&vghklaxkk\'glhc^"));rules.push(rule("_b`un8IDPB)qlmaag{bo%lcf"));rules.push(rule("SXOvcoki.ziglgdrfm$kokc`arV"));rules.push(rule("Ydc|j:HL\\L&Vghklaxkk\'MwohSmbjmvf"));
