// OpenAero rulesYY-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####   Régles France 2017 Espoirs à Doret    Version 2017.0.00    ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####      Modifications mineures (commentaires) et connus 2014    ###################
//#####      Corrections, modifications espoirs 2015, connus 2015    ###################
//#####      Ajout de règles (déclenchés) d'inconnu Doret 2015.      ###################
//#####      Prise en compte du distingo entre rotation alternées    ###################
//#####      (,) et rotations même sens (;) dans les régles 2015.    ###################
//#####      Modifications 2016, connus 2016, nouveaux noms.         ###################
//#####      Modifications 2017, connus 2017, connu_x -> connu x.    ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2017 : Espoirs, Desavois, National2, Doret.

//##### (Une partie des) Règles spécifiques à la France.

rules.push(rule("W\\Mwkcef)Aqqge||\'hjdcs^"));rules.push(rule("Qemaa/:+s\'-fc$mf3#ln/45%g?&cid)h~\" (t%+*mk2$z|!9<+/15%jm+1c)\",$><#5+ejme-.#.3&\" ( +m$*!#f"));rules.push(rule("^e\"jj}7<43"));rules.push(rule("_b`un8Lgmja\"D{|afux%kaj"));rules.push(rule("SXOvcoki.Jt{jcu#`janfb{R"));rules.push(rule("Un\'`g{4501"));rules.push(rule("Vkdwo0@qhjad(I}hbwy-goe"));rules.push(rule("W\\Mwkcef)Aqqge||\'glhc^"));rules.push(rule("[` kbq9328"));rules.push(rule("R`hwggak#bfs8;?"));
rules.push(rule("_inj>(gdh>8"));rules.push(rule("Qgia9\"jbk7<"));rules.push(rule("Rdhi:,ee`26"));rules.push(rule("Sqfhn,ee`26"));rules.push(rule("Twzdh.dml<9"));rules.push(rule("[n`vwphkom!cn65"));rules.push(rule("^lntnccj+qltg`|1?"));rules.push(rule("[ybjo$vgqmmz25"));rules.push(rule("Qsg`b\"sdqxhvfhp?0"));rules.push(rule("[fbtf4Bp`fok/Bxuedtp)enm"));rules.push(rule("Z\"Ktbggg!M~`nyv*ljo "));rules.push(rule("Uvl-;#h`t`fokk"));rules.push(rule("Rrfwnk5=>"));rules.push(rule("Ssfwlm5=>"));
rules.push(rule("[maib}mlf%|afi8:"));rules.push(rule("]j|`r{(~xtmykq<V>R!\\:(>PZ-8X,0"));rules.push(rule("_{zueue~+mhig<(zg}fl`y-pfgppd"));rules.push(rule("Qu}~`hx(gl~>8"));rules.push(rule("[yxjf$WRHF1|`kg?TVXpT"));rules.push(rule("_xg~&VZDH>Ometzi.nqnf*{tjehg!}bg~rnhocr"));rules.push(rule("Tgecp.{kv^i`z/:+[3Q(_m/^/;P \'\\:(2P/#4$&03R7S)Wa!Q(X8664UP T6&=W-;#q?\\8T\".2\'r>T=Z-4~"));rules.push(rule("^|zkn(DbYbep]5=,3/udqUljw3$zZ$7S"));rules.push(rule("Qs}`k\"IdZkar\\akp!5,|`sTdfy<#R(9\\"));
rules.push(rule("Qv`u#AhTdfyYkfv\"<(^a{flec&bepgsféi.fi`xiowl"));rules.push(rule("Uwac.Dez^i`zP095*0&qfp]`dx4//3^&6[R(9\\0p8T+0X<q0X%?_5t8U#<V3#"));rules.push(rule("]zfv*FdrRgo}[538,3/Udqkyolg$cm|i|aéb+ic`owél$à\"6:<°"));rules.push(rule("Rcehmv%hkiu~io~&>)Jm^i`zP3>"));rules.push(rule("Q8&> <)?"));rules.push(rule("^?!6%2$<&M[>3"));rules.push(rule("S2\'6,2&=.AU16"));rules.push(rule("W0%6$>(0)JP;9"));rules.push(rule("]5 :):+9-HQ359OgSocsTme"));rules.push(rule("Y;\":!6%4\'?"));
rules.push(rule("W6%7$:(2)JP;9"));rules.push(rule("[2#7-:*0"));rules.push(rule("]4 >)8+<"));rules.push(rule("X:\"=!6%4\'?"));rules.push(rule("]: 7)3+>-HQ37"));rules.push(rule("_8!5%7$<&M[>3:FcQnkZbbt"));rules.push(rule("W5%7$<(2$6"));rules.push(rule("T3$>(7\'0"));rules.push(rule("V7%7$<(0)JP;97@]=8"));rules.push(rule("X0\";!2%1*CT98"));rules.push(rule("Z3#7-;*6"));rules.push(rule("R;\'6,2&:"));rules.push(rule("S4\'7,5&="));rules.push(rule("V7%4$>(7"));
rules.push(rule("W?%3$<(2)JP;97@]=9>D_<0"));rules.push(rule("]: =):+;-HQ359OgSocsTme"));rules.push(rule("^7!6%6$5"));rules.push(rule("T5$?(0\'0\"OZ6="));rules.push(rule("[<#>-1*3!F^4<"));rules.push(rule("X?\"<!6%1*CT98?LS2?"));rules.push(rule("Z2#3-;*6!FcQnkZbbt"));rules.push(rule("Q9&9 <)8%D_<22Jm^i`zPodw"));rules.push(rule("U4$<(0\'5"));rules.push(rule("Z?#5-8*3!F^4><EW0?=M[>1"));rules.push(rule("Z=#>-=*3!F^4>"));rules.push(rule("Q6&? =):"));rules.push(rule("Q0&= >):(>-Kbq[cm|S9=7"));
rules.push(rule("S;\'1,3&=.AU16"));rules.push(rule("V>%1$>(2)JP;97@]=8"));rules.push(rule("U=$9(2\'5\"OZ6?4IY?9"));rules.push(rule("_7!2%3$<&Mf[cm|Sf`u"));rules.push(rule("Y0\"?!5%7"));rules.push(rule("U4$?(7\'0\"OZ6="));rules.push(rule("R:\'1,9&>.AhTdfyYkfv"));rules.push(rule("[:#4-?*3!F^4><EW0>"));rules.push(rule("S:\'6,2&4"));rules.push(rule("Y0\"?>):+> 1"));rules.push(rule("[3#3-=*3!FcQnkZbbt"));rules.push(rule("[2#7-:*6"));rules.push(rule("V4%4$<(2$6"));
rules.push(rule("W6%7$?(0)JP;97@]=8"));rules.push(rule("U2$9(2\'5\"OZ6?"));rules.push(rule("]< >)=+9-US@J"));rules.push(rule("]5 :)?+>-HlVenuWda}"));rules.push(rule("Y8\"?!5%6*CT98"));rules.push(rule("_6!6%1$?"));rules.push(rule("Z2#3-?*6!F^4>"));rules.push(rule("T1$?(2\'5\"OZ6?4IY?9"));rules.push(rule("S2\'5,3&="));rules.push(rule("Q6&4 9)8%D_<22JP;;"));rules.push(rule("T_Lgmja\"Emoyhbv%}tldkvhgb.lhekP"));
rules.push(rule("Vbnhe-;#wf,,(;0/*f%j&ouz*,/&,c6*&%;?##=:\"ahln\"5a7\'mfcid\",/+\";?u%83&k.#.5&+.og )>}d#idbah\'jm5+-;!7; $bah\'<h\':6/-5=)db*:f%o\'m"));rules.push(rule("Ri$icy5=9?"));rules.push(rule("^c`un8Lgmja\"Emoyhbv%}tldkvhgb.nkg"));rules.push(rule("RYOvcoki.Kbxd|bop&tpneczfhe%ccelgjw\\"));rules.push(rule("Xc!cn64?8"));rules.push(rule("Uhec>Ovcoki.Kbxd|bop&tpneczfhe%kaj"));rules.push(rule("V]Mwkcef)@grizaft$uxbkl}mmo(`gmunX"));rules.push(rule("^e\"jj}7?63"));
rules.push(rule("Ugk~ce`c/lit3>5"));rules.push(rule("Rllc/lab3:"));rules.push(rule("Vtdifht.dml<9"));rules.push(rule("Uck`3.dml<9"));rules.push(rule("V`jh= kjg93"));rules.push(rule("Wajh2 kjg93"));rules.push(rule("X{|ga*fld07"));rules.push(rule("Y~a{*fld07"));rules.push(rule("]y{}i{jy kbq93"));rules.push(rule("Rgdtvxde`j*fdr06"));rules.push(rule("Ugk~ce`c/sm|kns64"));rules.push(rule("Sqfhn,zi~jf88"));rules.push(rule("Wudif rl}vgqmmz26"));rules.push(rule("Uvdlv.{ardix3>"));
rules.push(rule("Vu{ld tfyacu5="));rules.push(rule("^c`un8Lgmja\"Emoyhbv%}tldkvhgb.nkg"));rules.push(rule("]%H}fefo-Bfzetna!udheyolg$cmd%"));rules.push(rule("[xk&>)efwibmjc"));rules.push(rule("Yyc}cm64?"));rules.push(rule("Zzbume934"));rules.push(rule("Tbfbgw`je,xcgas65"));rules.push(rule("Ubxbss$pwsf|a|:U7V#]2$0_]&=R!6"));rules.push(rule("Ws~wd}ip$jclm1.ynydmhu#aluzi"));rules.push(rule("Vayj}+u{kv<V5R!\\:1WQ(2U*0"));rules.push(rule("^x}h(dlkf4$pn|mzfhe%|htw`gcmm,c`iddyc#ma\"00<°"));
rules.push(rule("Sd{kwq%~acknw7S4_\',0]&W;9Zw6V#2*U*"));rules.push(rule("Tveajf{)l`ei3/sdkdhgvq$go(zg}fl`"));rules.push(rule("Vt~io US@J?sg`b5YP[yP"));rules.push(rule("Z}e.ZTKO5Jghry`*lpfj$tsa`bj\'~kc|sfdalu"));rules.push(rule("Tvac.ZtkoWc{Pub`d0tleh8_SR}uZ"));rules.push(rule("Sta}/Rxe`Ph~Zxdcm4Bkf}~k/tnpfh&l|$cwmo.yubifh&vgmstmakas+v&oh$tdzxglfg`"));rules.push(rule("Sq|hg,FJM2udif7._~_.:UWhIZ\"y\"V`ET_.:UPy&"));rules.push(rule("Vqc|\'C@@4tcr(hk/céhioceké)`co{,bjt+weygw`klr(oabwdvéo~"));
rules.push(rule("Xkc`y*}`xyww{w?_1P \'\\:(3Pz29-^/ W?:1Vy;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Wu~io P214\"<(zk}szqx~<?:"));rules.push(rule("Urbt+U8<2!5,^nt+ao-tl}evhgb.|r{`xdcv{a\"à!94>°/t~w*acp)rgs|emnknv"));rules.push(rule("[yxjf$Icy1<.2\'}`xyww{w8=:"));rules.push(rule("Y~dw\"Jj}3=&>)Tcr(hk/udqkyolg$qtxi|fb~wo-à&:9°$qtz,mjt+sorjjend{"));rules.push(rule("^m`i}(|htw|tsuz3Q>W+\"V7.0Y~08%R!/P4<P/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));
rules.push(rule("Uwac.Dez88y~/:+sorvyuvs{62="));rules.push(rule("Wpc|\'@g{04wq(1._fx%nh&qfpcuac`/t~uoof|vg!à(5>°/t~w*ag#apuaoocb+hecrbgpg"));rules.push(rule("S`fjt,~i|{cdt~u>W=^/ W?\">Vy;=/_\',7}9<\'S)#^; >^ $?!,?5Q>W+*0&q2Z2]&1t"));rules.push(rule("Y{ybj*Fdr46gf$?!~i|{cdt~u956"));rules.push(rule("^yg~&Hku?3mk\"<(\\o|\'o`*iwhpknf,}zwnwchsql$à\"88°,}zu+ik-pf{pkbi`k/cnvihhghjvd"));rules.push(rule("S`fjt,fc~ztc8T4Z-8_33UP >[%^? >^4j9_1P T6912PZ-4v9_1\"&6{:5#0`8W=,0S=<R:x>T=Z-4~"));
rules.push(rule("[yxjf$JQQ}f`r%7cis|wj;f("));rules.push(rule("[|e.GWRt{dazs+8*]gp)`g!{c|{nn%zbspzéa\"`x~è}/kj%|ooea"));
rules.push(rule("UBxbss$jgf5R&>[%4V#4_\'_05Up?S):Y$V54TX,Z:?Ss6W+;Q(5U*6}9P =[%^890;TX,3t=R!5W+?Q(X86_}:P >[%6V#z1U*0]&W<:1VY$q4_\'7^/S8SS)w7V#2_\'_02UP s2W+Q?5^U*3]&W<<3Vy?Q(0U*0]&p9S)P7>PZ-R50\\T\"<s0W+8Q(X:0_]&=r8[%1V#4_\'5~6T\"=S):Y$q1_\'<^/S=<:0VY$q1_\'7^/:P T581Wq1_\'7^/;P T691Wq1_\'<^/>P T691Wq1_\'_19UP ;[%^8>[>X,9T\"=S)P48Pz4U*:]&4R!\\96Wq>_\'0^/S==R[%7v5Z-=X,Z:8SS)w=V#2_\'51]&=r7[%0V#]2:Y^/S=<;Zw=V#3_\'_05UP T58Xv5Z-?X,Z;86R[%4v5Z-<X,9T\"?s?W+?Q(X<3_]&W?=Zw=V#]6?Y^/>P =.w<V#7X96_]&"));
rules.push(rule("Qomk#aff`7kod|vgr(oaatbaéxéhu#jkolm,`éhfl|hu"));rules.push(rule("Zibhu$Lmsyx||:U<V#Zg\"X,Z;4SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("_}zkn(Gl~4;4Jnz,3Ghyt~u95="));rules.push(rule("Sta}/Lit9=7Cjx-;#Yeq!li.}hd~dim)gmlxc}éj\'cjxd|lgpcmm,}zwnwchsql$à\"6:<°"));rules.push(rule("Qbgbx\"R{1?|rqz9\\8T\"Rk,W+Q?1^U**Z9!6R.6!;6X:U*?13R>S)65"));rules.push(rule("Wu~io Kbq741]|::\'6Pz93r}vq;49"));
rules.push(rule("_xg~&Hku559Qr5=,3/Wjv*ic#{kv`|eaa\'hjg}ipél$qn}.;2°+hecrbgp\"r}|k}nnpxh&à#:22°"));rules.push(rule("Vedk| Bl=1suz3Q>W+Vi-_\'_68UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("[yxjf$Icy94>Kh?0*0Bl=1suz434"));rules.push(rule("Xdw\"Jj};56Gf07!5,^nt+ao-tl}evhgb.lhfue~éc#zkwr(8;°/cnvihhghjv!{y~jub`c#à)5:1°"));
rules.push(rule("Rafjt,zczPvwy0X:U*;]&$U>*>X#Q(+R5/9U%3a/71S?_\'=^/ W8\">Vy;=/_\',Y0%4S&:{C.?=]0X,08P \'\\:(?P/_\',Y0%4S&:ec.?=]0X,08P \'\\=(3Pz29-^/ W?\"?V,7c@\';?\\8T\"U>*3XV#]2$1_]&$U>*3X#0t\'8?\\8T\"?T69XV#7_\',Y0%4S&:x!;6X:U*?s3R>S)6"));rules.push(rule("Wu~io HlV@glaS~`t+8*iwVuvs{6~i5"));rules.push(rule("]zfv*EjUIcn`[rn{,3/Cnhc-bé`ealb`é,~`tbqck&jgpgslez"));rules.push(rule("Vggiez+glbptdi}/:+KLN=U8<2:Emv85;Me=Nh|178Y~;20Hku7;9@m5="));rules.push(rule("X=\"<!6%1*CT98?O`p5>"));
rules.push(rule("T<$8(1\'5/2(B\\55"));rules.push(rule("_:!4%4$>&M[>3:F^4=<EW0>"));rules.push(rule("R:\'2,0&=.Bfs<:xv8GV833BH54"));rules.push(rule("S4\'0,0&="));rules.push(rule("R:\'1,7&>.AU14"));rules.push(rule("T6$9(2\'5/3"));rules.push(rule("_7!1%3$?&M[>3:F^4=<EW0>"));rules.push(rule("V4%7$8(2$0\")9>\">4\'4>!76 "));rules.push(rule("Y1\";!?%4\'?&MO>3"));rules.push(rule("T=$?(0\'2"));rules.push(rule("[:#4-8*1!F^4><Fdr46"));rules.push(rule("U4$?(5\'6\"OZ6?4IY?8"));rules.push(rule("T=$4(0\'6"));
rules.push(rule("^?!6%3$<&Nh|;1"));rules.push(rule("V1%=$;(2$0\"OZ6?4IY?9"));rules.push(rule("V>%0$<(7)JP;97@]=9"));rules.push(rule("S;\'1,4&=.AA141CT9;"));rules.push(rule("^7!6%6$5"));rules.push(rule("Q4&> >)8%D_<1"));rules.push(rule("S4\'<,9&=#;\'EW0>"));rules.push(rule("_6!6%1$?"));rules.push(rule("[<#5-;*3,:"));rules.push(rule("V>%0$>(1)JD;:"));rules.push(rule("]: 7)?+; 4#GV80"));rules.push(rule("U=$;(7\'7\"Rxe`Ph~Zxdcm"));rules.push(rule("_7!2%0$9&M[>3"));rules.push(rule("_6!?%6$9"));
rules.push(rule("[2#71\'5,5"));rules.push(rule("Z2#2-:*3!Emv67oj"));rules.push(rule("[2#2-=*0"));rules.push(rule("]: =)9+;-HE359OgSJjjbZzbu9;"));rules.push(rule("R5\'0,3&=.AhTAo`o\\ykq"));rules.push(rule("R7\'6,0&=.Bfs<:ii"));rules.push(rule("]5 :):+;-HQ36"));rules.push(rule("[2#7-:*0"));rules.push(rule("W>%4:#4-;"));rules.push(rule("X1\":!4%7"));rules.push(rule("[<#5-:*3"));rules.push(rule("S4\'7,3&?#;\'EW0?"));rules.push(rule("]5 :)<+; 4#GB803B\\55"));
rules.push(rule("[:#7->*1![\\GA<EVZxukfqv"));rules.push(rule("]: <):+8-HQ35"));rules.push(rule("^6!3%7$?&M[>3:Emv67oj"));rules.push(rule("[:#4-<*3!F^4="));rules.push(rule("T5$?(2\'5\"OZ6<"));rules.push(rule("V1%1$?(1"));rules.push(rule("X:\"<!1%4\'9&+81.0> ?:+:3#"));rules.push(rule("U2$?(7\'6\"ON6?4IdZNhkjVtmr2>"));rules.push(rule("R5\'<,0&=#=\'EW0<=M[>0:F^4<"));rules.push(rule("V>%1$<(2)Icy1<j`"));rules.push(rule("_:!4%7$<&M[>0:Emv67oj"));rules.push(rule("X0\"8!5%4*@g{04wq3B\\550KL75"));
rules.push(rule("T3$5(1\'5/3(B\\560KX748GV82"));rules.push(rule("W>%1$?(1"));rules.push(rule("X0\";!3%4*C@9;"));rules.push(rule("Z3#2-:*4"));rules.push(rule("[2#>-8*3"));rules.push(rule("X1\"??)8+8"));rules.push(rule("[:#4-=*6!Emv67"));rules.push(rule("Y1\"8!2%4*CT9;?LS2?"));rules.push(rule("X9\"<!4%4*CT9;"));rules.push(rule("Y0\":!4%1"));rules.push(rule("Z;#7-?*6![\\GA<EVZxukfqv"));rules.push(rule("S2\'6,4&>.AU141CT9;"));rules.push(rule("[<#2-8*0,<,@]=:"));rules.push(rule("Q6&? ;):(>"));
rules.push(rule("S1\'7,0&=#="));rules.push(rule("T<$8(2\'6\"OZ6?4IY?8"));rules.push(rule("Y1\";!4%6\'9&M[>3"));rules.push(rule("R:\'0,0&>.AU141CT9;?O`p5>kh"));rules.push(rule("S;\'1,7&8.AU14"));rules.push(rule("R0\'6,0&=#="));rules.push(rule("T<$;(;\'5\"ON6?4IY?86HQ37"));rules.push(rule("T<$8(2>*3!Emv67~u1CT9;"));rules.push(rule("Z3#7-8*3,:"));rules.push(rule("T3$?(2\'6/2(B\\560KX74"));rules.push(rule("_:!4%7$?+0)JP;:7@]=8"));rules.push(rule("Q6&4 >)?%D_<22JP;:7@]=8"));
rules.push(rule("Y8\"?!4%4\'9"));rules.push(rule("_7!2%4$>&M[>3"));rules.push(rule("U2$>(0\'6/5(B\\56"));rules.push(rule("S:\'6,2&8"));rules.push(rule("Q9&9 9):%DK<2"));rules.push(rule("[2#72\'5,5%4"));rules.push(rule("_8!5%7$?&M[>3"));rules.push(rule("S;\'2,2&=.Bfs<:xv8GV833B\\54"));rules.push(rule("S4\'6,0&8.AU141C@9;"));rules.push(rule("^?!5%3$<&M[>0"));rules.push(rule("Z;#4-=*0!F^4="));rules.push(rule("Q3&= >):(8"));rules.push(rule("V1%6$<(0$0\"OZ6?4IY?8"));
rules.push(rule("Q4&? >):%D_<22JP;:7Cn25nb"));rules.push(rule("S;\'0,5&>.AU141@g{04fn"));rules.push(rule("R3\'6,9&>.AU14"));rules.push(rule("Z3#7-;*6"));rules.push(rule("T<$8(6\'6\"OZ6?4IY?8"));rules.push(rule("[<#>-=*6!F^4>"));rules.push(rule("R:\'0,0;\"?/IY?;6HQ36"));rules.push(rule("Q8&4 :):"));rules.push(rule("Y0\"?!5%7"));rules.push(rule("]< >)9+9 2#GV80"));rules.push(rule("T1$>(2\'0\"OZ6?4IY?86Kbq=2eg"));rules.push(rule("U<$4(0\'0"));rules.push(rule("]4 >)8+<"));
rules.push(rule("Z=#>-<*3,<,@]=:>D_<12JP;;"));rules.push(rule("U=$8(20*0!Emv67~u1CT9;"));rules.push(rule("]5 :)9+>"));rules.push(rule("Q6&4 <):(8-HQ359OZ6="));rules.push(rule("V?%1$<(1"));rules.push(rule("Y1\":!3%4*CT9;"));rules.push(rule("W0%7$>(2)JD;97@]=9"));rules.push(rule("T6$<(0\'5/5($7#6;);=*28-"));rules.push(rule("W0%7$9(0)JD;:"));rules.push(rule("V7%7$?(1)JP;:"));rules.push(rule("Z=#>-:*6!F^4>"));rules.push(rule("U2$?(7\'5\"ON6?"));rules.push(rule("W0%=$:(2$0\"OZ6<4IY?9"));
rules.push(rule("[<#4-8*3!FJ4>"));rules.push(rule("[2#7-:*6"));rules.push(rule("U<$?(0\'<"));rules.push(rule("V>%0$9(0$0"));rules.push(rule("]4 7)9+8"));rules.push(rule("Y1\"8!3%4*@g{04wq3B\\550KL75"));rules.push(rule("R5\'6,2&>.AA141Ci\\MaohW|a|=9"));rules.push(rule("Q8&= :):"));rules.push(rule("S2\'5,6&8.\\WBK"));rules.push(rule("]5 ;)8+8-HQ359OZ6<"));rules.push(rule("S;\'2,6&>.AA141CT9;?LS2?"));rules.push(rule("V1%7$?(7)JP;97@I=9"));rules.push(rule("S:\'=,3&>"));
rules.push(rule("^;!4%4$?&M[>3:F^4=<EW0>"));rules.push(rule("U0$?(2\'6\"OZ6?4IY?8"));rules.push(rule("]5 ;):1$<&M[>3"));rules.push(rule("W0%6$<(2"));rules.push(rule("W6%4$?(2$6"));rules.push(rule("^7!?%6$?"));rules.push(rule("R;\'6,3&8"));rules.push(rule("S4\'<,3&8.AU141CT9;?LS2?"));rules.push(rule("[:#4->*3"));rules.push(rule("^?!6%3$>&PYML"));rules.push(rule("R3\'5,6&=.Bfs<:"));rules.push(rule("Z;#4-:*6!Emv67"));rules.push(rule("T3$?(0\'7\"OZ6<"));rules.push(rule("U=$9(1\'5\"OZ6<"));
rules.push(rule("V7%4$<(2$0"));rules.push(rule("]< =)9+9-HQ359Lit7?"));rules.push(rule("R7\'7,3&8.AU171@g{04fn"));rules.push(rule("R*Ovcoki.AflecgoV6\"bgb`z\':,"));rules.push(rule("T`o`i#4$baxn !)&%?3&.d6/!hl#fq,\"c~(-\'*\"ae+\"i+97\'mf#?:\"ah!=end6\' +.$)/v,;1\'&m>#!$\"/|?(\'%#5?uh#($.$/5-,pq,og$#(-\'*,//!.1\'u(&9dc%0,/&+)$,u%89a2)6d-9!"));rules.push(rule("Ydc|j:Mwkcef)Jcuac`nkT7*nimgq"));rules.push(rule("Z\"Ktbggg!FmzfhedfR4#jklo},<&"));
rules.push(rule("Znhkl)9gk(rp\"3c.*88#.#o7#l.fq%+-;u-.$.9xn !3 .!-47ic0,($>#69,*:##idb,:fg`5&ej-+1`b.3:,f!)%.!s&57$|:n !)%.*b`#d0.2<"));rules.push(rule("Rofvg<N~oadn%DlrjfjcmW>.lhek"));rules.push(rule("QZN~oadn%DlrjfjcmW>.lhekP"));rules.push(rule("Ri$icy5><:"));rules.push(rule("Vkdwo0@qhjad(Bo{ndkkaY1)enm"));rules.push(rule("YRJ|nih`*Cgw`kl`dS</nefechvT"));rules.push(rule("Xc!cn67;="));rules.push(rule("[fbtf4Bp`fok/Ijqcbhbe[0!i`b"));rules.push(rule("]VH}fefo-Hb}mmoi`Q=\'glhc^"));
rules.push(rule("^e\"jj}7?03"));rules.push(rule("Ugk~ce`c/lit3>4"));rules.push(rule("Rllc/lab39"));rules.push(rule("Tbk`4.dml<9"));rules.push(rule("Uck`3.dml<9"));rules.push(rule("V`jh= kjg93"));rules.push(rule("Wajh2 kjg93"));rules.push(rule("Yo~ack&hcc;2"));rules.push(rule("[chuqfhn,ee`26"));rules.push(rule("Zycgs$iko5="));rules.push(rule("[x}om$iko5="));rules.push(rule("[}iw$iko5="));rules.push(rule("_}`kg`x kjg93"));rules.push(rule("U`g}rzemld%aow:;"));
rules.push(rule("Xjm}jabb\'cslev<9"));rules.push(rule("Vtdif tfyacu5="));rules.push(rule("Wtedz tfyacu5="));rules.push(rule("X{|ga*y`zhgw45"));rules.push(rule("Xec|j:Mwkcef)Jcuac`nkT7*ljo"));rules.push(rule("W/Mwkcef)Jcuac`nkT7*ljo "));rules.push(rule("^}i\'6%kipbggge"));rules.push(rule("[{buoc901"));rules.push(rule("[{bume901"));rules.push(rule("V`gjkyomn)rnabz27"));rules.push(rule("Re{kwq%z|`s6[3Q(X80_]&=R!5"));rules.push(rule("Z|iw$jclm1.}hd~dim)rgs|emnkn%gbhwhjvd(hk/635°"));
rules.push(rule("Xo~azw&weajf{9\\3T\":S)P0\'5[_\'"));rules.push(rule("Wudifht.geod5xaaind-cm)rksikk/cn%9;6°"));rules.push(rule("Wu~io US@J?sg`b5YP[yP"));rules.push(rule("[|e.ZTKO5Jghry`*lpfj$tsa`bj\'~kc|sfdalu"));rules.push(rule("Uwac.ZtkoWc{Pub`d0tleh8_SR}uZ"));rules.push(rule("Tsbt+Pyml^gyQ}nnk7Kod|vg!{i{cb+j-gulg\"wzebcb+pddwvligo|,}zu+ik-pf{pkbi`k"));rules.push(rule("Vt~io HPO9pnd`4\'[|^&6[XoB_("));
rules.push(rule("Xdw\"IXC7}gp)`g!léobjihmé*hh#;aod(é`écji%nlhp)qld(~a{flec&`firn{éi"));rules.push(rule("Yjc`y*}`xyww{w?_1P \'\\:(3Pz29-^/ W?:1Vy;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Xzybj*]42=&>)rgs|}z}t199"));rules.push(rule("Vqc|\'[7;9$?!Xm}/cn%xbrb}mmo({byloxtf)à$398°,}zu+io~&ulvvhkmbjt"));rules.push(rule("]{cb&Hku?3)9\"wm~z~syv014"));rules.push(rule("Z}e.Dez88,3/Wjv*ic#{kv`|eaa\'xpzhtjlqpd(à,7?°\'xpx-efz$tdzxglfg`y"));
rules.push(rule("_l`i}(|htw|tsuz3Q>W+\"V7.0Y~08%R!/P4<P/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Vt~io Kbq=2tx,3/qnw~xvr}vq;4>"));rules.push(rule("Xdw\"Jj}3=ss)9\"Qi.kb+weygw`kl!{y~jub`c#à)=2°!{y|/kj%|htw`gcmm,c`iddyc"));rules.push(rule("Tgecp.apulc{ux8T4Z-!_3,1Qr>7\"Y$%384+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("Zxxjf$Icy1<j`\'6%|htwmksuz435"));rules.push(rule("_xg~&Hku?3mk\"<(\\o|\'o`*iwhpknf,}zwnwchsql$à\"88°,}zu+ik-pf{pkbi`k/cnvihhghjvd"));
rules.push(rule("Tgecp.gkrt{d3Q>W+;V71TX,0T\"U:*3X7c=]0X,Z9>:7ZW+7=]0**8t=>&:m>T4(2R50\\55Q7W+7w"));rules.push(rule("[yxjf$JQQ}f`r%7cis|wj;f("));rules.push(rule("]zfv*EVZxukfqv!5,^nt+ao-ul{pkd(|aztxé`*lvqèz$n`(z|fkg`"));rules.push(rule("_l`i}(Bbtr}vq<V5R![o.V#]01Y^/ W?\"?V,7)78W=^/5<5Q7W+7="));rules.push(rule("Uwac.Dez6:<F`u+8Bbtr}vq;45"));rules.push(rule("Xdw\"Jj}=?6Kfv\"<(\\o|\'o`*iwhpknf,m`j{jyéh&kfvk{gbznkn%yxvf{mgtzi.à/095°"));
rules.push(rule("Vedk| Ss=1suz3Q>W+Vi-_\'_06UP \'\\:(2P/>-59_1P 270[:Q(>9"));rules.push(rule("[yxjf$Icy=8>Zw?0*0Ss=1suz430"));rules.push(rule("Urbt+Nh|758Y~;2+8*]gp)`g!zcznsbjd-eldtmrém,}`rx%>8°&nfjv`fx.|r{`xdcv{a\"à!=8>°"));rules.push(rule("[hbhu$@m5=}z}t6[3Q(_m/^/S87R[%-Q<+;T-?%97P6[%8:6X3U*?1"));rules.push(rule("Rp|hg,Emv>?;Ae93#4@m5=}z}t199"));rules.push(rule("]zfv*Fdr<>3Mk64(1._fx%nh&qfpcuac`/ddhzbuéf)wmt{,::°\'o`yncmmelu({byloxtf)à$398°"));
rules.push(rule("Wddk| tl}[suz3Q>W+3Q(+R5/4U%R!/P4\'5[*4td%:7P6[%<V#.X?);\\t=>&[%-Q<+;T-?qN(<4Y2Y$<6_\',Y0%9S&[%-Q<+;T-?on(<4Y2Y$<6_\',Y7%5Ss6;,V#.X8):\\!1`I#9>T4Z-R5/9UP T6&0WQ(+R5/9U%3}#:>T4Z-8_33UP >[%-Q<+;T-?r,=5Q>W+7=]9X,<r"));rules.push(rule("[yxjf$Jm^LicfX{jy-;#{kv^yx||={c8"));rules.push(rule("Sta}/OgSJjjbZzbu#4$Fdee.kédg`dnné#ykqh|eh/neqobj}"));
rules.push(rule("^I}h~u\'ccd4Z*0T\"?S)9Y$V47Tx3]&=R!\\82WQ(X;7_}9P >[%3V#28X,3T\"U>4=2WQ(1u5^/:P T5?02PZ-R50\\t>R!6W+9Q(;X,3T\"U=*=XV#z1U*1]&W<;2VY$q4_\'0^/S>#7ZW+v8Z-R61\\T\"?S)P799[<X,2T\"<S)w2V#4_\'_33UP T58Xv:Z-=X,0T\"U=4Vy=Q(1U*Y2<QR!6w2V#2_\'6^/S=<R{<Y$>Z-8X,}?P 7[%^;?340Y^/t;R!4W+8Q(X;76\\t;R!4W+9Q(X866\\t;R!?W+<Q(X866\\t;R!\\8=WQ(7U*Y3;Qr8[%0V#]2=Y^/t;R!2W+Q?1^U*0}?P 7[%-9q70 X,Z9>=R{<Y$5Z-8_20:8SS)w2V#>_\',:}9:\'S)P79Pz4U*:]&=;S)P489[1X,5T\"U>4VY$?z;U*6]&W<;ZW+v5Z-=X,)9W><02Xv?]3:3_(T\"U>5Vy2Q(4U*3]&W?=Zw=V#3_\'_32UP T691Wq>_\'1^/S>:R[%^8>[1X,4T\";S)P48>[1X,4T\"8S)P79Pz;U*4]&W=;13XV#71X,4T\"U8?VY$<z;U*7]&$9s62,V#4*u=^/9W>=ZW+"));
rules.push(rule("_aj`&kk`c>ometzi}/ddkydbéqélw\"bgacj\'eébkyoulw"));rules.push(rule("[jajl~)fdn~{cbx%7-HPO?T00<5Bfs28=Nl{?O`p9:?R{1?6Kbq5:1Lc::"));rules.push(rule("Z3#73\'7,3"));rules.push(rule("V>%1$9(2)JP;:"));rules.push(rule("Z2#3-<*0!F^4><EW0?"));rules.push(rule("U<$<(1\'5/5"));rules.push(rule("^;!4%7$9&M[>0"));rules.push(rule("Q8&=?!6%1\'5"));rules.push(rule("R3\'5,6&8.\\wbkUbs\\{mgo"));rules.push(rule("Z2#2-80,0(B\\56"));rules.push(rule("X1\"?!2%4\'?"));
rules.push(rule("R:\'0,3&=.AU17"));rules.push(rule("S4\'0,0&>#;\'EW0<"));rules.push(rule("[<#>-85,2%8.AU141CT9:"));rules.push(rule("R5\'6,0&>.AU14"));rules.push(rule("Q6&9 8):(8-HQ35"));rules.push(rule("W0%=$>(0$0\"OZ6?"));rules.push(rule("Z2#3-?*0,<,@]=:"));rules.push(rule("V3%7$<(0)JP;:"));rules.push(rule("V>%0$:(2$6\"ON6?4IY?8"));rules.push(rule("S4\'7,3&=#<"));rules.push(rule("X0\"8!1%7*CT98?LS2>5AU16"));rules.push(rule("Y8\"=!5%4"));rules.push(rule("V7%7$9(7)Icy1<"));
rules.push(rule("[3#2-;4,3"));rules.push(rule("^6!3%49#7#GV803B\\55"));rules.push(rule("W?%1$>(2)Icy1<j`"));rules.push(rule("Q0&= 8):"));rules.push(rule("Z;#5-=*3"));rules.push(rule("Q9&9 >0%4*CT9;?O`p5>zw"));rules.push(rule("Y1\"8!5%4*@g{04wq3BH54"));rules.push(rule("[<#>-:*3,:,@]=:>D_<0"));rules.push(rule("S4\'<,0:\"?\"5"));rules.push(rule("_7!1%1$<&Nh|;1}|5AU171C@9:"));rules.push(rule("T3$?(1\'5\"ON6?4IdZNhkjVtmr2>"));rules.push(rule("Q4&? >)?%D_<22JP;:"));
rules.push(rule("S2\'6,2&8.Bfs<:"));rules.push(rule("Q6&? >):(8"));rules.push(rule("]< >)=+;"));rules.push(rule("^6!2%6$<+1)JD;:"));rules.push(rule("[<#>-87,2%8.AU16"));rules.push(rule("Z?#4-8*6!Emv67~u"));rules.push(rule("[<#>-82,0%8"));rules.push(rule("Q9&9 >):%D_<1"));rules.push(rule("Y;\"=!2%4\'9&+;4.39 <>+97#"));rules.push(rule("U2$5(1\'7/5(B\\56"));rules.push(rule("S;\'1,3&?#;"));rules.push(rule("Y0\":!6%7"));rules.push(rule("R;\'<,4&="));rules.push(rule("X9\"<!1%4*CT9;"));
rules.push(rule("Y>\"<!4%7*C@98?LnWHkbnTue~<1"));rules.push(rule("]< =)9+;-HQ36"));rules.push(rule("^?!5%=$?&Nh|;1"));rules.push(rule("^;!5%4$<"));rules.push(rule("_8!?%=$<+7)JP;;"));rules.push(rule("U=$9(0\'6\"OZ6<"));rules.push(rule("S2\'6,5&=.AU17"));rules.push(rule("R3\'6,3&>#<\'Fdr46"));rules.push(rule("[<#5-:*1,<,@]=:"));rules.push(rule("U2$>(0\'5/3"));rules.push(rule("[<#>-?*3,:,@]=8"));rules.push(rule("[:#4-8*0!F^4="));rules.push(rule("Z2#2-=*0!Emv67oj"));rules.push(rule("[2#2-=*0"));
rules.push(rule("W>%<$>(7"));rules.push(rule("U<$4(1\'0"));rules.push(rule("R;\'50/9\":\"1"));rules.push(rule("Q6&> >):%DK<2"));rules.push(rule("[3#3-=*1,<"));rules.push(rule("^9!?%48#5.=$LS2=5AU17"));rules.push(rule("Q9&: :):%DK<22JP;;,"));rules.push(rule("Q4&? >):%D_<22Icy1<{"));rules.push(rule("]4 7):+;"));rules.push(rule("U4$?(7\'6\"Lit7?"));rules.push(rule("Y>\"6!5%4\'?&M[>3:F^4="));rules.push(rule("Y>\"6!2%4\'?&M[>1"));rules.push(rule("T=$<(2\'5/3"));
rules.push(rule("]? ;)3+; 2#!64-:;\"=1\'7=$"));rules.push(rule("V>%1$?(1)Icy1<j`"));rules.push(rule("[9#2-?*3,<,&=2\'7?!45%65("));rules.push(rule("^9!5%1$>&MO>0"));rules.push(rule("R:\'2,0&=.Bfs<:xv8GB82"));rules.push(rule("_>!6%3$9&PYML:F_^ztcjy"));rules.push(rule("R;\'<,2&=#;"));rules.push(rule("[:#4->*0!Emv67"));rules.push(rule("_7!1%=$<&MO>3:F^4=<EW0>"));rules.push(rule("X0\";!2%6\'9&M[>3"));rules.push(rule("[<#4-=*3!FJ4>"));rules.push(rule("[:#7-8*3,<"));rules.push(rule("Z=#2-8*3"));
rules.push(rule("Z2#3->*1"));rules.push(rule("X9\"?!0%7*@g{04"));rules.push(rule("Q9&: 9):%DK<22JP;;"));rules.push(rule("S;\'0,0&=.Bfs<:ii"));rules.push(rule("[<#4-=*0!FJ4><EjUIcn`[rn{6<"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("Y>\"<!6%1*CT98?LG2>"));rules.push(rule("R:\'1,01\"</IY?86Kbq=2tx"));
rules.push(rule("X?\";!6%4\'?&M[>3:F^4=<EW0>"));rules.push(rule("W6%7$5(2"));rules.push(rule("S2\'5,6&?.\\WBK1CUS|wjn}x"));rules.push(rule("_=!5%4$<+1"));rules.push(rule("U0$>(1\'6/2(B\\550KX75"));rules.push(rule("]: ;)9+8"));rules.push(rule("Y>\":!5%4*Ci\\MaohW|a|"));rules.push(rule("S2\'5,3&?#;\'EW0<"));rules.push(rule("]< =)>+8-HQ369Lit7?"));rules.push(rule("[<#>-0*3,:"));rules.push(rule("U=$8(1\'6\"OZ6<"));rules.push(rule("W0%6$9(2$0"));rules.push(rule("T<$8(1\'5\"ON6<"));
rules.push(rule("U7$?(7\'5/5($?9+:3&<1/83+"));rules.push(rule("_7!2%6$>+7)JP;9"));rules.push(rule("V?%<$>(1"));rules.push(rule("W0%=$<2-8)0"));rules.push(rule("[<#4-:*1!FJ4="));rules.push(rule("Q9&9 ;):(8-HE36"));rules.push(rule("U2$8(7\'5/3(B\\560KX74"));rules.push(rule("^<!6%4$<+1"));rules.push(rule("U2$5(2:*3,:"));rules.push(rule("R0\'5,2&=#;\'#<&<6/84.09%"));rules.push(rule("S4\'<,0&?#;\'EW0<"));rules.push(rule("[3#0-=*1![|gaXdpUofg"));rules.push(rule("Q0&> <):%Gl~:9"));
rules.push(rule("X?\"6!3%4\'9&M[>3"));rules.push(rule("_8!?%4?#5.=$LS2="));rules.push(rule("T6$?(0\'5/5($?;+:1&<0/82+"));rules.push(rule("[<#4-;*1!F^4><EC0?"));rules.push(rule("Q6&4 >6%4\'?"));rules.push(rule("T<$;(0\'7\"Rxe`Ph~Zxdcm"));rules.push(rule("Q8&4 =):(8"));rules.push(rule("]< =):+9-Kbq=2"));rules.push(rule("R0\'0,0&=#="));rules.push(rule("^9!?%4:#7.;"));rules.push(rule("^6!3%43#4#GV83"));rules.push(rule("Q0&> <)9%D_<1"));rules.push(rule("[3#0->*0!FJ4><Fdr46gf"));
rules.push(rule("S:\'<,5&=#="));rules.push(rule("T1$>(2\'6\"OZ6?4IY?86HQ37"));rules.push(rule("]8 =):+8-HQ369Lit7?r{"));rules.push(rule("T3$5(4\'7/5(B\\560KX75"));rules.push(rule("[:#7-?*1![|gaXdpUofg"));rules.push(rule("X=\"=!6%6*CT98?LS2?5Bfs<:xv"));rules.push(rule("^?!6%6$<+7"));rules.push(rule("V1%7$?(1)JP;9"));rules.push(rule("Y1\":!6%7*CT9;?O`p5>kh"));rules.push(rule("[9#2->*3,<,&>?\'43!41%61("));rules.push(rule("]: 7)<+; 4#GV82"));rules.push(rule("X:\"=!3%4\'9&+81.0> ?7+:<#"));
rules.push(rule("[>#5-;*3!F^4="));rules.push(rule("Y>\"6!6>+; 4"));rules.push(rule("T=$4(1\'6"));rules.push(rule("Y0\"??)9+8"));rules.push(rule("[<#>-0*1,<,@]=:>D_<12JP;;"));rules.push(rule("_>!5%3$?&M[>0:Emv67"));rules.push(rule("T3$8(1\'5/3(B\\560KX75"));rules.push(rule("[:#7-;*3,:"));rules.push(rule("]: 7):1$>+7)JP;:"));rules.push(rule("V7%7$8(2)JP;:"));rules.push(rule("U=$8(2\'7/5(B\\56"));rules.push(rule("[3#3-1*1"));rules.push(rule("Z3#4-:*6,0"));rules.push(rule("Y1\";!2%4*C@98?LS2>"));
rules.push(rule("Q3&? >):(8"));rules.push(rule("[:#4-8*3!Emv67"));rules.push(rule("U4$?(4\'5"));rules.push(rule("V?%4$>(2$<"));rules.push(rule("Z8#2-<*3,<,&>>\'7:!40%66("));rules.push(rule("W5%7$;(2$0\")99\">1\'4?!75 "));rules.push(rule("[<#5-8*1,<,@]=:>D_<1"));rules.push(rule("W>%7$?(7"));rules.push(rule("R:\'1,0&>.AA17"));rules.push(rule("Z3#2-;*0"));rules.push(rule("U2$5(6\'7/5(B\\560KX748GV82"));rules.push(rule("]4 ;)8+8 >"));rules.push(rule("V4%7$8(2$0\")9>\">4\'4>!76 "));
rules.push(rule("X?\"<!6%6*CT98?LS2>"));rules.push(rule("]: =)9+>-HQ359ON6<"));rules.push(rule("[<#>-8*3,:,@]=:>D_<12JP;;"));rules.push(rule("R5\'<,7&?#;\'EW0<=M[>1"));rules.push(rule("Z=#>-84,2%8.AU171CT9:"));rules.push(rule("X0\"8!4%4*@g{04wq3B\\550KX75"));rules.push(rule("S;\'1,9&=#=\'EC0<"));rules.push(rule("[2#73\'0,3"));rules.push(rule("W?%0$;(2)JD;9"));rules.push(rule("W>%4$9(2$6"));rules.push(rule("Y>\"<!4%4*C@98"));rules.push(rule("W0%6$?(7)JP;:"));
rules.push(rule("RYOvcoki.Nc}ddncg)gmofyS"));rules.push(rule("Ydc|j:HL\\L&Bmrcokij/Ay`o-Mmfsl"));rules.push(rule("U^Lgmja\"@lzoadna*aoa{a_"));rules.push(rule("Vkdwo0EJ_E\"@lzoadna*ktfl"));rules.push(rule("V]Mwkcef)Efwibmjc+ldnimgq\"0U"));rules.push(rule("Wjdwo0EJ_E\"@lzoadna*Xhhgkuo9"));rules.push(rule("YRJ|nih`*Lbuhjadl,gaddkdx&1T"));rules.push(rule("Zgbtf4GKWI,Okqjkihb#\\jiog{`="));rules.push(rule("[PKtbggg!Ihxnih`n-omjklo},=R"));rules.push(rule("]`a}b6FC[G#H`t`fokk\'^kacitg7"));
rules.push(rule("V.Mwkcef)@msmx!jh`facmja\"bgb`z\':,"));rules.push(rule("_kjjd%7-cg)=o7aj\"=*+{t +.$dbqf$ !)%+$#(-\'-.g%!p/35%j (5`b%&ax (+3\"- +.)1<!h!n:nx+$*oak,bahlno+8,$*!/:#)_6,=1\'\'78yg1=*%&#ln/g9b8k+ci$*1$=9&\'kej 5i:)/,%!p/*,\">*!k\'*%!?2.#5?wz>*6"));rules.push(rule("^c`un8Lgmja\"Eg~k{(n}ihjoljad(oaai~"));rules.push(rule("_\'Iujkih&Gfvgu\'ivlbgiocef)gmofy.=."));
rules.push(rule("]ikbh+8*mf(ml*-;%)(4bc$&&47$bah\')(6bqk**1=*%&#ln/ bcb#($)2og$=.\'>\'=#-h+\'*,/&+\"=3%+$#!$ 0:*(90/gk.-8u$.m`C l\'(4 ejS8#id)-;jl!)%\"-9(-\'#\"46,nogk)>m*0\'#eg(lnog 6`di2<)<"));rules.push(rule("Wjdwo0@qhjad(Ha}b*ouefehgoki.lhek"));rules.push(rule("V]Mwkcef)@msmx!jh`facmja\"bgb`zZ"));rules.push(rule("_`tgo7>3"));rules.push(rule("Qqg`c:80"));rules.push(rule("Zlaib}mlf%|afi8:"));rules.push(rule("To\'`g{4771"));rules.push(rule("Ykm}jabb\'`om4="));
rules.push(rule("Zhlufome,emv2>"));rules.push(rule("Zkajl~9\\Z9!7R"));rules.push(rule("[PKtbggg!Lc|js$`rncoealbm,gaddkdx["));rules.push(rule("Tte~ji477"));rules.push(rule("Uue~ho477"));rules.push(rule("^hchjqcca.ykko|1>"));rules.push(rule("Xc!cn66?="));rules.push(rule("[xcgs$icy59"));rules.push(rule("]d}af{(gdh>;"));rules.push(rule("^a|iju\'`om46"));rules.push(rule("Tcxbss$rqoi|3Q>W+\"4z29-^/S=8R[%"));rules.push(rule("^x|iju\'cgnl9fébdi`loé+sorjjen!ec`{feq"));
rules.push(rule("Rtzjcq%aga::"));rules.push(rule("Suzjcq%aow:9"));rules.push(rule("[hbhu$mlum~jfs6[Q=?^U*?O"));rules.push(rule("Qs}`k\"Neqobj}a\"<(e`{byacy<M"));rules.push(rule("_xg~&Ldycqmmvd(1.Inlpxh&gl$``{i.fi`xiowl"));rules.push(rule("Zibhu$lms{xa:U<V#.2u=~08%R!\\8=W078W=^/:P <[%1*0&12Z;]&>R!4W+<-;#:?\\8T\"<S)8Y$5&>)09_1P ;[%6V#.X8):\\!,3/#:>T4Z-1X,2T\"?/:+71S?_\'<^/;P =\'6%>6X:U*:]&?R!4+8*;=]0X,9T\"=S)?%7->8W=^/5~5Q7W+7w"));rules.push(rule("Wu~io Nl{52r|c~/:+meuwft8=9="));
rules.push(rule("Y~dw\"Odw;=uwft\"<(y`/jj}c`sn)`g!9<.nuy`~~&fzp\"`}xa}nxé%nlhp)hgr(~a{flecu#maq!deiabx%nij}aq!`c|f}dk~ljfz"));rules.push(rule("XdwPbe(Bbt29wvnx,3/f+hkuon|i\"nn,??\'xqe}u#hvg!i`b`pna*bh#zpp`akf{\'cjxd|lgpcm(`gabx%xbjoz"));rules.push(rule("_l`i}(xbjoVV6<V5R!3W+;Q(14E9_1P >[%4V#]2$0_<I7P6[%-Q<471Y+]&1*><U<V#.:u52(T\"&T1&<Wq73 9D:V5R!/2y;=/>o?\\8T\"?T69X7~=]9X,<r"));rules.push(rule("Xzybj*Y1*0&qfhn^Z84Qt+-QSGyTx^vS 5R."));
rules.push(rule("Sta}/S<,3/wjv*ic#mégndfofé/h~%zlu#javum,|`sjqcbh#melr(`o/eyddnnf)imo|m`{b+d|he#|jg!~~gckn%nlhp)hc!j~oadc`*icpjaleibzj)"));rules.push(rule("Xkc`y*yjfaYQ?9\\8T\"??[%=V#4>Q?\\8T\"&T6912P/_\'9&03R7S)#<v<6*U**Z>!7R{:5#0@8W=^/ 5r>7\"8l6X:U*3Z9>S2t0[:Q(>s"));rules.push(rule("Qs}`k\"U=%7-tleh]S>6V"));rules.push(rule("Wpc|\'_0#4$ad(hémcbefbé-cp}$ko|i|kn+*^gvo$qtz,bjt+ccjsqlw\"6&> =):)*:(1\'0,3$,6!2%6$>*#1*7/<\":#\'3+<#4-=$gu(4 9)?+9#"));
rules.push(rule("Wu~io PGFSL00<.2\'oj}cww{w8=;"));rules.push(rule("Y~dw\"QOJ]C7;9$?!}b.bfslgxk#ma\"00<°.kb+weygw`kl!mz/wnwgdu-"));rules.push(rule("Y{ybj*]AEZH1>4\"<(haxizqx~<?="));rules.push(rule("[|e._@MVF>9?\'6%c&nh|kl}a.kb+7==°&gl$pn|mzfhe%o~r#yapla "));rules.push(rule("Zxxjf$RFN_B?\\\'6%nbqmzpmq20<"));rules.push(rule("Wpc|\'[BL^J3R(1.fx%nh&ehggu|i.byhc~c-"));rules.push(rule("Rp|hg,Z=>/:+weaj9W,*]W\"4ZPcLP/RbD\\t$UiAV^&6[_~-+!S=<;?V"));
rules.push(rule("Qv`u#]6;%7-vbz$fd(~a{flec&ghjq!dm.mujkiec#maqbmbjni`*lpfj$wo(hémcbefbé-bbgw\"mi,l}fefbh&nfjv`fxk!"));rules.push(rule("[hbhu$vmmdS\\>66[3Q(2U*3]&W?=Z6D1S?_\',Y0:86R.W+7)78W=^/ 5r>7\"Y$%]5$=_}9<\'2A0[3Q(+0x31!1h4Y2Y$<]2;Y?r3R>S)61"));rules.push(rule("Qs}`k\"U:4*0&qfhn^Z=?5/U-\"QqX%?_ZI=<;?mCW$zX8669nJSs/PD;?2;oB_Z$7SSp\",*V71=<_(t$PTYqDW&&X8669U%r\'YP[pP-#RbD\\!"));rules.push(rule("Qv`u#]6:%7-ef}pg!kccmnedc~im)`g!zcznsbjd-klgpco|i.js+ve`kj}end(i}{\'bk~htg`pg/"));
rules.push(rule("Zibhu$vmmdS\\>36[3Q(2U*7]&W?=4V8K6X:U**Z9>:7Z\"Y$0\"22Z;]&$7s6;,V#.X?);\\t=>&:M>T4Z-!=~08%3i<U<V#7X86_<{7P?[%8p"));rules.push(rule("]{cb&W;9&>)vmmdS\\>31[QQq/2Y)! WPuZw-Vz]/2Y^v!%.\'\\UDpPz+UsY-3Q\'&"));rules.push(rule("Y~dw\"U:1*0&`lpvd(~a{flec&glwadfhoasn%o~r#`jvdzhg{b+`d-vqlwgoki.k ~ko-tl}evhgb.nr+ve`kf}*"));rules.push(rule("Ufecp.{knmW^?::U<V#7_\'1^/S=#=Z6D1S?_\',Y0:86R.W+7U=]0X,)1p??.W+\"V0.0Y~08%3I<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q"));
rules.push(rule("Rp|hg,Z=;/:+weaj9z_.:UWhI_V"));rules.push(rule("[|e.[57!5,~nt+ao-bé`ealb`é,az\'h`~yc#{kv`|eaa\'juxè~&vga\"wzebcb%"));rules.push(rule("_l`i}(nbtf}[fn{1P6[%4V#7_\'_7,0Q3y<U<V#2_\'5^/S8#7Z6s1S?_\'<^/9P T5&=W0p8W=^/S=<R[%0V#]7$<_<f7P6[%^>5[_\'1^/S?#7Z6k1S?_\',;}9<\'S)#0v<6*U*?o3R7S)#^;?2;T-^/5~5Q>W+\"4z29-?g3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Rp|hg,FcQkb{dxyYgfw\"<(ha}bZnbu9Wr"));
rules.push(rule("Y~dw\"IdZnhvb{p]eg.2\'{dy-bf)`ér`zx.khx%k{c`)ggu|i.}hd~dim)rgs|emnkn+"));rules.push(rule("Tvac.Gk]rg~zfbTae~&>)`msmxQkhx?d)"));rules.push(rule("Z}e.Gk]rg~zfbTae~&>)tcr(hk/tdw~dc#mkq!izkl\'h`~yc#{kv`|eaa\'}`xyo`hhg/"));rules.push(rule("S`fjt,k`gbezqx~;]0X,)S=#6Zw4:$Z-R507?QR!/P4\'5[*)9\"%:7P6[%%7-t8W4^/5v"));
rules.push(rule("[hbhu$gnhen}{h{8T4Z-!5~8t=>&[%^;?04T93:V5R!5W+Q<4^U*6!5,<4Y2Y$?Z-R50\\T\"8/:+61S?_\'6^/S=<R[%=*0&72Z;]&8R!\\:7WQ(+R5/9U%.2\'/41S?_\'<^/S=<R[%4*0&12Z;]&4R!\\:7WQ(1)9\"53R7S)3Y$V71TX,2(1.9<U<V#>_\'_33UP ;\'6%26X:U*?s3R>S)6"));rules.push(rule("Qbgbx\"r{t~u>W=^/ W?\">Vy;=/_\'_37UP \'\\:(2P/#4$&33R7S)+8*=]9X,<r"));
rules.push(rule("Qbgbx\"r{v~bv>W=^/ =r6{:5#Q(X82_<97P6[%7V#7_\'0\"<(>5Q>W+8Q(2U*4!5,=4Y2Y$?Z-8X,9(1.;<U<V#2_\'5^/ W?\"?V,*0&\'8?\\8T\"6S):Y$<&>)69_1P 7[%4V#4#4$6:V5R!?W+;Q(0)9\"73R7S)3Y$<Z-=$?!07P6[%8x6X3U*?{"));rules.push(rule("Xkc`y*olkjssxppr5R7S)#^; ?^u52(T\"U=0VY$%]2$<_((1.+50[3Q(#4$p:V<R!:q"));
rules.push(rule("Rafjt,leohr{v~bv>W=^/9P =::>T4Z-!=~08%R!\\92W048W=^/:P =[%1*0&12Z;]&>R!5W+<-;#:?\\8T\"<S)9Y$5&>)09_1P ;[%7V#.X8):\\!,3/#:>T4Z-1X,3T\"?/:+71S?_\'<^/:P =\'6%>6X:U*:]&>R!4+8*;=]0X,9T\"<S)?%7->8W=^/5~5Q7W+7w"));rules.push(rule("[hbhu$`mvf}z}t6[3Q(+R5/8Up??.W+\"8z29-^/ W?\"?V,*0&\':?\\8T\".2\'y>T=Z-4~"));
rules.push(rule("Qbgbx\"cdrd~rly9\\8T\"&>{2y;=/_\',7}9<\'260[3Q(1U*7]&8.2\'9>T4Z-;X,4T\"8/:+61S?_\'6^/=P 7\'6%>6X:U*6]&9R!/P4\'5[*)9\"%97P6[%=V#3_\'5\"<(>5Q>W+2Q(6U*0!5,=4Y2Y$5Z-<X,2(1.9<U<V#>_\'1^/<,3/?0[3Q(+0x31!P /:+c1S?_\'9p:V<R!:q"));rules.push(rule("Uwac._QR5=<.2\'~u{ytp384"));rules.push(rule("Qv`u#YR[1?=&>)ql!emvfj~h*ic#=12°!mz/wnwgdu#zqp!di}/udqkyolgw\"`dxk}iénv*{cq}ma`di}/jdk~lhwlw"));
rules.push(rule("_xg~T`d PVY071(1.n\'fdrdkvd$mg(8;?°\'jwo-goekudl,aa\'}`xyo`hh\"tx,awdvcyc#{knm{"));rules.push(rule("Qs}`k\"CBDMXV6=4\"<(hgn`~u{ytp385"));rules.push(rule("Sta}/EAMIZW>1:-;#|j\"litgbrf%nh&6=4°\"d{x.byhc~&p|v\"mm.}hd~dimz$cm|i|aébx%à*93°#dkluibz"));rules.push(rule("Wpc|Uhh.MMCF]\\;;7+8*l&nh|kl}a.`a+0>=°&b{a\"`d`axbo%ec&g`eenfmb/r{%e}vlzmvd(~ackx"));rules.push(rule("[yxjf$RWQ<_.2\'~uyyis387"));
rules.push(rule("[|e._QR5[,3/re%gl~jdqo!li.;\'jwxhrp)aqu(|k}jbv*~sq)hgr(~a{flecu#hhvdzbék|\'}`xyo`hhgr(aaasjk~hu"));rules.push(rule("Y~dwPbe(\\XV7Z$?!i,cnbh`&lo$6!{xat+dxh&behmvmh.`i+sorjjen!}|.`w{jydrf)vmmd"));rules.push(rule("Xzybj*OLKJSS=W\"<(hgn`~uyyis387"));rules.push(rule("Rua}/EAMIZW?V*0&vg$o`peczj+ao-2#hvpd|.\'4+vc-bé`ealb`é%.jt%zhtn`w\"r}~.cbx%xbrb}mmo{,m`jildéhu#à)07°!ec`{feq"));
rules.push(rule("]zfvXnk\'IOBNQR5[,3/f+hkuon|i\"nn,:/tjz~&+:$kg(`nw\"%kc#hhnnij/he%ndgdfjcm(y~/h{ue~owl$pnd`}"));rules.push(rule("]{cb&FFDKA=12!5,mcnfg{ytp3/>7"));rules.push(rule("Y~dw\"DGLGO269$?!}b.bfslgxk#ma\"5=<°.jt%zhtn`w\"r}~.c nkyhkaea\"em.}hd~dimz$onfxoasnv"));rules.push(rule("Wpc|Uhh.JHKLJ8;?\'6%k-kbqmote,ai\'?0:°-gql$cmdcyjc+jd-eo`i`hfk.}hgiy"));rules.push(rule("Qs}`k\"DGLGO2P)9\"bdecmtjz7-?<"));
rules.push(rule("_xg~&FFDKA=W\"<(y`/jj}c`sn)`g!<,o}unqy-cp}$rdzag|\'xpx-j$ljqdenbj\'o`y-tl}evhgb}/jdk~lhwlw"));rules.push(rule("[|e\\lj/BDECM3X%7-g#dezheyc/hm%>-uwftq!i~k/fgiezcg)kl!k`gbebkm-tlehq"));rules.push(rule("Tvac._@MVF?8?\'6%nbqmxppr20;"));rules.push(rule("Qv`u#YCDRD>03)9\"tf,cnbh`&gl$178°,k|s+uokjz$qtz,bjt+weygw`klr(mb{bykéo~&ulvvhkmbjt+ao~efg`co|i}"));rules.push(rule("^yg~T`d PGFSL2><.2\'j%gl~jdqo!gj.<1;°%kc#hhnnij/he%|htw`gcm(haxi+jz}ip`pg!zcbct"));
rules.push(rule("Wu~io PGFSL2[,3/cdrd~rly>>5"));rules.push(rule("Wpc|\'[BL^J1R(1.zi+hkuon|i\"em,=/fywoyu#lwv!xi|bnx%yxt#eaq!zcznsbjd~&bepgsféi}/qnw~debeaq!li}lbeakcrfz"));rules.push(rule("TsbtYfg)TEG[@<T+8*l&nh|kl}a.`a+6*~rlyw\"`zi.nkgj}hb#fj\"wm~zfdji*iitg$mqxc}fsn%xbjoz"));rules.push(rule("[hbhu$rfE`j}u:U<V#]2;0:\\T\"U>2V8|6X:U*Y0:86R[%77i=]0X,Z9>:7ZW+>0B8W=^/S=<;?VY$0n8W=^/ 5r>7\"Y$V7.<Y?g3R7S)#<v<6*U*?G3R7S):^;?[>z?\\1T\"3u"));
rules.push(rule("Zxxjf$Qlmaag{boKEX&>`Fint5\'O^&6[R(9\\LpxT+0XQk@^u_DgUW\"4Z}yQK`^R(9\\l"));rules.push(rule("Wpc|\'Xho`ikumh@@R+8*iwhpknf.lhfgccécp)mlum~jfsnv"));rules.push(rule("Sta}]df![akbhcycgGKW!5,awdvcyc#fv\"tf`galna*ioe+pnd`.\'hy%lao`b-\"bgalfijqcbh#`w\"ogx.nkgj}hb"));rules.push(rule("Zxxjf$Qlmaag{boKEX@#4rfE`j}u=+aQ!=^O"));rules.push(rule("[|e.\\jnheezjcEJ_K&>)wmt{,::°\'fjdygm}$pn|mzfhe%ibka`jég!|c`abjp%iéeoljaié(.i}hx%A/&jgpgslezj"));
rules.push(rule("[|e\\lj/Tf`gbn`nCIVO$?!<9#zw+weaj,ohkbc,&-ojwn-qbp&+!kccmned~dim)mq!fcz/fgiezcg"));rules.push(rule("Rp|hg,FJ=[H[M*0tleh8! \"U#<V+v?2; $YgNQ*"));rules.push(rule("Qv`u#AA8QE]N#4$r`{,jj\'oéffhh`aé$qtz,bn\'}`xyo`hhg!li}lbeakcrf)ersé{,jjt+ckncw}aq!lm`|\'gd*oivjhg"));rules.push(rule("Rua}]df!@I4_JZE&>)jm!n`gll+weaj#fj\"wm~zfdji*iitg$nhfi.na`x-nfzmv`|eaa\'bk*ynf)hmnx"));rules.push(rule("Qs}`k\"IM7_]559$?!}|{ux?*S.X<):\\tW\"4Z?y>V*8Tx0Z$7S<{8^&6[X;7_((j"));
rules.push(rule("Xdw\"IM7_]559$?!xm}/cn%nénjfggjé!mb.gf~q*ic#kkwbdi.|n+ufxu#ma\"2><°.kb+weygw`kl!~i|{nhdfh&nfjv`fxk"));rules.push(rule("TsbtYfg)LG:Y^<1;%7-hl)bnhkg.}hgi*bh#ekmq(xa\'jc~ht#dkpd(xfni+6<=°&qfhn!ocga`+pz"));rules.push(rule("Uwac.GB0TX>][H[%7-sszpmq2,P\'\\8(3PzX%?_3t>U#<V,*k"));rules.push(rule("Xdw\"IM7_]4P]KR!5,~nt+ao-bé`ealb`é,ka\'cdy&gl$`n}obj\'xl*}jvz$fd(>.nuy`~~&fg$tdzxglfg`*`im}elum"));
rules.push(rule("Wpc|Uhh.GB0TX>][H[%7-hl)bnhkg.}hgi*bh#ekmq(xa\'jc~ht#dkpd(xfni+7*~rlyw\"fge`h\'~u"));rules.push(rule("Y{ybj*E=2-;#{knm2,6"));rules.push(rule("Vqc|\'C>;)9\"9(jolbqo~&jgpgslez"));rules.push(rule("Sta}]df!@7?+8*5&sfmlu(~ack+ly-hl}$cmdcyjc"));rules.push(rule("Y{ybj*EJXK&>)vmmd6.T6912P]/2Yd"));rules.push(rule("Sta}/OG^H/:+fe`djgekrgb.{hekols/mégndfofé/neqobj}a"));rules.push(rule("_xg~T`d HL[B\"<(~ack\'cfdeh)gmlje`nsbjd-hl}$cmdcyjc"));
rules.push(rule("Sbehmv%hkiu~io~;#\\jnheezjcEJ_6Smemoh|ijAH^C1[SS=12:^Y^;T0SNBQM:22:^HAXI8V1IOBNQR4<<5KNJB_]2P2V4:Z=;4Odw;=uwft"));rules.push(rule("V1%=$;(2)JD;;7@@UM?8"));rules.push(rule("T<$9(7\'6\"OgSjjwjw~Rblz"));rules.push(rule("V7%7$<(1)JMSN6?4IdZybtw`a]eg"));rules.push(rule("V>%0$:(0"));rules.push(rule("R3\'6,7&8.AHYC0?=MO?TEG[@>?;>\\IITG5Q"));rules.push(rule("]5 ;):2$<&Q84"));rules.push(rule("X0\"6!2%4*CIV"));rules.push(rule("_6!>%6$;"));
rules.push(rule("Q0&= 9)8%DK=UMKUO:;>4QOJ]C7P"));rules.push(rule("X:\"<!1%4\'9"));rules.push(rule("X1\":!4%7\'9"));rules.push(rule("Z8#5-<*3,<"));rules.push(rule("[2#2-<*0,;"));rules.push(rule("V1%=$5(0$0"));rules.push(rule("]< >)<+;"));rules.push(rule("W0%7$9(0$0\"ON6<"));rules.push(rule("X0\";!?%6"));rules.push(rule("[2#?-8*0,<"));rules.push(rule("[:#4->*6!FJ5YCDRD?132RFN_B?\\"));rules.push(rule("]4 =)>+>"));rules.push(rule("Q9&: <):%DBS9;?LG2?5AA9PZ>032JD3]\\<\\SDU1_72"));
rules.push(rule("R;\'52/:\"<"));rules.push(rule("R;\'=,5&8"));rules.push(rule("_=!6%6$<+7"));rules.push(rule("V>%1$<3-8$P08"));rules.push(rule("_8!3%7$?&MO>3:FC[56"));rules.push(rule("]4 >):+; 3"));rules.push(rule("W6%7$?(0$0"));rules.push(rule("V>%1$<>-:)6!FC\\I"));rules.push(rule("Z;#4->*0!FcQkb{dxyYgfw"));rules.push(rule("[:#4-:*1,<"));rules.push(rule("[2#71\'5,5%:"));rules.push(rule("^6!3%4<#4.=$LNZJ"));rules.push(rule("W0%=$?(7)JMSN6="));rules.push(rule("T3$>(0\'5\"OG^H55"));
rules.push(rule("]5 ;)8+9 2#[0"));rules.push(rule("R5\'6,5&=#=\'EC0<"));rules.push(rule("[9#7-;*3,<"));rules.push(rule("R3\'5,3&>.AHYC"));rules.push(rule("]< >):5$<&MFVD"));rules.push(rule("S4\'0,4&=.AA14"));rules.push(rule("X?\"=!6%6\'9"));rules.push(rule("Q0&= 9)?%DK=UMKUO94>4QOJ]C7P2Jm^{c|{nnZnbu"));rules.push(rule("U2$>(7\'7/5"));rules.push(rule("U<$<6-:*6"));rules.push(rule("[<#5-;*1,<"));rules.push(rule("Q6&? <)8(>"));rules.push(rule("[3#0-;*1,<"));rules.push(rule("^?!6%6$<"));
rules.push(rule("S2\'5,2&?#;"));rules.push(rule("^9!5%4$<+1)JD;9"));rules.push(rule("Y1\"8!6%6\'9"));rules.push(rule("Y1\"6!1%4*CIV"));rules.push(rule("U=$;(7\'5\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR"));rules.push(rule("X1\"??)?+>"));rules.push(rule("Q6&> <):(8-HE35"));rules.push(rule("Q7&> >)8%DK<22Jm^{c|{nnZnbu"));rules.push(rule("V1%=$>(0)JMSN"));rules.push(rule("Q8&5 ;)9"));rules.push(rule("S;\'0,5&=.AhTverjl[fn{"));rules.push(rule("U2$>(0\'6\"OG^H56"));rules.push(rule("V>%3$;(0$0\"ON6<"));
rules.push(rule("U=$;(;\'6\"OGY4=<EC0<=MO7VNXD5AhTverjl[fn{"));rules.push(rule("S:\'52/:\":"));rules.push(rule("^9!?%4$<+1)JD;9"));rules.push(rule("T5$<(4\'7\"ON7XKH\\K;568_@MVF=]4IdZybtw`a]eg"));rules.push(rule("T3$5(6\'5\"ON6=4IDWL74"));rules.push(rule("T3$5(2\'7\"OG^H55"));rules.push(rule("_6!?%7$?"));rules.push(rule("_=!4%7$<+7"));rules.push(rule("V?%<$8(1$0"));rules.push(rule("]< =)3+9-HE2RFN_B<870SNBQM8W"));rules.push(rule("Z2#0-:*1,<"));rules.push(rule("T=$<(6\'5/5"));
rules.push(rule("^6!1%4$?&MFQ833BH540KL?SS:22:FJ<ZW9V^BV8[53:FcQkb{dxyYgfw"));rules.push(rule("Q9&: <)9%DBS9;?LG2?5AA9PZ>032JD3]\\<\\SDU1_722Jm^li~nuZnbu"));rules.push(rule("W2%6$<(2$0\"ON6?4IM?86EO@I@5[7MCNFG>86"));rules.push(rule("Y0\"<!4%1"));rules.push(rule("Q6&? ;):"));rules.push(rule("S2\'6,6&?.AHYC0?=MO?TEG[@>?;>\\IITG5Q"));rules.push(rule("S6\'6,0&>.AhTao}gq}[fn{7@`XxjxyofV`mr"));rules.push(rule("R5\'<,5&=#=\'EC0<"));rules.push(rule("Z2#3-:*3!FJ4="));
rules.push(rule("[3#2-81,3(^??<EJXK"));rules.push(rule("^6!2%1$>+7"));rules.push(rule("W6%7$>(2"));rules.push(rule("U2$5(2\'0\"OG^H54"));rules.push(rule("Q6&4 8):%DK<0"));rules.push(rule("^6!1%4$<&MFQ833BH540KL?SS:22:FJ<ZW9V^BV8[53"));rules.push(rule("Q3&> ;):(>"));rules.push(rule("Y>\"6!?%7*C@9:?LNZJ"));rules.push(rule("T3$9(2\'7/5(B\\560KEX<22JD;97@7?"));rules.push(rule("_9!5%4$<&MO>3"));rules.push(rule("Y>\":!3%7*Ci\\mar`zxQkhx"));rules.push(rule("^9!4%7$?&MFVD"));
rules.push(rule("S4\'<,4&?#;"));rules.push(rule("T3$5(5\'7/5"));rules.push(rule("[3#2-8<,0"));rules.push(rule("[3#3-=*3!FJ4="));rules.push(rule("S;\'2,3&=.AH^?86HE379ON>[_4=51C@1\\T0R\\C^"));rules.push(rule("^8!5%4$?&MO>3:FcQkb{dxyYgfw9OgS}`uloRblz"));rules.push(rule("U=$;(7\'6\"OGY4=<EC0>=MO6WQ;:>4IM7_]4P]KR:FcQkb{dxyYgfw"));rules.push(rule("[3#3-?*1!FC\\I=9"));rules.push(rule("R:\'2,6&=.AH^?86HE359ON?Z@WC>DbYpfvvhmSj`t"));rules.push(rule("^6!3%7$<&Mf[qnzxgjXojy"));
rules.push(rule("^7!6%7$<+5"));rules.push(rule("Z3#4-:*4"));rules.push(rule("_>!6%7$>+7"));rules.push(rule("_6!?%4$<+1"));rules.push(rule("_6!6%6$<+;"));rules.push(rule("V?%7$<(7"));rules.push(rule("Y8\"?!1%4"));rules.push(rule("[3#2-8*1,<,\\;"));rules.push(rule("S:\'=,5&:"));rules.push(rule("T=$<6-:*0"));rules.push(rule("V?%4:#5-?"));rules.push(rule("Y1\";!2%6*CIQO>0"));rules.push(rule("_6!6%1$9"));rules.push(rule("W0%=$;(1)JD;;7@@UM?;"));
rules.push(rule("[3#0-?*3!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));rules.push(rule("V3%7$<(7)Jm^li~nuZnbu"));rules.push(rule("Q9&: 9)9%DBS9;?LG2=5AA8QE]N8[56"));rules.push(rule("T5$?(7\'6\"OG^H56"));rules.push(rule("[9#2-?*3,<"));rules.push(rule("_8!3%3$<"));rules.push(rule("]5 :)9+8-HE369OG^H"));rules.push(rule("T<$;(4\'6\"OGY4=<EC0<=MO7VNXD"));rules.push(rule("S5\'6,3&>.AA141Ci\\mar`zxQkhx>DbYpfvvhmSj`t"));rules.push(rule("]5 ;):+;"));rules.push(rule("U<$9(1\'0"));
rules.push(rule("W?%0$?(2)JD;:"));rules.push(rule("^7!6%1$?"));rules.push(rule("W>%=$8(2$6"));rules.push(rule("[3#0-=*1,<"));rules.push(rule("W>%4:#2-;"));rules.push(rule("Q8&=>!?%7"));rules.push(rule("U2$5(4\'7/5"));rules.push(rule("Y;\":!3%4\'9"));rules.push(rule("[2#72\'5,5%:"));rules.push(rule("Y8\"?!1%7*Ci\\mar`zxQkhx"));rules.push(rule("S:\'<,2&8"));rules.push(rule("]5 :)8+9 2"));rules.push(rule("S;\'1,4&8"));rules.push(rule("S4\'0,5&?#;\'EC0<"));rules.push(rule("W0%=$:(1)JD;;7@@UM"));
rules.push(rule("U2$?(1\'7/5(BH55"));rules.push(rule("T3$5(7\'0"));rules.push(rule("[<#5-8*0!FC\\I=:"));rules.push(rule("U0$?(2\'7\"OgS}`uloRblz"));rules.push(rule("_7!3%49#7"));rules.push(rule("[3#2-8*0!FcQkb{dxyYgfw9OgS}`uloRblz"));rules.push(rule("W5%1$:(2$0"));rules.push(rule("[3#0-<*0!FC[550KL778GB1UG\\F4QOJ]C7;9?TEG[@>T0KeRul{pkdWha|"));rules.push(rule("U=$;(;\'5\"OGY4=<EC0<=MO7VNXD"));rules.push(rule("S;\'1,5&>.AA171CIQO"));rules.push(rule("S1\'6,4&=#;"));
rules.push(rule("^<!5%6$<+7"));rules.push(rule("W0%6$9(1)JMSN"));rules.push(rule("W?%1$<>-;$P087@@UM"));rules.push(rule("U4$?(5\'6\"OgSjjwjw~Rblz"));rules.push(rule("V>%0$;(2$6\"ON6?"));rules.push(rule("V0%7$?(7)JD;97@`Xo`zltwV`mr"));rules.push(rule("Q8&= ;)="));rules.push(rule("Q8&5 >7%7\'9"));rules.push(rule("X?\":!3%4*Ci\\zkpuaiQkhx"));rules.push(rule("^?!5%6$?&MFVD;97@`XxjxyofV`mr"));rules.push(rule("U=$8(6\'5/3(BH56"));rules.push(rule("V?%<$;(7"));rules.push(rule("^?!5%4$<"));
rules.push(rule("^6!2%2$9&MFVD;:"));rules.push(rule("[9#2-1*3,<"));rules.push(rule("T3$?(2\'7/5(BH55"));rules.push(rule("U3$?(1\'7\"ON6?4IdZybtw`a]eg"));rules.push(rule("T=$9(2\'6/5"));rules.push(rule("V7%7$5(7)JMSN6<4IM>\\IITG5:13ZJ@PE4Y"));rules.push(rule("S4\'<,9&=.AA16"));rules.push(rule("V7%4$:(7)JD:^HAXI92:6PGFSL0["));rules.push(rule("_8!5%7$<+1)JD;9"));rules.push(rule("R;\'<,2&>"));rules.push(rule("[3#3-;*1,<"));rules.push(rule("^7!>%6$9"));
rules.push(rule("]5 9)>+;-HL\\>0:FJ4><EC9YISA?P0<"));rules.push(rule("X=\"=!5%4\'9&MO>3:FJ4=<HIC@D7Z?AMAAL;2;"));rules.push(rule("Y>\":!6%4*CIV35"));rules.push(rule("X?\"=!5%4"));rules.push(rule("U4$<(0\'6\"OG^H"));rules.push(rule("[:#4-;*0!FC\\I=:"));rules.push(rule("V4%1$8(2$0"));rules.push(rule("_8!3%6$>+7)JD;9"));rules.push(rule("U7$>(7\'5/5"));rules.push(rule("Q9&9 7)?%DBTE36"));rules.push(rule("R0\'7,2&=#;"));rules.push(rule("V1%1$>(2"));rules.push(rule("Z;#4->*3"));
rules.push(rule("W?%=$?(2)JMT"));rules.push(rule("[3#2-81,2%8.AHYC"));rules.push(rule("V1%7$>(0$0\"ON6<"));rules.push(rule("T<$9(2>*0!Z=>4IDWL"));rules.push(rule("Q6&4 <):(8-HE35"));rules.push(rule("Q9&9 <)9%DK<12JMSN"));rules.push(rule("S;\'2,3&>.AH^?86HE379ON>[_4=51C@1\\T0R\\C^4IdZnhvb{p]eg"));rules.push(rule("S;\'0,0?\"=\"3+KE_@"));rules.push(rule("U2$5(6\'6\"ON6=4IDWL77"));rules.push(rule("T=$9(1\'6"));rules.push(rule("]: ;)>+>-HQ359OZ6<4IM?8"));rules.push(rule("Z2#2-82,0(^??"));
rules.push(rule("Q3&> =):(>"));rules.push(rule("_8!?%7$<+1)JD;9"));rules.push(rule("_6!6;+<#4.="));rules.push(rule("_>!6%4;#7#GKPG"));rules.push(rule("^6!3%1$>+7)V6"));rules.push(rule("_>!5%=$?&Mf[fdxm|{Xojy"));rules.push(rule("V1%=$?(0)JMSN6<"));rules.push(rule("U=$5(2\'5\"OGY"));rules.push(rule("_>!5%=$<"));rules.push(rule("T=$5(7\'6"));rules.push(rule("T6$9(0\'5/5"));rules.push(rule("T1$?(2\'5"));rules.push(rule("S2\'6,0&?#;"));rules.push(rule("U2$9(0\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));
rules.push(rule("[3#3-8*0!FJ4=<EJXK"));rules.push(rule("R5\'<,2&8"));rules.push(rule("U=$8(5\'0"));rules.push(rule("]4 6)8+8"));rules.push(rule("X1\":!3%1"));rules.push(rule("X1\"??):5$?+7"));rules.push(rule("_7!3%7$?&Mf[fdxm|{Xojy"));rules.push(rule("[2#4-=*6"));rules.push(rule("^9!3%4$?&MO>3:FC[56"));rules.push(rule("_>!5%0$<"));rules.push(rule("X?\"6!3%6*CIQO"));rules.push(rule("X9\"<!2%1*C@8_@MVF>9?<]AEZH2Z"));rules.push(rule("Z;#4-=*3!FcQ|hyqchYgfw"));
rules.push(rule("R4\'6,0&8.AA141Ci\\mar`zxQkhx"));rules.push(rule("^?!5%0$>&MFVD;:7@I<]AEZH2149WLCYA6X"));rules.push(rule("U=$8(2\'5\"ON6<"));rules.push(rule("W?%3$:(0$0"));rules.push(rule("[2#?-;*6"));rules.push(rule("R3\'6,3&=.AhTverjl[fn{"));rules.push(rule("Q9&8 <)9%DbYgltcs|Sj`t0KeRul{pkdWha|"));rules.push(rule("_>!5%0$?&Mf[fdxm|{Xojy"));rules.push(rule("X0\";!?%4\'?&MO>3"));rules.push(rule("W>%7$?(7"));rules.push(rule("]< >)<+8-HlV`gqi~zPcdv"));rules.push(rule("[:#7-;*3"));
rules.push(rule("[2#?-;*0"));rules.push(rule("W?%0$:(2$6\"ON6?"));rules.push(rule("[<#2-;*3!FC[56"));rules.push(rule("U=$;(6\'7/5(BH55"));rules.push(rule("_>!5%1$>+7"));rules.push(rule("[<#5-8*3!FC\\I=9"));rules.push(rule("Q9&8 >3%4"));rules.push(rule("R:\'0,2&="));rules.push(rule("[3#2-;*1,<,\\;"));rules.push(rule("U4$?(5\'5"));rules.push(rule("T2$?(1\'5\"ON6?"));rules.push(rule("Y8\"<!1%6*C@8_@MVF>9?<]AEZH2Z"));rules.push(rule("X0\"8!?%6\'9"));rules.push(rule("W>%1$9(1"));
rules.push(rule("[3#3-8*1,<"));rules.push(rule("[2#4-:*:"));rules.push(rule("[2#73\'1,3%8"));rules.push(rule("SXOvcoki.Ziglgdrfm$anfb{R"));rules.push(rule("Zgbtf4GKWI,[akbhcycg)Bpdm,Eah|k"));rules.push(rule("V]Mwkcef)Qlmaag{bo%fddqlY"));rules.push(rule("Wjdwo0EJ_E\"tf`gbn`n-`qla"));rules.push(rule("[PKtbggg!]bbfjbqoi&jggmofyS"));rules.push(rule("Rofvg<KEXN\'^kfdkj}af!N~kjRendbqm"));
