// OpenAero rulesYY-France file

// This file is part of OpenAero.

//  OpenAero was originally designed by Ringo Massa and built upon ideas
//  of Jose Luis Aresti, Michael Golan, Alan Cassidy and many others. 

//  OpenAero is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.

//  OpenAero is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.

//  You should have received a copy of the GNU General Public License
//  along with OpenAero.  If not, see <http://www.gnu.org/licenses/>.

// This file defines year (YY) and rule type specific rules

//######################################################################################
//#####      Regles France 2014      Espoirs à Doret 2014  Olan 6.0  ###################
//#####      Regles France 2014      Version 2014_PN.1.00            ###################
//######################################################################################
//######################################################################################
//#####                                                              ###################
//#####      Modifications et corrections 2013 pseudo numerotation   ###################
//#####      Modifications mineures (commentaires) et connus 2014    ###################
//#####                                                              ###################
//######################################################################################
//#####                                                              ###################
//#####      Régles de l'inconnu Doret prises en compte, à affiner.  ###################
//#####                                                              ###################
//######################################################################################
// prog 2014 : Espoirs, Desavois, National2, Doret

//##### (Une partie des) Regles specifiques à la France.

rules.push(rule("T_Lgmja\"d{|afux%ibhm|Y"));rules.push(rule("[ohkl)9\"j:,81\'uh8-ouz*,//+.o5yf*%+:%54((a#/*,\"&<!$$$/3-,81\'&6` +.$z|!6,#= +;*s-0c$j/&\"p/h"));rules.push(rule("Xc!cn648="));rules.push(rule("Xec|j:Mwkcef)aqqge||\'jif"));rules.push(rule("ZQKtbggg!m~`nyv*dh`fjltU"));rules.push(rule("[` kbq9338"));rules.push(rule("[fbtf4Bp`fok/bxuedtp)enm"));rules.push(rule("[PKtbggg!m~`nyv*aoa{a_"));rules.push(rule("^e\"jj}7<53"));rules.push(rule("Ugk~ce`c/lit3>5"));
rules.push(rule("Rdhi7,ee`26"));rules.push(rule("Sehi5,ee`26"));rules.push(rule("Tbk`>.dml<9"));rules.push(rule("Uweaj.dml<9"));rules.push(rule("Vu{ld kjg93"));rules.push(rule("[n`vwphkom!cn65"));rules.push(rule("^lntnccj+qltg`|1?"));rules.push(rule("[ybjo$vgqmmz25"));rules.push(rule("Qsg`b\"sdqxhvfhp?0"));rules.push(rule("Ydc|j:Mwkcef)aqqge||\'jif"));rules.push(rule("W/Mwkcef)aqqge||\'jif$"));rules.push(rule("Qrn,3/foskcefm"));rules.push(rule("[{buoc931"));rules.push(rule("]}a|ig8;="));
rules.push(rule("Wagjkyomn)rnabz27"));rules.push(rule("Vayj}+w|vlqg3Q5W+Q<+7TX,0T\"?"));rules.push(rule("Vr~wd}ip$jclm1.ynydmhu#aluzi"));rules.push(rule("Ws~wd}ip$icy5="));rules.push(rule("_}zkn(Y]OM4vmmd6PTYxX"));rules.push(rule("Tsbt+PYML<Neizun%k{c`)rphd`k/rel{xcnljv"));rules.push(rule("Tgecp.{kv^i`z/:+[3Q(_m/^/;P \'\\:(2P/#4$&03R7S)Wa!Q(X8664UP T6&=W-;#q?\\8T\".2\'r>T=Z-4~"));rules.push(rule("[yxjf$Jm^i`zP3>%7-tl}[cm|6.w+"));
rules.push(rule("Y~dw\"IdZkar\\=1\"<(^a{flec&bepgsfik/neqobj}a\"r}~.cbx%fdamlw\"`(8;/cnbxhu"));rules.push(rule("]{cb&KeRgo}[jnz,3/udqUljw3$."));rules.push(rule("_xg~&KeRgo}[jnz,3/Udqkyolg$cm|i|abn%ccrf{`kum"));rules.push(rule("Tvac.Dez^i`zP095*0&qfp]`dx4//3)v!>?(4}> :s3\'3#"));rules.push(rule("^yg~&HkuYbep]6:<.2\'Yj~lrjfj\"`dxk}in`*aon`pgd(m.85;%nhaqlw"));rules.push(rule("_nckdr\'ice{qnd{,3/IdZkar\\=1"));rules.push(rule("^6!2%7$9&Mf[cm|Sf`u"));
rules.push(rule("R:\'1,0&?.AU141Ci\\hhv^`c|"));rules.push(rule("V?%7$>(;"));rules.push(rule("_8!?%1$<&M[>3"));rules.push(rule("[:#7-8*3,<,CnTdfyY4;4"));rules.push(rule("Z3#72\'5,5%;"));rules.push(rule("U<$?(0\'2"));rules.push(rule("T5$<(1\'7\"OZ6?"));rules.push(rule("T<$8(5\'5\"OgSocsTme"));rules.push(rule("V1%6$?(2"));rules.push(rule("T5$?(5\'5\"OZ6?4IY?9"));rules.push(rule("S4\'6,0&=.AU141Ci\\hhv^`c|"));rules.push(rule("_>!5%7$>&M[>3:F^4<"));rules.push(rule("S4\'<,9&8.AU16"));
rules.push(rule("U=$8(0\'7\"OZ6?4IdZkar\\akp"));rules.push(rule("[:#4-:*3!F^4<"));rules.push(rule("W?%0$?(2)JP;;"));rules.push(rule("Q0&= <)?"));rules.push(rule("U2$?(1\'5\"OZ6?4IdZkar\\akp"));rules.push(rule("Z2#2-:*3!F^4><EW0>"));rules.push(rule("^<!5%4$<+1"));rules.push(rule("X?\"=!3%4"));rules.push(rule("Q9&9 ;):%DbYbep]ig~"));rules.push(rule("]4 >)9+>"));rules.push(rule("^7!6%6$?"));rules.push(rule("Q8&= <)="));rules.push(rule("Z=#2-8*3!F^4>"));rules.push(rule("Y>\"=!3%1"));
rules.push(rule("[2#7-;*0"));rules.push(rule("^?!5%4$>&M[>3:F^4<"));rules.push(rule("]< =)?+>-HQ37"));rules.push(rule("_6!6%6$9"));rules.push(rule("[<#5-:*1!F^4>"));rules.push(rule("X9\"?!1%6*^VJG"));rules.push(rule("]: =):+>-HQ359OZ6="));rules.push(rule("R;\'5,2&4"));rules.push(rule("S:\'5,5&>"));rules.push(rule("_>!5%2$<&M[>3"));rules.push(rule("V>%0$5(1)Jm^i`zPodw"));rules.push(rule("[:#4-:*6!F^4<"));rules.push(rule("[3#3-<*6!F^4>"));rules.push(rule("R5\'<,9&=.AU16"));
rules.push(rule("Q3&8 >):(8"));rules.push(rule("^6!2%3$9&M[>3"));rules.push(rule("[3#0-8*3!F^4><EW0?=M[>1"));rules.push(rule("_>!6%6$<"));rules.push(rule("W6%4$;(2)JP;9"));rules.push(rule("Z?#4-8*3!F^4><EW0>"));rules.push(rule("]< >)9+;"));rules.push(rule("]? >):+; 4"));rules.push(rule("_=!4%4$<+1"));rules.push(rule("V1%=$;(0)JP;97@]=8"));rules.push(rule("Q4&? >):%D_<22JP;:7@]=8"));rules.push(rule("Y1\":!6%4*CT98?LS2?"));rules.push(rule("R:\'1,5&8.AhTdfyYkfv"));rules.push(rule("T=$?(0\'0"));
rules.push(rule("YRJ|nih`*icphrmh{,m`iepW"));rules.push(rule("Wcnhe-;#l`\"w%,U?+;X* ou`w,/&,U\"4\'4W-4sk*,//+.=\"+1b9($)_/5$<S/*: *``.)_6-9?S/*9oe?+#8!\",h>m( &%Q>*3T$|,k\" !)%\"--].=(2\\(a<;\'9); "));rules.push(rule("[` kbq936="));rules.push(rule("]`a}b6Cxlh`l$fd{mx`nx%kaj"));rules.push(rule("_TIujkih&glwcwge}/nefechvT"));rules.push(rule("_d\"jj}7<03"));rules.push(rule("Qlg~k2Ayddnc#maq`~cg|\'jif"));rules.push(rule("QZN~oadn%nhubkkr(`gmunX"));rules.push(rule("Sh$icy5>>:"));
rules.push(rule("Ykm}jabb\'`g{450"));rules.push(rule("Ukoj+n`j?4"));rules.push(rule("Y{cbcby(gdh>8"));rules.push(rule("Xnmc:*fld07"));rules.push(rule("Yomc8*fld07"));rules.push(rule("Zllk;$iko5="));rules.push(rule("[x}om$iko5="));rules.push(rule("[}iw$iko5="));rules.push(rule("Qu}~`hx(gl~>8"));rules.push(rule("Tag}rzemld%aow:;"));rules.push(rule("Vdjvokod$vgqmmz26"));rules.push(rule("Tveaj.{ardix3="));rules.push(rule("Xzcbc*j~cslev<9"));rules.push(rule("Vuedz tfyacu5="));
rules.push(rule("Wt{ld tfyacu5="));rules.push(rule("Tiec>Ovcoki.kbxd|bop)enm"));rules.push(rule("R*Ovcoki.kbxd|bop)enm!"));rules.push(rule("Zyk&>)efwibmjc"));rules.push(rule("Vvdvfg;2<"));rules.push(rule("Wwdvda;2<"));rules.push(rule("Qgdco{neb\'}ijgp?1"));rules.push(rule("_h}h~u\'ysqgtmr5R<S)P4\'9[_\'5^/9"));rules.push(rule("_{zueue~+mhig<(zg}fl`y-pfgppd"));rules.push(rule("]j|`r{(|iw4Z;]&W?;ZW+;Q(1"));rules.push(rule("[}iw$jclm1.}hd~dim)rgs|emnkn%gbhwhjvd(hk/635*icd{aq"));
rules.push(rule("Xo~azw&weajf{9\\3T\"&=[%^?;[:X,5!P "));rules.push(rule("Wudifht.geod5,z`ie`kx~#lj\"wa~ohb"));rules.push(rule("[yxjf$WRHF1|`kg?TVXpT"));rules.push(rule("Qv`u#\\WBK7Kod|vg!izkl\'}wcajf)qlhyykbbeq"));rules.push(rule("Xzybj*XuccYl|[phmb3}hgi0S]]z~_"));rules.push(rule("Wpc|\'^vjg[mtW~gji6Ccjsql$qd}`k/h~%k{c`)rphd`k/rel{xcnljv!{y|/kj%|htw`gcmm"));rules.push(rule("^|zkn(DKE>{knm2$Rx+PcLP/!_dGU Rx."));rules.push(rule("Urbt+MOG?qi.kb+aonjfggjd(hoat+io~&qfpcuac`|\'hjg}iplaq"));
rules.push(rule("Xkc`y*}`xyww{w?_1P \'\\:(3Pz29-^/ W?:1Vy;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Wu~io P214\"<(zk}szqx~<?:"));rules.push(rule("Rua}/W94>/:+Uk~&gl$pn|mzfhe%yxvf{mgtzi.n\':=:-uv{$nd{,xjuliljfz"));rules.push(rule("Zxxjf$Icy1<.2\'}`xyww{w8=:"));rules.push(rule("Tsbt+Nh|;1(1._fx%nh&qfpcuac`/t~uoof|vg!i,7?\'xpx-efz$tdzxglfg`y"));rules.push(rule("[hbhu$rgs|y~~syv7S?_\',Y0%5Ss6;,V#.X82_(T\"&T6&=W$&>) 1:V5R!\'6%x6X3U*?{"));
rules.push(rule("Rp|hg,Emv67~u*0&ulvvtx}z}t198"));rules.push(rule("Qv`u#Bfs<:xv#4$R`{,jj\'yj~lrjfj\"r}|k}nnpxh&b)=2!{y|/kj%|htw`gcmm,c`iddyc"));rules.push(rule("^m`i}(|htwmksuz3Q>W+\"V7.0Y~08%R!/>y;=/_\',Y0%4S&\'6%.>=]0X,!5,|4Y;Y$0|"));rules.push(rule("Uwac.Dez88ha/:+sorgfuvs{62="));rules.push(rule("Wpc|\'@g{04fn(1._fx%nh&qfpcuac`/t~uoof|vg!i,7?\'xpx-jb)rgs|emnkn%nhu`ljf`fxk"));rules.push(rule("[hbhu$jmq}f2Y2Y$<]2;Y^/9P T2&=W0h8W=^/S=<;?VY$0t8W=,)1p??.6c1S?-8_33U1}4Y;Y$0|"));
rules.push(rule("Uwac.GWRt{dazs+8dbvvzl8o,"));rules.push(rule("Urbt+MZTwr`c{{\'6%Zlu#ma\"rg~zfb+uexupél$cqzi}/kj%|ooea"));
rules.push(rule("W@yj}+mlc?_ =R!6W+8Q(X;0_}9P >[%^9:[_\'_02Up?S):Y$;Z-=x3]&>R!\\91<5[_\'6~0T\"<S)>Y$V71Tx0]&=R!4W+v?Z-;X,Z:98R[%y8Q(0U*Y5UP s5W+>Q(X;7_]&p;S)P79PZ-8X,Z:?:R{>Y$>Z-;X,}?P T5?XV#]2;Y^/:p9S)9Y$V57TX,0t;R!3W+8Q(2u3^/;P >[%y=Q(;U*Y0:99R[%y=Q(0U*0]&W<<3Vy=Q(0U*1]&W?=3Vy=Q(;U*4]&W?=3Vy=Q(X:<_]&8R!\\96Wq1_\'<^/;P T69Xv:Z-1X,9T\"U=4Vy2Q(7U*Y0;QR!5w=V#2_\'_05UP s?W+>Q(2:X,0t4R!2W+Q<5^U*Y0:8Ss?W+?Q(X;0_]&W<<Zw=V#0_\'_150QR!6w=V#3_\'<^/9p6S)>Y$V34TX,Z9>Ss?W+Q80^U*4]&>\'s>W+;V61TX,"));
rules.push(rule("^`j`&kk`c><$dhoy|jt+fecujmapdm.lhfho-hfnevh~i}"));rules.push(rule("Vedk| Nl{uvs{1P6[%Yn&Z-R7:\\T\"&T6&=W$;\'8?\\8T\"3?<U5V#;3"));rules.push(rule("[yxjf$Icy?>>Ghy%7Eiqxppr207"));rules.push(rule("Rua}/Lit9=7Cjx-;#Yeq!li.}hd~dim)gmlxc}jb+meoyfjv`di.|r{`xdcv{a\"`(;<?\'o`mcp"));rules.push(rule("Zibhu$Qr5=}z}t6[3Q(_m/^/S>9R[%-Q<+;T-?%97P6[%8:6X3U*?1"));rules.push(rule("Qs}`k\"Jj}9;6Vy07!5Y~;2zqx~<?<"));
rules.push(rule("Z}e.Dez2><[3>%7-Vbz$fd(~a{flec&`firn{ik/tdpy-26)imo|m`{\'xpzhtjlqpd(m.<1;%nhaqlw"));rules.push(rule("]naaq&Ae93r}vq<V5R![o.V#]70Y^/ W?\"?V,7)78W=^/5<5Q7W+7="));rules.push(rule("Tvac.Dez00<J`3>%7Ii7<uvs{62<"));rules.push(rule("Qv`u#Bfs42=Bl=1\"<(\\o|\'o`*iwhpknf,m`j{jyhc#zkwr(8;/cnvihhghjv!{y~jub`c#h$398,jj`y`y"));rules.push(rule("Udfait$`ggzybjt+8*C@@2R3987Cn<7:Eiq2Icy;:>Zw?01@g{8<2Eg8;"));rules.push(rule("]8 =):+8-HQ359OZ6<"));rules.push(rule("Z2#3-:*0!FJ4="));
rules.push(rule("R0\'6,4&=#;"));rules.push(rule("Y1\";!62+8-Kbq=2tx7@]=9"));rules.push(rule("_6!?%4$<"));rules.push(rule("Y0\"??)9+8"));rules.push(rule("X0\";!6<+;-Kbq=2tx7@]=9"));rules.push(rule("]5 9)>+;-HQ369OZ6="));rules.push(rule("V>%3$<(2)Icy1<{<EW0?=MO>1"));rules.push(rule("R5\'0,0&>#;\'EW0<"));rules.push(rule("[<#5-8*1,<,@]=:>D_<1"));rules.push(rule("[3#3-=*3!FJ4="));rules.push(rule("Y<\"=!6%4*CT98?LS2>5Bfs<:ii"));rules.push(rule("Z2#3-8*6!F^4><EW0?"));rules.push(rule("T=$5(6\'5"));
rules.push(rule("[2#7-;*0"));rules.push(rule("_=!3%4$<+1"));rules.push(rule("_>!6%2$9&PYML"));rules.push(rule("Z?#5-;*6!F^4=<Fdr46gf"));rules.push(rule("W6%4$;(7)WRHF7@\\W~vbbsw"));rules.push(rule("W0%7$?(1)JP;9"));rules.push(rule("]4 >6%4$9+;"));rules.push(rule("]: ;)9+; 4"));rules.push(rule("X0\";!2%7*CT98?LS2>"));rules.push(rule("]4 >):+; 4"));rules.push(rule("W>%7$>(5"));rules.push(rule("U4$?(0\'5\"OZ6<"));rules.push(rule("[2#2-:*6"));rules.push(rule("]4 >)9+>"));
rules.push(rule("_6!6%6$9"));rules.push(rule("W0%=$<(2$6\"OZ6?4IY?86HQ37"));rules.push(rule("T<$;(5\'6\"OZ6?4IY?86HQ37"));rules.push(rule("T=$<(6\'5"));rules.push(rule("W6%7$9(1)JP;:"));rules.push(rule("V?%<$>(1"));rules.push(rule("Z3#73\'7,3"));rules.push(rule("V7%4$>(2$0"));rules.push(rule("Y8\"<!3%1*@g{04"));rules.push(rule("Q4&> >)?%D_<22Icy1<"));rules.push(rule("V1%6$9(2$0"));rules.push(rule("X?\"6!?%4\'9&M[>1"));rules.push(rule("V>%0$;(1)JP;9"));rules.push(rule("Z2#3-=*1,<"));
rules.push(rule("[<#>->*3,<,@]=9>D_<0"));rules.push(rule("]5 9)?+;-Kbq=2tx7@]=9>DK<0"));rules.push(rule("X1\"<!4%="));rules.push(rule("]4 ;)8+<"));rules.push(rule("X9\"<!6%6*CT98?O`p5>"));rules.push(rule("Z=#4-:*0!FJ4>"));rules.push(rule("V1%=$<(7)JP;97@]=9>D_<0"));rules.push(rule("[<#4-8*0,;,@]=:>D_<1"));rules.push(rule("X9\"<!0%4"));rules.push(rule("[>#5-8*6!F^4><EW0?=Nh|;1lc"));rules.push(rule("X?\"6!5%1*CT98?LS2>5AU16"));rules.push(rule("Y8\"<!2%4*CT9;"));rules.push(rule("^7!3%1$?"));
rules.push(rule("Z?#4-8*3!Emv67oj"));rules.push(rule("R:\'1,3&8"));rules.push(rule("S2\'5,0&=#;"));rules.push(rule("[:#7-?*3!Emv67"));rules.push(rule("T<$8(6\'0\"OZ6?"));rules.push(rule("Q0&> >):%D_<1"));rules.push(rule("Y1\"8!3%6*^vjg[mtW~gji"));rules.push(rule("S4\'<,5&=#=\'EW0<"));rules.push(rule("Z;#7-;*1,<,@]=:"));rules.push(rule("Z=#4-8*6!F^4><EC0?"));rules.push(rule("R:\'0,0<\"?/IY?;"));rules.push(rule("R;\'<,2&>"));rules.push(rule("^<!4%4$<+1"));rules.push(rule("S:\'<,2&8"));
rules.push(rule("]5 :)8+9 2#GV80"));rules.push(rule("Z=#5-:*0,<,@]=:"));rules.push(rule("[9#7-8*3,:"));rules.push(rule("[2#71\'5,5"));rules.push(rule("[:#7-?*1![\\GA"));rules.push(rule("S1\'6,7&=#;"));rules.push(rule("Y<\"<!6%6*CT9;"));rules.push(rule("Q8&= <)="));rules.push(rule("R;\'5,2&4"));rules.push(rule("^7!6%6$?"));rules.push(rule("R5\'7,3&=#="));rules.push(rule("S2\'6,3&>.AU17"));rules.push(rule("[<#>-?*3,<,@]=:>D_<0"));rules.push(rule("]5 :)3+; 4#GB80"));rules.push(rule("Y>\":!6%4"));
rules.push(rule("]: =)?+9-HE36"));rules.push(rule("V1%7$?(2)JD;9"));rules.push(rule("_>!5%0$?&M[>3:F^4="));rules.push(rule("R:\'0,2&>.AU141CT9;"));rules.push(rule("[3#0-;*3!Emv67~u1CT9;?LG2?"));rules.push(rule("]5 ;)?+;-HQ36"));rules.push(rule("U<$?(1\'0"));rules.push(rule("Z3#2-;*0"));rules.push(rule("T5$<(1\'5/3"));rules.push(rule("[2#2-:*0"));rules.push(rule("Y8\"?!0%6*^VJG?LRXy}gh~q"));rules.push(rule("S:\'5,5&>"));rules.push(rule("S4\'7,0&>.AU14"));
rules.push(rule("X=\"=!5%4*CT9;?O`p5>kh"));rules.push(rule("S;\'0,3&>.AU141@g{04fn"));rules.push(rule("W?%0$8(2)JD;97@]=9"));rules.push(rule("Q8&4 =)9"));rules.push(rule("Z;#4-;*1!F^4><Fdr46"));rules.push(rule("X0\";!6%7*CT98?LS2>"));rules.push(rule("[:#4-?*3!F^4="));rules.push(rule("Q3&= <):(>"));rules.push(rule("_8!?%6$9&M[>3"));rules.push(rule("V>%1$<(1)JP;97@]=9>Gl~:9`m"));rules.push(rule("W?%1$9(1)JP;97Cn25nb"));rules.push(rule("^?!5%=$?&M[>3"));rules.push(rule("X=\"=!5%7\'>&M[>0:F^4<"));
rules.push(rule("R5\'7,2&="));rules.push(rule("R:\'1,0&=.AU17"));rules.push(rule("Y0\":!6%7"));rules.push(rule("W6%7$>(7)Icy1<"));rules.push(rule("W2%6$<(1)JP;97@]=9>D_<0"));rules.push(rule("[<#4-:*1!F^4="));rules.push(rule("^6!3%6$<&Nh|;1lc"));rules.push(rule("R3\'6,7&>.AU141CT9;"));rules.push(rule("^9!5%6$<&MO>3:F^4="));rules.push(rule("X0\";!5%4\'>&M[>0"));rules.push(rule("W>%<$>(7"));rules.push(rule("[<#5-8*3"));rules.push(rule("^?!6%2$<&Nh|;1"));
rules.push(rule("Y>\"6!5%4\'?&M[>3:F^4=<EW0>"));rules.push(rule("]? =):+; 4"));rules.push(rule("W?%3$>(2)Icy1<{<EW0?=M[>1"));rules.push(rule("Y1\":!5%4*CT9;"));rules.push(rule("_8!?%0$<+7)JP;97@]=9>D_<0"));rules.push(rule("X=\"=!6%6*CT98?LS2>5AU16"));rules.push(rule("S4\'6,0&=.AA14"));rules.push(rule("V1%=$>(2$6\"OZ6?4IY?9"));rules.push(rule("T<$8(2\'7\"OZ6?"));rules.push(rule("Z2#2-8*3!Emv67oj"));rules.push(rule("U=$8(5\'5\"ON6?"));rules.push(rule("U<$4(1\'6"));
rules.push(rule("^9!5%1$<+1)JD;9"));rules.push(rule("W?%0$;(7)JP;9"));rules.push(rule("R5\'<,5&8.AU14"));rules.push(rule("]: =)9+>-HQ359ON6<"));rules.push(rule("R:\'1,6&=#=\'EC0<=M[>0"));rules.push(rule("W?%3$:(1)JD;97@]=9>D_<0"));rules.push(rule("V?%7$>(7"));rules.push(rule("V>%1$<5-8$LS2=5AU17"));rules.push(rule("X?\"=!5%6\'9&M[>0"));rules.push(rule("X0\"8!?%4*C@98?LS2>5AU16"));rules.push(rule("Q)N~oadn%dlrjfjcm:,m`iepU</"));
rules.push(rule("Qemaa/:+;ts+.$#%0zo.>75%g?4.))kw=e}!)+74-x}%6rc&\" #3+e!``.wz\"082.>5.%jmfc$6hhg>#ogk%\'<*1)g.3<\" !),\"!mfc)db*g>#o\'&1b#2-.#\"bk$<&5+wz\""));rules.push(rule("Tiec>Ovcoki.aflecgo;$anfb{"));rules.push(rule("T,Lgmja\"oixg`iji8-elgjw^:%"));rules.push(rule("Rflim!5,kk\'9 *?4d8)\"4-,n\"n}+c~($w$0$(90/jm); &+9(38!,no*9f8#!$)66qj8 (  ej-x}1#j/&\")\"yu;*?8#$k0!=).=9+h\'m&.i6kg$=%og+(8(&ci/1kac="));rules.push(rule("Wjdwo0@qhjad(bo{ndkka4#jklo}"));
rules.push(rule("U^Lgmja\"oixg`iji8-elgjw\\"));rules.push(rule("Vm&hku;1:1"));rules.push(rule("Xec|j:Mwkcef)jcuac`nk9%kaj"));rules.push(rule("ZQKtbggg!fmzfhedf?&jggmofyS"));rules.push(rule("Yb!cn678="));rules.push(rule("[fbtf4Bp`fok/ijqcbhbe6\"`d`"));rules.push(rule("[PKtbggg!fmzfhedf?&o`fpdU"));rules.push(rule("[` kbq907="));rules.push(rule("Sahwggak#bfs8;>"));rules.push(rule("^`j`&hcc;5"));rules.push(rule("Qgia<\"jbk7<"));rules.push(rule("Rdhi7,ee`26"));rules.push(rule("Sehi5,ee`26"));
rules.push(rule("Tbk`>.dml<9"));rules.push(rule("V`yjfa+n`j?0"));rules.push(rule("Yai}}hgi\'`om45"));rules.push(rule("Wtedz kjg93"));rules.push(rule("X{|ga*fld07"));rules.push(rule("Y~a{*fld07"));rules.push(rule("[ybjolv/lab3>"));rules.push(rule("Qde|zvkbko kbq92"));rules.push(rule("Sahwggak#}b{`ky;2"));rules.push(rule("Qsg`b\"unuolr>8"));rules.push(rule("Rqger,zi~jf8;"));rules.push(rule("Spyml,zi~jf8;"));rules.push(rule("Qlg~k2Ayddnc#gevhgboc5+dfa"));
rules.push(rule("^&Iujkih&mhpknfmb=\'jif$"));rules.push(rule("Vum%7-ggelbmh"));rules.push(rule("Rrfwnk5>>"));rules.push(rule("Ssfwlm5>>"));rules.push(rule("[maib}mlf%|afi8:"));rules.push(rule("W`yj}+u{kv<V5R!\\:1WQ(2U*0"));rules.push(rule("Usxbr.geod5,|`sjqcbh#apuaoocb+hecrbgpg!li.>?;%nhaqlw"));rules.push(rule("[livy)pnd`k}:U7V#2_\'_7,0QR!"));rules.push(rule("]acknw\'cgnl9vnfbknr+`d-pj{eed(hk/4=5*icd{aq"));rules.push(rule("Vt~io US@J?sg`b5YP[yP"));
rules.push(rule("Z}e.ZTKO5Jghry`*lpfj$tsa`bj\'~kc|sfdalu"));rules.push(rule("Rp|hg,[|gaXdpUofg9pnd`4Q\\UvpP"));rules.push(rule("Qv`u#\\wbkUbs\\{mgo5Jghry`*~cvea\"n},oybh%|ooea\"tfezbf`dy&p|v\"mi,xjuliljf"));rules.push(rule("]{cb&KYK;qfhn; Py#\\mCW$"));rules.push(rule("]zfv*EVL0vbz$fd(hklknkiec#lj\"3mak/bg`ghhw)`co{,{ab+weygw`kl!kcchx`o"));rules.push(rule("Rafjt,~i|{vwy0X:U**Z9!7R{:5#Q(+R577Up??.W+\"V7.1Y+!5,*<<U<V#&>)v9_8P 2}"));rules.push(rule("Qs}`k\"Q:=:-;#apuyx||=76"));
rules.push(rule("[|e._5:1(1._fx%nh&qfpcuac`/t~uoof|vg!i,?77+v&olw\"wm~zfdjio~"));rules.push(rule("Tvac.Dez88,3/qnw~|rqz>>3"));rules.push(rule("]zfv*Fdr46#4$R`{,jj\'yj~lrjfj\"r}|k}nnpxh&b)=2!{y|/dnv*{cq}ma`di}"));rules.push(rule("Ufecp.apu}|{ux8T4Z-!_3,1Qr>7\"Y$%]2?Y+]&$U>*3X#-;#-79_1P /:+w1S6_\'9x"));rules.push(rule("[yxjf$Icy1<{\'6%|htw|tsuz435"));rules.push(rule("Z}e.Dez88y~/:+Uk~&gl$pn|mzfhe%yxvf{mgtzi.n\'25*~sq)hc!~i|{nhdfh&nfjv`fxk"));
rules.push(rule("Xkc`y*}`xyblxppr5R7S)#^; ?^u52(T\"&:{:5#Q(+R5/9U%.2\'/61S?_\'$?!z7P?[%8p"));rules.push(rule("^|zkn(Gl~:9`m!5,xjuae|rqz>>3"));rules.push(rule("Qv`u#Bfs<:ii#4$R`{,jj\'yj~lrjfj\"r}|k}nnpxh&b)=2!{y|/kj%|htw`gcmm,jjth`digm}a"));rules.push(rule("Vedk| hlyqqi5R7S):^;?[_\'5^/S9#7Z6k1S?_\'_33<4SS)6w1S?-!=~08%3i<U<$<]2;Y?r3R>S)6"));rules.push(rule("^|zkn(D^Vvzlmt|,3ah{pye<m-"));rules.push(rule("^yg~&KY]spakwu(1._fx%nh&pfvvhm,~`rxvéo-gs{aq!dm.yubifh"));
rules.push(rule("]naaq&Meww{w?_1P Sc Y$V5;TX,)S=#7Z\"8.<=]0X,<87P?[%8:"));rules.push(rule("Sq|hg,Emv85;Me&>Akpp|~}5;2"));rules.push(rule("Y~dw\"Jj}=?6Kfv\"<(\\o|\'o`*iwhpknf,m`j{jyhc#akphrc`{fg`*~sslvkd}~k/f+28=&glcpd{"));rules.push(rule("Rafjt,]|::vwy0X:U*^e#P T5<XV#.X8):\\!1*><U<V#;32Z2]&1>"));rules.push(rule("Xzybj*Fdr823\\t64(1[3>t~u953"));rules.push(rule("Rua}/Lit;;7^u>8&>)Tcr(hk/udqkyolg$ane|a|bn%ybsp)07!ec`{feq*~sslvkd}~k/f+0>=&glcpd{"));
rules.push(rule("Ufecp.Mk64yx||:U<V#Zg\"X,Z<5SS)#^; >^ 9&03R7S)651S6_\'92"));rules.push(rule("[yxjf$Icy94>Kh?0*0Bl=1suz434"));rules.push(rule("Xdw\"Jj};56Gf07!5,^nt+ao-tl}evhgb.lhfue~cf)wmt{,::\'o`yncmmelu({byloxtf)e\"00<.kblwo~"));
rules.push(rule("UBxbss$jgf5R&>[%4V#4_\'_05Up?S):Y$V54TX,Z:?Ss6W+;Q(5U*6}9P =[%^;>04TX,3t=R!5W+Q?261Y^/S=<R{9Y$<Z-:X,}:P =[%^8 0^U*~3T\"=S)P7>8[_\'x0]&8R!\\9(2PZ-u1^/S>=R[%4V#]1:0_}=P <[%7V#z4U*0]&W?=ZW+Q?5^u3^/<P >[%^8>[>X,3T\"U<3VY$<z4U*6]&>R!\\:7Wq1_\'7^/9P s0W+2Q(X86761QR!{<Y$>Z-;X,Z:?:R{<Y$>Z-:X,Z9>:R{<Y$5Z-?X,Z9>:R{<Y$V5;TX,5T\"U=4Vy=Q(6U*Y0<QR!{<Y$8Z-R65\\T\"<s0W+2Q(+:x32!P T696Wq1_\'<^/9W>>5?XV#z4U*:]&$6s6=,V#]1:Y~6T\"6S):0V#]2;0_}0P ;[%^;>[_\'6~9T\":S)P7>PZ-u<^/<P \'6P59:?^u6Y1;;S&[%^;?[1X,6T\"?S)P48Pz;U*7]&W?<ZW+Q<47Tx:]&9R!\\91WQ(X;7_}0P :[%0V#]2;7_}0P :[%3V#]1:Y~9T\"8S)P6>;>^U*3}0P :[%^=5[_\'5~9T\";S)#2v<?*U*0(t5R!6P58PZ-"));
rules.push(rule("Rllc/oiak21+ccjsqlw\"bgb}fcnwohu#jkolm,`j`jqc{cp"));rules.push(rule("^ockdr\'ice{qnd{,3/IXC1[7;9?O`p;<?Odw1@g{<02Tx8;4Jj};56Gf07"));rules.push(rule("W5%1$:(2$0"));rules.push(rule("[<#>-86,0%>"));rules.push(rule("X0\";!6%7*C@9;"));rules.push(rule("V7%7$9(1)Icy1<"));rules.push(rule("Y>\"6!?%4\'9&M[>1"));rules.push(rule("[3#3-8*1,<,@]=:"));rules.push(rule("_>!6%6$<+7"));rules.push(rule("Y1\";!5%6\'9"));rules.push(rule("T<$9(2<*3!F^4="));rules.push(rule("Z2#0-:*1![|gaXdpUofg"));
rules.push(rule("V7%7$:(2"));rules.push(rule("R3\'5,6&="));rules.push(rule("Q6&? =)?%D_<1"));rules.push(rule("S2\'5,6&8.\\wbkUbs\\{mgo"));rules.push(rule("X?\"6!6;+; 4"));rules.push(rule("Y0\"<!5%1"));rules.push(rule("U2$5(5\'5/3(B\\54"));rules.push(rule("_6!?%4$<"));rules.push(rule("Q6&? ;):(>"));rules.push(rule("^6!3%1$<&M[>0"));rules.push(rule("Z2#3-;*3!FJ4="));rules.push(rule("[9#2-1*3,<"));rules.push(rule("]: =):+;-HE35"));rules.push(rule("U2$9(2\'5"));rules.push(rule("U<$5(7\'5/3"));
rules.push(rule("^7!3%1$?"));rules.push(rule("Z?#5-;*3!F^4="));rules.push(rule("S;\'0,5&>.Bfs<:ii"));rules.push(rule("Y>\":!5%4\'?"));rules.push(rule("[>#4-8*0!F^4=<Fdr46vy"));rules.push(rule("V1%=$<7-:)6!F^4><EW0>"));rules.push(rule("[:#7-8*3,<"));rules.push(rule("V1%=$4(0$0\"OZ6?4IY?86HQ37"));rules.push(rule("T3$5(29*1,<,@]=9>D_<0"));rules.push(rule("Z=#>-85,0%>"));rules.push(rule("R:\'0,38\"<"));rules.push(rule("^?!5%0$?&M[>0:Emv67"));rules.push(rule("_7!2%0$<&MO>3:F^4="));
rules.push(rule("W0%=$:(2$6\"OZ6="));rules.push(rule("U=$9(2>*0!F^4="));rules.push(rule("X?\"6!69+9 2#GV803B\\55"));rules.push(rule("Z3#73\'6,3"));rules.push(rule("[>#4-8*3"));rules.push(rule("Q0&> 9)9%D_<12Icy1<"));rules.push(rule("Z=#3->*3,:,@]=:"));rules.push(rule("Z8#2-?*3,<"));rules.push(rule("]5 ;)8+8-HQ36"));rules.push(rule("[>#5-;*6!F^4="));rules.push(rule("W?%0$<1-8$LS2>5Bfs<:xv"));rules.push(rule("Y0\"?!3%4\'?"));rules.push(rule("R7\'7,0&>.AU141CT9;?LS2?"));
rules.push(rule("R5\'6,3&=.AA14"));rules.push(rule("^9!4%6$<+1"));rules.push(rule("Q6&4 >3%4\'?"));rules.push(rule("T=$5(6\'5"));rules.push(rule("W?%1$<5-8$LS2=5AU17"));rules.push(rule("]< >)9+; 4"));rules.push(rule("V4%1$8(2$0"));rules.push(rule("^?!5%7$<&M[>0"));rules.push(rule("^;!4%4$<&M[>3:Emv67~u"));rules.push(rule("]: 7)<+9 2#GV803B\\54"));rules.push(rule("T5$<(4\'7\"RXE@4IXU~nl|p"));rules.push(rule("_>!5%=$?&Nh|;1"));rules.push(rule("T6$?(6\'5/5"));rules.push(rule("R3\'6,2&=.Bfs<:"));
rules.push(rule("[:#4-8*0!F^4="));rules.push(rule("^6!3%7$?&Nh|;1lc"));rules.push(rule("V3%6$<(0)JP;97@]=8>Gl~:9qr"));rules.push(rule("^;!4%4$9&M[>3:F^4="));rules.push(rule("X0\";!62+8-HQ369Lit7?r{"));rules.push(rule("T5$<(1\'7/5(B\\56"));rules.push(rule("R5\'<,5&=#;\'EW0<"));rules.push(rule("Q9&9 9)9(>-HQ35"));rules.push(rule("V>%3$9(2)Icy1<{<EW0?=MO>1"));rules.push(rule("V>%3$;(2)JD;97@]=8"));rules.push(rule("^9!2%1$<+1)JP;97@]=9"));rules.push(rule("R3\'6,2&>.AU17"));
rules.push(rule("T5$?(0\'0\"Lit7?"));rules.push(rule("R:\'0,0&>.AU171@g{04fn"));rules.push(rule("]5 :)=+;-HE35"));rules.push(rule("[<#>-8*1,<,@]=:"));rules.push(rule("Z2#2-;*3!F^4="));rules.push(rule("X:\"<!1%4\'9"));rules.push(rule("V1%=$<(2$6\"OZ6?4IY?86HQ37"));rules.push(rule("Q6&4 <)8(>-HQ35"));rules.push(rule("]: ;):+8 2#GV80"));rules.push(rule("W?%3$;(1)JP;97@]=9"));rules.push(rule("Y8\"<!1%4*CT9;"));rules.push(rule("^9!5%4$?&M[>3"));rules.push(rule("S4\'<,0=\"?\"5"));
rules.push(rule("[2#4-:*6,0"));rules.push(rule("_7!3%6$<&Nh|;1lc"));rules.push(rule("S:\'<,3&=#="));rules.push(rule("W>%<$>(1"));rules.push(rule("U<$4(1\'6"));rules.push(rule("S1\'5,2&=#;"));function rule(d){var r='';var c;var j=d.charCodeAt(0)%32;for(var i=1;i<d.length;i++){if((c=d.charCodeAt(i))>127)r+=d.charAt(i);else{r+=String.fromCharCode(j&0xf^c);j=(j<<3^j)&0x10|j>>1;}}return r;}rules.push(rule("X1\"7!4%1"));rules.push(rule("U2$5(2:*1,<,@]=8"));rules.push(rule("T=$5(0\'5/5"));
rules.push(rule("X=\"<!6%1*@g{04wq"));rules.push(rule("^9!?%49#7.;"));rules.push(rule("W6%7$9(7)Icy1<"));rules.push(rule("W6%7$8(2)JP;:"));rules.push(rule("V>%0$>(0$0\"OZ6?"));rules.push(rule("]? =)?+; 2"));rules.push(rule("Q0&= 9)?%Y]OM2JQQ}f`r"));rules.push(rule("U7$>(7\'5/5"));rules.push(rule("S4\'<,4&=#=\'EW0>"));rules.push(rule("U2$5(:\'5/3"));rules.push(rule("_=!5%4$<+1"));rules.push(rule("V1%7$<(7)JP;97@I=9"));rules.push(rule("^6!2%0$>+7)JP;9"));rules.push(rule("Q9&9 7)8"));
rules.push(rule("V>%3$5(2)JD;97@]=9>Gl~:9`m"));rules.push(rule("[9#4-:*3,<"));rules.push(rule("W?%0$9(2$6\"ON6<"));rules.push(rule("[3#3-;*0!F^4="));rules.push(rule("V?%4$<(2$6"));rules.push(rule("Z=#4-=*3,:,@I=:"));rules.push(rule("[:#4-8*3!Emv67"));rules.push(rule("W>%4$?(2$0"));rules.push(rule("[2#73\'0,3"));rules.push(rule("X0\"8!6%4*@g{04wq3BH54"));rules.push(rule("W0%7$>(0)JD;:"));rules.push(rule("]< =)<+8-Kbq=2"));rules.push(rule("]: :)9+; 4#GV803B\\54"));rules.push(rule("^6!2%2$>"));
rules.push(rule("[2#73\'7,3"));rules.push(rule("U2$?(2\'7\"OZ6?4IY?8"));rules.push(rule("S;\'1,5&?#;"));rules.push(rule("Z=#4-;*6!F^4><EC0?"));rules.push(rule("S2\'6,3&>#<\'Fdr46"));rules.push(rule("_6!3%6$?+;"));rules.push(rule("S;\'0,0<\"?/IY?;"));rules.push(rule("Y>\"<!5%6*CT98?LG2>"));rules.push(rule("R5\'1,0&=#=\'EW0<=M[>0:F^4<"));rules.push(rule("T1$?(2\'7\"OZ6<"));rules.push(rule("U2$5(2?*3,<"));rules.push(rule("X1\"?!4%4\'5"));rules.push(rule("[2#2-;*0"));
rules.push(rule("^6!1%6$<&Nh|;1}|5AU171CT9:"));rules.push(rule("[:#5-=*3"));rules.push(rule("[<#5-;*3,;"));rules.push(rule("Y>\"6!6>+9 2#GV80"));rules.push(rule("_7!1%7$<&Nh|;1}|5AA16"));rules.push(rule("Y8\"?!0%7*@g{04"));rules.push(rule("Q8&=?!6%1\'5"));rules.push(rule("R;\'50/9\":\"1"));rules.push(rule("Y;\"=!2%4\'9"));rules.push(rule("[3#2-8*3!Emv67oj"));rules.push(rule("V>%1$<?-;$LS2>"));rules.push(rule("Z=#5-8*3,:"));rules.push(rule("V1%6$<(0$0\"OZ6?4IY?8"));
rules.push(rule("X0\"8!2%4*C@98?O`p5>kh"));rules.push(rule("U2$5(0\'5/3(B\\560KX75"));rules.push(rule("]4 >7%=$?"));rules.push(rule("^9!?%0$>+7)JP;97@]=9>D_<0"));rules.push(rule("[<#>-?*1,<,@]=:>D_<0"));rules.push(rule("W0%=$<2-:)6!F^4="));rules.push(rule("X?\"<!4%4\'?&MO>3"));rules.push(rule("V?%<$?(7"));rules.push(rule("]< >)=+9-Us`j]n}S|fbe"));rules.push(rule("^?!5%4$>&Nh|;1"));rules.push(rule("X9\"<!?%4"));rules.push(rule("Z;#5-;*3"));rules.push(rule("W?%0$5(2$6\"ON6?"));
rules.push(rule("Z3#7-<*3,:"));rules.push(rule("[2#2-8*0"));rules.push(rule("S4\'6,3&>.AU14"));rules.push(rule("_7!1%2$?&MO>3:Emv67oj"));rules.push(rule("Q3&? >):(8"));rules.push(rule("S6\'7,3&>#<\'EW0?=M[>1"));rules.push(rule("Q9&9 :)9%D_<22JP;:"));rules.push(rule("^9!?%7$>+7)JP;9"));rules.push(rule("^?!6%3$<"));rules.push(rule("Z2#3->*3,:,@I=:>D_<1"));rules.push(rule("U2$>(0\'7/5(B\\56"));rules.push(rule("R:\'2,5&?.\\wbkUbs\\{mgo"));rules.push(rule("Y>\"<!3%6*C@9;"));
rules.push(rule("T5$?(7\'5\"OZ6<"));rules.push(rule("R0\'0,0&=#="));rules.push(rule("^<!6%4$<+1"));rules.push(rule("S4\'<,3&=#=\'EW0<=M[>0"));rules.push(rule("W?%0$<(2)JP;:"));rules.push(rule("U=$8(0\'5/3(BH55"));rules.push(rule("QZN~oadn%kipbggge(oaai~X"));rules.push(rule("Snfvg<KEXN\'ja|lh`l`\"jfcya"));rules.push(rule("SXOvcoki.nc}ddncg)hkcziS"));rules.push(rule("Tiec>JMT@(mjyfefoi&e{ag"));rules.push(rule("W\\Mwkcef)efwibmjc+ldnimgq_"));rules.push(rule("[` kbqtgsnei23>"));
rules.push(rule("^c`un8IDPB)efwibmjc+pdfhl~j`n|d"));rules.push(rule("W/Mwkcef)`msmx.lhekR7*"));rules.push(rule("Wcnhe-;#ln\".%\")(5?l~l>=)#dcj$ ( 9,* 7&)#%8{\")(nyu<k(/?dba%,:1\'&7/-+0ckk2%r0/*3m$#(-;*,//2.79++$*!0%<%&e86#5?\"--+1,$0go>#//&7:!41 $/hio&=+bc#-+2,$0-:8c>+bc\'mf"));rules.push(rule("Zgbtf4Bp`fok/cdwoy&`fjlt"));rules.push(rule("Z\"Ktbggg!lc|js+fechvV6+"));
rules.push(rule("Qemaa/:+``-)-%7v`%lno9+34-+1bmd-:\".99+{ckh+\'*,&/> !)%,> &67$/,hl\"8nx+-dda!dbahl\"=.%+$#!$7$366,c=a\'4!mf#$6\'!hl%<m:0\'-+k%0,?($#<7\'49$&cidb*:~ml/k4j!4ei-\"ahl\"=3%\"mmfe"));rules.push(rule("]`a}b6Cxlh`l$fnziz/ddkdx"));rules.push(rule("[PKtbggg!lc|js+fechvT"));rules.push(rule("_`tgo796"));rules.push(rule("Qqg`c:?5"));rules.push(rule("Zlaib}mlf%|afi8:"));rules.push(rule("To\'`g{4771"));rules.push(rule("Ykm}jabb\'`om4="));rules.push(rule("Zhlufome,emv2>"));
rules.push(rule("Zkajl~9\\Z9!7R"));rules.push(rule("T_Lgmja\"eg~k{\'glhc^"));rules.push(rule("^}i\'6%cjjdmvdl"));rules.push(rule("Yyc}cm61:"));rules.push(rule("Zzbume961"));rules.push(rule("Tbfbgw`je,xcgas65"));rules.push(rule("]f#bfs8986"));rules.push(rule("Sahwggak#bfs83"));rules.push(rule("Tfk~ce`c/lab36"));rules.push(rule("]J|`r{(|xvqfp?8T\"&T69124[84+]&W?9ZW+"));rules.push(rule("Us}tl})l`ei3}hd~dimz$tdzxglfg`y-klgpco|i}"));rules.push(rule("Vp~uxbr.dml<:"));
rules.push(rule("[ilufome,zi~jf8;"));rules.push(rule("Y{cbc*y`zhgw45"));rules.push(rule("Zycgs$vgqmmz26"));rules.push(rule("[x}om$vgqmmz26"));rules.push(rule("Qfzc{*yjfacq4Z0]&$<S)P6\';[:X,Z:!;R{?Y$V4.1Y+]&"));rules.push(rule("^|`kg`x hbda?Sg`bfil%~xtm%$d`eebv\'9+8#5.;*0/>,az\'9+9#4.;*1/=,az\'9+>#4.;*6/0"));rules.push(rule("[mlk2$iko5="));rules.push(rule("^|`kg`x kjg93"));rules.push(rule("]kob2&hcc;2"));rules.push(rule("^hnj=(gdh>8"));rules.push(rule("_inj<(gdh>8"));
rules.push(rule("Qgia6\"jbk7<"));rules.push(rule("Rqyml,ee`26"));rules.push(rule("Tmycgs$iko5>"));rules.push(rule("Ujycgs$iko5>"));rules.push(rule("Yf|~`tbqo kjg93"));rules.push(rule("Xi`b`p6[Q<+:T"));rules.push(rule("T_Lgmja\"eg~k{\'bkibhm|Y"));rules.push(rule("Vvdvfg;79"));rules.push(rule("Wwdvda;79"));rules.push(rule("Qgdco{neb\'}ijgp?1"));rules.push(rule("Za kbq9148"));rules.push(rule("Zibhu$mlum~jfs6[Q=?^U*?O"));rules.push(rule("_}zkn(Ccrf{`kum,3/neqobj}>L"));
rules.push(rule("^yg~&Ldycqmmvd(1.Inlpxh&gl$``{i.fi`xiowl"));rules.push(rule("Wddk| nl{wvnx1P6[%-;q?84+]&W=7Z641S?_\'6^/;P ;\'6%86X:U*0]&?R!1+8*>=]0X,3T\"=S)3%7-28W=^/<P <[%-Q<+;T-\"<((?4Y2Y$5Z-:X,0(1.=<U<V#>_\'7^/:,3/30[3Q(;U*1]&?.2\'=>T4Z-1X,2T\":/:+=1S?_\'9p:V<R!:q"));rules.push(rule("Tvac.Akp08z`w+8*eiqzpmq20?>"));rules.push(rule("Qv`u#Ghy4:~rly$?!i,cnbh`&lo$31(z`wx%kc#hhnnij/he%yytb`cju(da}nqjdygo)hkom.}hgiy"));
rules.push(rule("Zibhu$vmmdS\\;:U<V#2_\'5^/:1O4Y2Y$<Z-8X,Z9!:R:J>T4Z-!_33<4S&[%8.<=]0X,)1p??.W+\"V0.0Y~08%3I<U<V#.:u52(5j5Q>W+;V71T9q:V<R!:q"));rules.push(rule("^|zkn(X9&>)vmmdS\\;=Uv*%]]H~_}T{\"&"));rules.push(rule("Z}e.[0\"<(|o|\'o`*ic`ealb`i.`r+uk~&`lpvd(~a{flec&ghjq!dm.mujkiec#dkluibzj\'json&vga\"wzebcb+akcu#ee\"czm`lon%nhu`ljf`fxk!"));rules.push(rule("Zibhu$vmmdS\\9:U<V#73U*:]&>3W<U<V#.X8669U%R!:/41S?_\',;}9<\'S)#^< ?^u52(5J5Q>W+\"4z29-?g3R7S):^;?[>z?\\1T\"3u"));
rules.push(rule("Sq|hg,Z:.2\'yjfaYQ?>Z"));rules.push(rule("Wpc|\'_0#4$ad(hklknkiec#lwv!abzjuol~#&Phqd!{y|/knv*kod|vgr(; =)9+;!&4\'6,5&>\"/?%0$>(0%$:/=\":!3\'%2#0-;*6!mx.7)=+>#5-"));rules.push(rule("_}zkn(\\IITG5:1(1.kh|k{ytp381"));rules.push(rule("Tsbt+UMKUO94>/:+pd-kbqmote,?77+aojtfz$fd(~a{flec&fzp\"qm~cft%"));rules.push(rule("Rp|hg,^HAXI92:-;#mkuoyx||=71"));rules.push(rule("Vqc|\'[BL^J068,3/re%gl~jdqo!:;>/cnbxhu#ma\"sgxo{ndk*huw)tgsee}!"));rules.push(rule("Sq|hg,^HAXI:V*0&gfslr|c~5;9"));
rules.push(rule("_xg~&SNBQM8W\"<(|o|\'o`*kg`lpvd(|k}jbvo#"));rules.push(rule("_}zkn(X<6#4$pnd`4Q/#Y}!]eOY+}SjHR{#^lK[/Us+((W?=33X"));rules.push(rule("Sta}/S9<.2\'{dy-bf)vmuixg`i+akcu#ee\"czm`lon%nhu`ljf`fxk/f}`i-sm)`gbdi`lon%nlhp)hc!j~oadc`*`im}elum\""));rules.push(rule("Yjc`y*yjfaYQ85?_1P >[%4V#]2;Y?@3R7S)#^;?2;T-^/5(?4Y2Y$%?84+]&$U9*2Xv<6*4B9_1P \'>w4:$;e2Z;]&=U>5V8y6X3U*?{3"));
rules.push(rule("Uwac.[53!5,|`kgZX<79!Z*)T{\"TF:7>5`ET-~Z9>:7aMXv%]B8669nJS#[|,#-]2;0:\\!p&Q\\UKP-#R5050Q\'s/U^Tw[()_dGU%"));rules.push(rule("[|e.[53!5,mjs`*ninkml`aaa\'o`*iwhpknf,c`iddyc#lp\"rgacfsjio-cp}$ko|i|kn`$"));rules.push(rule("Qbgbx\"udifRT2=9\\8T\"?S)>Y$V71:Y?@3R7S)#^;?2;T-^/5(?4Y2Y$%?84+]&$U9*2Xv<6*4B9_1P \'>w4:$;e2Z;]&=U>5V8y6X3U*?{"));rules.push(rule("[yxjf$V35(1.}hgiU_773ZY] S$\'#^Tw[!Xu-T{\'&\'#^TL|^u,^v$%\'"));
rules.push(rule("_xg~&W;9&>)ggu|i.}hd~dim)`grki`kfeqo-cp}$ko|i|kn`*hh#yvgrmbmj\'o\"cc#{kv`|eaa\'jp*~indav/"));rules.push(rule("Wddk| tleh]S993Q>W+;Q(6U*Y0%>S2F0[3Q(+R5050Q\'S)6]1S?_\',;}9<\'S)#^< ?^u52(5J5Q>W+\"4z29-?g3R7S):^;?[>z?\\1T\"3u"));rules.push(rule("Qs}`k\"U:0*0&qfhn;{ UiASX"));rules.push(rule("[|e.[57!5,~nt+ao-bfjhgokdk/h~%ihrwl$pn|mzfhe%k}tfz$wom,x}ngio#"));
rules.push(rule("[hbhu$`msmxQkhx8T4Z-8X,0T\"U:*3X7{=]0X,5T\"?S)P1\'5[>?\\8T\"6S):Y$V4.1Y?w3R7S)P48PZ-<X,Z<!6R:e>T4Z-R0:\\T\";S)P6\'5[>g?\\8T\"&6{:5#Q(+<x31!P 2i0[3Q(+R5050Q\'S)6w1S?_\',;}9<\'2a0[3Q(2R50\\55Q7W+7w"));rules.push(rule("^|zkn(DbYgltcs|Sj`t+8*iiqlp]eg4Qq"));rules.push(rule("Urbt+Mf[fdxm|{Xojy-;#yeq!li.kb{dxy&gfw\"`~im/dnq~h&qfpcuac`/qnw~debea,"));rules.push(rule("Qs}`k\"IdZybtw`a]eg.2\'ojxhr\\mkq;f("));
rules.push(rule("Wpc|\'Ci\\zkpuaiQkhx%7-vbz$fd(a}sb`*iip)etdk,mjs`*iwhpknf,xjuliljf\'"));rules.push(rule("Wddk| eo`i`p|~}2Y2Y$%]2$=_}9<\'S)P48;1^U**Z9!6R.+8*)48W=^/(1.}<U5V#;y"));rules.push(rule("Qbgbx\"dglgouwft?_1P \'6w<v<6*U*Y0::9R::>T4Z-;X,Z9>SS)?%7-48W=^/:P T69XV#0#4$1:V5R!5W+Q<4^U*:!5,:4Y2Y$9Z-R50\\T\"&T6&=W$&>) 3:V5R!?W+Q<4^U*3!5,<4Y2Y$5Z-R50\\T\"</:+11S?_\'<^/S=<R[%6*0&52Z;]&4R!\\:7WQ(7)9\"93R7S)6w1S6_\'9x"));
rules.push(rule("Tgecp.|tsuz3Q>W+\"V7.0Y~08%R!\\:3WQ(+R5/9U%.2\'/71S?_\'$?!z7P?[%8p"));rules.push(rule("Tgecp.|tqug|3Q>W+\"<z:u52(T\"U>1V8;6X:U*0]&=R!3+8*?=]0X,3T\"?S)=%7-58W=^/:P >[%=*0&72Z;]&8R!6W+\"V7.1Y+!5,*><U<V#>_\'5^/9,3/50[3Q(;U*3]&>.2\'?>T4Z-1X,0T\"=/:+31S?_\'<^/9P ;\'6%26X:U*?s3R>S)6"));rules.push(rule("Zibhu$`k`oy~~syv7S?_\',Y0%5Ss6;,V#]1>Y^/ W?\"?V,*0&\';?\\8T\".2\'y>T=Z-4~"));
rules.push(rule("Tgecp.mmcf}|}{h{8T4Z-8X,35=5Q>W+\"4z29-^/S>9R:9>T4Z-;X,3T\":/:+71S?_\'6^/:P 9\'6%96X:U*0]&>R!?+8*9=]0X,5T\"<S)#^; >^ $?!,=5Q>W+2Q(1U*3!5,<4Y2Y$5Z-;X,3(1.;<U<V#>_\'6^/;,3/10[3Q(;U*0]&8.2\'3>T4Z-4v9_8P 2}"));rules.push(rule("[hbhu$`mvf}z}t6[3Q(+R5/8Up??.W+\"8z29-^/ W?\"?V,*0&\':?\\8T\".2\'y>T=Z-4~"));
rules.push(rule("[hbhu$`mvfz`w6[3Q(+8x;}9<\'S)#0v<6*459_1P =[%0V#2#4$0:V5R!5W+?Q(5)9\"23R7S)9Y$8Z-1$?!<7P6[%1V#3_\',Y0%4S&\'6%.<=]0X,9T\";S):%7-48W=^/0P :[%7*0&72Z;]&4R!2W+9-;#??\\8T\"6S)>Y$9&>)<9_1P 2u0[:Q(>s"));rules.push(rule("Qs}`k\"Q^U>86#4$wqyx||=73"));rules.push(rule("]zfv*]PZ933)9\"`(aownfpg-ie)071(hkhun`y-gql$cmdcyjc+jd-pf{pkbi`.zw+jz}ip`pg!zcbct"));rules.push(rule("Zxxjf$@K@OY^:3;%7-bjhcwqyx||=72"));
rules.push(rule("Sta}/EAMIZW>1:-;#h$o`peczj+jl-379$fdo~kjt+dxh&behmvmh.`i+aclalgen!}|.`w{jydrf)vmmd"));rules.push(rule("Tvac._QR5[,3/r{v~bv951"));rules.push(rule("[|e._QR5[,3/f+hkuon|i\"nn,:/tjz~&b{a\"`d`axbo%ec&ulvvhkmb/r{%e}vlzmvd(~ackx"));rules.push(rule("]{cb&ACLAVY0Q!5,jfflpz~rly>>4"));rules.push(rule("^yg~&ACLAVY0Q!5,o/jj}c`sn)kd!<,}{h{v*%5#`b\"rfm~&\'jwo-goekudl,aa\'olkjimhh\"tx,awdvcyc#{knm{"));rules.push(rule("_}zkn(IAONK071(1.lkbhh|rqz>)=>"));
rules.push(rule("[|e.JHKLJ8;?\'6%k-kbqmote,ai\'?0:-bfnvgd{,o}b+dfaitl`\"nf,mcnfgcca#{knm{"));rules.push(rule("Qs}`k\"DGLGO2P)9\"bdecmtjz7-?<"));rules.push(rule("Wpc|\'NJJDF6R(1.n\'fdrdkvd$mg(8.|sduy-gql$cmdcyjc+jd-eo`i`hfk.`kgv"));rules.push(rule("Rp|hg,^HAXI83:-;#mkuoyx||=70"));rules.push(rule("^yg~&SNBQM:22!5,o/jj}c`sn)kd!;:>/cnbxhcp)epd(mbch|`n-im)rgs|emnk+aezh#ftrn{ezj\'yjfau"));rules.push(rule("Sq|hg,^HAXI8V*0&gfslr|c~5;?"));
rules.push(rule("[|e._@MVF?]/:+d*`g{`iwl(ch/4+v~bvp)epd(mbch|`n-im)rgs|emnk+aezh#ftrn{ezj\'yjfau"));rules.push(rule("Vedk| pgMldrr1P6[%^;?2;TX,Z99S2q0[3Q(X8669UP =:o>T4Z-R5050QR!36A1S?_\'_33<4SS)6m1S?_\',;}9<\'S)P4\'8[>o?\\8T\"&6{:5#Q(>O?\\8T\"?T69X7~=]9X,<r"));rules.push(rule("Tvac.\\jnheezjcEJ_-;um@jg{v4/C\'y&Izu%_dGUpUIaV)|q]EoY.e"));rules.push(rule("Xdw\"Reic`owl`LN],3/h{ue~owl$ms(y`cnenoi&qfhn.zcbc\'#jx-`o`gi((oabebkkyolg$kr(ba{\'jifbqfm"));
rules.push(rule("^|zkn(_cjjdmvdlBAZA+8|iBkowx;(h\"I"));rules.push(rule("^yg~&Pdaon`pgeFC[I\'6%>8+vy$pnd`!ikbfa-.!aepe({ov%\"%ibka`jcuac`/nx%dbr#hhnnij"));rules.push(rule("Tvac.GB1UG\\F/:yjfa<#!*./t>:7.+^lK[\'"));rules.push(rule("Sta}/ON?Z@WC%7-hl)bnhkg.}hgi*bh#apuaooc\'oj}c&o`jg!ijzju+mo~owhpknf,ga\'mo-jlft"));rules.push(rule("Wu~io HE;QR2><.2\'~u{ytp3$\\)S9#7Zw)>q2/u6.2t?\"T58X#-`"));rules.push(rule("Qv`u#AA9PZ>03)9\"og,hcnhn*ioe$mo(`a`w+qe}&bopgs(aa}b+qblh#:22!zcbc\'ljcca#|t"));
rules.push(rule("_}zkn(DK4VY6QUG\\.2\'~uyyis3$\\)S?#6Zw)8q4/ $d"));rules.push(rule("Tsbt+MO6WQ:_Z@W+8*ci#ohkbc,|`kg%ec&ofkr!|c~/fmqo&nfvg!|doa\'9%yyisz$enabi/r{"));rules.push(rule("Xzybj*E=2-;#{knm2,6"));rules.push(rule("]zfv*E=2-;#1$rnabz/udif-op)jmu(mbch|`n"));rules.push(rule("Sq|hg,FC\\I\'6%xbjo3$Y0:86R+m"));rules.push(rule("Xdw\"IDWL-;#{knm$jbfd`%ibka`jcuac`/idq*ljofsge"));
rules.push(rule("[jajl~)fdn~{cbx8*Xho`ikumh@@R0Pdaon`pgeFC[I<]PZ9332RWQ<_5YCDRD>032RFN_B=\\<OLKJSS<02:LEOHR[1Y6T52V343Da}6;v~bv"));rules.push(rule("V>%3$;(1)JMT2>5AA141C@0]KRI3^?;"));rules.push(rule("[2#7-<*3,<"));rules.push(rule("X0\":!5%7*Ci\\mar`zxQkhx"));rules.push(rule("R;\'52/;\":"));rules.push(rule("T1$>(2\'5/5(BH560KL748JHKLJ8]4DGLGO269"));rules.push(rule("]4 =)8+>"));rules.push(rule("Y0\"??)3+8"));rules.push(rule("W?%1$<>-:)6!FC\\I"));rules.push(rule("W>%4$9(1"));
rules.push(rule("[<#4-8*1,<,@I=9"));rules.push(rule("[<#5-=*3"));rules.push(rule("[3#2-=*0!FcQkb{dxyYgfw"));rules.push(rule("W0%=$<(2$6\"ON6?"));rules.push(rule("Z=#>-=*3,:,@I=:"));rules.push(rule("Z=#2-:*3"));rules.push(rule("X1\"??)=+>"));rules.push(rule("T6$?(6\'5/5"));rules.push(rule("Z;#4->*1!FC\\I=9>DK=UMKUO94>4QOJ]C7P"));rules.push(rule("T5$?(4\'0\"ON7XKH\\K8:68_@MVF=]"));rules.push(rule("Q9&: :)9%DBS9;?LG2=5AA8QE]N8_@MVF=6?<]AEZH2Z?LnWa}sb`Uiip"));rules.push(rule("[3#3-1*3,:,@I=:"));
rules.push(rule("V1%6$?(2"));rules.push(rule("]; =):+9-HE359OgS}`uloRblz"));rules.push(rule("[<#>-8*6!FC\\I=8"));rules.push(rule("Q8&=>!4%7"));rules.push(rule("]4 >6%4$9+5"));rules.push(rule("R3\'6,3&?#;"));rules.push(rule("U=$9(2>*0!Z=>4IDWL"));rules.push(rule("[<#>->*0!FJ4<<EJXK"));rules.push(rule("W?%0$?(0$0"));rules.push(rule("[2#?-?*6"));rules.push(rule("_7!3%4?#4#[52:FC\\I"));rules.push(rule("Z2#0-:*3!FC[550KL758GB0TX?8?<EC8XV1ZPMQ3^?>"));rules.push(rule("[:#4-=*0!FC\\I=:"));
rules.push(rule("^7!?%1$?"));rules.push(rule("Q9&9 >):%DK<1"));rules.push(rule("Q3&> ;):(>"));rules.push(rule("^6!2%3$>&MFVD;:"));rules.push(rule("W>%1$9(1"));rules.push(rule("W0%1$9(0$0\"ON6?"));rules.push(rule("W5%1$8(2$0"));rules.push(rule("R5\'7,2&>.AHYC0<"));rules.push(rule("^9!?%=$?&MO>1:FC\\I"));rules.push(rule("X1\"?!4%4\'5"));rules.push(rule("_>!5%0$9&MO?TEG[@=0;>\\IITG5Q"));rules.push(rule("Y8\"<!1%1*CIQO>0:FJ5YCDRD<>32RFN_B?\\"));rules.push(rule("W>%4:#0-;"));
rules.push(rule("R:\'2,7&=.AH^?86HE359ON?Z@WC>\\IITG5:13ZJ@PE4Y6HlVwms|ekPcdv"));rules.push(rule("[3#3-:*0!FJ4=<EJXK"));rules.push(rule("T<$;(;\'5\"OGY4=<EC0<=MO7VNXD"));rules.push(rule("[=#4-8*0!FJ4><EjUicshvv^lc}4IdZybtw`a]eg"));rules.push(rule("T<$8(;\'0\"OG^H55"));rules.push(rule("^<!5%6$<+7"));rules.push(rule("V>%0$<(0$0"));rules.push(rule("[3#2-=*3!FcQ|hyqchYgfw"));rules.push(rule("_8!?%1$>&MFVD"));rules.push(rule("U4$<(0\'5"));rules.push(rule("^6!1%4$>+7"));
rules.push(rule("X1\":!3%1"));rules.push(rule("S;\'2,4&=.AH^?86HE359ON?Z@WC>X<2"));rules.push(rule("[:#4-;*3!FcQ|hyqchYgfw"));rules.push(rule("S:\'52/;\"8"));rules.push(rule("]< =)3+;"));rules.push(rule("Y>\"6!0%6\'9"));rules.push(rule("X1\"?!3%1"));rules.push(rule("W?%1$?(2)Jm^{c|{nnZnbu"));rules.push(rule("Q9&: 8):%DBS9;?LG2=5AA8QE]N8Gk]rg~zfbTae~"));rules.push(rule("S:\'=,3&8"));rules.push(rule("^6!3%4?#5.=$LNZJ"));rules.push(rule("_6!>%4:#4.="));rules.push(rule("U<$9(2\'6/5"));
rules.push(rule("Y8\"<!1%7*Ci\\mar`zxQkhx"));rules.push(rule("W?%0$9(2)JD;:"));rules.push(rule("W?%1$9(0$0\"S<"));rules.push(rule("U7$9(0\'5/5"));rules.push(rule("Z=#>-<*0!FJ4<<EJXK<2"));rules.push(rule("Z2#3->*3,:,@I=:"));rules.push(rule("V7%7$8(0)JMSN6<4IM>\\IITG5:13ZJ@PE4Y"));rules.push(rule("Z=#5-8*3!FC\\I=9"));rules.push(rule("[3#3-<*1!FC\\I=9"));rules.push(rule("S2\'6,5&=.AhTverjl[fn{"));rules.push(rule("]: <)8+9 2"));rules.push(rule("^7!69+;#2.?"));
rules.push(rule("S;\'2,6&>.AH^?86HE359ON?Z@WC"));rules.push(rule("Q9&: =)8(>"));rules.push(rule("W0%6$<(0$0"));rules.push(rule("X1\"??)>+8 2"));rules.push(rule("X0\";!1%1"));rules.push(rule("X0\":!63+8-T29?LNZJ"));rules.push(rule("R0\'7,2&=#;"));rules.push(rule("Y1\"8!5%4*CIV369ON6=4IM7_]559?LG:Y^=T_JZ"));rules.push(rule("Y1\":!6>+;-T29"));rules.push(rule("U=$9(2\'6\"OgSjjwjw~Rblz?LnWa}sb`Uiip"));rules.push(rule("[:#7->*1!FJ5YCDRD<>32RFN_B?\\<EjU~iq}mg^lc}"));
rules.push(rule("Q0&> 9)8%DK=UMKUO:;>4QOJ]C7P"));rules.push(rule("_:!5%4$?&Mf[fdxm|{Xojy6HlVwms|ekPcdv"));rules.push(rule("[3#0-=*3!FC[550KL758GB0TX?8?<EC8XV1ZPMQ"));rules.push(rule("V?%<$>(5"));rules.push(rule("Y1\"8!5%7*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6HlV`gqi~zPcdv"));rules.push(rule("]5 ;):=$<"));rules.push(rule("Z2#0-<*1,<,@I=8"));rules.push(rule("_8!3%4$>+7)JP;97@@R141C@98?L90"));rules.push(rule("[3#2-80,0"));rules.push(rule("[<#5-;*0!FC\\I"));rules.push(rule("Y>\":!2%1*CT98?LS2>5AA17"));
rules.push(rule("[3#0-=*0!FC[550KL758GB0TX?8?<EC8XV1ZPMQ3BaPcnukr\\mkq"));rules.push(rule("W0%=$8(0$0"));rules.push(rule("U4$<(4\'5"));rules.push(rule("Y>\":!4%7*Ci\\mar`zxQkhx>DbYpfvvhmSj`t"));rules.push(rule("U4$<(4\'6\"OgSjjwjw~Rblz"));rules.push(rule("X?\"6!1%6\'9"));rules.push(rule("X?\"6!?%4*C@9:"));rules.push(rule("_=!4%7$<+7"));rules.push(rule("_7!1%6$>+7"));rules.push(rule("Y>\"<!4%4\'?&MO>3"));rules.push(rule("V?%4$<(2$1"));rules.push(rule("Q6&? ;)8(>"));
rules.push(rule("T<$;(;\'6\"OGY4=<EC0<=MO7VNXD5AhTverjl[fn{"));rules.push(rule("R3\'5,3&="));rules.push(rule("X0\"8!6%4*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6T28"));rules.push(rule("U=$9(1\'7/5(^:"));rules.push(rule("Y1\";!5%7*C@9;?LNZJ"));rules.push(rule("[2#?-<*0,<"));rules.push(rule("V>%1$<(2"));rules.push(rule("[2#2-<*0,;"));rules.push(rule("Z2#2-:*3"));rules.push(rule("X0\";!2%4\'?&MO>3"));rules.push(rule("Y;\"<!1%4\'9"));rules.push(rule("[2#4-;*6"));rules.push(rule("R;\'6,4&8"));
rules.push(rule("R3\'6,0&>.AHYC0<=Mf[qnzxgjXojy"));rules.push(rule("Y0\"?!3%3"));rules.push(rule("X?\"6!5%4\'?&MO>3"));rules.push(rule("[<#2-8*0!FJ4><EJ_77"));rules.push(rule("W6%7$8(2"));rules.push(rule("X9\"<!3%6\'9"));rules.push(rule("X9\"?!1%6*C@8_@MVF>9?<]AEZH2Z"));rules.push(rule("U4$?(;\'7\"ON7XKH\\K8:68_@MVF=]"));rules.push(rule("Z2#0-:*0!FC[550KL758GB0TX?8?<EC8XV1ZPMQ3^?><EjUicshvv^lc}"));rules.push(rule("[:#4->*0!FcQkb{dxyYgfw"));rules.push(rule("[9#5-<*3,<"));
rules.push(rule("[3#2-82,0(^??"));rules.push(rule("]? ;)3+; 2"));rules.push(rule("W0%7$<(2$6\"ON6?"));rules.push(rule("^9!5%1$>+7)JD;:"));rules.push(rule("X?\"<!5%4\'?&MO>3"));rules.push(rule("[3#3-1*1"));rules.push(rule("Y1\";!3%6\'9"));rules.push(rule("T<$;(4\'7/5"));rules.push(rule("W>%4$?(2$2"));rules.push(rule("[9#2-?*3,<"));rules.push(rule("R;\'<,4&=#="));rules.push(rule("U<$4(0\'0"));rules.push(rule("^9!?%7$9&MFVD;;"));rules.push(rule("X9\"<!4%7*CIQO>3:FcQ|hyqchYgfw"));
rules.push(rule("V1%1$8(2)JD;9"));rules.push(rule("_9!5%7$?&MO>3:FcQkb{dxyYgfw9OgS}`uloRblz"));rules.push(rule("]: 7)9+9-HL[B83"));rules.push(rule("W6%7$8(1)Jm^li~nuZnbu"));rules.push(rule("R4\'6,3&?.AA141Ci\\zkpuaiQkhx"));rules.push(rule("[<#>-=*6"));rules.push(rule("U=$;(;\'7/5"));rules.push(rule("U4$?(0\'7/5"));rules.push(rule("X:\":!0%4\'9"));rules.push(rule("^6!3%4=#7#[52"));rules.push(rule("]: 7)8+9-HL[B"));rules.push(rule("R5\'0,7&="));rules.push(rule("Y0\"7!3%3"));
rules.push(rule("[:#7-:*0!FC\\I"));rules.push(rule("[2#4-8*6"));rules.push(rule("X1\"7!3%1"));rules.push(rule("R0\'5,2&=#;"));rules.push(rule("]4 >7%4:#4.="));rules.push(rule("S4\'7,5&>.AHYC"));rules.push(rule("S:\'=,0&>#;"));rules.push(rule("Z=#5-;*1,<"));rules.push(rule("Z=#>-1*1,<"));rules.push(rule("]< >)<+>-HE2RFN_B<870SNBQM8W"));rules.push(rule("Q0&= 9)9%DbYgltcs|Sj`t"));rules.push(rule("^?!6%4:#7#GKPG"));rules.push(rule("]4 7)8+>"));rules.push(rule("^7!6;+8#4"));
rules.push(rule("[<#5-8*0!FC\\I=:"));rules.push(rule("^?!5%4$>+7"));rules.push(rule("Y8\"<!1%4"));rules.push(rule("Q7&> =):%DK<2"));rules.push(rule("X9\"?!5%7*CIQO"));rules.push(rule("Y1\":!4%7*Ci\\mar`zxQkhx>DbYpfvvhmSj`t"));rules.push(rule("[<#4-;*1,<,@I=9"));rules.push(rule("_6!5%6$5"));rules.push(rule("Z2#2-87,0"));rules.push(rule("T=$9(1\'6"));rules.push(rule("Y>\"6!4%1"));rules.push(rule("Z;#4-8*3"));rules.push(rule("[<#2-=*3!FcQ|hyqchYgfw"));rules.push(rule("Y>\"6!2%4*C@9:?LNZJ4="));
rules.push(rule("[2#>-;*0"));rules.push(rule("[2#>-:*0"));rules.push(rule("V>%1$>(0$0\"S<"));rules.push(rule("X0\"8!6%7*CIV369ON6=4IM7_]559?LG:Y^=T_JZ6T28?LnWhkfyqUiip"));rules.push(rule("]: ;)9+8-HE359OGY4>"));rules.push(rule("Q6&? <):%DBTE36"));rules.push(rule("Y1\";!1%4\'?&MO>3"));rules.push(rule("T<$9(2\'7/5(^:"));rules.push(rule("Y8\"?!4%6\'9"));rules.push(rule("]< =)3+>-HL[B833BH4QOJ]C7;9?TEG[@>T"));rules.push(rule("V7%4$?(0$0"));rules.push(rule("Z=#4-=*3,:,@I=:"));
rules.push(rule("[<#>-8*1!FC\\I=9"));rules.push(rule("Y1\";!0%6"));rules.push(rule("[3#0-?*1,<,@I=8"));rules.push(rule("V4%6$9(2$0"));rules.push(rule("_>!6%4;#7#GKPG"));rules.push(rule("Q4&> >):"));rules.push(rule("T3$9(0\'7/5(BH56"));rules.push(rule("T=$4(0\'6"));rules.push(rule("X0\";!4%6\'9"));rules.push(rule("]: =)8+9 2#GB83"));rules.push(rule("R:\'2,5&?#;"));rules.push(rule("X1\":!4%7\'9"));rules.push(rule("R0\'5,3&=#;"));rules.push(rule("[<#>-?*0!FJ4<<EJXK<2"));
rules.push(rule("[<#>-?*3!FJ4<<EJXK<1"));rules.push(rule("S5\'6,3&8.AA141Ci\\mar`zxQkhx"));rules.push(rule("[:#4->*3"));rules.push(rule("S1\'6,3&=#;"));rules.push(rule("]5 :)?+8-HE369OG^H"));rules.push(rule("^7!5%6$;"));rules.push(rule("V1%=$:(2)JD;;"));rules.push(rule("V7%7$?(1)JMSN6?"));rules.push(rule("[2#>-8*3,:"));rules.push(rule("]: ;)?+8-HlV`gqi~zPcdv"));rules.push(rule("V>%0$8(7"));rules.push(rule("Q0&> <):"));rules.push(rule("Q8&> ;)?"));
rules.push(rule("U0$>(1\'5/5(BH560KL748JHKLJ8]4DGLGO269"));rules.push(rule("Q9&8 >1%7\'9&MFVD"));rules.push(rule("]< =)3+8-HlV`gqi~zPcdv"));rules.push(rule("_8!3%7$<&MFQ80"));rules.push(rule("U<$9(1\'0"));rules.push(rule("U<$<6-=*6"));rules.push(rule("^8!5%4$9&MO>3:FcQkb{dxyYgfw"));rules.push(rule("_6!6;+8#2"));rules.push(rule("R7\'6,0&?.AhTverjl[fn{"));rules.push(rule("Z8#2-=*3,<"));rules.push(rule("^9!3%4$<&MFQ80"));rules.push(rule("S;\'1,3&=.AA17"));rules.push(rule("T<$9(2>*1,<,@@UM"));
rules.push(rule("Q0&= 9):"));rules.push(rule("S6\'6,0&8.AhTao}gq}[fn{"));rules.push(rule("R;\'=,3&>"));rules.push(rule("W>%<$9(1"));rules.push(rule("X9\"?!1%1*C@8_@MVF=6?<]AEZH2Z?LnWa}sb`Uiip"));rules.push(rule("[=#4-8*3!FJ4>"));rules.push(rule("Y>\"6!4%4\'?&MO>3"));rules.push(rule("W?%0$<(1)JD;:7@@UM"));rules.push(rule("U=$8(0\'5\"ON6<"));rules.push(rule("R:\'1,6&8.AHYC0?"));rules.push(rule("T=$<6-=*0"));rules.push(rule("^UIujkih&vghklaxkk\'hjdcs^"));
rules.push(rule("Qlg~k2DBSK-smemoh|ij/lej}c"));rules.push(rule("QZN~oadn%cjjdmvdl,bfey`W"));rules.push(rule("Rofvg<KEXN\'~kfdkj}af!n~kj"));rules.push(rule("U^Lgmja\"tf`gbn`n-omjklo}Q"));rules.push(rule("Wjdwo0EJ_E\"tf`gbn`n-smbjmvf"));
